### ISSUE TITLE
Building on Amazon Linux 2023

### ISSUE THREAD

**Issue by ivosabev** [VROOM-Project/vroom#1005]
I am not able to find a way to install asio-devel, any ideas how to build it and install it on Amazon Linux 2023 (ARM)?

**Comment by jcoupey** [comment]
I have no clue on how to install stuff for Amazon Linux, my guess is it should be similar to what you'd expect on [RPM-based operating systems](https://docs.aws.amazon.com/linux/al2023/ug/relationship-to-fedora.html). In any case, you may have better luck posting to an Amazon Linux related forum.

**Comment by ivosabev** [comment]
Here is my solution for whoever encounters the same issues, maybe you can add it to the Installation docs

### Create file `/etc/yum.repos.d/fedora.repo`

```
[fedora]
name=Fedora 37 - \$basearch
#baseurl=http://download.example/pub/fedora/linux/releases/37/Everything/\$basearch/os/
metalink=https://mirrors.fedoraproject.org/metalink?repo=fedora-37&arch=\$basearch
enabled=0
countme=1
metadata_expire=7d
repo_gpgcheck=0
type=rpm
gpgcheck=1
gpgkey=https://getfedora.org/static/fedora.gpg
skip_if_unavailable=False
```

### Install the needed packages

```
dnf --enablerepo=fedora install glpk-devel -y
dnf --enablerepo=fedora install asio-devel -y
dnf install openssl-devel -y
```

### Install Vroom

```
cd ~ && git clone https://github.com/VROOM-Project/vroom.git
cd ~/vroom && git checkout v1.13.0
cd ~/vroom && git submodule init
cd ~/vroom && git submodule update
cd ~/vroom/src/ && make
```

**Comment by jcoupey** [comment]
Thanks for sharing!
