### ISSUE TITLE
Timeout Problems (API does not return a solution)

### ISSUE THREAD

**Issue by cpprofs** [VROOM-Project/vroom#1011]
Dear Jcoupey,

I am running a docker with openrouteservice and vroom. Somehow, it is either still 'running' or the program stops without giving a response. 

I always check the docker stats, in the beginning the ors docker goes to 100% CPU with about 20gb RAM. Eventually it will send the information to the Vroom docker, where CPU spikes to 3200% (32 threads). After about 40 minutes you can see the CPU drop as the algorithm finishes. A few minutes after the Vroom docker has 0% cpu usage, I will get the response via de API. 

However this does not always happen, I have even left it open for a whole night and I get no response. Why is this? Do I have to tweak any settings, is the dataset too big?

Is it possible to save the response in JSON on the server instead of waiting for a response?

Thanks! 

CP

**Comment by jcoupey** [comment]
> is the dataset too big?

Hard to tell since you don't really describe the size of the problems you're trying to solve. But from the times you're reporting this might be the problem. In that case you may want to look at the `-x` option to lower the exploration level.

**Comment by jcoupey** [comment]
>Is it possible to save the response in JSON on the server instead of waiting for a response?

By "waiting for a response" I think you mean waiting for a response from `vroom-express`. You can do everything on the command-line using files, see https://github.com/VROOM-Project/vroom/wiki/Usage.

**Comment by cpprofs** [comment]
Thank you for your response! The dataset is around 5500 points, each with time windows of specific dates. So one point has a time window of not more than 5 days, from 10:00 till 19:00. 

It should distribute the points over a timespan of 30 days and make aprox. 1000 routes in total. 

The problem is very intermittend. Sometimes after a server restart it will not 'freeze'.

**Comment by jcoupey** [comment]
There are a number of "external" things that could go wrong, e.g. the time it takes to compute a 5500x5500 matrix with ORS, hitting some limitation related to Docker, etc.

If the problem is related to the length of the VROOM optimization phase itself, then again you should lower the exploration level (see `-x` usage).
