### ISSUE TITLE
Not recieving any cost, geometry and duration values in the output

### ISSUE THREAD

**Issue by AKA2501** [VROOM-Project/vroom#1012]
![image](https://github.com/VROOM-Project/vroom/assets/69507035/b64cb1f0-de1e-4a69-b867-dfc262bdd6c9)
Also i am a little confused wrt to the planning and the solving mode and the difference that it makes

**Comment by AKA2501** [comment]
Dear Jcoupey,
Also when initially i thought to parse all my routes as shipments so they would have a pickup and drop feature the api does no give any route generated in return all the trips are moved to unassigned category in the output.
I have followed the dockerized approach to install these components

**Comment by jcoupey** [comment]
It's impossible to help without having a minimal example to reproduce. Can you share the actual instance you're using as text (not a screenshot!)?

**Comment by jcoupey** [comment]
Closing as discussed through another channel.
