### ISSUE TITLE
`TimeWindow::length` should be scaled

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#1015]
The `length` member of `TimeWindow` class defined here: https://github.com/VROOM-Project/vroom/blob/f5f078f2e27712452c51503bfc76438a426da10f/src/structures/vroom/time_window.h#L21 is initialised here: https://github.com/VROOM-Project/vroom/blob/f5f078f2e27712452c51503bfc76438a426da10f/src/structures/vroom/time_window.cpp#L22-L25

Due to both `start` and `end` members being shadowed by `start` and `end` arguments, the computed `length` value is based on `UserDuration` instead of `Duration`.

At the moment it is not a big deal, because `TimeWindow::length` is used only in vehicle comparison: https://github.com/VROOM-Project/vroom/blob/f5f078f2e27712452c51503bfc76438a426da10f/src/structures/vroom/vehicle.h#L138-L153, which works correctly whether or not the value is scaled, and in job: https://github.com/VROOM-Project/vroom/blob/f5f078f2e27712452c51503bfc76438a426da10f/src/structures/vroom/job.cpp#L17-L22, where it is used to initialise `Job::tw_length`, which itself is not used anywhere and gets removed in #1014.

Anyway, to avoid any possible confusion in the future, I would propose to either scale the value: `length(utils::scale_from_user_duration(end - start))` or add a `length()` member function and compute the value on the fly.

**Comment by jcoupey** [comment]
Landed with #1014.
