### ISSUE TITLE
Issue with -g flag

### ISSUE THREAD

**Issue by KevinLRos** [VROOM-Project/vroom#1017]
Hello,

I am encountering an issue that I cannot seem to resolve using the VROOM API. When I perform a route optimization without the -g flag, the optimization works fine. However, when I try to use this option, especially to obtain the distance traveled by the vehicles, I get the error 'Invalid routing response'. Furthermore, when I combine the -c flag with the -g flag, the optimization runs but I only get assigned results. 

Can you help me resolve this error or assist me in identifying its source?

Thank you in advance.

PS: A big thank you for this tool, which I find very efficient :)

**Comment by jcoupey** [comment]
An "Invalid routing response" error means that something went wrong while sending a routing request to get the full route geometry. So it's hard to help without more details: what routing engine are you using? what version of VROOM (the distance management workflow changed in `master` compared to the previous release)?

In any case, your best bet is to lookup the logs of the routing engine you're using, then isolate/reproduce the problem at routing level to understand what's going wrong.

**Comment by jcoupey** [comment]
Closing as stale.

**Comment by salarnz** [comment]
Dear jcoupey

How can i use the -g flag ? where should i put it?

**Comment by jcoupey** [comment]
> How can i use the -g flag ? where should i put it?

Please check our [wiki page on usage](https://github.com/VROOM-Project/vroom/wiki/Usage). How to use commands and options is a generic skill on its own so going into more details is outside the scope of this project. You'll probably find plenty of resources and tutorials out there to help you.
