### ISSUE TITLE
optimizing for setup cost

### ISSUE THREAD

**Issue by martinon97** [VROOM-Project/vroom#1025]
Hey Julien,

Using vroom and loving it so far - thanks.
I have one question regarding the cost optimization of the algorithm. 
From the documentation, I understand that the cost is computed as (cost_per_km * vehicle driving km) + (cost_per_hour * vehicle driving time) + fixed cost. However, I find myself in a situation where the setup costs for a specific job are really high. So, what I would like to do is bundle many jobs that are going to a shipment location, to minimize the impact of the setup costs (basically minimizing the number of unique shipment locations). 

As of now the algorithm is trying to optimize for the vehicle costs, is there a way to include setup costs (not time) in this?

Thanks,
Martino

**Comment by jcoupey** [comment]
No, there is no way to account for specific tasks costs. But "bundl[ing] many jobs that are going to a shipment location" is something that should already happen in most situations with the existing cost model:

- if we don't bundle as much as we can, then it means more going back and forth so also a higher cost with the usual cost (based on hour/km);
- if you use `setup` and `service` keys for tasks, grouping them reduces the overall `setup` time so indirectly makes room for more work. In a packed scenario, good solutions should thus naturally have bundled same-location tasks.

**Comment by jcoupey** [comment]
Closing as answered.

**Comment by saalihou** [comment]
If someone somehow stumbles upon this, it seems like this was solved in 1.15.0 (See https://github.com/VROOM-Project/vroom/issues/1130)

**Comment by jcoupey** [comment]
Yes, as per the last release, the time spent in setup/service is now part of the objective function. We introduced a `costs.per_task_hour` value that can be used for ponderation. Default value is zero, i.e. no change with previous behavior with task time not accounted for.
