### ISSUE TITLE
different routes and output with same input

### ISSUE THREAD

**Issue by salarnz** [VROOM-Project/vroom#1041]
Hi
I'm using Vroom 1.14.0-rc.1 and Osrm for routing engine.
every time i run my request with fixed input parameters ( start and end , vehicles , jobs ) , i got different routes and output.

Of course, I have noticed that the changes when I use the test server(http://solver.vroom-project.org/) are much less than when i use my instance on my docker

is there any way to get the same result with same input parameters?

Regards

**Comment by jcoupey** [comment]
It is expected to get the same route plan from the demo server (or your own instance) across requests *with exact same input*. Note that reordering the vehicles or the jobs makes for a different input.

Regarding results from your own instance, it's not really possible to answer without more details. How exactly are you calling the solving engine (exact command-line parameters)? What is the input you're using? What kind of differences are you noticing? Can you share an example of a single input along with two different outputs it produces?

**Comment by salarnz** [comment]
dear @jcoupey 
i find my problem ! it was a very small different in start and end values .
