### ISSUE TITLE
Equal jobs distribution

### ISSUE THREAD

**Issue by Robertolupu** [VROOM-Project/vroom#1042]
Hi,

Is there a way to get routes for all vehicles?

I would like my vehicles to finish their route aproximately at the same time so they all have the same(aprox) "working_hours".
The algorithm's aim is to reduce costs. In order to reduce costs there are vehicles that have no route because all jobs can be done by the other ones, it makes sense. Anyways my principal aim is they have similar "working_hours".

Thank You, Great job

**Comment by jcoupey** [comment]
If you want to balance "jobs distribution", you should look at the `max_tasks` key for vehicles.

> I would like my vehicles to finish their route aproximately at the same time so they all have the same(aprox) "working_hours".

That is a bit different, you can refer to #466 and the suggested solution over there.

**Comment by jcoupey** [comment]
Closing as answered.
