### ISSUE TITLE
latest code binary doesn't work with custom matrices input file that worked fine with v1.13.0

### ISSUE THREAD

**Issue by answerquest** [VROOM-Project/vroom#1043]
For the same input json file with custom matrices included, vroom v1.13.0 is solving properly, but the vroom binary compiled from latest master branch code keeps erroring out

```
# with binary compiled from latest master branch
vroom -i input.json
[Error] Invalid matrix entry.
{"code":2,"error":"Invalid matrix entry."}
```

```
# with binary compiled from v1.13.0
vroom -i input.json
{"code":0,"summary":{"cost":6202,"routes":1,"unassigned":0,"delivery":[4],"amount":[4],"pickup":[0],"setup":0,"service":1200,"duration":6202,"waiting_time":0,"priority":0,"violations":[],"computing_times":{"loading":0,"solving":0}},"unassigned":[],"routes":[{"vehicle":1,"cost":6202,"delivery":[4],"amount":[4],"pickup":[0],"setup":0,"service":1200,"duration":6202,"waiting_time":0,"priority":0,"steps":[{"type":"start","location_index":0,"setup":0,"service":0,"waiting_time":0,"load":[4],"arrival":0,"duration":0,"violations":[]},{"type":"job","location_index":4,"id":4,"setup":0,"service":300,"waiting_time":0,"job":4,"load":[3],"arrival":2074,"duration":2074,"violations":[]},{"type":"job","location_index":3,"id":3,"setup":0,"service":300,"waiting_time":0,"job":3,"load":[2],"arrival":3222,"duration":2922,"violations":[]},{"type":"job","location_index":2,"id":2,"setup":0,"service":300,"waiting_time":0,"job":2,"load":[1],"arrival":3816,"duration":3216,"violations":[]},{"type":"job","location_index":1,"id":1,"setup":0,"service":300,"waiting_time":0,"job":1,"load":[0],"arrival":4802,"duration":3902,"violations":[]},{"type":"end","location_index":0,"setup":0,"service":0,"waiting_time":0,"load":[0],"arrival":7402,"duration":6202,"violations":[]}],"violations":[]}]}
```

Sample input file for testing:
```
{"vehicles": [{"id": 1, "start_index": 0, "end_index": 0, "profile": "truck", "capacity": [4], "speed_factor": 0.5}], "jobs": [{"id": 1, "location_index": 1, "service": 300, "delivery": [1]}, {"id": 2, "location_index": 2, "service": 300, "delivery": [1]}, {"id": 3, "location_index": 3, "service": 300, "delivery": [1]}, {"id": 4, "location_index": 4, "service": 300, "delivery": [1]}], "matrices": {"truck": {"durations": [[0, 1173, 1079, 1392, 1037], [1150, 0, 406, 670, 432], [1282, 343, 0, 346, 260], [1363, 424, 147, 0, 244], [1344, 405, 270, 424, 0]], "distances": [[0.0, 24.911, 22.377, 26.951, 21.572], [24.6, 0.0, 5.673, 10.108, 7.021], [26.689, 5.415, 0.0, 4.414, 3.279], [28.29, 7.016, 1.778, 0.0, 3.188], [28.15, 6.876, 3.552, 5.588, 0.0]]}}}
```

And I'm not able to find any breaking change between the usage docs for 1.13 https://github.com/VROOM-Project/vroom/blob/release/1.13/docs/API.md and current https://github.com/VROOM-Project/vroom/blob/master/docs/API.md which might justify this difference. 

Is there some breaking change in the expected input format that hasn't been documented? I'm seeing there's a ton of code changes made since v1.13.0, wanted to avail new features / improvements. But I'm not able to make the latest binary work.

**Comment by jcoupey** [comment]
Your input works "by chance" with v1.13.0 in the sense that the distance matrix is totally ignored. Now using the latest code, `matrices.truck.distances` is indeed parsed and it's not valid since integer values are expected and you have floats.

My guess is that your distances are km. If I convert them all to meters, I get the exact same solution with v1.14.0-rc.3 (except for the additional reported distances).

**Comment by answerquest** [comment]
Ah! Valhalla matrix api gives this in kms by default. Thanks!
I'll try making a documentation PR to highlight this in the API doc.

**Comment by CarsonStevens** [comment]
> Your input works "by chance" with v1.13.0 in the sense that the distance matrix is totally ignored. Now using the latest code, `matrices.truck.distances` is indeed parsed and it's not valid since integer values are expected and you have floats.
> 
> My guess is that your distances are km. If I convert them all to meters, I get the exact same solution with v1.14.0-rc.3 (except for the additional reported distances).

The was the solution for me. Both distances and durations for the custom matrices had to be integers to not get the `{"code":2,"error":"Invalid matrix entry."}`. Our OSRM server is returning meters and seconds, but the resolution is with an extra decimal place. Converting these values to ints (loss of resolution) fixed this problem. This loss of resolution can be seen through the response cost. Not a huge effect on this project, but might affect some.

No custom matrice: `{'cost': 91398, 'routes': 1, 'unassigned': 0, 'setup': 0, 'service': 4800, 'duration': 4998, 'waiting_time': 0, 'priority': 4, 'violations': [], 'computing_times': {'loading': 103, 'solving': 1}}
`
Custom matrice: `{'cost': 91397, 'routes': 1, 'unassigned': 0, 'setup': 0, 'service': 4800, 'duration': 4997, 'waiting_time': 0, 'priority': 4, 'violations': [], 'computing_times': {'loading': 0, 'solving': 1}}`

Potentially adding float resolution to custom matrice request could be an easy feature to add.

Request with distance and duration floats:
`{'vehicles': [{'id': 58932,
   'description': '58932',
   'start': [-111.97499847, 41.19810104],
   'end': [-111.97499847, 41.19810104],
   'time_window': [25200, 61200],
   'max_travel_time': 48000.0,
   'breaks': [{'time_windows': [[36000.0, 59400]],
     'service': 1800,
     'description': '>= 8 hours; 30 minute unpaid meal',
     'flexible': 1800,
     'id': 0}],
   'costs': {'fixed': 86400},
   'speed_factor': 0.95,
   'profile': 'car',
   'skills': [1, 2, 3, 4, 5, 6, 7, 8, 36, 18, 19, 58932],
   'start_index': 2,
   'end_index': 3}],
 'jobs': [{'id': 4761426,
   'description': '4761426',
   'location': [-111.88706, 40.863297],
   'service': 1500,
   'priority': 1,
   'time_windows': [[28800, 72000]],
   'skills': [5],
   'location_index': 0},
  {'id': 4761402,
   'description': '4761402',
   'location': [-111.842094, 40.872772],
   'service': 1500,
   'priority': 3,
   'time_windows': [[28800, 72000]],
   'skills': [5],
   'location_index': 1}],
 'matrices': {'car': {'durations': [[0, 459.5, 2030.8, 2030.8],
    [466.4, 0, 2260.9, 2260.9],
    [2049.1, 2263.3, 0, 0],
    [2049.1, 2263.3, 0, 0]],
   'distances': [[0, 5681.8, 42206.2, 42206.2],
    [5681.8, 0, 44037.9, 44037.9],
    [42487.3, 44193.2, 0, 0],
    [42487.3, 44193.2, 0, 0]]}}}`
Response: `{'code': 2, 'error': 'Invalid matrix entry.'}`
 
Request with just integer distance:
`{'vehicles': [{'id': 58932,
   'description': '58932',
   'start': [-111.97499847, 41.19810104],
   'end': [-111.97499847, 41.19810104],
   'time_window': [25200, 61200],
   'max_travel_time': 48000.0,
   'breaks': [{'time_windows': [[36000.0, 59400]],
     'service': 1800,
     'description': '>= 8 hours; 30 minute unpaid meal',
     'flexible': 1800,
     'id': 0}],
   'costs': {'fixed': 86400},
   'speed_factor': 0.95,
   'profile': 'car',
   'skills': [1, 2, 3, 4, 5, 6, 7, 8, 36, 18, 19, 58932],
   'start_index': 2,
   'end_index': 3}],
 'jobs': [{'id': 4761426,
   'description': '4761426',
   'location': [-111.88706, 40.863297],
   'service': 1500,
   'priority': 1,
   'time_windows': [[28800, 72000]],
   'skills': [5],
   'location_index': 0},
  {'id': 4761402,
   'description': '4761402',
   'location': [-111.842094, 40.872772],
   'service': 1500,
   'priority': 3,
   'time_windows': [[28800, 72000]],
   'skills': [5],
   'location_index': 1}],
 'matrices': {'car': {'durations': [[0, 459.5, 2030.8, 2030.8],
    [466.4, 0, 2260.9, 2260.9],
    [2049.1, 2263.3, 0, 0],
    [2049.1, 2263.3, 0, 0]],
   'distances': [[0, 5681, 42206, 42206],
    [5681, 0, 44037, 44037],
    [42487, 44193, 0, 0],
    [42487, 44193, 0, 0]]}}}`
Reponse: `{'code': 2, 'error': 'Invalid matrix entry.'}`

Request with both distance and durations as integers
`{'vehicles': [{'id': 58932,
   'description': '58932',
   'start': [-111.97499847, 41.19810104],
   'end': [-111.97499847, 41.19810104],
   'time_window': [25200, 61200],
   'max_travel_time': 48000.0,
   'breaks': [{'time_windows': [[36000.0, 59400]],
     'service': 1800,
     'description': '>= 8 hours; 30 minute unpaid meal',
     'flexible': 1800,
     'id': 0}],
   'costs': {'fixed': 86400},
   'speed_factor': 0.95,
   'profile': 'car',
   'skills': [1, 2, 3, 4, 5, 6, 7, 8, 36, 18, 19, 58932],
   'start_index': 2,
   'end_index': 3}],
 'jobs': [{'id': 4761426,
   'description': '4761426',
   'location': [-111.88706, 40.863297],
   'service': 1500,
   'priority': 1,
   'time_windows': [[28800, 72000]],
   'skills': [5],
   'location_index': 0},
  {'id': 4761402,
   'description': '4761402',
   'location': [-111.842094, 40.872772],
   'service': 1500,
   'priority': 3,
   'time_windows': [[28800, 72000]],
   'skills': [5],
   'location_index': 1}],
 'matrices': {'car': {'durations': [[0, 459, 2030, 2030],
    [466, 0, 2260, 2260],
    [2049, 2263, 0, 0],
    [2049, 2263, 0, 0]],
   'distances': [[0, 5681, 42206, 42206],
    [5681, 0, 44037, 44037],
    [42487, 44193, 0, 0],
    [42487, 44193, 0, 0]]}}}`
Response: `{'code': 0, 'summary': {'cost': 91397, 'routes': 1, 'unassigned': 0, 'setup': 0, 'service': 4800, 'duration': 4997, 'waiting_time': 0, 'priority': 4, 'violations': [], 'computing_times': {'loading': 0, 'solving': 1}}, ...}`
