### ISSUE TITLE
Is there a way to dynamically add time windows?

### ISSUE THREAD

**Issue by BokYannEVCO** [VROOM-Project/vroom#1045]
I have a jobs that I would like to assign to workers and subsequently create a schedule for them. These jobs can happen monthly, fornightly, etc. 

I am trying to use vroom to basically assign the tasks optimally based on their distance and also these 'timing windows' that they have. However, I am coming across a problem when trying to create a 4 month schedule as they get assigned too close to one another and does not follow the stipulated timing window that I need. For example, a monthly job may happen at the end of this month and also the start of the next month which is wrong. What i need is a month long difference between this job and the next.

Is there a way that vroom can support this?

**Comment by jcoupey** [comment]
No, there is no way to set constraints on difference between visits other than by choosing TW in your model. See https://github.com/VROOM-Project/vroom/issues/902#issuecomment-1467696861 for more details.

**Comment by jcoupey** [comment]
Closing as answered.
