### ISSUE TITLE
Slow loading and routing times with OSRM

### ISSUE THREAD

**Issue by SimonBradley1993** [VROOM-Project/vroom#1046]
We're seeing slow loading and routing times reported by Vroom, even for very small optimisation requests. We've just updated OSRM to CH algorithm and haven't seen any performance improvements for small requests. We're a bit unclear on the process Vroom is taking when it is monitoring the `loading` time, but we can see the OSRM requests are responding extremely quickly with Vroom taking 1s for both `loading` and `routing`.

Using this Vroom request as an example with the `-g` flag enabled : 

```
{"vehicles":[{"id":0,"start":[0.148317,52.671397],"end":[0.148317,52.671397]},{"id":1,"start":[-1.099386,53.751111],"end":[-1.099386,53.751111]},{"id":2,"start":[1.316472,52.104216],"end":[1.316472,52.104216]}],"jobs":[{"id":0,"location":[-0.992666,51.579481]},{"id":1,"location":[-2.362146,53.454536]},{"id":2,"location":[1.405839,51.339921]},{"id":3,"location":[-1.854486,52.157928]},{"id":4,"location":[-0.005142,51.449163]},{"id":5,"location":[0.095966,51.39239]},{"id":6,"location":[-0.005909,51.768088]},{"id":7,"location":[-4.293411,55.888554]},{"id":8,"location":[-5.960468,54.617074]},{"id":9,"location":[-1.580776,53.676541]}]}
```

With the compute times response of 

```
"computing_times":{"loading":1012,"solving":1,"routing":1020}
```

The OSRM logs show a few requests, 2 of which are the table and route requests which show 9.3ms and 17ms response times respectively : 

```
[2023-11-28T11:12:51.526140837] [info] 28-11-2023 11:12:51 9.37702ms 127.0.0.1 - - 200 /table/v1/car/0.148317,52.671397;-1.099386,53.751111;1.316472,52.104216;-0.992666,51.579481;-2.362146,53.454536;1.405839,51.339921;-1.854486,52.157928;-0.005142,51.449163;0.095966,51.392390;-0.005909,51.768088;-4.293411,55.888554;-5.960468,54.617074;-1.580776,53.676541
```

```
[2023-11-28T11:12:52.546314627] [info] 28-11-2023 11:12:52 17.1922ms 127.0.0.1 - - 200 /route/v1/car/-1.099386,53.751111;-0.005909,51.768088;1.405839,51.339921;0.095966,51.392390;-0.005142,51.449163;-0.992666,51.579481;-1.854486,52.157928;-2.362146,53.454536;-5.960468,54.617074;-4.293411,55.888554;-1.580776,53.676541;-1.099386,53.751111?alternatives=false&steps=false&overview=full&continue_straight=false
```

We aren't surely exactly what Vroom is doing with the OSRM responses but can see it is building the distance matrices in parts.  I wouldn't expect that to take the ~ 990ms remainder of the 1s reported loading time when the OSRM response was around 9ms.

Our OSRM is running on a separate EC2 instance on AWS and Vroom is invoked on the CLI. Manually triggering Vroom while on the box and sending the same OSRM requests show the same behaviour - slow Vroom response and fast OSRM response.

We've also tried this with a single engineer and a single job and are getting the same 2s response time.

Is there something we've set up incorrectly or is Vroom taking a while to deserialise the response from OSRM? Or is there something else going on?

**Comment by jcoupey** [comment]
The various time points used for the computing time reports are defined in the `Input` class:

https://github.com/VROOM-Project/vroom/blob/b9928306a4d44886fb610600ea52b18fb7bb7bf6/src/structures/vroom/input/input.h#L33-L38

All durations are computed within the `Input::solve` function. The loading phase includes parsing the input, computing the matrices and doing some extra preprocessing on the instance (see https://github.com/VROOM-Project/vroom/blob/b9928306a4d44886fb610600ea52b18fb7bb7bf6/src/structures/vroom/input/input.cpp#L1093-L1117). Computing the matrix itself does include the routing engine call (and result deserialization) plus some extra checks. Especially for big instances, the loading time is usually dominated by matrix computing.

The `routing` phase is simply wrapping the routing engine call for the geometry so in that sense it is closer to the actual routing request duration, see https://github.com/VROOM-Project/vroom/blob/b9928306a4d44886fb610600ea52b18fb7bb7bf6/src/structures/vroom/input/input.cpp#L1144-L1160 (used to be a bit of additional work there up to v1.13.0).

Now the completion time reported in OSRM logs and the "routing request duration" as seen from a remote server may be quite different. My first guess is most of the time you see in loading and routing are spent in network exchanges. You can easily check that by bypassing VROOM altogether and sending the same OSRM request that you have in the logs from the box running VROOM.

**Comment by jcoupey** [comment]
> The total request time was 12ms.

Is it the request time as reported by OSRM in the logs, or a measure you did from the VROOM box calling OSRM remotely? In the latter case, can you share exactly how you timed the OSRM request sent outside VROOM?

**Comment by SimonBradley1993** [comment]
I got the 12ms value by measuring the request from the Vroom box calling out to the remote OSRM instance. I did this by running : 

```
curl -w "@curl-format.txt" "http://osrmurl:5000/table/v1/car/0.148317,52.671397;-1.099386,53.751111;1.316472,52.104216;-0.992666,51.579481;-2.362146,53.454536;1.405839,51.339921;-1.854486,52.157928;-0.005142,51.449163;0.095966,51.392390;-0.005909,51.768088;-4.293411,55.888554;-5.960468,54.617074;-1.580776,53.676541"
```

And this responds with the metrics : 

```
time_namelookup:  0.001509s
time_connect:  0.001920s
time_appconnect:  0.000000s
time_pretransfer:  0.001942s
time_redirect:  0.000000s
time_starttransfer:  0.012620s 
             ---------- 
   time_total:  0.012702s
```

**Comment by jcoupey** [comment]
Hum, I can't really reproduce this difference. When solving your input against the demo server, I get:

```bash
curl --header "Content-Type:application/json" --data @input.json http://solver.vroom-project.org | jq .summary.computing_times
{
  "loading": 11,
  "solving": 1,
  "routing": 24
}
```

The matching logs from the demo server instance are:

```
[info] 28-11-2023 16:42:20 10.7003ms 127.0.0.1 - - 200 /table/v1/car/0.148317,52.671397;-1.099386,53.751111;1.316472,52.104216;-0.992666,51.579481;-2.362146,53.454536;1.405839,51.339921;-1.854486,52.157928;-0.005142,51.449163;0.095966,51.392390;-0.005909,51.768088;-4.293411,55.888554;-5.960468,54.617074;-1.580776,53.676541
[info] 28-11-2023 16:42:20 23.3208ms 127.0.0.1 - - 200 /route/v1/car/-1.099386,53.751111;-0.005909,51.768088;1.405839,51.339921;0.095966,51.392390;-0.005142,51.449163;-0.992666,51.579481;-1.854486,52.157928;-2.362146,53.454536;-5.960468,54.617074;-4.293411,55.888554;-1.580776,53.676541;-1.099386,53.751111?alternatives=false&steps=false&overview=full&continue_straight=false
```

OSRM reports 10.7003ms for the `table` request and 23.3208ms for the `route` request, which is totally in line with the 11 and 24 values we get in the VROOM response.

Since I can't reproduce, this would probably require some advanced debugging on your side to determine what is actually taking much longer. Are you experiencing similar discrepancies when solving bigger instances?

**Comment by SimonBradley1993** [comment]
Thanks for trying to reproduce this, it's good to see that you're able to get very quick loading and routing times which are similar to the OSRM response times.

I've just attempted this locally and am seeing the same thing as you, around 450ms response for OSRM and the same figure reported by Vroom.

We'll have to do some investigation for our setup on AWS to find out where the issue is.
