### ISSUE TITLE
select a job as optional

### ISSUE THREAD

**Issue by janderadutra** [VROOM-Project/vroom#1047]
How do I make a job optional? I know there are priorities, but but it is not the same.

**Comment by jcoupey** [comment]
Priorities are a way to get control on what is assigned or not in a scenario where not everything can be done.

> it is not the same.

Sounds very similar to me, can you maybe elaborate on the difference for your use-case?

**Comment by jcoupey** [comment]
All tasks are tied to a specific location so there is no way to handle time-dependent locations.

**Comment by janderadutra** [comment]
Today it is very common to have several options with alternative delivery locations. Imagine giving 3 delivery location options, it would be much more agile. I'll try to implement this solution, if it works I'll commit it. Thanks.
