### ISSUE TITLE
Set two parameters for capacity

### ISSUE THREAD

**Issue by salarnz** [VROOM-Project/vroom#1050]
Hi
is there any way to set two parameter for vehicle capacity?
For example, vehicles have two limits for cargo. weight limit and volume limit. but we have only 1 parameter for it in vroom ( capacity ).

**Comment by jcoupey** [comment]
As stated in the docs, `capacity` is _"an array of integers describing multidimensional quantities"_, so you can use any arbitrary number of metrics you want.

**Comment by jcoupey** [comment]
Yes, exactly.
