### ISSUE TITLE
priority for a specific time_window item

### ISSUE THREAD

**Issue by Bonjour123** [VROOM-Project/vroom#1051]
First, thanks for the good work. 
I wanted to know if it was possible to set priorities on each item of the time_window array in a shipment step. 
The specific use-case is that someone would set an ideal time-window for, let's say a pickup, but if not possible, this person could also add one (or more) fallback time-windows.

**Comment by jcoupey** [comment]
> if the task cannot be accommodated within its main time window

My point is that you can't have a simple task-level reasoning for this. The ability to assign a task depends on its TW of course, but also of other constraints for this task **and** the full plan that is considered, which in turn is connected with all other tasks/vehicles constraints.

> the fallback time windows come into play only after it's determined that the task cannot fit 

Sounds like you could actually apply this approach yourself: solve with main TW, then if a task gets unassigned fallback to another TW in another solving round.

**Comment by jcoupey** [comment]
Closing as answered, feel free to provide feedback on the last suggestion or re-open with new input.
