### ISSUE TITLE
Multiday 'evenly' distributed same-adress stops.

### ISSUE THREAD

**Issue by cpprofs** [VROOM-Project/vroom#1052]
Dear Jcoupey, 

Casus:
You have a delivery company of for example food. Your customer gives you days on which you are allowed to deliver it (time windows). 

Let's also say you stock up this customer's warehouse for around 4 weeks. This means you need to deliver the next stock at a maximum within 4 weeks, but taking in acount other customers, you have a week margin, so you can come by for the next delivery between 3-4 weeks after the previous one. 

Question:
Is it possible for the algorithm to somehow deal with recurring deliveries, based upon the previous delivery? Or should I mark this as a feature request (if at all feasable).

**Comment by jcoupey** [comment]
This is more like a periodic VRP and there is no way to handle that kind of constraint in VROOM. See also #958 and #902 on related topics.

Other more flexible solving engines such as OR-Tools may be more appropriate to add this kind of additional constraint. My advice if you still want to use VROOM for this would be to translate the recurring aspect into modelling choices that VROOM can understand. This means making assumptions and probably reducing flexibility compared to the generic model, but this could work if you make sound choices based on business constraints.
