### ISSUE TITLE
Enforcing Specific Starting Point for Vehicle Route

### ISSUE THREAD

**Issue by moh96af** [VROOM-Project/vroom#1054]
Hello,

I've been working on setting up vehicle routing and encountered a scenario where the vehicle does not start from the assigned starting point. According to the documentation, vehicle steps are used only if they are valid. I'm looking for a way to enforce the starting point for a vehicle, ensuring it begins its route exactly where specified, even if other pickups are geographically closer.

My current setup involves a vehicle (Vehicle 1) with orders ready for pickup at various locations. The vehicle is explicitly assigned to start at Al Abdallah restaurant; however, the route starts at Wooden Bakery instead.

![2023-12-26_15-51](https://github.com/VROOM-Project/vroom/assets/31189844/685c62f4-f8ec-4fc9-8b94-6f680b42d256)

Here is the JSON body:

```
{
    "vehicles": [
        {
            "id": 1,
            "description": "Shopper in store (Al Abdullah)",
            "capacity": [2],
            "max_tasks": 4,
            "start": [35.573740, 33.903584],
            "steps": [
                {
                    "type": "pickup",
                    "id": 1
                },
                {
                    "type": "delivery",
                    "id": 2
                }
            ]
        }
    ],
    "shipments": [
        {
            "pickup": {
                "id": 1,
                "description": "Al Abdullah order",
                "location": [35.573740, 33.903584]
            },
            "delivery": {
                "id": 2,
                "description": "Al Abdullah client",
                "location": [35.591753, 33.896119]
            },
            "amount": [1]
        },
        {
            "pickup": {
                "id": 5,
                "description": "Wooden Bakery order",
                "location": [35.573233, 33.903196]
            },
            "delivery": {
                "id": 6,
                "description": "Wooden Bakery client",
                "location": [35.581014, 33.905217]
            },
            "amount": [1]
        },
        {
            "pickup": {
                "id": 7,
                "description": "Malak Al Tawouk order (near wooden bakery)",
                "location": [35.576267, 33.903813]
            },
            "delivery": {
                "id": 8,
                "description": "Malak Al Tawouk client (near wooden bakery)",
                "location": [35.580511, 33.906136]
            },
            "amount": [1]
        },
        {
            "pickup": {
                "id": 9,
                "description": "Pizzanini order",
                "location": [35.578701, 33.899912]
            },
            "delivery": {
                "id": 10,
                "description": "Pizzanini client",
                "location": [35.598503, 33.897005]
            },
            "amount": [1]
        }
    ]
}
```
Expected Assignment:
![2023-12-26_15-50](https://github.com/VROOM-Project/vroom/assets/31189844/0102a1fc-c9d9-4179-b344-36f2ce160028)

Actual Assignment:
![2023-12-26_15-50_1](https://github.com/VROOM-Project/vroom/assets/31189844/f55a6a24-8bf0-4587-876d-3acb09c4bd45)

Is there an attribute or a setting I can use to enforce the starting point for Vehicle 1 to be Al Abdallah resto regardless of other variables?

**Comment by jcoupey** [comment]
The start point is always the `vehicle.start` location, which in your case has the exact same coordinates as the Al Abdallah restaurant. So your vehicle does actually start from there (check the output start step).

Now what probably happens is that despite starting there, the vehicle does not handle the shipment whose pickup is located there, simply because the solution you get has a lower cost.

**Comment by moh96af** [comment]
Thank you for the clarification. I understand that the vehicle starts from the `vehicle.start` location. However, I need to ensure that a pre-assigned order (already picked up by the driver at Al Abdallah) is delivered first. The current behavior has the vehicle starting at Al Abdallah but then picking up another order from Wooden Bakery instead of delivering the Al Abdallah order, which is already on board.

In a scenario where the starting shipment is locked, I expect the driver to deliver both Al Abdullah and Pizzanini orders, as their clients are near each other. 

Is there a configuration in VROOM to lock in a shipment start or force the driver to deliver a specific order first?

**Comment by jcoupey** [comment]
No, there is no notion of "locked" task to directly force things into a route. The "deliver first" part could be handled using time windows but depending on the use-case that is not always very flexible. Again in your situation it's not about ordering but rather that you get an unexpected solution with different shipments assigned simply because it's cheaper overall.
