### ISSUE TITLE
Simply get output 'killed'

### ISSUE THREAD

**Issue by cpprofs** [VROOM-Project/vroom#1056]
Dear jcoupey,

In commandline, the command stops without any message other than 'Killed':

This is within my docker:
root@9628ac498d0d:/vroom-express/junction# vroom -i data.json -a driving-car:172.18.0.2 -p driving-car:8080 -g -o data_sol.json -r ors -t 32
Killed

Usually it saves something in data_sol.json but this time I just get the message Killed.

**Comment by nilsnolde** [comment]
sounds like out of memory. did you monitor RAM usage?

**Comment by cpprofs** [comment]
hmm it seems my ors docker quit working. It has 64gb of ram, i never saw memory rise over 70%. Let's see if it quits after 5 minutes of hard number crunching labor.

**Comment by nilsnolde** [comment]
what did the logs of the ors container say?

**Comment by nilsnolde** [comment]
matrix does use some memory, but not nearly as much as other engines, e.g. valhalla. although that does also depend on your exact ORS server configuration (and possibly request, but haven't been looking into ORS for years), at which point it's probably better to start a discussion at their repo:)

**Comment by cpprofs** [comment]
So you would think this is not a VROOM issue? The matrix has already been created by ORS at the time of 'being killed'. What I assume is, first a matrix is made by ORS, it only uses one thread and lots of memory. Afterwards VROOM takes over, you see all 32 threads going to 100%. After about 5-6 minutes, it just gives the message 'Killed'.  I have not seen this before to be honest. 

I do get the unfortunate result of it suddenly stopping without any error logs anywhere after 5-6 hours of work. But that's may be some other issue.

**Comment by nilsnolde** [comment]
Didn't you say your ORS container stopped working? Doesn't sound like it was done?

If it was done indeed, then yeah, some vroom stuff likely exceeds some hardware limitation, disk, ram, whatever (I have little idea of the internals). Probably worth noting what your problem size was, or even attach the full json.

**Comment by cpprofs** [comment]
Ah, I am not sure why VROOM starts to use it's threads but it is ORS memory issue: ors-app exited with code 137. Thanks for thinking with me!
