### ISSUE TITLE
Question about breaks in vehicles

### ISSUE THREAD

**Issue by Richard6536** [VROOM-Project/vroom#1057]
Hi,

I'm having some trouble understanding how breaks work. I'll give some examples:

Let's say I have a vehicle with a time_window:
Start window: **08:30**
End window: **18:30**

The result is that the route starts at 08:30 and ends before 10:00. That's fine.

Input: https://pastebin.com/panTfW7b
Output: https://pastebin.com/znf8z8jQ

![sin_break](https://github.com/VROOM-Project/vroom/assets/26555098/6442cdee-6cd2-41cd-96f1-2d4cffb4c802)

Now, let's suppose I add a break to the vehicle:
Start break: **13:00**
End break: **14:30**

The result is that the route begins much later than 08:30 and ends just after the break. I was expecting the same result as the first example, because the route could easily starts at 08:30 and end before the break.

Input: https://pastebin.com/aKSZESu1
Output: https://pastebin.com/UHk7TcE1

![con_break](https://github.com/VROOM-Project/vroom/assets/26555098/5595840a-42b0-4d9e-b8f6-16af64a21b62)

Additionally, as a third example, when I change the break to:
Start break: **09:00**
End break: **12:00**

The break is not respected.

Input: https://pastebin.com/R0JxQsLV
Output: https://pastebin.com/EUMrVevs

![error_break](https://github.com/VROOM-Project/vroom/assets/26555098/7af64eac-bf04-46ce-988a-631b7c1ed815)

Thanks.

**Comment by jcoupey** [comment]
> I was expecting the same result as the first example, because the route could easily starts at 08:30 and end before the break.

Breaks provided in input are mandatory, they will always be present in output. So if we were to start the route earlier, that would result in a huge waiting time before the break can happen. You can see that as a matter of how the route is presented: as a general rule we return "packed" routes in output to minimize internal waiting time. In your situation the break is the only task with a timing constraint, so it "attracts" the other tasks timewise later in the day.

> The break is not respected.

Can you elaborate on this? The break start time in output in your third example is definitely in the initially provided time window.

**Comment by Richard6536** [comment]
Thanks @jcoupey, I understand.

In relation to the third example, if I set the time window for the break at 9 am, I was wondering why there are 2 jobs scheduled after 9 am.

![error_break](https://github.com/VROOM-Project/vroom/assets/26555098/08bfa07c-5595-4bf3-b4e4-3898fd30bfb4)

**Comment by jcoupey** [comment]
Can you be more specific on how you "set the time window for the break at 9 am"?

**Comment by Richard6536** [comment]
In my input for the third example, I defined this break: 

'breaks': [{'id':1,'time_windows':[[32400,43200]],'service':300}].

This time_window is supposed to start at 9 a.m and ends at 12 p.m. I was wondering why there are 2 jobs that start after 9 a.m when there is a time_window break defined during that time. Shouldn't these jobs continue after the break is over?

**Comment by jcoupey** [comment]
There is a misunderstanding here: the time window for the break does not describe the full span of the break. As per the docs, the `time_windows` key is an *array of `time_window` objects describing valid slots for break start*. 

In your example it means the break is valid if it **starts** any time between 9:00 and 12:00. The length of the break itself is 5 minutes (`service` key). So it is totally valid to have any set of tasks before the break as long as it starts before 12:00.

**Comment by Richard6536** [comment]
Now everything makes sense, thanks you!
