### ISSUE TITLE
VROOM ignores my capacities

### ISSUE THREAD

**Issue by cpprofs** [VROOM-Project/vroom#1058]
I somehow managed to get back routes with higher capacity per verhicle than allowed. (I removed some data for privacy purposes)

This is a vehicle, all with the same properties:

```
[{'id': 170652240011,
  'profile': 'driving-car',
  'start': [],
  'end': [],
  'capacity': [211],
  'time_window': [1706522400, 1706554800],
  'description': '',
  'cost': {'fixed': -3600, 'per_hour': 3600, 'per_km': 10},
  'skills': [5]},
```

This is a delivery:

```
[{'id': 0,
  'location': [],
  'service': 6000,
  'amount': [30],
  'time_windows': [[1707829200, 1707850800]]},
```

If I understood the readme correctly, the capacity of the vehicle will never be higher than 211? So in this case I could manage about 7 deliveries with amount 30 right? 

In the final results, I get routes of 400. 

I did do something experimental like making the fixed cost of using a vehicle negative, to force the use of vehicles, I actually believe that the algorithm actually takes the absolute value doing the exact opposite of what I hope to achieve. 

Also, at this moment the deliveries do not have skills, this should not matter right? A vehicle with a skill, can do all deliveries without skills, and those with matching skills?

**Comment by jcoupey** [comment]
> the capacity of the vehicle will never be higher than 211? So in this case I could manage about 7 deliveries with amount 30 right?

Sounds right.

> In the final results, I get routes of 400.

Hard to help here without being able to reproduce the problem. Can you share a minimum (non-)working example?

**Comment by cpprofs** [comment]
I think it was a combination of the negative values of fixed cost in combination with wrong use of skills.
