### ISSUE TITLE
Vehicle id is always 1 in the model's output result json

### ISSUE THREAD

**Issue by debasmita-dutta** [VROOM-Project/vroom#1059]
Hello,
I am using the ORS routing engine to execute the VROOM optimization. The model is running fine and the results are coming as well. While analyzing the output json, I have observed that in the 'route' object, the 'vehicle' has always the value 1. Which implies that the vehicle id is 1. However in the model the vehicle number is mentioned as 100 and there are 57 jobs to perform.  The result shows that all jobs are performed as expected. The amount, distance all these values are also being displayed in the json correctly. The only thing which makes me curious is that, why the vehicle id is always 1.  As per my understanding, it will increase for each job delivery.
Could you please explain?

**Comment by jcoupey** [comment]
> it will increase for each job delivery

No, the `routes[].vehicle` values in output have nothing to do with jobs, their purpose is to allow matching an outputted route with one of the vehicles that were provided in input.

If all the `routes[].vehicles` values are 1 in output, it's probably that you defined all `vehicles[].id` values to 1 in input. If not, then please share an actual instance to look at.

**Comment by debasmita-dutta** [comment]
Hello,
Thank you for your response. Sorry for the late reply.
I have used ORS routing engine. The vehicles are defined like below and all vehicles have different ids.

vehicles = list()
    cnt=0
    for d in depot.itertuples():
        for idx in range(vehicle_cnt):        
            vehicles.append(
                ors.optimization.Vehicle(
                id=cnt+1,
                profile = 'driving-hgv',
                start=[d.lon,d.lat],
                capacity=vehicle_capacity
            ))


The delivery or demand detail is something like below. It's just a snapshot and also the location coordinates are masked.
I have more than 50 deliveries to be done. The constraints are 34000 for volume and 25000 for weight. For a single customer there can be multiple entries as the demand is high, multiple entries are created so that the model sends multiple vehicles to the same location. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/debasmitadutta/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/debasmitadutta/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


cust_id | demand_volume | demand_weight | cust_lat | cust_lon
-- | -- | -- | -- | --
1 | 34000 | 16000 | 0.0003 | 0.0003
2 | 33000 | 19000 | 0.0003 | 0.0003
3 | 33000 | 20000 | 0.0004 | 0.0004
4 | 34000 | 25000 | 0.0005 | 0.0005
5 | 30000 | 25000 | 0.0005 | 0.0005
6 | 33000 | 25000 | 0.0006 | 0.0006



</body>

</html>


I can ensure from the json output that, when the model runs, all deliveries are done.  But my only concern is the vehicle.id in the json.
Attaching a sample json from a successful output result. It might not be in sync with the above delivery example. I have truncated the json and also masked the location coordinates.

[json_result_routes_copy.txt](https://github.com/VROOM-Project/vroom/files/13986499/json_result_routes_copy.txt)


Could you please advise me, why the vehicle ids are always 1 in the json.

**Comment by nilsnolde** [comment]
Wait, are you using https://github.com/GIScience/openrouteservice-py (I authored that a long time ago, but still recognize it..)? If so, you're using the hosted VROOM version at ORS, right? Then I'd recommend you first install VROOM locally **from master** and try your examples again.

**Comment by nilsnolde** [comment]
FWIW, I have not at all read anything you wrote other than the bit of code..

**Comment by jcoupey** [comment]
As far as I can tell, `id` will always be 1 since you never increment your `cnt` counter variable in the above code snippet.
