### ISSUE TITLE
vroom 1.14.0 osx build failure due to `jthread`

### ISSUE THREAD

**Issue by chenrui333** [VROOM-Project/vroom#1062]
Apple clang MacOS does not accept yet `jthread` C++ 20 extension (see https://en.cppreference.com/w/cpp/compiler_support/20), while vroom uses it. Thus vroom [does not compile with Apple clang](https://github.com/Homebrew/homebrew-core/pull/160054).

One solution is to follow rule CP.4 of [CppCoreGuidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md): "Think in terms of tasks, rather than threads". Thus, vroom should prefer `std::async` to `std::jthread`.

**Comment by jcoupey** [comment]
The use of `std::jthread` over `std::thread` was introduced in 02eb40b4e as part of a refactoring based on the sonarcloud static analysis recommendations. A quick fix for anyone needing to build using Apple clang would be to simply `git revert 02eb40b4e` (works out of the box on the release branch).

Thanks for pointing out the recommendation in the core guidelines. I have virtually no knowledge of `std::async` but I can see the benefit of using a higher-level abstraction. So happy to look at options for this kind of replacement. The only potential concern would be to know whether we can still tune the number of underlying threads that are used. Not only do we do it currently, but we allow users to decide on that parameter with the `-t` option.

**Comment by chenrui333** [comment]
Cool, cool, I will just revert that commit to my homebrew PR. Thanks for the pointer!

**Comment by jcoupey** [comment]
What is the status here? Looks like the downstream PR https://github.com/Homebrew/homebrew-core/pull/160054 has been closed, shall we close this ticket too?

**Comment by jcoupey** [comment]
Closing as stale.
