### ISSUE TITLE
beyond the route

### ISSUE THREAD

**Issue by gutofurlan** [VROOM-Project/vroom#1063]
Good evening, I have the following problem, I spend enough work to be done in one day (tested if I put the start at 08:00:00 and end at 18:00:00 perfectly it fits, however if I spend the same amount of job and in the end date add 1 extra day, he must use this extra day, even though he doesn't need it, he allocates some jobs to the end.
EX. 10 jobs starting on 2023-01-17 08:00:00 ending on 2023-01-17 188:00:00, allocates without orphan...
Now if I place the same 10 jobs, starting on 2023-01-17 08:00:00 ending 2023-01-18 18:00:00, it allocates without orphan, however it places some jobs to do on the 18th, even without need ...
Does anyone know what it could be?
Thanks

**Comment by jcoupey** [comment]
It's hard to provide a specific answer with just a verbal description. Can you please share both instances inputs and solutions and pinpoint what exactly in the second solution is unexpected?
