### ISSUE TITLE
Feature request : fixed location(s) for vehicle break

### ISSUE THREAD

**Issue by answerquest** [VROOM-Project/vroom#1064]
Hi, thank you for this amazing software.  
In input json, for each `vehicle`, we're able to specify `breaks`, with each break object containing a time duration and time windows for the break to happen in.

We have a requirement wherein there are designated break locations for each vehicle/driver in the operating region. This can include reserved restrooms, washrooms, canteen, charging etc. We want to optimise the jobs in such a way that the job locations nearest to the break location get selected before and after the break time. Basically, the vehicle shouldn't have to travel from and to another end of the city for break time. 

This can have two variations, second might be tougher to implement:
- 1. One break location provided for the vehicle, so in addition to starting and ending point, there is a fixed midway point
- 2. Multiple possible break locations provided and a vehicle can go to any one of them; and vroom chooses most convenient one as per the jobs/shipments locations

The first variation could also be implemented by breaking up one vehicle entry into two with successive operating shifts - one ending before the other starts, setting the end location of first shift as the break location and start location of second shift as the break location.

But the second variation would be the desired feature to have, so that optimization of deliveries/pickups is done in tandem with choosing the most convenient break location.

Requesting authors and contributors to please explore ways to make this happen.

I haven't been able to find a matching issue/PR to this in this repo; if there's already a similar post then kindly point me to it. Thanks in advance!

**Comment by jcoupey** [comment]
> One break location provided for the vehicle,

That first variation simply amount to defining the break as a job forced upon the vehicle. So you should already be able to handle that.

> The first variation could also be implemented by breaking up one vehicle entry into two with successive operating shifts

That is not very flexible as you'd have to decide on the splitting time beforehand, while using a job leaves some flexibility wrt time windows.

> optimization of deliveries/pickups is done in tandem with choosing the most convenient break location

On the idea of having the optimization choose between several locations, I totally understand how that could be useful in some contexts such as the one you describe. Off the top of my head, I'd say that this would probably be far from trivial to implement, though not impossible.

Meanwhile, you may have some luck using workarounds, e.g. deciding actual break locations *a priori* (and comparing options across solving rounds) or placing them with a post-processing step.

**Comment by jcoupey** [comment]
Closing as answered.
