### ISSUE TITLE
some logical problems in route optimization 

### ISSUE THREAD

**Issue by salarnz** [VROOM-Project/vroom#1066]
Hi
I think there is some logical problems in route optimization .
My main problem is that some routes are not optimal 

![111](https://github.com/VROOM-Project/vroom/assets/48475945/958abcce-e751-4d3c-b4f2-96c96ac6af0c)
![444](https://github.com/VROOM-Project/vroom/assets/48475945/07851e02-51ef-4da0-8667-de705eeef549)

For example, in the second photo, you can see that there are two routes on the map and their points are marked with yellow and brown colors. The points that have been drawn around it seem that it would be better not to be on this path

**Comment by jcoupey** [comment]
Hum, what you call a "logical" problem here sounds like a result that differs from your "geographical grouping" expectation. There are many reasons why this may still be the best solution: what is the cost of that one and the cost of another one you'd think would be more appropriate? This depends on a lot of factors that are not visible here. Is another "more grouped" solution even possible? This is highly dependent on all constraints.

If you want more feedback, please share a [reproducible instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) along with the solution you get and the one you think we should output instead.

**Comment by salarnz** [comment]
Yes, I mean that the points closer to each other could be placed in the same path. Anyway, as you said, the algorithm checks many parameters. I think I need to look deeper

**Comment by jcoupey** [comment]
Right, closing here then. Feel free to reopen with new input if required!
