### ISSUE TITLE
 Unfound route(s) from location and similar errors handling

### ISSUE THREAD

**Issue by msmolka** [VROOM-Project/vroom#1068]
When route is unfound or other routing error occurs there is no way to find out which job/vehicle is failing. Even location is in plain string.
Would it possible to give information about failing job/resource or at least location to easier remove/find problematic entries?

Currently only parsing string can be done to achieve that.

**Comment by jcoupey** [comment]
>  give information about failing job/resource

For some other errors, when we have the task/vehicle id at hand we provide it in the error message. For what it's worth, the reason we do not give info on a task and/or vehicle that causes the failure in this instance is that this error happens in the routing context where only the locations are passed (we do not track matching between locations and tasks/vehicles the other way around).

> Currently only parsing string can be done to achieve that.

Even with info on a task, e.g. a job id, you'd still have to parse the message, or maybe you have something else in mind?

**Comment by msmolka** [comment]
I was thinking if id is not possible to be passed to have location instance as separate property instead for part of error message? To easier extract correct value.

**Comment by jcoupey** [comment]
Hum, that would mean changing the API output format to add stuff that is only present in rare occasions, and just for a bit of convenience on debugging. I'm not really fond of the idea.

In my experience, 99% of such error occurrence are users switching lon,lat to lat,lon. The rest is probably people solving problems outside their map data extract. My point is in most situations it is an upstream problem that once fixed should never show up again.

**Comment by msmolka** [comment]
We have this problem quite often for UK. When e.g. have jobs in Northern Ireland and no vehicle there.

**Comment by msmolka** [comment]
Thanks for response. I took closer look to our data and tested request on http://solver.vroom-project.org. Request here is working, so the issue needs to be ors data. 

Will work with my team to solve data problem. Thanks again

**Comment by nilsnolde** [comment]
It’s not necessarily a data error. It can also be algorithmic problems or you’re trying to connect unconnected islands (eg trying to go over the Darien Gap). For Valhalla, where the algorithmic logic can’t guarantee full optimality in favor of performance, you could observe unfound connections which might not be data related. You could call them bugs, but in any case, it’s likely ouf of your hands. Same I’d expect if osrm can route smth ORS can't, one of them has a bug. Doesn’t need to be ORS but probably is:)

**Comment by msmolka** [comment]
I've double checked with other team, it looks only GB was deployed not whole UK. So that was the problem in our case :) We are now updating pipelines. Once deployed I will double check how all that works
