### ISSUE TITLE
Vehicle Prioritization by Cost per Kilometer

### ISSUE THREAD

**Issue by mauroalexandre** [VROOM-Project/vroom#1071]
Hello, is it possible to prioritize the use of vehicles based on the costs per kilometer driven?

I'm a bit confused. I updated to the latest version of VROOM, but when I input the cost_km, the result doesn't seem correct to me.

**Comment by jcoupey** [comment]
As of the previous release (v1.14.0), the cost of km driven can be accounted for internally using the `costs.per_km` key for `vehicle` objects (there is no such thing as `cost_km`).

> the result doesn't seem correct to me.

Hard to get any further here, can you expand? Ideally share a reproducible example and pinpoint precisely what looks wrong in the solution you get.

**Comment by rafaelwebrota** [comment]
Hello, @jcoupey.
I'm working with @mauroalexandre and i'm tring to help him in this question.
I'll describe the test scenarios to get a better understand about how VROOM works with flag "cost".

In your test, we tried sent 20 jobs, each job with  pickup = 100.
And we sent four vehicles to distribuit the load with capacity and cost attributes defined for each vehicle.
Vehicles:
  1) { ... , capacity : [1000, 1000, 1000] } / {... , cost: {per_km : 5000 }}
  2) { ... , capacity : [1000, 1000, 1000] } / {... , cost: {per_km : 5000 }}
  3) { ... , capacity : [100, 100, 100] } / {... , cost: {per_km : 100 }}
  4) { ... , capacity : [200, 200, 200] } / {... , cost: {per_km : 200 }}

The VROOM response, doesn't cosider the vehicles with low cost in jobs distributed.
And our doubt is how the attribute cost is considered by your API.
How can we using the cost of vehicle to be considered before the capacity ? 

Payload attached.
[example_payload.json](https://github.com/VROOM-Project/vroom/files/14314033/example_payload.json)
