### ISSUE TITLE
Assignment for food delivery where order keep coming in streams instead of batch.

### ISSUE THREAD

**Issue by itsmesubham** [VROOM-Project/vroom#1073]

**Comment by itsmesubham** [comment]
I am wondering how this will work in context of food delivery, Right now I am thinking of storing the previously assigned orders and then reusing them by adding them as a job for each of the drivers back when recalculating assignment for new orders. Is there a way where I dont have to store those assignments in DB and instead just keep on assigning orders to the best available driver? 
Best driver could be nearest or the one who will be nearest when the food is finally prepared and is ready to be delivered.

**Comment by jcoupey** [comment]
If you have dynamic orders, this requires setting up a dedicated logic to run and re-run the optimization at different times. This logic is highly dependent on the use-case and your requirements, so it's not really possible to advise in general without knowing the full story. But then it would probably go outside the scope of a simple GitHub ticket.

**Comment by itsmesubham** [comment]
Yes I have dynamic order requirement where I can get orders anytime and needs to be fulfilled ASAP, usually drivers are located near to  restaurant but mostly they could be roaming anywhere in the city, I have set up vroom and will be using the ASAP order assignment with constraints on driver like re adding incomplete preassigned jobs from previous runs of vroom before re calculating assignments.
Thanks
