### ISSUE TITLE
Is there any documents about algorithms that are using for VPRTW?

### ISSUE THREAD

**Issue by Ivinnic** [VROOM-Project/vroom#1075]
Hello, 

I want to drive deep into the algorithms that are using in this library to solve VRPTW problem.

If you can kindly provide some documents or scientific works, whatever, for better understanding, I would really appreciate!

Thank you for you hard work!

**Comment by jcoupey** [comment]
There is no paper directly describing the approach so your best bet is to look at the code. The main parts are as follow.

1. we generate a set of initial solutions (up to 32 different initial solutions) using different heuristic tuning. See https://github.com/VROOM-Project/vroom/issues/735.
2. Each solution is then refined in parallel using a local search phase were we quickly converge to a local minima using a bunch of "simple" operators, then break the current solution to start searching in a new place in the solution space.

The overall solving approach is described in [this talk](https://2018.stateofthemap.org/2018/T053-Solving_vehicle_routing_problems_with_OpenStreetMap_and_VROOM/). It was for CVRP only at the time but the overall principle remains though many new features have been added along with dedicated local search operators.
