### ISSUE TITLE
Second depot configuration

### ISSUE THREAD

**Issue by sangeetha-m-04** [VROOM-Project/vroom#1076]
I have been trying to develop a VRP model for a delivery project.  I have two depots one is the main home depot where all drivers start and end their journey and another depot (Laboratory).The delivery person delivers and pickups certain goods from different locations and all the products are either marked as refrigerated or non refrigerated. Every time the delivery person picks up a refrigerated product from a location they have to visit the Laboratory within 2 hours to drop off the product and then continue with the other deliveries. I am not able to get this to work. How can I make sure the vehicle travels to the second depot within 2 hours after picking up the refrigerated product?

**Comment by jcoupey** [comment]
> they have to visit the Laboratory [...] to drop off the product

Sounds like a typical pickup-and-delivery context, did you check the `shipment` object from the docs?
