### ISSUE TITLE
Is it possible to add "hard priority" property to jobs?

### ISSUE THREAD

**Issue by hellobody** [VROOM-Project/vroom#1077]
Hello Julien.

Thank you for creating and maintaining this great open-source project!

We would like to use VROOM for our needs, but we need to be able to influence existing algorithms to make them include jobs with highest "hard priority" value first. Like no matter how far it is and how big is the cost of the job it should be visited first and must be included into the route and never ommitted.

Here is how we expect it to work:

When some job has **"hard priority"** property with value **1**, for example, and all other jobs has this property value as **0**, the algorithms **must include the job with higher priority value first** **no matter how inefficient it may be**. (It should probably only consider time windows over hard priority. And of course take the shortest possible path to reach those high prioritized locations.)

![image](https://github.com/VROOM-Project/vroom/assets/1161879/403ce241-3ca3-4749-9de7-1b9bf92c9df6)

Could you please advice if it's possible or how difficult it may be to add kind of **"hard priority"** property to jobs and shipments?
Is it possible to add such a property without breaking existing functionality?
If so could you please advice how would you do that?

I see that there is already a "priority" property exists. But it seems like it only slightly influences algorithms decision to choose between similar by cost jobs. And the algorithms are building routes taking into account jobs location and cost based on paths duration. And looks like in existing implemenation the "priority" property isn't considered when there is only one vehicle for example and VROOM decides to use simple TSP solving algorithm to build a route. Looks like existing "priority" property is only used by CVRP algorithm implementation.

Your advice would be highly appreciated. Thank you.

**Comment by jcoupey** [comment]
The notion of `priority` we have in place is about deciding what gets into the plan or not if we cannot find a solution where everything fits in. So `priority` values impact assignment, not the time of service.

You seem to be more concerned about "urgency", which should probably translate to timing constraints. Did you try setting tight time windows for the jobs you want to happen first?

**Comment by hellobody** [comment]
I see. Time windows are slightly different from what we want. We don't have specific TWs for those locations, we just want to force an order of jobs to be of priority that we decide by our own. We just have locations which need to be visited first regardless at what time the vehicle starts its trip and at what time it'll arrive at those locations. We just want to be able to specify strict order for some locations. Is it possible? What modifications could be done to the project's code?

**Comment by jcoupey** [comment]
> We don't have specific TWs for those locations

My point is that you could maybe add TW to achieve the "visit first" requirement.

> We just want to be able to specify strict order for some locations. Is it possible?

You could provide an initial ordering using the `vehicle.steps` array, but there is no guarantee that the jobs won't be reshuffled if that results in a cheaper solution.

I'd argue that if you want to specify an ordering for (part of) a route, then there's nothing left to optimize for that part, so you may probably remove the "visit first" jobs that you already ordered and have the vehicle start only after that as far as the actual optimization is concerned.

**Comment by hellobody** [comment]
OK, I understand. Thank you.
