### ISSUE TITLE
Question: are geo locations rounded when considering setup times?

### ISSUE THREAD

**Issue by hklarner** [VROOM-Project/vroom#1078]
Two quick questions regarding the setup times of jobs.

1) If there are 2 jobs at the identical location and a third job somewhere else, then a route that visits the jobs at the same location one directly following the other only considers the setup time once. If however a route "splits" the two jobs at the same location (services another job in between) then the setup time is considered twice, right?

2) what exactly does "identical location" mean, that is, is there any precision / rounding of locations (latitude and longitude) anywhere?

Thanks for a great tool!

**Comment by jcoupey** [comment]
On 1: yes that is the intended behavior for the `setup` key.

On 2: there is no rounding involved, at least not explicitely. The coordinates from the json input are parsed as `double` [using rapidjson](https://github.com/VROOM-Project/vroom/blob/176f57a969fd2150915bdb3cdfba1607ee19e10e/src/utils/input_parser.cpp#L26). Once coordinates are stored, locations are considered "equal" based on coordinates if their lon and lat [are equal](https://github.com/VROOM-Project/vroom/blob/176f57a969fd2150915bdb3cdfba1607ee19e10e/src/structures/vroom/location.cpp#L58), as in double equality.

So if you use the exact same decimal representation in the json file, you have a guarantee that locations are considered to be the same. If you're using very close decimal values, they may or may not be represented internally with the same `double` value so you have no guarantee based on any level of rounding.
