### ISSUE TITLE
vroom Error missing duration

### ISSUE THREAD

**Issue by DejavuDaniel** [VROOM-Project/vroom#1079]
on my local everything works with vroom-express , but when i uploaded to vps server i get error : Error response: {"code":3,"error":"Missing durations."}

what is the problem ?

**Comment by jcoupey** [comment]
As per [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#code), an error code value of 3 means you encountered a routing error. Seen from that perspective the "Missing durations." message seems to indicate that we're unable to retrieve the travel time matrix from the routing engine call.

You need to check your routing setup.

**Comment by DejavuDaniel** [comment]
yes that was the problem. thanks!
maybe its possible to to get the km/miles of each route ? is there a parameter ?

**Comment by jcoupey** [comment]
> maybe its possible to to get the km/miles of each route ? is there a parameter ?

You want to check the `distance` key for `route` objects in output.

**Comment by DejavuDaniel** [comment]
and the distance is in meters ?

**Comment by jcoupey** [comment]
From [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md): _"all distances are in meters"_.
