### ISSUE TITLE
#include organization

### ISSUE THREAD

**Issue by krypt-n** [VROOM-Project/vroom#108]
As mentioned in #86, some include-statements could be moved around to improve compile times.

Things that might be worthwhile to look at:

* [x] Move unnecessary includes from .h files to .cpp files.
* [ ] Forward declare more structs/classes.
* [x] Change include paths to be relative to the project root instead of the current working directory.

**Comment by jcoupey** [comment]
Done in #109.

**Comment by sashakh** [comment]
Good improvement indeed. But two small issues:
- it breaks compilation when libosrm exists
- it breaks compilation of examples

So two tiny fixed in PR #116
