### ISSUE TITLE
Use `std::format`

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#1081]
We have a bunch of warnings in [the sonarcloud report](https://sonarcloud.io/project/issues?resolved=false&rules=cpp%3AS6185&id=VROOM-Project_vroom) about using `std::format`. I did not address this earlier in #984 or #986 simply because the support was missing in compilers at that time.

I suspect newer versions of both gcc and clang would now be OK with the changes so we should dig into this once the CI compiler upgrade in #1080 is completed.

**Comment by kkarbowiak** [comment]
On one of my machines I am using gcc 13.2.1 and clang 16.0.6 and both seem to support `std::format` nicely, so the versions mentioned in #1080 should be fine.

**Comment by SebMilardo** [comment]
I would like to help with this one, could you assign this to me?

**Comment by jcoupey** [comment]
@SebMilardo great, please feel free to open a PR. A good place to start is the sonarcloud report listing expected changes (see above link).

**Comment by jcoupey** [comment]
Thanks @SebMilardo, this removed 76 sonarcloud warnings on "maintanability issues", and those parts of the code are now indeed easier to read.
