### ISSUE TITLE
Design of Matrix class

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#1089]
Looks like the design of `Matrix` class could be improved. Here are some points:

1. `Matrix` is a template class, but is only instantiated for `uint32_t` (in fact it's `UserCost`, `UserDuration` and `UserDistance`, but all boil down to the same type).
2. The implementation is partly in source file, which requires explicit template instantiation (see: https://github.com/VROOM-Project/vroom/blob/176f57a969fd2150915bdb3cdfba1607ee19e10e/src/structures/generic/matrix.cpp#L36) to prevent linking errors. The instantation is for `UserCost`, which automatically works for `UserDuration` and `UserDistance` due to all three being an alias for `uint32_t`. Adding explicit instantiation for the latter two types for clarity results in compiler error (`duplicate explicit instantiation of ‘class vroom::Matrix<unsigned int>’`).
3. Trying to reuse the class for any other type is not possible due to linker errors.
4. The constructors could be cleaned up a bit.

I propose to leave `Matrix` as a template class but move the implementation entirely to the header file.

**Comment by kkarbowiak** [comment]
Looks like there are some other template functions implemented in source files together with explicit template instantiation, e.g. https://github.com/VROOM-Project/vroom/blob/176f57a969fd2150915bdb3cdfba1607ee19e10e/src/structures/vroom/tw_route.cpp#L1441-L1504
What is the intention of this?

**Comment by jcoupey** [comment]
> I propose to leave Matrix as a template class but move the implementation entirely to the header file.

Makes sense. As I understand it, this will allow the direct template instantiation in compilation units using the `Matrix` class, along with potential compiler optimizations.

**Comment by jcoupey** [comment]
The other explicit template instantiation occurrences (`TWRoute::is_valid_addition_for_tw` and the likes) are meant to allow using those functions in a wide range of contexts with const/non-const foward/reverse iterators. Happy to discuss a better way to do it. Obviously #1090 could make this simpler too.

**Comment by kkarbowiak** [comment]
> > I propose to leave Matrix as a template class but move the implementation entirely to the header file.
> 
> Makes sense. As I understand it, this will allow the direct template instantiation in compilation units using the `Matrix` class, along with potential compiler optimizations.

Exactly this.

**Comment by kkarbowiak** [comment]
> The other explicit template instantiation occurrences (`TWRoute::is_valid_addition_for_tw` and the likes) are meant to allow using those functions in a wide range of contexts with const/non-const foward/reverse iterators.

This I understand.

> Happy to discuss a better way to do it. Obviously #1090 could make this simpler too.

A common practice is to implement template functions in header files. This allows the compiler to instantiate the template as needed in translation units and avoids the need for explicit template instantiations. Potential drawbacks include increased compilation time and increased binary size.

**Comment by jcoupey** [comment]
> whether there was any reason to have the implementation in source file (with explicit template instantiation) as opposed to have the implementation in header file

I kind of made it this way to keep some level of separation between definition in headers and actual implementation. I have no strong feeling about this though and there are other situations where we moved things to the headers for optimization purposes. Yet, the implementation for `TWRoute::replace` and `TWRoute::is_valid_addition_for_tw` being much bigger, I guess I'd be a bit more hesitant to move them to the header than with the `Matrix` class. I realize this is rather subjective.

**Comment by jcoupey** [comment]
Done in #1091.
