### ISSUE TITLE
Compiler warning in gcc-12 build

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#1092]
Since switch to gcc-12 there are some warnings emmited, e.g.
https://github.com/VROOM-Project/vroom/actions/runs/8720162756/job/23921121862#step:4:106

Those seem to be false-positives caused by a bug in gcc. I have seen very similar ones in other projects (e.g. `-Wstringop-overflow` due to gcc bug 106757).

A simple workaround is to disable the specific warning in place it occurs.

**Comment by jcoupey** [comment]
Hum, if this is a bug, maybe it would simply just vanish when updating to gcc 13 as part of #1080?

**Comment by kkarbowiak** [comment]
> Hum, if this is a bug, maybe it would simply just vanish when updating to gcc 13 as part of #1080?

Quite possibly. Compiling using g++ 13.2.1 does not show this warning. I am not sure which version will be shipped with the new Ubuntu though.

**Comment by jcoupey** [comment]
> looks like Ubuntu 24.04 is out 

It is available for fresh installs but the update path from the previous LTS is not open yet, which is currently the blocker for the compilation tests I plan to run locally.

> and features gcc 14.

That is both good in term of having a recent compiler, but bad in the sense that we'll probably be in even bigger trouble to get OSRM to compile...

**Comment by kkarbowiak** [comment]
I have installed 24.04 as a virtual machine. It ships with g++ 13.2.0 and clang++ 18.1.3. Looking at the [toolchain upgrades](https://discourse.ubuntu.com/t/noble-numbat-release-notes/39890#toolchain-upgrades-10) part of the release notes page I thought it would be g++ 14.

For what it's worth, both compilers emit no warning when compiling vroom.

**Comment by jcoupey** [comment]
Closing as we don't need to work around this problem any more since we now use gcc 13 and 14 in CI builds.
