### ISSUE TITLE
Mismatch in compilers used for OSRM and VROOM in CI

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#1098]
It looks like the gcc build uses the default g++ to build OSRM (11.4.0) and g++-12 (12.3.0) to build vroom.

For clang build it is g++ 11.4.0 for OSRM and clang-15 for vroom. How this one works I have no idea.

**Comment by jcoupey** [comment]
@kkarbowiak thanks for spotting the problem and reporting. I've ported your suggested changes from #1101 in #1113 as part of the global OS/compiler CI update.
