### ISSUE TITLE
Can i solve this user case with VROOM?

### ISSUE THREAD

**Issue by Pleiospilos** [VROOM-Project/vroom#1100]
Hello,
I would like to solve the following problem using VROOM:
There is a pool of service orders whose location and duration are known. The company has two (possibly three) vehicles available to drive to and process these orders.
The service orders (operations) should be optimized and divided between the two vehicles.

### The following requirements apply:
The first vehicle starts daily at the headquarters and ends daily at the headquarters.
The second vehicle can start and end at the headquarters every day, but can also drive to one or more hotels, spend the night there, and then travel to the next mission from there. After the last mission, the return journey to the headquarters takes place. The hotels for overnight stays are clearly defined.

This results in the following scenarios:
### First scenario (use for one day)
Start at the headquarters, travel to the locations and return to the headquarters
### 2nd scenario (use for several days with overnight stays)
Start at the headquarters, drive to the locations and then drive to a hotel. The missions are processed over several days and after the last mission the return journey to the headquarters takes place
### 3rd scenario (use for several days with overnight stays in several hotels
Same as 2., but there is also a change of hotels between missions

### Further requirements:
- Working hours should be between 8:00 a.m. and 4:00 p.m
- Arrival and departure can/should be outside working hours

Can this generally be achieved using VROOM?

Thank you for every hint and advice.

Best regards
Marco

**Comment by jcoupey** [comment]
You can decide independently where vehicles will start and end their trips (see `vehicle.start` and `vehicle.end` keys in the docs) so this should give you enough flexibility to model the described situation if you know the locations in advance.

Having a problem spanning several days is not a problem, just use `vehicle.time_window` to specify day/working hours.

**Comment by jcoupey** [comment]
Closing as answered.
