### ISSUE TITLE
position job by time 

### ISSUE THREAD

**Issue by DejavuDaniel** [VROOM-Project/vroom#1105]
hi , whats the right way to lets say deliver one parcel at a selected time but not the rest ? 
if i have 20 jobs and one job i needed to be deliverd in 2h-2h:15 time 

ive tried like this but it doesnt work 

{
    "vehicles": [
        {
            "id": 1,
            "profile": "driving-car",
            "start": [
                25.272143,
                54.709692
            ],
            "end": [
                25.272143,
                54.709692
            ],
            "time_window":[1713337200, 	1713348000]

        }
    ],
    "jobs": [
        {
            "id": 179,
            "service": 300,
            "location": [
                25.269890,
                54.693050
            ],
            "time_windows": [1713340800, 1713342600]
        },
        {
            "id": 178,
            "service": 300,
            "location": [
                25.289531,
                54.683740
            ]
        },
        {
            "id": 182,
            "service": 300,
            "location": [
                25.293319,
                54.685166
            ]
        },
        {
            "id": 181,
            "service": 300,
            "location": [
                25.281992,
                54.685856
            ]
        },
        {
            "id": 183,
            "service": 300,
            "location": [
                25.292441,
                54.681682
            ]
        },
        {
            "id": 185,
            "service": 300,
            "location": [
                25.292420,
                54.676300
            ]
        },
        {
            "id": 186,
            "service": 300,
            "location": [
                25.277140,
                54.684549
            ]
        },
        {
            "id": 187,
            "service": 300,
            "location": [
                25.285071,
                54.677009
            ]
        },
        {
            "id": 189,
            "service": 300,
            "location": [
                25.288001,
                54.684012
            ]
        },
        {
            "id": 190,
            "service": 300,
            "location": [
                25.287042,
                54.679161
            ]
        },
        {
            "id": 191,
            "service": 300,
            "location": [
                25.288050,
                54.675749
            ]
        },
        {
            "id": 194,
            "service": 300,
            "location": [
                25.280552,
                54.680044
            ]
        },
        {
            "id": 180,
            "service": 300,
            "location": [
                25.057288,
                54.592051
            ]
        },
        {
            "id": 193,
            "service": 300,
            "location": [
                25.279566,
                54.683943
            ]
        },
        {
            "id": 176,
            "service": 300,
            "location": [
                25.276155,
                54.687952
            ]
        },
        {
            "id": 195,
            "service": 300,
            "location": [
                25.286386,
                54.676440
            ]
        },
        {
            "id": 192,
            "service": 300,
            "location": [
                25.281333,
                54.682603
            ]
        },
        {
            "id": 177,
            "service": 300,
            "location": [
                25.282857,
                54.680198
            ]
        }
    ], "options":{"g":true}
}

**Comment by jcoupey** [comment]
Using time windows is the expected way to force tasks to happen in a given time frame. Can you elaborate on the "it doesnt work" part?

**Comment by DejavuDaniel** [comment]
it works now as ive added  job.time_windows = [[arrivalTime, endTime]]; time window , 
ive added 30 min to the arrivalTime to be the endTime. but it doesnt work for me with only the arrivalTime give...

everything works but the way it does is not smart but logical , it just chooses to take a longer route , maybe there is a way i can set it to wait in the location if it makes the route longer. ?

**Comment by jcoupey** [comment]
Indeed, there was a syntax error, good you sorted it out.

**Comment by DejavuDaniel** [comment]
is it possibel to pass only the start time ? to the vehicles "time_window":[1713337200]

**Comment by jcoupey** [comment]
No, you have to pass a time frame, not a single value. But if you have no biding timing constraint on the vehicle end, you can use a deadline that is far away in time.

**Comment by DejavuDaniel** [comment]
And if i dont give time window for vehicle then the time windows on a job wont work correctly, yes ?

**Comment by jcoupey** [comment]
You can omit the vehicle time window altogether, it means "no constraint on timing" for the vehicle and will definitely work. Then if you have TW on (some) jobs, this will still force the vehicle to perform tasks at the relevant times.

**Comment by DejavuDaniel** [comment]
so if i remove the time window from vehicle and leave only on the job it would works the same ? 

{
"vehicles": [
{
"id": 1,
"profile": "driving-car",
"start": [
25.272143,
54.709692
],
"end": [
25.272143,
54.709692
]

    }
],
"jobs": [
    {
        "id": 179,
        "service": 300,
        "location": [
            25.269890,
            54.693050
        ],
        "time_windows": [1713340800, 1713342600]
    },
    {
        "id": 178,
        "service": 300,
        "location": [
            25.289531,
            54.683740
        ]
    },
    {
        "id": 182,
        "service": 300,
        "location": [
            25.293319,
            54.685166
        ]
    },
    {
        "id": 181,
        "service": 300,
        "location": [
            25.281992,
            54.685856
        ]
    },
    {
        "id": 183,
        "service": 300,
        "location": [
            25.292441,
            54.681682
        ]
    },
    {
        "id": 185,
        "service": 300,
        "location": [
            25.292420,
            54.676300
        ]
    },
    {
        "id": 186,
        "service": 300,
        "location": [
            25.277140,
            54.684549
        ]
    },
    {
        "id": 187,
        "service": 300,
        "location": [
            25.285071,
            54.677009
        ]
    },
    {
        "id": 189,
        "service": 300,
        "location": [
            25.288001,
            54.684012
        ]
    },
    {
        "id": 190,
        "service": 300,
        "location": [
            25.287042,
            54.679161
        ]
    },
    {
        "id": 191,
        "service": 300,
        "location": [
            25.288050,
            54.675749
        ]
    },
    {
        "id": 194,
        "service": 300,
        "location": [
            25.280552,
            54.680044
        ]
    },
    {
        "id": 180,
        "service": 300,
        "location": [
            25.057288,
            54.592051
        ]
    },
    {
        "id": 193,
        "service": 300,
        "location": [
            25.279566,
            54.683943
        ]
    },
    {
        "id": 176,
        "service": 300,
        "location": [
            25.276155,
            54.687952
        ]
    },
    {
        "id": 195,
        "service": 300,
        "location": [
            25.286386,
            54.676440
        ]
    },
    {
        "id": 192,
        "service": 300,
        "location": [
            25.281333,
            54.682603
        ]
    },
    {
        "id": 177,
        "service": 300,
        "location": [
            25.282857,
            54.680198
        ]
    }
], "options":{"g":true}`
`

**Comment by DejavuDaniel** [comment]
but how does it know the time ? it works perfectly without time window on vehicle

**Comment by jcoupey** [comment]
The job TW forces the scheduling around that time.

**Comment by DejavuDaniel** [comment]
Thank you for your help 🙏🏽
