### ISSUE TITLE
high loading time when using 1000 points or more 

### ISSUE THREAD

**Issue by DevNerds2020** [VROOM-Project/vroom#1114]
Hello, I am using Vroom for routing over 1000 points with certain constraints. The system performs well when there are around 250 points, taking less than 5 seconds. However, when I use 1000 points, the processing time increases to 1 minute and 30 seconds. Upon investigating, I found that the loading time is particularly high, around 1 minute and 20 seconds. I would like to know if there is any way to reduce the loading time in Vroom. I am currently using Vroom Express and ORS as my routing system.

![image](https://github.com/VROOM-Project/vroom/assets/89212105/b32c8c8b-64e7-4854-9bbe-e109cbd1aad2)

**Comment by jcoupey** [comment]
The loading time includes parsing the input problem and defining the basic structures on our side, but it mostly consists in computing the travel times and distance matrices. It is expected that this time increase significantly with the problem size, depending on the underlying routing engine.

In your example, it simply means that the call to ORS for matrices actually dominates the overall computing time. The `solving` part which is only our core VRP optim probably also increased (~6s here) but is still reasonable in comparison.

There is not much we can do here as this is related to the performance of a dependency.

**Comment by jcoupey** [comment]
Closing as not actionable.
