### ISSUE TITLE
Some questions about time windows, duration and...

### ISSUE THREAD

**Issue by salarnz** [VROOM-Project/vroom#1116]
First of all, thank you for developing this powerful vrp engine and making it available to everyone.

Is there a way to calculate the duration based on street traffic?
Currently, I use job objects to define waypoints.

Best Regards

**Comment by jcoupey** [comment]
> Is there a way to calculate the duration based on street traffic?

At VROOM level, we're consuming whatever durations you're passing in through `matrices`, or getting from the underlying routing engine, so that's something you'd have to setup upstream.

**Comment by salarnz** [comment]
Got it ! thanks a lot
