### ISSUE TITLE
Second trip pickup duration

### ISSUE THREAD

**Issue by salarnz** [VROOM-Project/vroom#1117]
Dear @jcoupey 
Based on what you explained in https://github.com/VROOM-Project/vroom/issues/188#issuecomment-602462376 , i use shipment object for multi-trip implementation .

Consider that vehicles leave the depot  at 7 am and return to the depot at 10 am. Now it takes a total of 1 hour to reload the vehicle for the second route. Is there any way to add this 1 hour for the second route?
I know that the service time parameter can be added to each pickup, but I don't want the first trip pickups to have service time. In fact, the initial pickup happens before 7 am.

The next issue is that I use "max_tasks" parameter for my vehicles . with job object , the tasks count is jobs count . but in shipment object the task count should be double for vehicles?

Regards

**Comment by jcoupey** [comment]
> In fact, the initial pickup happens before 7 am.

What about having the vehicles start at 6am then? It would be OK if the first hour is just pickup time.

**Comment by salarnz** [comment]
thanks
