### ISSUE TITLE
Add Parameter for Route Execution Order Based on Task Urgency

### ISSUE THREAD

**Issue by tauk7** [VROOM-Project/vroom#1120]
I am currently facing an issue with prioritizing the execution order of routes based on the urgency of tasks. My requirement is to optimize the route such that the most urgent tasks are executed first, followed by less urgent tasks, and finally tasks that can be done if time permits.

Currently, I am aware of the priority parameter, which indicates the importance of a route being completed within a certain time frame. However, this does not seem to affect the execution order of the routes themselves.

Is there a parameter or method available that allows me to set the execution order based on task urgency? If not, I would like to request the addition of such a feature. This would greatly enhance the ability to manage tasks efficiently by ensuring that the most critical tasks are addressed first.

Example Scenario:

Urgent tasks that must be done today.
Less urgent tasks that still need to be completed.
Optional tasks that should be done if there is extra time.

I appreciate any guidance or updates regarding this feature. Thank you!

**Comment by jcoupey** [comment]
> I am aware of the priority parameter, which indicates the importance of a route being completed within a certain time frame.

Not exactly, priority is not about timing, but about deciding which tasks to include in the plan in the situation where not all can be performed. This sounds like exactly what you describe in your scenario.

> However, this does not seem to affect the execution order of the routes themselves.

Priority won't affect route *ordering*, but only the choice of which tasks are done, or discarded. That is different from having tasks done early in the day, for this you want to check out time window constraints.

**Comment by tauk7** [comment]
I understand, I think I didn't express myself well about my understanding of the priority parameter, but I do understand how it works and I found it very useful. Congratulations on the work. But I mean in scenarios like this:

I work for 500 companies, and I have 50 employees. Of these 500 companies, 100 request me to attend as quickly as possible because they have problems that directly affect their production, while the other 400 only ask for simple repairs. Since the problem directly affects production, I would need the first routes assigned to the 50 employees to be these urgent activities, and then proceed to the less urgent activities.

I don't know if this makes sense and if you understood my problem, but in this case, I just wanted to see if there is another parameter besides priority that could solve this problem I am having, or if this would be a valid suggestion for future implementations.

Anyway, thank you very much for your response and your attention.

**Comment by jcoupey** [comment]
> I would need the first routes assigned to the 50 employees to be these urgent activities, and then proceed to the less urgent activities.

Yes, that is a need of "urgency" rather than priority in the sense described above (must have task vs optional task). In this case, you want the tasks to happen soon so you may have luck translating that directly to time window constraints.

**Comment by tauk7** [comment]
Man, thank you so much. I believe with this information I can change the order and achieve what I wanted. Thank you very much.

One last question: for the timeWindows of the jobs, can I specify, for example, specific timeWindows for certain vehicles? Because not all vehicles will start at the same time. I just want to know if it’s possible to specify in a job that a certain timeWindow in the array is valid for a vehicle with a certain start time, and the next one is valid for another vehicle with a different start time.

I think it might be a bit confusing, but it’s just a doubt. If it’s not possible, that’s okay, you’ve already helped me a lot.

**Comment by jcoupey** [comment]
> know if it’s possible to specify in a job that a certain timeWindow in the array is valid for a vehicle with a certain start time, and the next one is valid for another vehicle with a different start time

Usually you don't have to bother between job/vehicle timing compatibility that much: just define time windows for jobs and independently a time window for each vehicle availability, then VROOM will make sure to provide solutions that make sense for both job and vehicles timing constraints.

**Comment by jcoupey** [comment]
Closing as answered.
