### ISSUE TITLE
Strict access times - Best way to solve?

### ISSUE THREAD

**Issue by Conway6288** [VROOM-Project/vroom#1121]
If I have a site with strict access times of 09:00 - 11:00 and the job on the site takes 30 minutes. What is the best way to get this to optimise so that the job doesn't start later than 10:30?

- Send the job with a time window of 09:00 - 10:30.
- Send the job with a "setup" value of 30 minutes/1500 seconds.
- Send the job with a "service" value of 30 minutes/1500 seconds.

Thanks in advance.

**Comment by jcoupey** [comment]
> so that the job doesn't start later than 10:30

Setting a 09:00 - 10:30 TW to the job will ensure the tasks *starts* in this time frame. So if the time spent on the premises is less than 30 minutes (either using `service` or `setup`), then you have a guarantee that the task will end before 11:00.

**Comment by Conway6288** [comment]
I figured that was the case, setting either service/setup I was still getting a time back of 10:50! 

Many thanksl
