### ISSUE TITLE
API documentation on distance information in output

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#1126]
For both total distance in all routes in summary and total route distance for each route, the documentation states that this information is available if `-g` flag is used. However, the information is also provided if custom distance matrix is passed in input.

**Comment by jcoupey** [comment]
Thanks for spotting the miss, the behavior indeed changed when we introduced the ability to provide custom distance matrices in v1.14.

**Comment by jcoupey** [comment]
Done in #1127.
