### ISSUE TITLE
api not optimizing for weight and volume and is always assigning the largest vehicle

### ISSUE THREAD

**Issue by ptpmashish** [VROOM-Project/vroom#1133]
when I have 2 vehicles with 100 kg and 1000 kg weight capacities and if I have 2 parcels totalling to 20kg, the larger vehicle of 1000kg is getting assigned. 

but it should have assigned the smaller vehicle of 100KG

similar situation if there is volume capacity.

**Comment by jcoupey** [comment]
TL;DR you want to use vehicle `costs` to control assignment choice.

For more context see https://github.com/VROOM-Project/pyvroom/issues/107#issuecomment-2152541942.

**Comment by jcoupey** [comment]
Closing as answered based on https://github.com/VROOM-Project/pyvroom/issues/107#issuecomment-2206018407.
