### ISSUE TITLE
Shipments with unknown pickup points

### ISSUE THREAD

**Issue by faustoschiavoni** [VROOM-Project/vroom#1135]
Hello!
I have a modelling question: is there the possibility to specify a shipment object such that the number of pick-ups are not know a priori? Here is an example:
- PointA: delivery station of 300 units of product1
- PointB: delivery station  of 200 units of product1
- PointC: delivery station of 150 units of product1
- PointD: pickup station for PointA, PointB, PointC where the truck can load as many times as wanted (the only constraits would be its capability) for 500 units of product1

Is there any way to model this (or something similar) and having also optimized the number of times the truck re-loads?

**Comment by jcoupey** [comment]
You want to use shipments to model the pickup-and-delivery situations: `D -> A`, `D -> B` and `D -> C`. Pickup actions at `D` may be performed in isolation or grouped in subsequent steps depending on constraints such as timing, capacity etc.

The number of re-loading is decided during the optimization phase, in output it is the number of times the route goes through `D`.

**Comment by faustoschiavoni** [comment]
Thank's a lot Julien! I highly appreciated your clear and quick answer!

**Comment by jcoupey** [comment]
Great, closing as answered then.
