### ISSUE TITLE
Handling Shipments with multiple orders  to the Same Address in VROOM

### ISSUE THREAD

**Issue by ilirjusuf1** [VROOM-Project/vroom#1136]
Problem Statement:
I'm using VROOM for vehicle routing optimization, and I'm facing a scenario where I have multiple packages (jobs or shipments) that need to be picked up or delivered to the same address. I need to ensure that all these packages are loaded onto the same vehicle to optimize efficiency and minimize unnecessary stops.

Scenario Details:

I have shipments/jobs with varying sizes and requirements.
Some shipments/jobs may have different pickup times but are destined for the same delivery address.
It's critical that all packages intended for the same address are consolidated onto a single vehicle to avoid partial deliveries or inefficient routing.

Ensuring that VROOM understands that shipments/jobs with the same delivery address should be grouped together.
Optimizing vehicle load to accommodate all packages intended for the same address without exceeding capacity constraints.
Minimizing travel time and distance by consolidating deliveries to the same location on fewer vehicles.
Proposed Solution Requirements:

Grouping Logic: Define a grouping mechanism or constraint in VROOM that allows shipments/jobs with the same delivery address to be treated as a single unit.
Capacity Management: Ensure that vehicle capacities are configured to handle the combined volume or weight of all packages intended for the same address.
Optimization: Seek suggestions or best practices from the VROOM community on how to best structure the input JSON or configure constraints to achieve optimal results.

I'm currently structuring my JSON input with separate jobs and shipments, but I need guidance on how to modify this to ensure that VROOM handles shipments to the same address as cohesive units for vehicle loading and routing.

Thanks.

**Comment by jcoupey** [comment]
> ensure that all these packages are loaded onto the same vehicle to optimize efficiency

It can be indeed more efficient in many situations to group same-address deliveries (provided it's doable based on other constraints). In this case, you may expect this to happen out-of-the-box simply as a result of the optimization process seeking for a cheap solution.

Before trying to add any additional constraint on the problem, I'd advise to solve as is and see whether the grouping make sense simply based on cost optimization.

**Comment by jcoupey** [comment]
Additional note: in some situations, you can preprocess the data to group a bunch of packages as a single job or shipment.

**Comment by Katori-FatosF** [comment]
> Additional note: in some situations, you can preprocess the data to group a bunch of packages as a single job or shipment.

Facing the same issue, grouping into a single shipment is not accurate as it causes problems in calculating the volume and capacities of vehicles.

Let's take an example: if we take an order consisting of 3 products: a refrigerator, a TV, and a microwave, what would be the ideal solution to send the dimension on terms of x, y, z?

If i split on3 different jobs/shipments it's a risky that this single order to be assinged on 1/2/3 differnt couriers

**Comment by jcoupey** [comment]
> what would be the ideal solution to send the dimension on terms of x, y, z?

This has nothing to do with grouping actually: the current capacity model does not allow to use dimensions anyway even for single items (that would require to solve another hard packing problem on top of the vehicle routing problem).

> If i split on3 different jobs/shipments it's a risky that this single order to be assinged on 1/2/3 differnt couriers

If splitting is expensive, then it should not happen unless 1. some constraint make it impossible to perform the grouping or 2. we provide a suboptimal solution. Do you have actual examples of situations where the splitting happens despite a feasible grouping?

**Comment by ilirjusuf1** [comment]
How can I group multiple packages into a single job or shipment and fit them within the vehicle's capacity based on their amount? Here is my current JSON configuration for vehicles and shipments:

{
  "vehicles": [
    {
      "id": 1,
      "start": [21.12580361999419,42.56435913271596],
      "end": [21.12580361999419,42.56435913271596],
      "capacity": [20, 20, 20],
      "profile": "car",
      "description": "Vehicle with dimensional capacity 40x40x40",
      "time_window": [28800,49600],
      "skills":[2]
    }
  ],

  "shipments": [
    {
\\how to group this from this 
      "pickup": {
        "id": 1,
        "location": [20.74344727317911,42.2192303834748],
        "service": 1,
        "description": "package 1 pickup  of the order 10"
      },
      "delivery": {
        "id": 1,
        "location": [21.12580361999419,42.56435913271596],
        "service": 300,
        "description": "package 2 Delivery of the order 10"
      },
      "skills":[2],
      "amount": [5, 5, 5], \\ if i doo this 12,4,4 fill not add to vehicle 
      "priority": 100
    },
    {
      "pickup": {
        "id": 2,
        "location": [20.74344727317911,42.2192303834748],
        "service": 1,
       "description": "package 1 pickup  of the order 10"
      },
      "delivery": {
        "id": 2,
        "location": [21.12580361999419,42.56435913271596],
        "service": 300,
        "description": "package 2 Delivery of the order 10"
      },
      "amount": [5, 5, 5],
      "skills":[2],
      "priority": 100
    },
    {
      "pickup": {
        "id": 3,
        "location": [20.74344727317911,42.2192303834748],
        "service": 1,
       "description": "package 1 pickup  of the order 10"
      },
      "delivery": {
        "id": 3,
        "location": [21.12580361999419,42.56435913271596],
        "service": 300,
        "description": "package 2 Delivery of the order 10"
      },
      "amount": [5, 5, 5],
      "skills":[2],
      "priority": 100
    },

//to this 

    {
      "pickup": {
        "id": 4,
        "location": [20.79922342481282,42.37008890163713],
        "service": 1,
        "description": "order2 independent"
      },
      "delivery": {
        "id": 4,
        "location": [20.687515083116992,42.0607020412149],
        "service": 300,
        "description": ""order2 independent"
      },
      "amount": [5, 5, 5],
      "skills":[2]
    }
  ],

  "options": {
    "g": false
  }
}

**Comment by jcoupey** [comment]
> in some situations, you can preprocess the data to group a bunch of packages as a single job or shipment.

By "in some situations" I meant if different items share the same pickup and delivery locations. This does not seem to be the case in your example.

**Comment by ilirjusuf1** [comment]
how to make Json request to make different items share the same pickup and delivery locations.

**Comment by jcoupey** [comment]
I mean if your packages have *both* the same pickup and delivery, you don't want to generate one shipment per package. In that case you can group the total quantity for several packages in the `amount` key for a single shipment.

**Comment by ilirjusuf1** [comment]
> I mean if your packages have _both_ the same pickup and delivery, you don't want to generate one shipment per package. In that case you can group the total quantity for several packages in the `amount` key for a single shipment.

what if i have that packages with different volume size how to handle that?

**Comment by jcoupey** [comment]
You can't handle actual sizes directly, see https://github.com/VROOM-Project/vroom/issues/1136#issuecomment-2219976702. You can use volume as a proxy for capacity limitation.

**Comment by ilirjusuf1** [comment]
> You can't handle actual sizes directly, see [#1136 (comment)](https://github.com/VROOM-Project/vroom/issues/1136#issuecomment-2219976702). You can use volume as a proxy for capacity limitation.

how can I use volume as proxy  can you give me any example

**Comment by jcoupey** [comment]
I mean just use the volume as capacity restriction, not taking into account sizes at all. That is the closest you can get with the current capacity model.
