### ISSUE TITLE
Hierarchical Skill Definitions

### ISSUE THREAD

**Issue by mehmetriza** [VROOM-Project/vroom#1138]
Hello,

I am working on a scenario where jobs are assigned within specific districts and neighborhoods, and vehicles have dependencies based on these locations.

**For example:**

The 1st vehicle operates in the 1st district.
The 2nd vehicle operates in the 1st district but only within the 1st and 2nd neighborhoods.
The 3rd vehicle operates in the 1st district, specifically in the 3rd and 4th neighborhoods.

_The skills required for the jobs are defined at the neighborhood level._

The 1st vehicle can handle all jobs within the 1st district.
The 2nd vehicle can only handle jobs within the 1st and 2nd neighborhoods of the 1st district.
To achieve this, I have created a temporary solution by assigning skills as follows:

1st vehicle skills = [11, 12, 13, 14]
2nd vehicle skills = [11, 12]
3rd vehicle skills = [13, 14]
However, since there are many neighborhoods, this method requires adding a very high number of skills, which is not efficient.

How can I define vehicle skill definitions in a more hierarchical or nested manner to handle these dependencies more effectively?

**Comment by jcoupey** [comment]
We have no way to setup a kind of hierarchy or nomenclature for skills. That is on purpose: the way users would like this nomenclature or hierarchy to be defined is highly use-case dependent. What makes sense for a given situation (e.g. the district/neighborhood in your example) may have no relevance in other situations. This is why we only expose a "flat" view of skills as integers, leaving the nomenclature setup as an exercise to the users.

> To achieve this, I have created a temporary solution by assigning skills as follows

That is a perfectly valid way of achieving what you describe.

> this method requires adding a very high number of skills

Yes, but that's just the result of having a lot of neighborhoods in your setup so there's not really a way around that.

> which is not efficient.

Having a high number of skills has no impact on solving times whatsoever so doing it the way you describe *is* efficient.

**Comment by jcoupey** [comment]
Closing as answered.
