### ISSUE TITLE
Help with shipments and time windows

### ISSUE THREAD

**Issue by SebMilardo** [VROOM-Project/vroom#1139]
I just noticed the following behavior:

Scenario 1:
```
{
  "vehicles": [
    {
      "id":0,
      "start_index":0,
      "time_window":[0,10000]
    }
  ],
  "shipments": [
    {
      "pickup": {
        "id": 1,
        "location_index": 1
      },
      "delivery": {
        "id": 2,
        "location_index": 3
      }
    },
    {
      "pickup": {
        "id": 3,
        "location_index": 2
      },
      "delivery": {
        "id": 4,
        "location_index": 4
      }
    }
  ],
  "matrices": {
    "car": {
      "durations": [
        [    0,  1000,  9000,  1000,  1000],
        [ 1000,     0,  1000,  1000,  1000],
        [ 1000,  1000,     0,  1000,  1000],
        [    0,  1000,  1000,     0,  1000],
        [    0,  1000,  1000,  1000,     0]
      ]
    }
  }
}
```
Solution 1:
```
{
  "code": 0,
  "summary": {
    "cost": 4000,
    "routes": 1,
    "unassigned": 0,
    "setup": 0,
    "service": 0,
    "duration": 4000,
    "waiting_time": 0,
    "priority": 0,
    "violations": [],
    "computing_times": {
      "loading": 5,
      "solving": 3,
      "routing": 0
    }
  },
  "unassigned": [],
  "routes": [
    {
      "vehicle": 0,
      "cost": 4000,
      "setup": 0,
      "service": 0,
      "duration": 4000,
      "waiting_time": 0,
      "priority": 0,
      "steps": [
        {
          "type": "start",
          "location_index": 0,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "arrival": 0,
          "duration": 0,
          "violations": []
        },
        {
          "type": "pickup",
          "location_index": 1,
          "id": 1,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "job": 1,
          "arrival": 1000,
          "duration": 1000,
          "violations": []
        },
        {
          "type": "pickup",
          "location_index": 2,
          "id": 3,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "job": 3,
          "arrival": 2000,
          "duration": 2000,
          "violations": []
        },
        {
          "type": "delivery",
          "location_index": 4,
          "id": 4,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "job": 4,
          "arrival": 3000,
          "duration": 3000,
          "violations": []
        },
        {
          "type": "delivery",
          "location_index": 3,
          "id": 2,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "job": 2,
          "arrival": 4000,
          "duration": 4000,
          "violations": []
        },
        {
          "type": "end",
          "location_index": 3,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "arrival": 4000,
          "duration": 4000,
          "violations": []
        }
      ],
      "violations": []
    }
  ]
}
```

Scenario 2:
```
{
  "vehicles": [
    {
      "id":0,
      "start_index":0,
      "time_window":[0,10000]
    }
  ],
  "shipments": [
    {
      "pickup": {
        "id": 1,
        "location_index": 1
      },
      "delivery": {
        "id": 2,
        "location_index": 3
      }
    },
    {
      "pickup": {
        "id": 3,
        "location_index": 2
      },
      "delivery": {
        "id": 4,
        "location_index": 4
      }
    }
  ],
  "matrices": {
    "car": {
      "durations": [
        [    0,  1000,  10000,  1000,  1000],
        [ 1000,     0,  1000,  1000,  1000],
        [ 1000,  1000,     0,  1000,  1000],
        [    0,  1000,  1000,     0,  1000],
        [    0,  1000,  1000,  1000,     0]
      ]
    }
  }
}
```
Solution 2:
```
{
  "code": 0,
  "summary": {
    "cost": 2000,
    "routes": 1,
    "unassigned": 2,
    "setup": 0,
    "service": 0,
    "duration": 2000,
    "waiting_time": 0,
    "priority": 0,
    "violations": [],
    "computing_times": {
      "loading": 1,
      "solving": 1,
      "routing": 0
    }
  },
  "unassigned": [
    {
      "id": 4,
      "location_index": 4,
      "type": "delivery"
    },
    {
      "id": 3,
      "location_index": 2,
      "type": "pickup"
    }
  ],
  "routes": [
    {
      "vehicle": 0,
      "cost": 2000,
      "setup": 0,
      "service": 0,
      "duration": 2000,
      "waiting_time": 0,
      "priority": 0,
      "steps": [
        {
          "type": "start",
          "location_index": 0,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "arrival": 0,
          "duration": 0,
          "violations": []
        },
        {
          "type": "pickup",
          "location_index": 1,
          "id": 1,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "job": 1,
          "arrival": 1000,
          "duration": 1000,
          "violations": []
        },
        {
          "type": "delivery",
          "location_index": 3,
          "id": 2,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "job": 2,
          "arrival": 2000,
          "duration": 2000,
          "violations": []
        },
        {
          "type": "end",
          "location_index": 3,
          "setup": 0,
          "service": 0,
          "waiting_time": 0,
          "arrival": 2000,
          "duration": 2000,
          "violations": []
        }
      ],
      "violations": []
    }
  ]
}
```

The only change between the two scenarios is the duration of the trip between the initial location of the vehicle and the pickup point of the second shipment. Based on https://github.com/VROOM-Project/vroom/issues/846 I thought I could use matrices that do not respect the triangular inequality. However, it looks like there is some sort of filtering based on time windows which removes the second shipment even if it "might" be feasible. Is this an expected behavior, have I misunderstood something, or is it just a bug?

**Comment by SebMilardo** [comment]
The reason why the second shipment is not included seems to be the following: 

`tw_route.cpp:736`: the function `previous_info` is used to fill the values of `PreviousInfo current`. This function uses the duration matrix value (`tw_route.cpp:119`) to provide the actual travel duration between two points. Then, on line `tw_route.cpp:1004`, current.earliest + next.travel > next.latest and the shipment is not included.

I think the problem is a little more complex then expected. Basically, it looks like in this case the duration matrix is used to both retrieve the duration of a trip between two locations and to retrieve the duration of the shortest trip between two locations. 

A possible quick fix would be to use inside the `TWRoute::previous_info` function the shortest path between two locations instead of the value returned by `Vehicle::duration` but I need to test this.

In any case, given that my objective is to avoid any solution that uses the location_id:0 -> location_id:2 link, is there any other way to achieve this goal?

**Comment by jcoupey** [comment]
@SebMilardo thanks for reporting, I can reproduce. For clarity for anyone else reading this: the problem here is that for scenario 2 our heuristic process fails to find a solution with all shipments assigned while the solution for scenario 1 - with both shipments assigned - is still a valid one in that case (the modified duration in the matrix relates to a route leg that is *not* part of the solution).

**Comment by jcoupey** [comment]
OK, I first had the intuition that there was a bug in the validity evaluation, but I actually now what's going on. The reason for what's happening is that the `3 -> 4` shipment (using ids here) is not doable on its own in scenario 2.

You can confirm that by playing around with the values. Starting with scenario 1, raising the 9000 value to 9001 will trigger the same behavior than with scenario 2 because total duration for `start -> 3 -> 4` is then 10001 which is just above the vehicle TW length. But now if you push the TW deadline to 10001 everything is assigned again.

Another take at it is to do some logging.

<details>
  <summary>See debug</summary>

```patch
diff --git a/src/algorithms/heuristics/heuristics.cpp b/src/algorithms/heuristics/heuristics.cpp
index 5e7751d2..ca404831 100644
--- a/src/algorithms/heuristics/heuristics.cpp
+++ b/src/algorithms/heuristics/heuristics.cpp
@@ -7,6 +7,8 @@ All rights reserved (see LICENSE).
 
 */
 
+#include <iostream>
+
 #include <algorithm>
 #include <set>
 
@@ -29,6 +31,8 @@ Eval basic(const Input& input,
     return r.empty();
   }));
 
+  std::cout << "* start heuristic" << std::endl;
+
   Eval sol_eval;
 
   // Consider all jobs as unassigned at first.
@@ -224,9 +228,12 @@ Eval basic(const Input& input,
       Eval best_eval;
 
       for (const auto job_rank : unassigned) {
+        std::cout << "Trying task: " << input.jobs[job_rank].id;
         if (!input.vehicle_ok_with_job(v_rank, job_rank)) {
+          std::cout << " not doable!" << std::endl;
           continue;
         }
+        std::cout << std::endl;
 
         const auto& current_job = input.jobs[job_rank];
 
```

```
$ vroom -t 1 -i scenario_2.json -o /dev/null -x 0
* start heuristic
Trying task: 1
Trying task: 2
Trying task: 3 not doable!
Trying task: 4 not doable!
Trying task: 3 not doable!
Trying task: 4 not doable!
* start heuristic
Trying task: 1
Trying task: 2
Trying task: 3 not doable!
Trying task: 4 not doable!
Trying task: 3 not doable!
Trying task: 4 not doable!
* start heuristic
Trying task: 3 not doable!
Trying task: 4 not doable!
* start heuristic
Trying task: 3 not doable!
Trying task: 4 not doable!
```
</details>

What happens is that we simply consider that shipment `3 -> 4` is not doable at all with this vehicle so we don't bother trying to insert it in the heuristic (same during the local search). This comes from the checks we do in `Input::set_extra_compatibility`:

https://github.com/VROOM-Project/vroom/blob/bc294146ea168d1b7ff3263c34a217c99072ea9d/src/structures/vroom/input/input.cpp#L516-L520

The rationale for that check is to consider that if a job/shipment is not even doable in a route on its own, then there is no point in trying to insert it at all, let alone in a more packed route. That assumption does not hold any more if there is a huge break in triangular inequality like in scenario 2: doing `start -> 1 -> 3 -> 4 -> 2` is an order of magnitude faster than simply doing `start -> 3 -> 4` so shipment `3 -> 4` is doable in a more complex route, but not on its own.

**Comment by jcoupey** [comment]
Removing the bug label here as I don't think we want to change the current behavior. While we could theoretically face the same limitation with a real-life instance, this is less likely to be a problem as triangular inequality violations in "real" matrices are not that frequent and "small".

On the other hand, if you think of a country-wide instance with vehicles starting from multiple cities, the overlap between vehicle zones can be very small, so setting extra (in)compatibilities is a way to drastically prune the local search process, removing a lot of moves that really do not make sense to try.

I see two ways to deal with that when messing with the matrices values to "block" some route legs:

- make sure the "prohibitive" value used are set in such a way that jobs/shipments are still doable in an empty route;
- bypass `Input::set_extra_compatibility` by commenting out [this line](https://github.com/VROOM-Project/vroom/blob/bc294146ea168d1b7ff3263c34a217c99072ea9d/src/structures/vroom/input/input.cpp#L1115).

**Comment by SebMilardo** [comment]
Thank you so much @jcoupey! Exactly this:

> What happens is that we simply consider that shipment 3 -> 4 is not doable at all with this vehicle so we don't bother trying to insert it in the heuristic

I believe that this could be easily fix if `v.duration` in `TWRoute::next_info` and `TWRoute::previous_info` is replaced with something like `v.shortest_duration` where `shortest_duration` is defined as follows:

```
  Duration shortest_duration(Index i, Index j) const {
    // Start with the direct duration
    Duration shortest_duration = cost_wrapper.duration(i, j); 

    const size_t matrix_size = cost_wrapper.get_duration_matrix_size();
    for (size_t k = 0; k < matrix_size; ++k){
      Duration via_k_duration = cost_wrapper.duration(i, k) + cost_wrapper.duration(k, j); 
      if (via_k_duration < shortest_duration) {
        // Update to a shorter duration if found
        shortest_duration = via_k_duration; 
      }
    }
    return shortest_duration;
  }
```
The loop might take some time but it might be worth it. Please correct me if I'm wrong, I'm not very familiar with the codebase. In the meantime I'm running some tests to check if there are side effects (I have created a branch here https://github.com/SebMilardo/vroom/tree/fix/shortest_duration, If you want to try it I can open a PR)

**Comment by jcoupey** [comment]
I see what you mean but this is called inside `TWRoute::is_valid_addition_for_tw` which is a very hot part of the code in the sense that it is heavily called for all validity checks. I fear that replacing a constant lookup by a linear-time computation is a no-go, especially if only to accommodate "exotic" matrices. 

Besides, this would only catch inequality violations from a "single triangle". Let's say that $k$ is such that $shortestduration(i, j) = duration(i, k) + duration(k, j)$. Maybe then this shortest duration is still prohibitively high, while there is a longer chain of $k_r$ with $k_0=i$ and $k_n=j$ such that: 

$$\sum_{r=0}^{n - 1} duration(k_r, k_{r + 1}) < shortestduration(i, j).$$

**Comment by jcoupey** [comment]
Also following this idea, with scenario 1 you have m[0][2] = 9000, while shortest_duration[0][2] = m[0][1] + m[1][2] = 2000 which somehow defeats the purpose of setting a prohibitive value in the first place.

**Comment by jcoupey** [comment]
Correcting the statement from https://github.com/VROOM-Project/vroom/issues/846#issuecomment-1345278138, I'd replace "the code never relies on triangular inequality" by "you'll never get an invalid solution if triangular inequality do not hold". We may miss a couple opportunities though because some options are ruled out based on triangular inequality (e.g. `Input::set_extra_compatibility` pre-filtering).

I really think your best bet is to remove that filtering step if you have very special matrices with custom manual modifications. Except for the kind of instances I described above, this won't make a significant difference anyway.

**Comment by SebMilardo** [comment]
I see and it totally makes sense. Perfect! Thank you again
