### ISSUE TITLE
new step to start at a specific time defined in previous step

### ISSUE THREAD

**Issue by 2800chic** [VROOM-Project/vroom#1140]
Hi everyone,
I have this scenario: a job to transfer some to a public transportation system ( train) definition of job is made to be sure to do not miss the conection (arrival within 15-5 minutes before train stop) I need to know how to instruct optimizer to do not start next job before real delivery time whici is 5 minutes later than time window of the job. Even if the driver arrive with 15 minutes earlier he will leave after transfer...

**Comment by 2800chic** [comment]
I tried  "time_windows": [[33300, 33360]],
      "service": 960 still in response it seems next step start at 33685 instead of 34260

**Comment by jcoupey** [comment]
If you use `"time_windows": [[33300, 33360]], "service": 960`, then the task can start anytime between 33300 and 33360, so the vehicle will be available after completion some time between 33300 + 960 = 34260 and 33360 + 960 = 34320.

So if you want to fix the availability time, say at 34260, you should use `"time_windows": [[33300, 33300]], "service": 960`. Setting aside the fact that it is a very tight constraint, having a "single-time" time window is not a problem. Also it won't prevent the vehicle from arriving earlier, in which case you'd always have `arrival + waiting_time = 33300` on the step.

**Comment by jcoupey** [comment]
Closing as answered.
