### ISSUE TITLE
Could not find route near location

### ISSUE THREAD

**Issue by bsayiner** [VROOM-Project/vroom#1141]
Hi, I have completed the installation process through the source code as stated in the document. osrm and vroom were installed. then I completed the installation of vroom-express and I did not encounter an error during installation. but when I send a request via http, I get the error "Could not find route near location".

I get the same error when I install with docker. You can see the request sent below.

`{"vehicles":[{"id":0,"start":[2.3526,48.8604],"end":[2.3526,48.8604]}],"jobs":[{"id":0,"location":[2.3691,48.8532]},{"id":1,"location":[2.2911,48.8566]}]}`

**Comment by amks1** [comment]
> This happens if you do not have coverage at the routing layer for the locations used. What OSM data extract did you use to prepare routing data with OSRM?

Hi, not OP but I'm running into this issue frequently because my input data is not very clean. I have some jobs in the sea etc. 

Is there a way to ignore such Jobs and do the routing for other jobs?

**Comment by jcoupey** [comment]
> Is there a way to ignore such Jobs and do the routing for other jobs?

Silently failing is not a good idea, because then you'd never know if the jobs were unassigned because they do not fit in or because they have "bad" coordinates. At least the error here is explicit so you can re-solve after removing the jobs with wrong locations.

> Edit: I notice this issue with v.1.14-rc-2, but when I downgraded to 1.13 it seems to be fine.

That is because of https://github.com/VROOM-Project/vroom/issues/922. Again not having an error is not ideal here because it means that you have a very wrong location snapping that goes on unnoticed. This can result in absurd and hard to debug solutions, hence the introduction of a snapping threshold in the linked ticket.

**Comment by amks1** [comment]
@jcoupey I agree with you. 

However, right now it returns only one error location per request so I would need to make `n + 1` requests where n is the number of erroneous locations.

Can it be made to raise all such locations so at max I would need to make 2 requests?

**Comment by jcoupey** [comment]
> I would need to make n + 1 requests where n is the number of erroneous locations.

I mean, you should really tidy the location input before-hand. This can be done with a single `nearest` OSRM request per location, before storing a "right" location once and for all, and prior to submitting any "multi-location" optimization request.

> Can it be made to raise all such locations so at max I would need to make 2 requests?

This could result in *huge* errors. What you could simply do is perform the same matrix request yourself beforehand and spot all `null` values in the response, just as we do internally. FWIW, there is a [handy script](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) to do this. If the matrices you get do not contain errors, you would not need to fetch them again once embedded in the problem description.
