### ISSUE TITLE
Routing algorithm

### ISSUE THREAD

**Issue by heiko86** [VROOM-Project/vroom#1143]
Hi there,

first of all thank you for sharing your algorithm with us!
I'm running your api in a python project. 

There are 100+ transports with palettized goods to be distributed in a radius of 200km of the warehouse.
When checking on the generated tours I experience the issue as follows:

Truck starts at warehouse.
Truck drives for like 60km into one direction to a client.
Truck drives for like another 20km into the same direction to a client.
Truck heading back in the direction of the warehouse, passes by the warehouse and drives 40km into the opposite direction.
Truck returns to warehouse

I wonder why it doesn t keep up the work in the direction it already headed with the first two destinations,
like a mixture between sweep algorithm optimized with savings algorithm ?

In the scenario seen above there's the risk that the warehouse is running out of close-ranged target destinations while the tours are getting longer and longer?

Thanks in advance for your feedback and your time and efforts,

kind regards
Heiko

**Comment by jcoupey** [comment]
If you get a route that seems to be "too expensive", this is usually the consequence of how constraints set in the model make it impossible to get a cheaper/more natural route.

In your specific situation, hard to tell with just a broad description, can you share a [reproducible example](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) and pointers to the route you find weird?

**Comment by heiko86** [comment]
Thanks for your feedback.
Tried it in a live-production run with more transports, now it works :)
Thanks
