### ISSUE TITLE
VRP Optimization with SLA

### ISSUE THREAD

**Issue by alitooshmanali** [VROOM-Project/vroom#1145]
Hi @jcoupey !
I have a list of vehicles with limited carrying capacity, a list of requests with the coordinates of pickup and delivery, and a list of vehicles that have refused to receive and deliver the order for any reason.
Now I want to enter the following restrictions through Vroom:
1) If a vehicle refuses to perform a job for any reason, that job will not be given to that vehicle.
2) The best vehicle to do the job should be selected based on the dimension of the encounter.
3) If the request is for immediate delivery, only this package should be given to the vehicle and other packages should be taken from that vehicle.

How should I feed this scenario to VROOM and get the most optimal response from it?

If you want more information about this scenario, let me know.

**Comment by jcoupey** [comment]
If by "VRP Optimization with SLA", you mean a route optimization service you can use reliably with redundancy, load-balancing, improved performance and ETA, then you want to check the [Verso route optimization API](https://verso-optim.com/route-optimization-API/).

On handling scenarios where vehicles can or cannot perform given jobs, you want to check out [the `skills` key](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#skills) for vehicles and tasks.

**Comment by jcoupey** [comment]
Closing as this is essentially the same question as in #1151.
