### ISSUE TITLE
Optimizing for Time Travelled Between Pickup and Delivery in Vroom

### ISSUE THREAD

**Issue by richard-Lakar** [VROOM-Project/vroom#1147]
Hi,

We are working on a logistics problem where a truck picks up a load from a pickup location and immediately delivers it. Each shipment has a different pickup location, and drivers do not return to a depot between shipments—they move directly from one shipment to the next. The drivers' start and end locations at the beginning and end of the day are their homes. Importantly, drivers are only paid for the time spent traveling while carrying a load (i.e., from pickup to delivery).

I am familiar with Vroom and its strong capabilities for total cost optimization, but I am interested in understanding whether it can be adapted to optimize for different criteria. Specifically, is there a way to configure the solver to rather work towards:

1. Increasing the total time traveled between pickup and delivery across the overall problem?
2. Or, maximize the total time traveled between pickup and delivery for each drivers route?

Any advice or thoughts on how to approach this would be greatly appreciated.

Thanks!

**Comment by jcoupey** [comment]
If every pickup is immediately followed by the matching delivery, then there is zero travel time shared between any two shipments. So the _"total time traveled between pickup and delivery across the overall problem"_ is fixed, it is simply the sum of travel times from pickup to delivery across all shipments.

So it sounds like there is nothing to optimize for that criteria (of course how you chain shipments is still relevant for overall travel time that includes "empty" rides). Or am I missing something here?

**Comment by richard-Lakar** [comment]
Hi jcoupey, 

Thanks for your response. I think you've miss understood, or more likely I haven't explained it very well. I have attached an example output of a drivers route to help me explain. I've left the geometry in so you can view on a map if needed
[example_route.json](https://github.com/user-attachments/files/16822492/example_route.json)
. 

But essentially a driver will pick up a load from a pickup location-> drive to matching delivery location -> deliver the load -> drive to a new pickup location -> pickup a new load -> drive to new matching delivery for new pickup -> deliver the load..... etc until the end of the day when the driver then goes home.

**Comment by jcoupey** [comment]
You indeed get a situation where you alternate pickup and deliveries:

```
$ jq .steps[].type example_route.json
"start"
"pickup"
"delivery"
"pickup"
"delivery"
"pickup"
"delivery"
"pickup"
"delivery"
"end"
```

My previous point was that all `pickup -> delivery` travel times are fixed, based on the respective locations. The optimization process will basically pick an ordering that minimizes the cost for *all other route legs* (`start -> pickup, `delivery -> pickup` and `delivery -> end`).

**Comment by richard-Lakar** [comment]
Yup exactly. Is that optimization process something I could potentially achieve with the vroom solving engine?

**Comment by jcoupey** [comment]
> Is that optimization process something I could potentially achieve with the vroom solving engine?

Well, that is the primary goal of a route optimization tool, so yes.
