### ISSUE TITLE
Max vehicle per skill

### ISSUE THREAD

**Issue by thucnc** [VROOM-Project/vroom#1159]
My original problem as below:
- I have many vehicle types with different capacities suck as 1.9T, 2.5T, 5T, etc...
- I also have many delivery nodes with volume bigger than a single vehicle capacity, so I have to split all nodes into smaller nodes at size of 50kg
It means that now more than 1 vehicles can visit many nodes belonging to a original location.

My expectation is: I only want 2 vehicles maximum to visit an original location, and because I can't know exactly what size to split, so I think below solution:
I will consider all nodes of an original location as a "skill", and I want a constraint to allow a max vehicles to fulfill this skill.

Please advise me on my expectation and my suggested solution as well.
Thank you.

**Comment by jcoupey** [comment]
> I want a constraint to allow a max vehicles to fulfill this skill.

Skills are provided in input, so it does not really make sense for VROOM to decide on which (or how many) vehicles get a given skill. Following this idea, you'd have to decide yourself on which two vehicles are allowed, that does not sound really flexible.

It seems like a solution minimizing the number of vehicles serving a given location would usually be cheaper, so I'd expect this to happen naturally. Now if you split jobs in many smaller chunks, the solving phase may have a hard time figuring out how to group duplicate jobs across multiple vehicles.

I would first question the 50kg size used for splitting, especially if vehicles can handle tons.

**Comment by thucnc** [comment]
I used the 50kg size for splitting because I have a vehicle type with capacity at 1950kg (but some locations have various volumes from hundreds to thousands). For example, if a location has total weight 560kg, so I will split into 11 nodes (11x50 + 10) 
I think we can call my problem as Split Delivery VRP ?

**Comment by jcoupey** [comment]
What's sure is that using a lot of same-location jobs makes the optimization much harder, no matter how you call it. ;-)

For example we have operators to improve the route by relocating a job or a pair of jobs to another route. That is never gonna help in the situation where you have tens of jobs in a row at the same place.

My point was: if 560kg fits into all vehicles, why split it in the first place? I understand you are somehow forced to do it for high amounts, but the way you do it has a huge impact, so maybe you could consider generating less jobs with higher amounts when splitting.

**Comment by thucnc** [comment]
In my problem, we need to deliver many SKUs (line items) with its own weight to each location, so we need to choose a "proper" size to group these line items into virtual nodes as I mentioned above. 
On the other hand, I can't combine all SKUs into a single node, because there are many possibilities that we need to split the SKUs to fit the remaining capacity of a vehicle. For example, if I have 3 nodes, 1700 - 1700 and 560, and only 2 vehicles with a capacity of 1960 kg,  the last node needs to be split into 200 & 260, or 230 & 230 ... to fit the 2 vehicles, to give us optimal cost.

**Comment by jcoupey** [comment]
> there are many possibilities that we need to split the SKUs to fit the remaining capacity of a vehicle

Sure the splitting part sounds like a combinatorial problem of its own that VROOM is not designed to handle.

> the last node needs to be split into 200 & 260, or 230 & 230

As far as VROOM is concerned, that would be much better than having 12 jobs with 50kg or less. If you split into many small jobs, you're kind of bypassing the splitting problem, but you're making it harder on the VRP side.
