### ISSUE TITLE
Problem in not assigning jobs

### ISSUE THREAD

**Issue by AlirezaAzizi14** [VROOM-Project/vroom#1165]
hello
I have a problem that I want to randomly generate the data I give to vroom.
A question that came to me is, why is the data for time_window like this in the sample json file that you put in the documents?
"time_window": [1600416000, 1600430400]

Isn't this the ambassador's working hours or the ambassador's shift?
I generate the data for time_window in this way and now I feel that the reason why the orders are not assigned to the ambassadors is because of the time_window input.

Generate random time window
`public static double[] GenerateRandomTimeWindow()
{
    int start = random.Next(8, 24);
    int end = random.Next(start + 1, 25);
    return new double[] { start, end };
}`

My problem is that none of the jobs are assigned to the vehicles.
Where do you think the problem comes from?

**Comment by AlirezaAzizi14** [comment]
Hello,
Which of these routers does Vroom use by default for routing?
• OSRM
• Openrouteservice
• Valhalla
I want to know which one Vroom uses to provide duration and distance in the output.

**Comment by jcoupey** [comment]
It is entirely up to you to pick the routing engine your prefer. The default is to send routing queries to an OSRM server on localhost, see `-r` option.
