### ISSUE TITLE
Resolving the Costing Method Error in VROOM When Using Valhalla for Routing

### ISSUE THREAD

**Issue by AlirezaAzizi14** [VROOM-Project/vroom#1168]
Hello, good day!

I have compiled and built VROOM, and I'm using the following command to send a request to VROOM:
`./bin/vroom -r valhalla -a valhalla1.openstreetmap.de/isochrone -p 80 -i dataUser.json`

I want to use Valhalla for routing. However, when I send the request to VROOM, I encounter this error:
`[Error] Valhalla matrix error (No costing method found: 'car').
{"code":3,"error":"Valhalla matrix error (No costing method found: 'car')."}`

From what I understand, it seems like a costing method is not being sent to Valhalla, which is why this error occurs.

What solution would you suggest for this issue?
How can I specify a costing method for Valhalla in the input data?

**Comment by jcoupey** [comment]
You're hitting `valhalla1.openstreetmap.de/isochrone` which is intended to compute isochrones, not matrices. Probably we simply can't make sense of the response because we expect to retrieve matrices from Valhalla.
