### ISSUE TITLE
Improve TSP heuristic

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#117]
This issue is a braindump about something that might be worth investigating.

The current Christofides heuristic implementation for TSP starts by computing a minimum spanning tree (MST). Then, we want to end up with an eulerian graph (i.e. all nodes should have an even degree). This is achieved by starting with the MST and adding edges between nodes that have odd degrees. In order to minimize the overall cost of all edges, such nodes are paired using the Munkres algorithm.

MST are not unique for a given graph (except if *all* edges costs are different). Computing several MST would still be cheap and *might* result in options with a lowest number of nodes with odd degrees. I see two positive effects in that case:

1. speed-up the application of the Munkres algorithm, which is by far the most expensive step for the heuristic
2. probably reduce the overall edges cost for the resulting eulerian graph: the edges cost when pairing odd degree nodes is globally minimized, but we still get expensive edges anyway (if they where really cheap, they would have been included in the MST in the first place)

To that, we might add that if we start with better solutions after the heuristic phase, the local search phase convergence will probably be faster.

**Comment by krypt-n** [comment]
I'd like to take a look at this, if it isn't urgent (I can't commit to any time frame).

Some initial remarks:

* There are indeed multiple MSTs for TSPLib instances. I was sceptical at first since I figured the euclidean distances would make it unlikely for two edges to have the same weight, but measuring the number of not included edges with the same weight as an included egde disproved that.

* Enumerating all MSTs seems to require a non-trivial algorithm. Implementing one would give us a lower bound on the best possible MST and help finding a heuristic for constructing better MSTs. I'll look into doing that.

**Comment by jcoupey** [comment]
@krypt-n great if you can investigate this. It might be an easy gain so worth looking at, but no hurry.

On your first remark: yes, there are surprisingly few edges that have a unique cost in the TSPLIB instances, especially for tightly packed ones. The situation is probably very different for real problems where the costs are durations returned by OSRM rounded to seconds, and the MST is probably nearly always unique. I think this is worth exploring though.

On your second remark: I'd say that the (ordered) list of costs for included edges is unique among all MST. Given that, different MST would "only" occur when not all edges with the same cost can be included (some of them adding cycles), yielding a combinatorial choice on the ones to include or not.

Maybe an easy first step before exhaustive enumeration would be to implement Prim's algorithm alongside the existing Kruskal implementation, run both and compare. Another easy test might be to fiddle around with the stability of the edges sorting [in current Kruskal](https://github.com/VROOM-Project/vroom/blob/master/src/algorithms/kruskal.cpp#L23-L26) to force other choices.

**Comment by krypt-n** [comment]
Some unreadable graphs if you want to take a look at them:

Number of nodes of odd degrees in the MSTs found by kruskal's vs prim's algorithm. < 0: prim finds a "worse" MST, > 0: kruskal finds a "worse" MST:

![odd_nodes](https://user-images.githubusercontent.com/1621822/40084066-39911b0a-5896-11e8-8738-c351d440dba4.png)

Relative tour cost after the christofides heuristic but before the local search, again kruskal vs. prim. < 0: prim's MST results in a better tour, > 0: kruskal's MST results in a better tour.

![cost_christofides](https://user-images.githubusercontent.com/1621822/40084082-4489336c-5896-11e8-9dd2-156aa8f9575e.png)

Relative tour cost after the local search, again kruskal vs. prim. < 0: prim's MST results in a better tour, > 0: kruskal's MST results in a better tour.

![cost_local_search](https://user-images.githubusercontent.com/1621822/40084086-47fde06a-5896-11e8-8312-fcd10643ff51.png)


So...if I looked at the data correctly:
* the resulting tour depends on the specific MST, the local search does not "fix" it.
* chosing the MST with fewer nodes of odd degree does not guarantee that the the resulting tour is cheaper.  
* there is no obvious correlation visible

**Comment by jcoupey** [comment]
Another thing crossing my mind is related to the way Munkres algorithm is currently used to pair nodes of odd degree. The [algorithm itself](https://en.wikipedia.org/wiki/Hungarian_algorithm) is a bit tricky, but the thing is it does not quite account for the symmetric situation we have here. Based on matrix costs, it can come up with matchings that respect symmetry, e.g. if we get `1 -> 5` and `5 -> 1` assignments then we can add the (undirected) `1 - 5` edge. But many assignments turn out to not respect that (e.g. with cycles such as `1 -> 5`, `5 -> 7`, `7 -> 8`, `8 -> 1`).

Usually around 20-30% of nodes are actually not part of pairs derived from the minimum weight perfect matching.  I've been using a simple way to solve this [here](https://github.com/VROOM-Project/vroom/blob/master/src/problems/tsp/heuristics/christofides.cpp#L56-L78) with a greedy pairing of the remaining nodes. This is probably way too sub-optimal.

What just occurred to me is that we could probably re-run repeatedly Munkres algorithm on the remaining nodes to get edges that derive from a minimum weight matching. We would only fallback to the greedy approach in case a new execution is not able to yield new edges.

**Comment by jcoupey** [comment]
Update on the above comment: I did give it a try in the `experiment/TSP-heuristic` branch. It does not seem to change much, as reapplying Munkres algorithm to the remaining nodes seldom allows to add new edges.

**Comment by jcoupey** [comment]
Closing as stale, see also https://github.com/VROOM-Project/vroom/issues/123#issuecomment-584084095.
