### ISSUE TITLE
Is there a way to capture missing road/dotted lines in VROOM?

### ISSUE THREAD

**Issue by TusharB31** [VROOM-Project/vroom#1171]
We are using OSM with VROOM. But OSM has missing road network where it shows dotted line. Is there a way to capture such dotted lines in VROOM?

**Comment by TusharB31** [comment]
My current workflow is as follow:
1. we are using VROOM with OSRM and OSM. 
2. We have developed our custom program on top of it.
3. Getting the distance Matrix using OSM. 

We are using OSRM "https://map.project-osrm.org/" for plotting locations dynamically in GIS view. But, it shows dotted lines wherever the road between two locations is missing or if there is partial road available then it creates dotted line till location from the road not available.

**Comment by jcoupey** [comment]
This has nothing to do with VROOM. What happens is that OSRM, or any other routing engine, will snap your input location to the nearest relevant road segment (see OSRM `nearest` endpoint). The frontend just shows a straight dotted line between your input location and the matching road segment. It's not a "missing road", just a sign that your locations are a bit away from the network.

**Comment by TusharB31** [comment]
Yes, It just shows the dotted sign. But is it possible to capture such locations in the Vroom code?

**Comment by jcoupey** [comment]
> is it possible to capture such locations in the Vroom code

Not sure what you mean exactly.

The snapping happens at the routing level, so totally outside of VROOM. If you have a lot of distance between your locations and the road network, you may want to improve your geocoding or find a better snapping mechanism in the first place.

**Comment by jcoupey** [comment]
Closing as answered, feel free to reopen with new input if required.
