### ISSUE TITLE
Problem in duration, distance, and geometry

### ISSUE THREAD

**Issue by AlirezaAzizi14** [VROOM-Project/vroom#1173]
Hello,  
I'm facing an issue with routing. I've set up Vroom on Docker and I'm using it, but it's not providing me with duration, distance, and geometry.  
What's the problem?  
What steps should I take when I want to run Vroom on my server to ensure it gives me duration, distance, and geometry?

**Comment by jcoupey** [comment]
See https://github.com/VROOM-Project/vroom/blob/release/1.14/docs/API.md#routes, some values (typically the geometry) are only provided in output if you use `-g` since they require an additional call to the routing engine that not everyone may want to perform.

**Comment by jcoupey** [comment]
Closing as answered.
