### ISSUE TITLE
OSRM Matching Version With Vroom

### ISSUE THREAD

**Issue by alitooshmanali** [VROOM-Project/vroom#1176]
Hi @jcoupey ,

I hope you are doing well.

I am currently working with Vroom and OSRM and facing an incomplete data output issue when retrieving detailed information like distance and geometry. Specifically, I am using the second-to-last version of OSRM with the second-to-last version of Vroom. However, the summary does not display complete data, including distance and geometry, which are essential for my use case.

Could you please let me know which version of OSRM is fully compatible with Vroom so that I can receive the complete data, similar to what the Vroom server provides on your main instance? I’d appreciate any guidance on using the right setup to get accurate and full responses.

Thank you in advance for your help and the great work you’re doing with Vroom!

Best regards,

Example:
Input json:

{
  "vehicles": [
    {
      "id": 1,
      "start": [7.425, 43.73], 
      "end": [7.425, 43.73],   
      "profile": "car"
    }
  ],
  "jobs": [
    { "id": 1, "location": [7.421, 43.727] },
    { "id": 2, "location": [7.426, 43.732] }
  ],
  "options": {
    "g": true, 
    "compute_durations": true,
    "compute_distances": true
  }
}

output json:
{
    "code": 0,
    "summary": {
        "cost": 0,
        "routes": 1,
        "unassigned": 0,
        "setup": 0,
        "service": 0,
        "duration": 0,
        "waiting_time": 0,
        "priority": 0,
        "distance": 0,
        "violations": [],
        "computing_times": {
            "loading": 3,
            "solving": 0,
            "routing": 11
        }
    },
    "unassigned": [],
    "routes": [
        {
            "vehicle": 1,
            "cost": 0,
            "setup": 0,
            "service": 0,
            "duration": 0,
            "waiting_time": 0,
            "priority": 0,
            "distance": 0,
            "steps": [
                {
                    "type": "start",
                    "location": [
                        7.425,
                        43.73
                    ],
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "arrival": 0,
                    "duration": 0,
                    "violations": [],
                    "distance": 0
                },
                {
                    "type": "job",
                    "location": [
                        7.421,
                        43.727
                    ],
                    "id": 1,
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 1,
                    "arrival": 0,
                    "duration": 0,
                    "violations": [],
                    "distance": 0
                },
                {
                    "type": "job",
                    "location": [
                        7.426,
                        43.732
                    ],
                    "id": 2,
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 2,
                    "arrival": 0,
                    "duration": 0,
                    "violations": [],
                    "distance": 0
                },
                {
                    "type": "end",
                    "location": [
                        7.425,
                        43.73
                    ],
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "arrival": 0,
                    "duration": 0,
                    "violations": [],
                    "distance": 0
                }
            ],
            "violations": [],
            "geometry": "wsioFe|skG??????"
        }
    ]
}

in the Example output 
cost = 0,
"setup": 0,
"service": 0,
"duration": 0,
"waiting_time": 0,
"priority": 0,
"distance": 0,

and duration is not set in output.

**Comment by jcoupey** [comment]
Your colleague @AlirezaAzizi14 already opened a ticket about this, which I answered yesterday: https://github.com/VROOM-Project/vroom/issues/1173#issuecomment-2441185749.

Let's please keep all the related discussion in a single place.
