### ISSUE TITLE
How to investigate the cost matrix

### ISSUE THREAD

**Issue by mabilinab** [VROOM-Project/vroom#1178]
Hi there,
Is it possible to get the cost matrix that VROOM used to optimize the route request?
I see some things that are off with the jobs order and would like to understand the cost matrix used in details.

**Comment by jcoupey** [comment]
By simply looking at the logs of your routing engine, you should be able to see what requests are sent by `vroom` to get the travel times and distances matrices. So the easiest approach would be to replay those requests and you'd get the matrices  that are used internally.

We also have scripts to [generate standalone problems](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) that embed the matrices in the input file, so if you use that you could also inspect the costs along with your input.
