### ISSUE TITLE
Non-deterministic result in CVRP heuristic

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#118]
After running the CVRP heuristic with a set of parameters, we pick the best clustering result [here](https://github.com/VROOM-Project/vroom/blob/master/src/problems/cvrp/cvrp.cpp#L83).

In some cases, there are different clustering options associated with the same cost. The problem is that clustering options are just [pushed back](https://github.com/VROOM-Project/vroom/blob/master/src/problems/cvrp/cvrp.cpp#L68-L69) at the end of the `clusterings` vector whenever computation is over. As a result, the "best" clustering that is picked may vary across executions and depending on the number of threads used.

Getting different solutions across several executions can be disturbing (and differences will propagate to the local search phase), so we should fix the ordering to have a deterministic behavior.

**Comment by krypt-n** [comment]
An easy fix for this would be to add the parameter-index as a fallback ordering in `clustering::operator<`. I don't have a non-deterministic example here to test that though.

**Comment by jcoupey** [comment]
Yes, or just make sure in some way that the ordering in `clusterings` is the same as in the initial vector of parameters.

No hurry here as I'm currently toying with the idea of applying the local search phase to several clustering results in #110, so this may somehow get fixed in the process.

**Comment by jcoupey** [comment]
This was solved in the process of #110.
