### ISSUE TITLE
Want to know terminology

### ISSUE THREAD

**Issue by muskanImpero** [VROOM-Project/vroom#1183]
{
    "jobs": [
        {
            "id": 1,
            "service": 300,
            "delivery": [
                1
            ],
            "location": [
                1.98465,
                48.70329
            ],
            "skills": [
                1
            ],
            "time_windows": [
                [
                    32400,
                    36000
                ]
            ]
        },
        {
            "id": 2,
            "service": 300,
            "delivery": [
                1
            ],
            "location": [
                2.03655,
                48.61128
            ],
            "skills": [
                1
            ]
        },
        {
            "id": 3,
            "service": 300,
            "delivery": [
                1
            ],
            "location": [
                2.39719,
                49.07611
            ],
            "skills": [
                2
            ]
        },
        {
            "id": 4,
            "service": 300,
            "delivery": [
                1
            ],
            "location": [
                2.41808,
                49.22619
            ],
            "skills": [
                2
            ]
        },
        {
            "id": 5,
            "service": 300,
            "delivery": [
                1
            ],
            "location": [
                2.28325,
                48.5958
            ],
            "skills": [
                14
            ]
        },
        {
            "id": 6,
            "service": 300,
            "delivery": [
                1
            ],
            "location": [
                2.89357,
                48.90736
            ],
            "skills": [
                14
            ]
        }
    ],
    "vehicles": [
        {
            "id": 1,
        
            "start": [
                2.35044,
                48.71764
            ],
            "end": [
                2.35044,
                48.71764
            ],
            "capacity": [
                4
            ],
            "skills": [
                1,
                14
            ],
            "time_window": [
                28800,
                43200
            ]
        },
        {
            "id": 2,
      
            "start": [
                2.35044,
                48.71764
            ],
            "end": [
                2.35044,
                48.71764
            ],
            "capacity": [
                4
            ],
            "skills": [
                2,
                14
            ],
            "time_window": [
                28800,
                43200
            ]
        }
    ]
}

What is unit of capacity,tons,meters,centimeters

what is delivery  in job?

**Comment by jcoupey** [comment]
> What is unit of capacity,tons,meters,centimeters

It's up to you to use whatever metric you need based on your use-case, see https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#capacity-restrictions.

> what is delivery in job?

The `delivery` models the amount that is delivered at a job location, see https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#jobs.

**Comment by jcoupey** [comment]
Closing as answered.
