### ISSUE TITLE
Skip CVRP clustering for TSPs

### ISSUE THREAD

**Issue by krypt-n** [VROOM-Project/vroom#119]
On larger TSP instances (>2000 jobs) the CVRP clustering starts to take a noticeable amount of time. Since there are no capacities involved, skipping the clustering for TSP instances would have no negative consequences and save some time.

**Comment by jcoupey** [comment]
Currently every problem is seen as a CVRP, even with a single vehicle. This change was introduced in #99, see https://github.com/VROOM-Project/vroom/issues/97#issue-306924125 (advantages) for some of the reasons.

The rationale is that you may want to define a "CTSP", i.e. have a single vehicle and capacity limitations if you'd like to do as many jobs as possible even if you know that not all are doable. In that case the clustering heuristic is a good way of choosing the jobs to include. The good part is that it works out of the box for capacities (and skills too) without having to support those in the TSP code.

Now for the unnecessary overhead of clustering you're pointing out we could probably:

1. reduce the number of parameters used [here](https://github.com/VROOM-Project/vroom/blob/master/src/problems/cvrp/cvrp.cpp#L34-L51) when there is only one vehicle (e.g. parallel versus sequential does not make sense anymore).
2. bypass the clustering altogether when no capacity and skills have been defined in input (`input::_has_skills` is `false` and `input::_amount_size` is `0`). In that case, all clusterings are indeed identical.

**Comment by krypt-n** [comment]
This was addressed in 6bd1a883162748890e10f05add9d7fa4fd9e7798
