### ISSUE TITLE
Speed factor, but for job service time (service_factor)

### ISSUE THREAD

**Issue by vanflux** [VROOM-Project/vroom#1195]
We are using VROOM and it is pretty good, but for some reason on our use-case some drivers/vehicles take less service time on jobs and I would like to have some feature like vehicle speed_factor, but instead of travel time, a factor for service time.
I was looking for a way to model this scenario with current features, but I haven't figure out how to do, the initial solution I think is to just use speed_factor, but it isn't the same thing as this "service_factor" I'm talking about.

There is a way of modeling this "service_factor" with current features? Can this be added on future versions?

**Comment by jcoupey** [comment]
There is no way currently to have service time that are vehicle-dependent. There are two aspects to this:

1. being able to provide various times in the input model and use them internally, especially for timing validity checks;
2. including service times in costs.

Those are ticketed in #336 and #1130.

**Comment by vanflux** [comment]
Thanks for the fast response, closing this issue as it is a dup of #336.
