### ISSUE TITLE
If the OSRM profile determines the best routes, are vehicle costs merely used for reporting (and not optimization)?

### ISSUE THREAD

**Issue by hklarner** [VROOM-Project/vroom#1198]
At first sight, the vehicle costs seem to define how I want to route my vehicles, namely by choosing the cheapest routes based on cost per meter and cost per second. But my understanding is that vroom does not have that information, it only has the matrices that the router, eg OSRM, returns based on the lua profile. In other words, is my understanding correct that, whatever cost I enter, the routes will always be the same, namely the cheapest ones based on the lua profile, and only the reported costs will change?

**Comment by jcoupey** [comment]
There are two layers of optimization here:

1. what happens at the routing level (e.g. OSRM profile tuning);
2. the cost that is accounted for at the VRP level, deriving from duration/distance matrices **and** assignment/ordering choices.

As you point out, the costs you provide to VROOM have impact on 2, but no influence whatsoever on 1. Put it differently it's not about how to influence the routes themselves, as that would be the routing engine responsibility. It is about how to influence task assignment to various vehicles based on the overall costs for an heterogeneous fleet. So yes costs are definitely used internally for optimization, not just for reporting.

Of course it does not make sense if you have conflicting setups across the two layers. For example if you only set distance costs for vehicles in input, you probably want to optimize based on distance in the routing profile.

**Comment by hklarner** [comment]
@jcoupey have you also noticed the tendency to "zig-zagging" in the resulting routes if you use the extreme case of, e.g. OSRM profile `car` (which is "fastest car") and then use VROOM cost profile `per_km=1, per_hour=0`?

**Comment by hklarner** [comment]
For example, in one of my problems I get this "big corner" of `1, 2, 3` which in the meters matrix is shorter than `1, 3`.
![zig-zagging](https://github.com/user-attachments/assets/dae23ad9-ac69-4c40-adee-651f01faf8c5)

**Comment by jcoupey** [comment]
> So in an ideal setup, I would once define my lua profiles in terms of meters and duration and then use the same values for the VROOM vehicle cost properties. 

If you have static costs, then yes that would give you "perfect alignment" of both layers. Now at the VROOM level, the costs values are mostly useful when you have quite heterogeneous vehicles. For example if you have a fleet with electric and combustion engine cars, in most situations they'd drive the same roads (so use the same matrix for duration and distances), yet the actual cost per km can be radically different.

>  I noticed that the triangle inequality for the distance matrix does not hold when I use the fastest-car profile

See https://github.com/Project-OSRM/osrm-backend/issues/5178.

> OSRM profile car (which is "fastest car") and then use VROOM cost profile per_km=1, per_hour=0

That's typically the "conflicting setup" situation I described above. Using `per_km=1` and `per_hour=0` at VROOM level means you want to optimize for distance only, regardless of duration. But the underlying distance matrix matches trips that have been optimized (mostly) for duration. So I don't think this makes sense unless you also optimize purely on distance at routing level.

**Comment by hklarner** [comment]
Thanks for the clear feedback :+1:
