### ISSUE TITLE
Compilation problem between VROOM and OSRM

### ISSUE THREAD

**Issue by tadiasse69** [VROOM-Project/vroom#1203]
Hi,

I'm desperately trying to compile vroom with OSRM. OSRM works perfectly. 
The version is: v5.27.1. 
When I run the "make" command in the /src directory I get this message (libosrm_wrapper file):

routing/libosrm_wrapper.cpp: In function ‘void vroom::routing::throw_error(osrm::util::json::Object&, const std::vector<vroom::Location>&)’:
routing/libosrm_wrapper.cpp:41:27: error: ‘std::unordered_map<std::basic_string_view<char>, std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null> >::mapped_type’ {aka ‘class std::variant<osrm::util::json::String, osrm::util::json::Number, osrm::util::json::Object, osrm::util::json::Array, osrm::util::json::True, osrm::util::json::False, osrm::util::json::Null>’} has no member named ‘get’
   41 |     result.values["code"].get<osrm::json::String>().value;

I can't find the solution :-(
Can you help me please ?

Thank, Thibaut.

**Comment by jcoupey** [comment]
Are you sure you are building OSRM v5.27.1? The reason I ask is that we have CI checks for builds against that version and no error was reported. On the other hand there are known issues with more recent changes to OSRM `master` that look similar to your problem.

**Comment by tadiasse69** [comment]
Hell and thank you for this very quick response.

Yes I am sure I am on OSRM v5.27.1 (osrm-routed --version).
Can you give me a stable version of OSRM that works well with VROOM?

Thanks

**Comment by tadiasse69** [comment]
I'm currently on vroom version 1.15.0-dev. I just upgraded to version v1.14.0 and I no longer encounter any compilation problems. Thank you for your help and congratulations on this great project !

**Comment by tadiasse69** [comment]
I can use vroom + osrm with a json file but cannot start the service for CURL requests. I run the command "<dir>/vroom -a 3000 -r osrm -a 0.0.0.0 -p 5000" but vroom is not activated on port 3000. Did I make a mistake?

**Comment by jcoupey** [comment]
Compiling `vroom` will provide you the command-line executable to run on json input files, not a server listening for requests. You want to check out the [vroom-express](https://github.com/VROOM-Project/vroom-express/) repo or use a similar approach.

**Comment by tadiasse69** [comment]
Thanks !!
