### ISSUE TITLE
Replace Munkres algorithm

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#123]
This is a dedicated ticket to experiment on https://github.com/VROOM-Project/vroom/issues/117#issuecomment-389442512.

TL;DR: it seems that what we really need is an implementation of [Edmonds' algorithm](https://en.wikipedia.org/wiki/Blossom_algorithm) in place of Munkres that currently produces sub-optimal results for part of the TSP heuristic.

Potential gains might include:

- speed-up the heuristic (the computational complexity looks lower)
- get better solutions from the heuristic
- maybe also speed-up the local-search convergence if starting from better solutions

**Comment by krypt-n** [comment]
A thing to think about is that we are dealing with complete graphs that most likely satisfy the triangle inequality, so we could be able to cut some corners in the implementation.

**Comment by jcoupey** [comment]
>  we could be able to cut some corners in the implementation

You mean for Edmond's? I did not actually got around taking a close look at the implementation, it seems far from intuitive at first sight. I actually recall considering it in the first place and falling back to Munkres that looked much simpler (although it's not really intuitive either).

**Comment by nielsenko** [comment]
You could consider https://www.mimuw.edu.pl/~mucha/pub/mucha_sankowski_focs04.pdf.

**Comment by nielsenko** [comment]
Regarding implementation of Edmonds's original maximum matching algorithm, this site does a fairly good job explaining it:
http://web.eecs.utk.edu/courses/spring2016/cosc494/notes/Edmonds/index.html

including actual code:
http://web.eecs.utk.edu/courses/spring2016/cosc494/notes/Edmonds/Edmonds.cpp

**Comment by jcoupey** [comment]
Thanks @nielsenko for the references, I had quickly gone through some of them a while back but wasn't aware of all.

The thing is that this would only benefit to the TSP solving code. As it's now only a small subset of the problems we handle, the priority is rather low and I don't think I'll be able to take some time to look this up myself any time soon.

On the other hand, even it's not possible to include the available existing implementations in the code base, it might allow to do some quick tests to evaluate the potential gain. Let me know if you feel like giving this a try, I can provide a few pointers!

**Comment by nielsenko** [comment]
I'll consider giving it a try, but I'm a bit rusty. Last time I slinged C++ code was before C++03 got any traction.

**Comment by jcoupey** [comment]
> I'll consider giving it a try

Great!

The Edmonds implementation from Plank handles the undirected case where the number of edges included is optimized, whereas we want to minimize overall cost for all edges in a directed graph, which seems to be exactly what Kolmogorov's Blossom V is about. As [stated here](http://pub.ist.ac.at/~vnk/software.html#BLOSSOM5), the code is "licensed for research purposes only", which I think is fine as long as we're testing things out. I think we should first start by asserting that this approach provides a significant gain before even thinking of re-implementing anything.

**Comment by jcoupey** [comment]
The first step for testing would be to replace the [current portion](https://github.com/VROOM-Project/vroom/blob/fd087ef2932b4b9cbd0b98e8945650c5782d200f/src/problems/tsp/heuristics/christofides.cpp#L41-L77) of the TSP heuristic that calls stuff in `algorithms/munkres.h`.

From what I can tell from the `blossom5-v2.05.src` project layout, directly linking to solving primitives from C++ does not seem a trivial task. The easiest way to get started I can think of is:

1. compile the code in `blossom5-v2.05.src` to have the `blossom5` executable at hand
2. write an input file to `blossom5` from `christofides.cpp` (containing all edges as described by [`sub_matrix`](https://github.com/VROOM-Project/vroom/blob/fd087ef2932b4b9cbd0b98e8945650c5782d200f/src/problems/tsp/heuristics/christofides.cpp#L42))
3. run `blossom5` on this file using e.g. [`std::system`](https://en.cppreference.com/w/cpp/utility/program/system)
4. read the result file to populate [`mwpm_final`](https://github.com/VROOM-Project/vroom/blob/fd087ef2932b4b9cbd0b98e8945650c5782d200f/src/problems/tsp/heuristics/christofides.cpp#L51)
5. run on (the not-too-big instances from) TSPLIB using [the usual scripts](https://github.com/VROOM-Project/vroom-scripts/tree/master/benchmarks/TSP#solving)

@nielsenko what do you think?

**Comment by nielsenko** [comment]
I had hoped to use Planck's implementation, since it matches on license, but I had failed to consider its shortcomings in this setting.

I will try calling out to `Blossom V` instead. I expect to give it a try first week of 2019.

**Comment by jcoupey** [comment]
@nielsenko thanks for running this experiment! I'm not too worried by the computing times, probably related to the share of IO (especially with very low total computing times). I'm more surprised by the quality degradation.

I need some time to take a closer look and think about it. What I'd like to try is to log the total cost of edges in `mwpm_final` to see how it differs when using _Munkres_ and _Blossom V_. Theoretically, the values should always be lower with the later.

**Comment by jcoupey** [comment]
Now that #193 proved unsuccessful, I don't think there is much interest in digging this further. Also as new features are added to the project, the TSP actually becomes kind of a corner-case now.
