### ISSUE TITLE
Feature :  OSRM {profile} arg options

### ISSUE THREAD

**Issue by dmpvost** [VROOM-Project/vroom#124]
Hi, 

I have a use case where I need to calculate a way, but a walking way.
Could it be possible to configure OSRM {profile} by an option ? (profile : car, biking, foot)

I see 2 options : 

1. For all queries it's the same profile

2. vehicule.profile = car/biking/foot
  but I don't know if this one is relevant, 

Thank
Vincent

**Comment by jcoupey** [comment]
There are two ways to go for this.

1. Use the `-m` flag to pass the mode from command-line (e.g. `-m foot`). Note that this will only affect the value passed as `profile` in the requests, which OSRM does not actually use. So this is only useful if you use a server that filters the requests based on the profile to redirect them to the relevant OSRM server.

2. Point to different OSRM servers using their address and port (`-a` and `-p` flags).

**Comment by jcoupey** [comment]
@dmpvost shall we close this now?

**Comment by dmpvost** [comment]
Yes, I don't have time to check this option right now, I will see in the future

**Comment by jcoupey** [comment]
Ok, feel free to re-open then if necessary.
