### ISSUE TITLE
Time-windows data structures

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#136]
As a first step toward #113, we need an efficient way to deal with time-windows.

## Requirements

- support for multiple time-windows for jobs
- constant-time complexity to decide whether a job insertion in an existing route is feasible or not

## Implementation

- create a time-window type, add one for each vehicle and a vector of time-windows for jobs.
- describe solutions in a way that maintain margins for each step: earliest and latest possible ETA to match TW constraints (requires at most a linear pass through the route upon each modification)
- implement insertion validity checks based on the above margins for every step
- implement logging ETAs for such a solution: use earliest possible arrival for last step then "push" all previous steps forward to pack the route and minimize waiting times

## Defaults

I see two ways to deal with cases with not all time-windows defined in input:

- enforce that if a time-window is defined, then all vehicles/jobs have them defined
- no time-window means no constraint

The first option is what we currently do with skills. Not the most usage-friendly approach but easier to deal with. The second one is probably what most users would expect in term of API. Not sure how painful this is to handle (edge cases etc.).

**Comment by sashakh** [comment]
> - create a time-window type, add one for each vehicle and a vector of time-windows for jobs.

Are we looking for an option to have vector of time windows for vehicle too? Let's say when it works with breaks?

**Comment by jcoupey** [comment]
Good question. I currently have two reasons to favour having a single time-window per vehicle.

1. "Real" breaks will have to be handled differently anyway because more flexibility will be required: think situations like "I want a 30-minutes break that can take place anywhere and starts anytime between 10:00 and 11:00".

2. Users may wish to have different start/end for different time-windows, so we would have to make the start and end time-window related in the API, which looks overly complicated.

On the other hand, defining "hard-coded" breaks could still be doable using one vehicle per time-window (possibly with the same id). I don't see any limitation so far with this approach. Could not hurt to have other views though.

**Comment by sashakh** [comment]
Got it.

**Comment by jcoupey** [comment]
> no time-window means no constraint

When no time-window is defined, we can impose a "default" one that spans `[0, MAX_TIME]`. Turns out this works flawlessly with the current way earliest/latest arrival dates are computed in `tw_route`, and the way ETAs are derived from those margins. 

When a vehicle has no time-window provided, the matching route start time will be:

- any time that allows matching jobs time-window constrains (if present) and minimize waiting time down the line.
- 0 if it only handles unconstrained jobs (with no time-windows either), just like in the CVRP case.

A job with no time-windows provided in input can be included in any route wrt timing constraints.

**Comment by jcoupey** [comment]
Done in #140
