### ISSUE TITLE
Local search phase with timing constraints

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#138]
Once #137 is available, we'll need to apply a local search phase to the heuristic solutions as a next step toward #113.

The easiest way to do that would be to re-use the outline of the CVRP local search. If time-aware versions of the operators inherit from the existing ones, all gain-related computing will remain the same, the only thing we need to change (supplement) is the validity checks embedded in `is_valid`.

What is not clear to me right now is if we'll be able to extend all operators without increasing the complexity of the validity check.

**Comment by jcoupey** [comment]
Most of the work has been handled in #159 where the overall local search scheme for CVRP has been ported and adjusted to handle timing constraints. Now that this PR is merged, we should start getting quite interesting solutions out of the `master` branch, so people wanting to do early tests could use that as a beta version for VRPTW. Note that solution quality and computing times (and the trade-off between the two) will probably still vary significantly before the next release.

One last thing we could re-use from the CVRP approach is the way the route constraints can be loosened by removing a number a "not very well placed" jobs when hitting a local minima, then bringing them back in a better way and firing a new local search step.

**Comment by peterdn1** [comment]
Great news! Thank you.  Unfortunately, I'm out of town for 2weeks but will test this as soon as I return.
