### ISSUE TITLE
Improve amount comparisons

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#150]
While working on #140, I noticed a surprising behaviour: when comparing default "empty" amounts created with `amount_t(0)`, both `operator<=` and `operator<` return true. This is really misleading for the later. For example I thought wise to code a vehicle capacity check as follows:

https://github.com/VROOM-Project/vroom/blob/8a127f66e5d121fb17083f7604eef60e6b769013/src/problems/vrptw/heuristics/solomon.cpp#L130-L133

The result is that when no amounts are provided in input, the above check is always true and as a result not a single job gets assigned.

Rephrasing the comparison works:

```patch
-            vehicle.capacity < route_amount + input._jobs[job_rank].amount) {
+            !(route_amount + input._jobs[job_rank].amount <= vehicle.capacity)) {
```

but the real solution seems to be to adjust the `operator<` implementation:

```patch
diff --git a/src/structures/vroom/amount.h b/src/structures/vroom/amount.h
index 1621cf9..25263b0 100644
--- a/src/structures/vroom/amount.h
+++ b/src/structures/vroom/amount.h
@@ -30,7 +30,7 @@ public:
 template <typename E1, typename E2>
 bool operator<(const amount_expression_t<E1>& lhs,
                const amount_expression_t<E2>& rhs) {
-  bool is_strict_inf = true;
+  bool is_strict_inf = !lhs.empty();
   assert(lhs.size() == rhs.size());
   for (std::size_t i = 0; i < lhs.size(); ++i) {
     if (lhs[i] >= rhs[i]) {
```

which is probably the way I should have written it in the first place.

I don't see any possible side-effect of this change related to the recent `amount_t` refactor, @krypt-n can you confirm this?

**Comment by krypt-n** [comment]
Yeah, the real bug is that `empty < empty` should be `false`. Your patch fixes that and does work with the refactor.

**Comment by jcoupey** [comment]
Another unnatural thing happening right now is that `[1, 1] < [1, 2]` is `false`. We could adjust that but I think the whole `operator<` thing is flawed anyway. As soon as there is more than one amount component not all pairs are comparable so there is no way we can use `b < a` as the strict opposite of `a <= b `. For example with `a = [1, 2]` and `b = [2, 1]`, both `a <= b` and `b < a` are `false`.

I'll probably just remove the `operator<` implementation altogether to force all checks to be performed using `operator<=`, which easily describe the kind of "fits in" conditions we have to verify.

**Comment by krypt-n** [comment]
Since `fitsInto` is only a partial order, there will still be case where `a <= b` and `b <= a` are both false. If we want `a<b` to be consistent with `a<=b && a!=b`, it should be implemented as: all elements smaller or equal, but at least one element smaller than.

**Comment by jcoupey** [comment]
> it should be implemented as: all elements smaller or equal, but at least one element smaller than.

Exactly. But my point is that even then it's wrong to use `b < a` as a replacement for `!(a <= b)` (same example as above). I think it's safer to stick to the `fitsInto` semantic provided by `operator<=`, that's all we need.

Also we really should have unit tests for this, among other stuff...

**Comment by jcoupey** [comment]
My last comment holds for all validity checks but does not account for situations where heuristic choices and orderings are based on comparing amounts (e.g. pick the job with the "highest amount" or order vehicles by capacity). We should then rely on some operator implementing a total order.

**Comment by jcoupey** [comment]
Commit 5501acd introduced a regression in the capacity checks for `relocate` and `Or-opt` operators.

**Comment by jcoupey** [comment]
Closing here as I don't see a way to make this any better for now. To sum up:

1. All capacity checks ("does x fits in y") should be written using `operator<=` exclusively
2. Decisions based on sorting or picking the "biggest" amount/capacity rely on a (total) lexicographic order on `amount_t` components

A corollary of 2. is that in case of multi-components amounts, it's expected to get better heuristic choices if the most important/limiting metric is put first. We should add this to the docs.
