### ISSUE TITLE
Compilation fails in osx (10.11.6) due to missing "include <string>" 

### ISSUE THREAD

**Issue by simon-b** [VROOM-Project/vroom#160]
Xcode 8.2.1, OS X 10.11.6

Compilation fails due to `std::string` in "src/structures/vroom/solution/route.h" and "src/structures/vroom/solution/solution.h"

**Comment by jcoupey** [comment]
Thanks for the fix.

Your compiler seems to be more strict than the ones we check against because this went unnoticed so far. Do you know which compiler and version you are using?

**Comment by simon-b** [comment]
Sure, info below:

    > g++ --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin15.6.0
    Thread model: posix
    InstalledDir: 
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
