### ISSUE TITLE
Stoporder flipped in one case while using TimeWindows

### ISSUE THREAD

**Issue by K-Leon** [VROOM-Project/vroom#169]
This Ticket is about a case, where a strange result occured ( vehicle had to drive forth, back and forth again. )

![image](https://user-images.githubusercontent.com/2196713/46606705-882db180-cafe-11e8-80b3-0e7ad46a708e.png)

Request including a Matrix Request: 
https://gist.github.com/K-Leon/19a0721329248aa65399e53df717f908

https://github.com/VROOM-Project/vroom/issues/113#issuecomment-427779684

Btw: The Demo Frontend is ignoring the Matrix attributes from the json - took me some time to realize.

Thanks so much for your help!

**Comment by jcoupey** [comment]
It seems like the problem does not show up any more with current `master` (at 1440df6), but is visible with 96996ef. I'm getting a `... -> 18 -> 0 -> 10 -> 9 -> ...` route (using job ids) where you'd expect `... -> 18 -> 10 -> 0 -> 9`. Is that correct?

**Comment by K-Leon** [comment]
I just tested with latest Master - the latest routes a little different the small Version of the Request ( i created a reduced one of the original to have less noise. )
The "source" still shows the wrong order. 

I just postet Request, Mapping, Response.

**Comment by jcoupey** [comment]
@K-Leon I can't reproduce with your full version request, probably due to different OS[R]M settings. Could you share the full request with embedded matrix?

**Comment by K-Leon** [comment]
Sorry!!! Now it‘s complete

**Comment by jcoupey** [comment]
We currently compute initial solutions with heuristic approaches, and then try to improve them via a local search process. So far, the local search moves only apply to pair of (different) routes. In this example, the local search phase is useless because there is only one route, so what we're seeing is the result of a natural limitation in the heuristic choice. This is expected at the heuristic level, but we should come up with a way to "mend" it afterwards. Ironically, it's much less likely to happen on harder problem with many routes...

Until this gets fixed, a way to improve the heuristic results is to throw more computing efforts via the `-x` flag. On the above example, the problem shows when using the default `-x 1`, but the solution gets better as of `-x 2`.

**Comment by K-Leon** [comment]
Pushing the x flag up is solving this - at least for now :)

One other - related - thing i noticed is this effect:

![image](https://user-images.githubusercontent.com/2196713/46660568-97bd0100-cbb7-11e8-88c8-6c3d0b175015.png)

Often the algorithm passes a target, just to come back later on. In a total view both solutions are absolutely valid. But if a human needs to work with it, it isn't exactly clear for him, why he should drive by and stop on the way back. Also if you look at it from a logistic point of view, you can go there twice if no one is present, if you tried to reach it early.

So a nice addition would be some kind of rule that the algorithm is eager to finish a stop as early as possible, if both solution won't influence the total outcome.

Regarding Multi Vehicle: 
Is it easy possible to assign some Stops fixed to specific vehicles? So only "Swing" Stops get planned? I think this could be also some kind of workaround for this issue. At least it would be a great feature ;)

But nevertheless: Great Work! With every hour i dig deeper into this Project i'm more impressed.

**Comment by jcoupey** [comment]
> some kind of rule that the algorithm is eager to finish a stop as early as possible

I'm not sure overall completion time could do much here, as finishing item 37 earlier would mean postponing item 36 with the same gap (if service time is identical and no other timing constraint applies).

>  possible to assign some Stops fixed to specific vehicles

You want to use [skills](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#skills) for this.

**Comment by K-Leon** [comment]
I just experimented a little with this version, but it stumbled upon an issue with Timewindow acceptance.
```
vroom -a 127.0.0.1 -p 5054 -m car -t 12 -x 2 '{"jobs":[{"id":118,"location":[8.8295108,50.7874401],"service":180,"time_windows":[[1537482600,1537506000]],"amount":[800]},{"id":120,"location":[8.752294740766,50.7919516],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[6400]},{"id":122,"location":[8.7759053614341,50.98136845],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":123,"location":[8.7759053614341,50.98136845],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":124,"location":[8.76606228821495,50.78484565],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":127,"location":[8.6385714,51.0066059],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[700]},{"id":129,"location":[8.7535789,50.792579],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[3000]},{"id":132,"location":[8.7680357,50.8333449],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[4119]},{"id":134,"location":[8.7680357,50.8333449],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[2640]},{"id":135,"location":[8.8723022,51.0972462],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[800]},{"id":138,"location":[8.831980910548197,50.980182023713255],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":140,"location":[8.8650895,50.9809644],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":141,"location":[8.7730608,50.832544],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[1860]},{"id":142,"location":[8.74217301782134,50.78953105],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":143,"location":[8.826504,50.7849082],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":145,"location":[8.8182801,50.8794016],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[2500]},{"id":146,"location":[8.7966672,51.170655],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[2400]},{"id":147,"location":[8.6573077051718,50.81819315],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[200]},{"id":149,"location":[8.7654881,50.7805206],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[500]},{"id":152,"location":[8.6573077051718,50.81819315],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":153,"location":[8.863736,50.973455],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[700]},{"id":155,"location":[8.6392439928375,50.8570542],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[2400]},{"id":156,"location":[8.8280905,50.7850461],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[300]},{"id":159,"location":[9.3246091,50.9712486],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[500]},{"id":164,"location":[9.55425999944149,50.854187566381995],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[5100]},{"id":167,"location":[8.9408751,50.8181974],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[3600]},{"id":168,"location":[9.1865274,50.8728609],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[3000]},{"id":171,"location":[8.9160609,50.8271604],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[70]},{"id":173,"location":[9.61968,50.79446],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":174,"location":[9.4694066,50.8568134],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[400]},{"id":176,"location":[8.938849879868,50.8246233],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[5602]},{"id":179,"location":[8.8996125,50.8984156],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[600]},{"id":183,"location":[8.9411608,50.8188873],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":184,"location":[9.3362813,50.8719773],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[480]},{"id":186,"location":[8.9679162,51.0656896],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":189,"location":[9.5747265816338,50.7757021],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":191,"location":[9.0077634,50.8106106],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[100]},{"id":192,"location":[8.9275546585098,50.87856305],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[1200]},{"id":196,"location":[9.5119291,50.8195278],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[1800]},{"id":198,"location":[9.094876,50.847427],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[300]},{"id":199,"location":[9.3467657,50.8706218],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[200]},{"id":222,"location":[8.8119078,50.7367503],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[300]},{"id":523,"location":[9.9900379,50.8399805],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[330]},{"id":536,"location":[10.00906,50.83948],"service":180,"time_windows":[[1537482600,1537509600]],"amount":[1900]}],"vehicles":[{"id":4,"start":[9.673008,50.661192],"capacity":[80000],"time_windows":[[1537482600,1537709600]]}]}'
```

The Result is (with the current Feature branch) 
```
Assertion failed: (current_earliest <= latest[i]), function fwd_update_earliest_with_TW_from, file structures/vroom/tw_route.cpp, line 121.
Abort trap: 6
```

Looking at the Json there is nothing obvious regarding the timewindows which could cause it to fail.

**Comment by jcoupey** [comment]
@K-Leon can you share a stand-alone version of the input problem with embedded matrix?

**Comment by K-Leon** [comment]
Sorry - next time i'll think about it :)

`vroom -x 2 -i input_matrix.json`

[input_matrix.txt](https://github.com/VROOM-Project/vroom/files/2466449/input_matrix.txt)
Important is -x 2 - otherwise it'll work.

**Comment by jcoupey** [comment]
> there is nothing obvious regarding the timewindows which could cause it to fail.

The error you're getting is an internal inconsistency due to the solver dealing with a route that should be valid wrt time windows, but is not. I've ticketed the problem in #172.
Can you confirm the behaviour spotted from the matrix values described there? It didn't show up on [OSRM demo server](http://map.project-osrm.org/?z=12&center=50.872711%2C9.278641&loc=50.871977%2C9.336281&loc=50.873122%2C9.186562&loc=50.847392%2C9.094798&hl=en&alt=0), so it's probably related to your setting (maybe some profile customization?).

> And sorry for all the tickets 

No problem, thanks for testing and reporting! It's actually super helpful to uncover problems.

**Comment by K-Leon** [comment]
> Can you confirm the behaviour spotted from the matrix values described there? It didn't show up on OSRM demo server, so it's probably related to your setting (maybe some profile customization?).

I'm using probably a newer Version then osrm demo server - i took the release 5.19 with stock profile and Europe data from last week Friday from geofabric. It's aktually a build in github without RC marking, but it isn't promoted in github as latest release. So i guess OSRM Demo server isn't running it yet.

**Comment by jcoupey** [comment]
@K-Leon I was just being curious because the [3-steps route](http://map.project-osrm.org/?z=12&center=50.872711%2C9.278641&loc=50.871977%2C9.336281&loc=50.873122%2C9.186562&loc=50.847392%2C9.094798&hl=en&alt=0) and the [route without intermediate waypoint](http://map.project-osrm.org/?z=12&center=50.872711%2C9.278641&loc=50.871977%2C9.336281&loc=50.847392%2C9.094798&hl=en&alt=0) are the exact same on the OSRM demo server. Can you check the same requests on you own instance to make sure you get the triangle inequality violation on durations?

**Comment by K-Leon** [comment]
[osrmResultSecondary.txt](https://github.com/VROOM-Project/vroom/files/2472615/osrmResultSecondary.txt)
[osrmResultDirect.txt](https://github.com/VROOM-Project/vroom/files/2472616/osrmResultDirect.txt)

If i'm looking at the results i guess it's coming from the optimization target of osrm. It seems to optimize for Distance - the direct way takes longer, but is a little shorter. Or we just have some kind of interesting hickup.

**Comment by jcoupey** [comment]
Right, the default optimization target is "weight", which is based on duration but with some penalties.

```
$ jq .routes[0].weight osrmResultDirect.txt
1842.5
$ jq .routes[0].weight osrmResultSecondary.txt
1922.6
$ jq .routes[0].duration osrmResultDirect.txt 
1776.5
jq .routes[0].duration osrmResultSecondary.txt 
1501.6
```

The direct route is (as expected) cheaper on weight, but much longer on duration.
