### ISSUE TITLE
Vehicle Time Window applied in a strange manner (Bug?)

### ISSUE THREAD

**Issue by K-Leon** [VROOM-Project/vroom#174]
This is i think something with room for arguing about the right way.

**Currently i have a vehicle:**
- `Working hours set from 8 am to 16 pm`
- `Job 1 is from 8 am to 10 am. `
- `Job 2 is from 9 am to 16 am. `

The vehicle isn't starting at 8 am at the start point, like the Wording "working hours" suggests, but it's starting at 8 am, (stop type start) subtracted the actual distance to travel to stop 1. 
So the **actual start of the vehicle is 7:35** or something like that and not 8 am. 

Usually this isn't what you're expecting - it would mean variable working times for the guy driving the van. Nevertheless it would be an absolut valid behaviour - i just wanted to start some kind of discussion if this is the best way.

**Comment by jcoupey** [comment]
Are you using `time_window ` (without a s) for the vehicle? Otherwise, it might explain that    the default "no constraint" behaviour is applied to the working hours.

**Comment by K-Leon** [comment]
You're right! My bad - Sorry! Rempoving the 's' did the trick
