### ISSUE TITLE
Skills restriction wrongly applied after changing the capacity

### ISSUE THREAD

**Issue by tediyuwono** [VROOM-Project/vroom#180]
I change the capacity of vehicle 2 in the example https://github.com/VROOM-Project/vroom/blob/master/docs/API.md from 4 to 40 .. everthing else is unchanged.
{
  "vehicles": [
    {
      "id": 1,
      "start": [2.35044, 48.71764],
      "end": [2.35044, 48.71764],
      "capacity": [4],
      "skills": [1, 14],
      "time_window": [28800, 43200]
    },
    {
      "id": 2,
      "start": [2.35044, 48.71764],
      "end": [2.35044, 48.71764],
      "capacity": [40],
      "skills": [2, 14],
      "time_window": [28800, 43200]
    }
  ],
  "jobs": [
    {
      "id": 1,
      "service": 300,
      "amount": [1],
      "location": [1.98935, 48.701],
      "skills": [1],
      "time_windows": [[32400, 36000]]
    },
    {
      "id": 2,
      "service": 300,
      "amount": [1],
      "location": [2.03655, 48.61128],
      "skills": [1]
    },
    {
      "id": 3,
      "service": 300,
      "amount": [1],
      "location": [2.39719, 49.07611],
      "skills": [2]
    },
    {
      "id": 4,
      "service": 300,
      "amount": [1],
      "location": [2.41808, 49.22619],
      "skills": [2]
    },
    {
      "id": 5,
      "service": 300,
      "amount": [1],
      "location": [2.28325, 48.5958],
      "skills": [14]
    },
    {
      "id": 6,
      "service": 300,
      "amount": [1],
      "location": [2.89357, 48.90736],
      "skills": [14]
    }
  ]
}

I got the following result : 
{
  "code": 0,
  "summary": {
    "cost": 0,
    "unassigned": 0,
    "amount": [
      6
    ],
    "service": 1800,
    "duration": 0,
    "waiting_time": 0,
    "distance": 0,
    "computing_times": {
      "loading": 5,
      "solving": 0,
      "routing": 3
    }
  },
  "unassigned": [],
  "routes": [
    {
      "vehicle": 2,
      "cost": 0,
      "amount": [
        4
      ],
      "service": 1200,
      "duration": 0,
      "waiting_time": 0,
      "distance": 0,
      "steps": [
        {
          "type": "start",
          "location": [
            2.35044,
            48.71764
          ],
          "arrival": 31500,
          "duration": 0,
          "distance": 0
        },
        {
          "type": "job",
          "location": [
            2.89357,
            48.90736
          ],
          "job": 6,
          "service": 300,
          "waiting_time": 0,
          "arrival": 31500,
          "duration": 0,
          "distance": 0
        },
        {
          "type": "job",
          "location": [
            2.28325,
            48.5958
          ],
          "job": 5,
          "service": 300,
          "waiting_time": 0,
          "arrival": 31800,
          "duration": 0,
          "distance": 0
        },
        {
          "type": "job",
          "location": [
            2.03655,
            48.61128
          ],
          "job": 2,
          "service": 300,
          "waiting_time": 0,
          "arrival": 32100,
          "duration": 0,
          "distance": 0
        },
        {
          "type": "job",
          "location": [
            1.98935,
            48.701
          ],
          "job": 1,
          "service": 300,
          "waiting_time": 0,
          "arrival": 32400,
          "duration": 0,
          "distance": 0
        },
        {
          "type": "end",
          "location": [
            2.35044,
            48.71764
          ],
          "arrival": 32700,
          "duration": 0,
          "distance": 0
        }
      ],
      "geometry": "}}_b@k_bcQ??????????"
    },
    {
      "vehicle": 1,
      "cost": 0,
      "amount": [
        2
      ],
      "service": 600,
      "duration": 0,
      "waiting_time": 0,
      "distance": 0,
      "steps": [
        {
          "type": "start",
          "location": [
            2.35044,
            48.71764
          ],
          "arrival": 28800,
          "duration": 0,
          "distance": 0
        },
        {
          "type": "job",
          "location": [
            2.41808,
            49.22619
          ],
          "job": 4,
          "service": 300,
          "waiting_time": 0,
          "arrival": 28800,
          "duration": 0,
          "distance": 0
        },
        {
          "type": "job",
          "location": [
            2.39719,
            49.07611
          ],
          "job": 3,
          "service": 300,
          "waiting_time": 0,
          "arrival": 29100,
          "duration": 0,
          "distance": 0
        },
        {
          "type": "end",
          "location": [
            2.35044,
            48.71764
          ],
          "arrival": 29400,
          "duration": 0,
          "distance": 0
        }
      ],
      "geometry": "}}_b@k_bcQ??????"
    }
  ]
}

I think it should be expected that vehicle 1 must take the job 1 and 2.
Is it a possible bug?

Thanks and Regards

**Comment by jcoupey** [comment]
Thanks for reporting, we need to have this fixed before releasing v1.3. I just pushed a `hotfix/wrong-skills` branch where I added a couple assertions when formatting the solution (better to crash than to return a wrong solution for now).

Sounds like some gap in the skill checking logic for one of the local search operators, I'll dig into this ASAP.

**Comment by jcoupey** [comment]
> Sounds like some gap in the skill checking logic

Not even close. Changing capacity for vehicle 2 to a higher value results in this vehicle being treated first when building the initial routes. This is an expected heuristic choice, but due to an indirection error in the heuristic code the route for vehicle 2 was built with the skills of vehicle 1 and the other way around.

I've merged the fix in `hotfix/wrong-skills` in the `release/1.3` branch and tagged a new release candidate `v1.3.0-rc.3`.

@tediyuwono can you confirm you don't notice any weird skills behaviour anymore?
