### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by dmpvost** [VROOM-Project/vroom#182]
Hi, 

It could be nice if the API could return something else than 200 when there is an error, 

404, bad request or some other code

thank
vincent

**Comment by jcoupey** [comment]
We'd have to have some kind of error indirection level for this. The `vroom` command-line tool does not know anything about http requests and error codes, it just ingest and returns json. The system process itself exits with a status code that also shows up under the `code` key in the json output (currently only 0 or 1).

What we could do is decide on a set of meaningful error types on the `vroom` side, associate them with predefined exit statuses and then make sure that the `vroom-express` wrapper that handles requests will translate those with relevant http statuses.

Off the top of my head:
- something wrong with user data -> 400 Bad request
- `vroom` crash or some other exception catched -> 500 Internal server error

Any other idea?

**Comment by dmpvost** [comment]
Yes, this is good enough, so I could be able to catch the HTTP error, just to know if everything is fine or not.

**Comment by jcoupey** [comment]
Done over in #208. The possible status code in output are:

| Value         | Status |
| ------------- | ----------- |
| `0` | no error raised |
| `1` | internal error |
| `2` | input error |
| `3` | routing error |

I'll file an issue in the `vroom-express` repo to track handling the http error codes based on that.
