### ISSUE TITLE
Relink API-Documentiation in Wiki from 1.2 to 1.3 branch.

### ISSUE THREAD

**Issue by PattyDePuh** [VROOM-Project/vroom#183]
Hello @jcoupey ,
as the title describes the current [wiki 'Usage' page](https://github.com/VROOM-Project/vroom/wiki/Usage) refers to the API-documentation from the older VROOM version 1.2, which does not include the time-window examples.
Updating that reference would be highly appreciated.

Happy Advent!

**Comment by jcoupey** [comment]
Hi!

I've been wondering about how to handle that in the wiki: either point to the latest versions for everything (with the possible drawback of experimental features that are only in `master`), or point to the latest **stable** release.

I've been sticking to the second option lately, both for documentation and code checkout in the "Building" section. In [this draft](https://github.com/VROOM-Project/vroom/blob/c67fd834739a4ef2ec4ac932bbd57b0706023a0a/docs/release.md) for the release process, I've made the wiki update part of the process for a final release... which did not happen yet for `v1.3`.

I agree this can be quite misleading (especially with the functional diff between `v1.2` and `v1.3`), so I'm also happy to have other ideas on how to best handled this!

**Comment by PattyDePuh** [comment]
_How about_: preparing a release overview table with the latest of each major version. Place it in the root of the Wiki and add a column for the repository link, API link, download link, etc... 
With that attempt we don't have to alter existing entries but adding additional rows with each major versino branch.

About the dynamic linking - i'm curious, if it is possible inside the README.md files, that they can refer to the API file of the current repository.

**Comment by jcoupey** [comment]
There is already a lot of browsing through versions enabled by the "releases" section in the GitHub UI so I'm not sure that adding a table to the wiki would really improve on that.

The main issue is that users redirected to the previous documentation might miss features under development but not released yet. I updated the "Usage" page to provide both links to current master and last released version, so users can decided from themselves. Is that good enough?

**Comment by PattyDePuh** [comment]
Sounds and looks good enough. Thank you.
