### ISSUE TITLE
Vehicle Reduction

### ISSUE THREAD

**Issue by Eichenherz** [VROOM-Project/vroom#184]
Does VROOM support vehicle number reduction ? 
If not how hard would it be to add this feature ?

**Comment by Eichenherz** [comment]
Ok .
Thank you a lot for the detailed replay !

**Comment by jcoupey** [comment]
Do you have some use-cases where you suspect you would have a significant difference when switching objectives?

In any case, I'd be interested in feedback if you try something along this line.

**Comment by jcoupey** [comment]
Closing here, feel free to reopen if required.
