### ISSUE TITLE
Using Graphhopper as backend

### ISSUE THREAD

**Issue by appelflap** [VROOM-Project/vroom#192]
I wanted to build my own Vroom setup, but the osrm-backend is failing at the moment due to [a libc bug](https://github.com/Project-OSRM/osrm-backend/issues/5324) in the [Docker image](https://hub.docker.com/r/osrm/osrm-backend) and I wasn't able to build it from Dockerfile source due to other bugs in current code.

And I was wondering if it would be possible to use a Graphhopper instance as backend for routing as I already have it running with a europe-latest.osm.pbf. So I would not have to do the whole import part again and run two hungry processes parallel. The basic Graphhopper API provides routing between two points or more points and gives distance, time and weight. And can also optimize a route if you give more than 2 points. Would this be enough though, to substitute osrm-backend? How heavy does vroom lean on the full osrm-backend functionalities.

Maybe it's outside of the scope for the Vroom project and I'll just drop it, but I would be interested in building a wrapper if Graphhopper is compatible with the needed functionality and the Graphhopper routing wrapper has more interest from others.

**Comment by appelflap** [comment]
ok, clear. Thanks for taking the time. The [Graphhopper](https://github.com/graphhopper/graphhopper) project is written in java and mainly open source. I say mainly, because the API exposing the advanced route optimization is intentionally left out. So, calculating route distances and optimizing 1 vehicle driving multiple locations is still working, but more advanced stuff is not. I do not think the basic functions support a matrix with travel times. So it can't substitute OSRM directly. It could still be done, but by making a wrapper that does many calls to make the matrix by itself and return it to Vroom. The calculation speed would be vastly degraded though.

**Comment by nilsnolde** [comment]
Likely we can help you here:
https://github.com/GIScience/openrouteservice/tree/master/openrouteservice/src/main/java/heigit/ors/matrix

openrouteservice also runs in Docker and if you get rid of all the extra options, it runs on similar resources as GraphHopper (after all the same code base).. We use a similar matrix code.

Wait for @sfendrich, who might even have a wrapper at hand.

**Comment by jcoupey** [comment]
For what it's worth, I'll outline here how to add a routing wrapper based on the existing `RoutedWrapper` (the one that perform calls to `osrm-routed`). This would allow VROOM to use internally any other API endpoint that can handle matrix and route queries. Happy to answer questions for anyone wishing to give this a try! ;-)

## Define a custom wrapper class

By copying the existing `src/routing/routed_wrapper.h` and `src/routing/routed_wrapper.cpp` files and adjusting class names, say to `MyWrapper`.

## Adjust requests to the API syntax

This happens in [`MyWrapper::build_query`](https://github.com/VROOM-Project/vroom/blob/196597228c462c8f255c7584869e523fd536fad9/src/routing/routed_wrapper.cpp#L26-L51) that takes a bunch of locations, a service name (`table` or `route` for OSRM) and optional extra arguments.

## Adjust response parsing

### The matrix call

Happens in [`MyWrapper::get_matrix`](https://github.com/VROOM-Project/vroom/blob/196597228c462c8f255c7584869e523fd536fad9/src/routing/routed_wrapper.cpp#L89-L141). The current code already takes care of parsing the response and creating a `rapidjson` object used to build the `Matrix` object based on `infos["durations"]` (`durations` is OSRM-related and need to be adjusted). We are only interested in retrieving travel times at that point (not distances).

The `nb_unfound_from_loc` and `nb_unfound_to_loc` vectors serve for error-handling in case there is an unfound route that shows up in the matrix. OSRM then has a `null` value so this might need to be adjusted too depending on the API.

### The route calls

Those are only fired *after* optimization when all routes are decided. They allow to retrieve total route distance, elapsed distance per step and detailed geometry as a polyline. The OSRM-related part is [here](https://github.com/VROOM-Project/vroom/blob/196597228c462c8f255c7584869e523fd536fad9/src/routing/routed_wrapper.cpp#L171-L187).

## Expose the new wrapper

- Add a new routing option [in this enum](https://github.com/VROOM-Project/vroom/blob/196597228c462c8f255c7584869e523fd536fad9/src/structures/typedefs.h#L45).
- Set this routing option [here](https://github.com/VROOM-Project/vroom/blob/196597228c462c8f255c7584869e523fd536fad9/src/main.cpp#L110-L118) based on the command-line argument contained in `router_arg`.
- Add a new case to [this switch](https://github.com/VROOM-Project/vroom/blob/196597228c462c8f255c7584869e523fd536fad9/src/utils/input_parser.cpp#L364-L373) to handle the new wrapper creation.

**Comment by sfendrich** [comment]
I opened a new issue for the ORS support here: #203

**Comment by jcoupey** [comment]
Closing here as not actionable (no support for matrix requests in GraphHopper). Matrix requests are possible using OpenRouteService (based on a fork of GraphHopper), and support for ORS has been added in #204.
