### ISSUE TITLE
Invalid solution with negative amount

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#197]
When using a negative `amount`, an invalid solution can be reached and chosen for output, hitting an assertion when trying to format the solution:

```
vroom: ./utils/helpers.h:196: vroom::Solution vroom::utils::format_solution(const vroom::Input&, const RawSolution&): Assertion `amount <= v.capacity' failed.
```

This happens because during the local search there is no validity check wrt capacity for **removing** a job from a route. But removing a job can break the capacity restrictions if it holds a negative amount.

The rationale behind capacity values being [signed integers](https://github.com/VROOM-Project/vroom/blob/196597228c462c8f255c7584869e523fd536fad9/src/structures/typedefs.h#L31) is that I was thinking this could be useful to model some pick-up and drop-off situations. I'd like to keep this as is, so the fix would be to add validity checks for capacity to all local search operators upon job removals.

Note : using current `master` or `v1.3.0` with *positive values only* for capacities is safe from this bug.

**Comment by rishabhdeepsingh** [comment]
Any updates on this error?
also the line number has been changed.

**Comment by jcoupey** [comment]
@rishabhdeepsingh I plan to start working on this in the next few weeks, along with #241.

**Comment by stefanocudini** [comment]
may e related to this https://github.com/VROOM-Project/vroom/issues/317
