### ISSUE TITLE
Error when building on Windows

### ISSUE THREAD

**Issue by TeodoraB21** [VROOM-Project/vroom#207]
Hello!
I tried to build the project on Windows and I receive linking errors. I don't want to use it with osrm, so I didn't add that lib. I added the boost_system.lib and pthreads.lib and libvroom.lib.
I don't know if the libvroom.lib is created correctly, because when I built it, it didn't created anything in bin/vroom.
Do I have to add some more libraries or what should I do?

**Comment by jcoupey** [comment]
I have virtually no experience building anything on windows but maybe others can help here. In any case, if you have an explicit error message from your compiler, please post it here.

For what it's worth, there is no `libvroom.lib` file: if you successfully run `make` from the `src` folder, you end up with the executable at `bin/vroom` and a static library at `lib/libvroom.a` (you only need that one if you want to use VROOM as a library in your own C++ code).

**Comment by TeodoraB21** [comment]
I need the lib, because I want to run the example.

This is the output of mingw32-make:
es/cl_args.o utils/version.o utils/input_parser.o utils/exception.o utils/output_json.o -lboost_system -lpthread
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0x121): undefined reference to `_imp__WSAStartup@8'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0x4d2): undefined reference to `_imp__WSACleanup@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0xf40): undefined reference to `_imp__WSASetLastError@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0xf73): undefined reference to `_imp__getaddrinfo@16'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0x1014): undefined reference to `_imp__freeaddrinfo@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0x12f7): undefined reference to `_imp__WSASocketW@24'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0x1306): undefined reference to `_imp__WSAGetLastError@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0x18d9): undefined reference to `_imp__select@20'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0x1fd1): undefined reference to `_imp__select@20'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text+0x2067): undefined reference to `_imp__setsockopt@20'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail17winsock_init_base7cleanupERNS2_4dataE[__ZN5boost4asio6detail17winsock_init_base7cleanupERNS2_4dataE]+0x12): undefined reference to `_imp__WSACleanup@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops4recvEjP7_WSABUFjiRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops4recvEjP7_WSABUFjiRNS_6system10error_codeE]+0x14): undefined reference to `_imp__WSASetLastError@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops4recvEjP7_WSABUFjiRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops4recvEjP7_WSABUFjiRNS_6system10error_codeE]+0x64): undefined reference to `_imp__WSARecv@28'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops4recvEjP7_WSABUFjiRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops4recvEjP7_WSABUFjiRNS_6system10error_codeE]+0x6f): undefined reference to `_imp__WSAGetLastError@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops4sendEjPK7_WSABUFjiRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops4sendEjPK7_WSABUFjiRNS_6system10error_codeE]+0x12): undefined reference to `_imp__WSASetLastError@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops4sendEjPK7_WSABUFjiRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops4sendEjPK7_WSABUFjiRNS_6system10error_codeE]+0x5a): undefined reference to `_imp__WSASend@28'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops4sendEjPK7_WSABUFjiRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops4sendEjPK7_WSABUFjiRNS_6system10error_codeE]+0x65): undefined reference to `_imp__WSAGetLastError@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops24translate_addrinfo_errorEi[__ZN5boost4asio6detail10socket_ops24translate_addrinfo_errorEi]+0xa9): undefined reference to `_imp__WSAGetLastError@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text.unlikely+0x3c6): undefined reference to `_imp__freeaddrinfo@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops13error_wrapperIiEET_S4_RNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops13error_wrapperIiEET_S4_RNS_6system10error_codeE]+0xa): undefined reference to `_imp__WSAGetLastError@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE]+0x40): undefined reference to `_imp__WSASetLastError@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE]+0x46): undefined reference to `_imp__closesocket@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE]+0x135): undefined reference to `_imp__WSASetLastError@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE]+0x161): undefined reference to `_imp__setsockopt@20'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE]+0x1b0): undefined reference to `_imp__ioctlsocket@12'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops5closeEjRhbRNS_6system10error_codeE]+0x1ca): undefined reference to `_imp__WSASetLastError@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE]+0x2a): undefined reference to `_imp__WSASetLastError@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE]+0x4c): undefined reference to `_imp__connect@12'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE]+0x108): undefined reference to `_imp__WSASetLastError@4'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE]+0x15e): undefined reference to `_imp__select@20'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE[__ZN5boost4asio6detail10socket_ops12sync_connectEjPK8sockaddrjRNS_6system10error_codeE]+0x1ca): undefined reference to `_imp__getsockopt@20'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEED0Ev[__ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEED0Ev]+0x182): undefined reference to `_imp__WSACleanup@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEED0Ev[__ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEED0Ev]+0x192): undefined reference to `_imp__WSACleanup@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEE8shutdownEv[__ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEE8shutdownEv]+0xb2): undefined reference to `_imp__WSACleanup@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEED1Ev[__ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEED1Ev]+0x146): undefined reference to `_imp__WSACleanup@0'
routing/routed_wrapper.o:routed_wrapper.cpp:(.text$_ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEED1Ev[__ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEED1Ev]+0x152): undefined reference to `_imp__WSACleanup@0'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x121): undefined reference to `_imp__WSAStartup@8'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x502): undefined reference to `_imp__WSACleanup@0'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x10ab): undefined reference to `_imp__WSASetLastError@4'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x10de): undefined reference to `_imp__getaddrinfo@16'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x117f): undefined reference to `_imp__freeaddrinfo@4'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x1457): undefined reference to `_imp__WSASocketW@24'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x1466): undefined reference to `_imp__WSAGetLastError@0'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x1a29): undefined reference to `_imp__select@20'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x2113): undefined reference to `_imp__WSAStartup@8'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x218a): undefined reference to `_imp__select@20'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text+0x221a): undefined reference to `_imp__setsockopt@20'
routing/orshttp_wrapper.o:orshttp_wrapper.cpp:(.text.unlikely+0x39d): undefined reference to `_imp__freeaddrinfo@4'
collect2.exe: error: ld returned 1 exit status
mingw32-make: *** [makefile:44: ..\bin\vroom] Error 1

**Comment by jcoupey** [comment]
Thanks for reporting the output. The linker is unable to find the definition for some functions used by `Boost.asio` for routing requests, so it looks like there is some extra information required on windows...

I can't really help much more here, but maybe you could dig into how to setup `Boost.asio` on windows, or similar issues: searching for "undefined reference to _imp__getaddrinfo undefined reference to _imp__getsockopt windows" does bring up results that mention a `Ws2_32` library and a `-lWs2_32` flag.

**Comment by jcoupey** [comment]
@TeodoraB21 did you manage to solve your linking problem? If there is nothing more we can do to help on the VROOM side, I think we should close this ticket.

**Comment by TeodoraB21** [comment]
i solved it.

**Comment by jcoupey** [comment]
@TeodoraB21 nice to know, you're probably the first to build on Windows. Could you maybe give an hint on how you solved the problem so that others running into this issue could find a solution?

**Comment by TeodoraB21** [comment]
I used Visual Studio. I added only the .cpp files (without the main and the example). I made the project to be a .lib, I set the "additional include directories" the path to include/rapidjson, /src, and /boost. At "preprocessor definitions" I set USE_LIBOSRM=false, because I didn't want to use the OSRM. There are some .cpp files that have the same name, so I renamed them. And the I built the project and a .lib file was created. Also, in some files I added #include <iso646.h> because it is used "or" and "and", not "||" and "&&", I don't remember in which files, but you will see in the error.

After I created another project in the same solution, this one is a .exe. I added the .cpp example file. I set the additional include directories to /src and /boost. At linker, at Input/Additional dependencies I set the boost_system.lib, pthread.lib and the lib that  was created earlier.

**Comment by jcoupey** [comment]
Thanks for the pointers.

**Comment by AffectedArc07** [comment]
> I used Visual Studio. I added only the .cpp files (without the main and the example). I made the project to be a .lib, I set the "additional include directories" the path to include/rapidjson, /src, and /boost. At "preprocessor definitions" I set USE_LIBOSRM=false, because I didn't want to use the OSRM. There are some .cpp files that have the same name, so I renamed them. And the I built the project and a .lib file was created. Also, in some files I added #include <iso646.h> because it is used "or" and "and", not "||" and "&&", I don't remember in which files, but you will see in the error.
> 
> After I created another project in the same solution, this one is a .exe. I added the .cpp example file. I set the additional include directories to /src and /boost. At linker, at Input/Additional dependencies I set the boost_system.lib, pthread.lib and the lib that was created earlier.

Do you happen to still have this as a branch you can push to a fork?
