### ISSUE TITLE
Support multiple time windows for vehicles

### ISSUE THREAD

**Issue by sinaabadi** [VROOM-Project/vroom#211]
Hi @jcoupey 
Vehicle may work in two different time shifts e.g. 8:00 AM - 11:00 AM and 4:00 PM - 8:00 PM.
Does vroom support this feature (Multiple time windows)?

**Comment by jcoupey** [comment]
Hi, the rationale here is that a vehicle with different time shifts can still be modelled using one entry per time window in `vehicles` (re-using the same vehicle id is not a problem). More background on this choice back at https://github.com/VROOM-Project/vroom/issues/136#issuecomment-406896877.

Let me know if you see any situation related to this that the current API does not allow to model.

**Comment by jcoupey** [comment]
Closing here. @sinaabadi feel free to re-open for any follow-up question.
