### ISSUE TITLE
Distance optimization

### ISSUE THREAD

**Issue by TeodoraB21** [VROOM-Project/vroom#214]
Can I optimize the route after the distance, and not after time? 

I want to set a distance matrix, and to receive the shortest distance between all the locations.

**Comment by jcoupey** [comment]
Not out-of-the-box, but there are two ways that could work depending on the kind of problems you want to solve:

- use the built-in [`matrix` key](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#matrix) in input
- adjust the releveant routing wrapper in VROOM (e.g. https://github.com/VROOM-Project/vroom/blob/master/src/routing/routed_wrapper.cpp if you're using `osrm-routed`) to query for distances on top of durations, then adjust the response parsing to get the right matrix

In both cases you'll end up replacing a travel-time costs matrix with a distance costs matrix and the whole solving  process can remain untouched as far as costs are concerned.

**But** you need to be aware that for all time-related constraints, we expect to have travel time costs in the matrix. For example, checking if a job can be added in an empty route with regard to a vehicle time window looks like:
```
vehicle_start_date + m[vehicle_start][job] + service[job] + m[job][vehicle_end] <= vehicle_end_date
```
So you might get strange results if your problem contains timing constraints.

**Comment by jcoupey** [comment]
Also probably worth trying to make this happen at the routing level. If you're running on top of OSRM, you can adjust [the profile](https://github.com/Project-OSRM/osrm-backend/blob/2c7c18fd24f9a46de04c935126fc29992f57113f/profiles/car.lua#L23) to compute shortest routes based on distance.

We'd then still be optimizing on durations within VROOM, but based on travel-times for shortest distance trips. And you could use timing constraints.

**Comment by TeodoraB21** [comment]
This is actually the problem: I tried to set the matrix, but I also need to set some time constraints, and the result was bad.
Also, I don't use OSRM.

**Comment by jcoupey** [comment]
You could adjust the current codebase to supply two distinct matrices. One for travel times, used in all time validity checks. The other one would hold the costs to take into account in all evaluations (heuristic choices and local search operator gains).

Before getting into this, I'd first try to evaluate the results when providing a travel-time matrix that is based on shortest distance trips (see my last post), if you can get that from the routing engine you're using.

I'm curious about your use-case, what are the reasons for favouring distance over travel time in the optimization objective?

**Comment by jcoupey** [comment]
Closing as stale. @TeodoraB21 feel free to reopen if required.

**Comment by cbeltrangomez84** [comment]
Hi @jcoupey, you know if there is anything new about this topic, I need the same, my vroom route add more than 6 kilometers only for 2 minutes less in time. Maybe is something new I can use to solve this?

**Comment by jcoupey** [comment]
@cbeltrangomez84 nothing new here, my previous comment above still holds. What you're experiencing is expected as we optimize on overall travel time, not distance. As suggested above, there are a couple things you may try at the routing level to mitigate this effect.

**Comment by cbeltrangomez84** [comment]
Thanks @jcoupey I'm new using vroom and sadly that's too advance for me now.

**Comment by danielcxt** [comment]
> Also probably worth trying to make this happen at the routing level. If you're running on top of OSRM, you can adjust [the profile](https://github.com/Project-OSRM/osrm-backend/blob/2c7c18fd24f9a46de04c935126fc29992f57113f/profiles/car.lua#L23) to compute shortest routes based on distance.
> 
> We'd then still be optimizing on durations within VROOM, but based on travel-times for shortest distance trips. And you could use timing constraints.

@jcoupey: Can you explain what you mean by the "routing level" here? Is the proposed workaround just a way to get route geometries that follow the minimum distance path rather than a way to distribute shipments/jobs to vehicles such that distance is minimized?
