### ISSUE TITLE
Feature: Jobs as Trips

### ISSUE THREAD

**Issue by jsfurniss** [VROOM-Project/vroom#222]
Greetings:

Do you have plans for supporting Jobs that have both an origin and destination (each with time windows)?  Alternatively, could a Job be defined as a "pick" or "drop" where the vehicle's current load is increased by job.amount(s) at "pick" and decreased by job.amount(s) at "drop" but always constrained by vehicle.capacities throughout the route duration.

Our goal is solving the traditional "Dial-a-Ride" people moving problem which involves trips having a specified origin and destination with the pickup and/or drop off time windows being specified.  The job.amount(s) defines the number of passengers to be transported on each leg from point a to b. The fact that Vroom supports multiple capacity values is valuable since a passenger might be ambulatory (serviced by a sedan) or requiring a wheelchair (serviced by a wheelchair van).  The "skills" definitely come into play as well since passengers require various vehicle and driver attributes.

This functionality would also support a localized courier service which not only moves packages from a depot to locations, but may also move packages from one point to another along a given route.

Thank you in advance, Steve.

**Comment by jcoupey** [comment]
We're tracking something related at #189. Could you take a look at this ticket (and especially https://github.com/VROOM-Project/vroom/issues/189#issuecomment-447906698) to see if this would cover the use-case you have in mind?

**Comment by jsfurniss** [comment]
Thanks for prompt reply.  I did review issue #189 before posting and the sequencing seemed like it was a concept headed in the right direction.  In our use case, we would know the required skills for each job beforehand, however we would not know which vehicle or driver would necessarily be performing each job.

All "jobs" in our process are point to point composed of an origin (load) w/ time window as well as a destination (drop) w/ time window.  The job would have one or more "amounts" (typically passengers) for allocating against vehicle capacities and potentially "skills" for filtering the vehicle assignment.

Conceptually a vehicle (with a capacity of 3) would start it's route from the depot with currentLoad==0 and head to job 1 origin adding one passenger (currentLoad+=1).  Before dropping off passenger 1, vehicle heads to second job origin adding 2 passengers (currentLoad+=2, currentLoad==3  maximum capacity).  The vehicle is handling two jobs simultaneously.  Vehicle then drops off the first passenger at job 1 destination (currentLoad-=1 bringing currentLoad==2, "completing" job 1, but still handling job 2).  This vehicle could conceivably pickup somebody else (job 3) before dropping the job 2 passengers because it has the capacity for one more.  The vehicle's load goes up and down dynamically throughout the route but cannot go over maximum capacity.

**Comment by jcoupey** [comment]
What you describe sounds like a typical pickup and delivery problem. In term of modelling, I think it would be easier if jobs keep describing one single thing at a given location (rather than spanning overlapping parts of a route).

In your example, you'd have one job for each trip start and end (the later with a negative amount). In term of constraints, mixing pickups and drops means monitoring overall capacity throughout the route, and making sure related start and ends are on the same route, in the right order. This is why I linked to #189 in the first place. Does that make sense?

**Comment by jsfurniss** [comment]
I guess in my reading I did not realize jobs could have negative amounts to define a "drop" so yes, using two jobs to define our "trip" would work assuming we have the ability to ensure same route and correct order as you stated. I will monitor issue #189 and attempt to build an integration model around this concept.  One final question and I'll leave you alone:  What do you suggest for the best platform to compile the application?  I've attempted a variety of scenarios on Win 10 (Visual Studio 2017, clang, CodeBlocks, etc.) and cant get a full compile to succeed.  Looks like you build on Linux/Unix - which flavor and compiler/IDE if you don't mind?

**Comment by jcoupey** [comment]
> using two jobs to define our "trip" would work assuming we have the ability to ensure same route and correct order as you stated

OK, so I suggest we keep the discussion over in #189. Technically negative amounts are already allowed, but note there is currently a known bug (see #197).

Regarding the platform, we have [Travis builds](https://travis-ci.org/VROOM-Project/vroom) setup for gcc 6, 7, 8 and clang 5, 6. Those are run on ubuntu boxes. I think most users (including myself) are running on linux. There is one report of someone successfully building under windows though (see #207). Feel free to open a dedicated ticket if you're experiencing build errors.

**Comment by jcoupey** [comment]
Closing in favour of #189
