### ISSUE TITLE
Runing vroom with OSRM not on local host

### ISSUE THREAD

**Issue by GarfAbh** [VROOM-Project/vroom#223]
Hi,

I had a look at vroom usage and it says that with -a and -p we can change the routing server and the routing server port. I currently set up osrm on 0.0.0.0:5001 and I tried everything to give it correctly to vroom but I always get 

{"code":2,"error":"The document root must not be followed by other values. (offset: 4019)"}

my cmd is : 

vroom -a 0.0.0.0 -p 5001 -i tmp.json

i don't know what to do any one to help me ?

**Comment by jcoupey** [comment]
Can you report the result of running just `vroom -i tmp.json` with that same file?

What you're seeing is definitely a parsing error, so no routing query is fired yet and the `-a` and `-p` *should* make no difference.

**Comment by GarfAbh** [comment]
Sure 
it return the normal output : the summary with all the unasigned and assigned job ...

{"code":0,"summary":{"cost":10252,"unassigned":0,"amount":[16],"service":12060,"duration":10252,"waiting_time":0,"computing_times":{"loading":19,"solving":50}},"unassigned":[],"routes":[{"vehicle":601,"cost":10252,"amount":[16],"service":12060,"duration":10252,"waiting_time":0,"steps":[{"type":"start","location":[6.68973,46.5019],"arrival":21600,"duration":0},{"type":"job","location":[6.8010133,46.6681697],"job":1008740,"service":720,"waiting_time":0,"arrival":23253,"duration":1653}, ...

**Comment by jcoupey** [comment]
Could you share the vroom version you're running and the whole input file (you can drag it in a comment and it will get linked) ?

**Comment by GarfAbh** [comment]
I use vroom 1.4.0. 

with this
[input1.zip](https://github.com/VROOM-Project/vroom/files/3053158/input1.zip)

**Comment by jcoupey** [comment]
I can't reproduce the problem:

``` bash
$ vroom -h
Version: 1.4.0
$ vroom -i input1.json  # expected solution output
$ vroom -a 0.0.0.0 -p 5000 -i input1.json  # expected solution output
$ vroom -a 0.0.0.0 -p 5001 -i input1.json 
[Error] Failed to connect to OSRM at 0.0.0.0:5001
{"code":3,"error":"Failed to connect to OSRM at 0.0.0.0:5001"}
```

The last command errors as expected when running `osrm-routed` on the default port 5000, but works when using `osrm-routed -p 5001 [...]`.

The error is definitely generated by `rapidjson`. Can you experiment with adding the default `-a 0.0.0.0 -p 5000`, and with another file like [the example from the doc](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#using-osrm), or by just reading the problem instance from standard input:

```
vroom -a 0.0.0.0 -p 5001 '{"vehicles":[{"id":0,"start":[2.3526,48.8604],"end":[2.3526,48.8604]}],"jobs":[{"id":0,"location":[2.3691,48.8532]},{"id":1,"location":[2.2911,48.8566]}]}'
```

**Comment by GarfAbh** [comment]
`vroom -a 0.0.0.0 -p 5001 '{"vehicles":[{"id":0,"start":[2.3526,48.8604],"end":[2.3526,48.8604]}],"jobs":[{"id":0,"location":[2.3691,48.8532]},{"id":1,"location":[2.2911,48.8566]}]}'`
Return me a correct solution output

**Comment by GarfAbh** [comment]
I don't what happened and how it's possible but I don't want to bothering you with that I will continuing searching and let you know as soon as I found the issues

**Comment by GarfAbh** [comment]
I found where It come from. I had a script that work on the json file just before sending it to vroom. This script corrupted the file that's why I got this issue. I close the issue.
