### ISSUE TITLE
[Question] maximize vehicle capacity before using another vehicle

### ISSUE THREAD

**Issue by tediyuwono** [VROOM-Project/vroom#226]
Hello,

I have following cases for 83 jobs with each amount is 1.
1. there are 2 vehicles with each capacity is 40
result : each vehicle will handle 40 jobs. 3 jobs are unassigned.

2. there are 4 vehicles  with each capacity is 40
result: one vehicle handle 40 jobs, another one handle 24 jobs, and the last vehicle handle 19 jobs.

Is it correct that for the second case, the distributions of the jobs are not 40:40:3 because 'The current optimization objective is overall travel time' (quote from other issue) ? if it is correct, the overall travel time is that the sum of all those steps travel time is the most optimized result , right?

Is it possible in the second case to enforce getting 40:40:3 jobs distribution?

Thanks

**Comment by jcoupey** [comment]
Yes, you're right this is very similar to #225. We do our best to lower the overall travel time (sum of all travel times along all routes) while respecting capacity constraints. But we don't bother to fill up vehicles or balance route amounts.

> Is it possible in the second case to enforce getting 40:40:3 jobs distribution?

If you badly need this distribution, you just have to input vehicles with respective capacity 40, 40 and 3. Note that the same applies here as in #225: as a result of inputting tighter constraints, you'll probably get a more expensive solution with regard to travel time.

**Comment by jcoupey** [comment]
Looks like this has been answered, so closing now. Feel free to re-open if required.
