### ISSUE TITLE
Travel distance as a capacity

### ISSUE THREAD

**Issue by sfendrich** [VROOM-Project/vroom#227]
Is it possible to include a maximum travel distance as a capacity? E.g., for electric cars.

**Comment by jcoupey** [comment]
There is currently no way to enforce a constraint on maximum travelled distance. The closest you can get right now is to adjust vehicle time windows to avoid getting too long routes. Do you have a use case where this would not be enough?

Notwithstanding the fact that we currently don't store a distance matrix, such a constraint could technically be implemented in a similar way as capacity constraints by maintaining routes distance information and checking for validity upon each route update.

**Comment by sfendrich** [comment]
Thanks for the hints, I'll look whether adapting the time windows will solve the problem.

FYI: The use case is a fleet of electric cars. Before they run out of battery, they either must return to their home base or find a nearby charging station. Because recharging takes about 30min, it might affect the optimal round trip, in particular, if the jobs have time windows.

**Comment by AwesomeIbex** [comment]
> Thanks for the hints, I'll look whether adapting the time windows will solve the problem.
> 
> FYI: The use case is a fleet of electric cars. Before they run out of battery, they either must return to their home base or find a nearby charging station. Because recharging takes about 30min, it might affect the optimal round trip, in particular, if the jobs have time windows.

:+1: similar use case (EV)
