### ISSUE TITLE
demo server json issue

### ISSUE THREAD

**Issue by atisnz** [VROOM-Project/vroom#230]
Hi,
I'm trying to use the demo server with our locations, but I'm getting  "invalid json" error:
`curl --header "Content-Type: application/json" --data '{"vehicles":[{"id":0,"start":[174.806435,-36.9151492],"end":[174.806435,-36.9151492]}],"jobs":[{"id":0,"location":[174.597249,-36.808421]},{"id":1,"location":[174.587964,-36.774432]},{"id":2,"location":[174.544603,-36.772491]}],"options":{"g":true}}' http://solver.vroom-project.org
{"code":1,"error":"Invalid json."}`
 
I've saved the json data to a file and loaded to http://map.vroom-project.org/ and it seems to like it. Could you tell me where is the problem? Thanks!

**Comment by jcoupey** [comment]
This is weird, pasting your curl command in a terminal does work on my side. Can you retry to see if there was a temporary hitch?

A wild guess: maybe there are a few subtleties related to quote escaping that may vary from one system to the other...

To work with files in a more convenient way, you can use `--data @file.json` with `curl`.

**Comment by atisnz** [comment]
I assume, you use linux... I have windows 10. it will be some weird escape conversion. the @file.json worked. Thanks!

**Comment by jcoupey** [comment]
> I assume, you use linux...

Yes, and all commands and examples provided in the wiki and various readmes have not been tested on other platforms.

Glad you found a way that works for you!
