### ISSUE TITLE
Possible encoding error

### ISSUE THREAD

**Issue by karsfri** [VROOM-Project/vroom#233]
I'm reading in a csv file with a WINDOWS-1252 encoding. It works perfectly with readr but some characters get messed up when using vroom. For instance I get a heading `SveitarfÃ©lag` instead of `Sveitarfélag`

```
library(tidyverse)
library(vroom)

vroom(
  "https://px.hagstofa.is:443/pxis/sq/47d9838b-da9d-4386-aa52-66d389ae5e49",
  delim = ";",
  locale = locale(encoding = "WINDOWS-1252")
  )

read_delim(
  "https://px.hagstofa.is:443/pxis/sq/47d9838b-da9d-4386-aa52-66d389ae5e49",
  locale = locale(encoding = "WINDOWS-1252"),
  delim = ";"
)

```
p.s. This is my first post on github ever. I don't know if I need to post any more details?

**Comment by jcoupey** [comment]
My understanding is that you have a custom routine to parse your csv file and translate it in an input file following [the vroom API](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md) for solving, is that correct? If so could you share an example of a json input file that could be used to reproduce your problem?

**Comment by karsfri** [comment]
Wow, I'm really sorry, This was ment for the vroom package for r but not for the vroom project. No wonder it took me some time to understand your comment :D  Do I delete the post or...?

**Comment by jcoupey** [comment]
OK, so closing as off topic.
