### ISSUE TITLE
"computing_times" seem not in seconds

### ISSUE THREAD

**Issue by iedmrc** [VROOM-Project/vroom#234]
In the API doc it is written:
`all timings are in seconds`

But the computing_times components seem in milliseconds instead of seconds:

```
    "computing_times": {
      "loading": 4142,
      "solving": 57402,
      "routing": 304
    }
```

What do you think?

**Comment by jcoupey** [comment]
Yes, the values reported under this key are milliseconds. Their sole purpose is debugging and benchmarking, I don't expect them to be really useful for anything else.

As such, they're not actually part of the "stable" API and this is why they're not mentionned in the API docs. I would not considerer it a breaking change if they were to be modified or removed at some point.

**Comment by iedmrc** [comment]
I agree with you. But just wanted to be sure about the measure :). Would you mind to add a "p.s." to the API doc ? If it so, I could send a pull request.

**Comment by jcoupey** [comment]
I don't really feel the need to issue a warning in the docs about something that is (purposely) undocumented. Again I don't want to make this part of the "official" API to avoid being tied to the current format and unable to make any change without considering it a breaking API change.

I guess people getting confused can always come (or be pointed) to this ticket for context. ;-)
