### ISSUE TITLE
Not receiving the correct Output  

### ISSUE THREAD

**Issue by MedAlyH** [VROOM-Project/vroom#239]
I have problem with the vroom api i'm sending the correct input but i'm not receiving the correct output :

**here's my input** : {"vehicles":[{"id":1,"start":[51.756757,-1.258567],"end":[51.756757,-1.258567]}],"jobs":[{"id":0,"location":[51.74772,-1.23702]},{"id":1,"location":[51.75782,-1.59422]},{"id":2,"location":[51.734,-1.21765]},{"id":3,"location":[51.73372,-1.33662]},{"id":4,"location":[51.76166,-1.26804]},{"id":5,"location":[51.75268,-1.25781]},{"id":6,"location":[51.7519,-1.26008]}],"options":{"g":true}} 

**and this is the output :** 

{"code":0,"summary":{"cost":0,"unassigned":0,"service":0,"duration":0,"waiting_time":0,"distance":0,"computing_times":{"loading":2,"solving":0,"routing":2}},"unassigned":[],"routes":[{"vehicle":1,"cost":0,"service":0,"duration":0,"waiting_time":0,"distance":0,"steps":[{"type":"start","location":[51.756757,-1.258567],"arrival":0,"duration":0,"distance":0},{"type":"job","location":[51.734,-1.21765],"job":2,"service":0,"waiting_time":0,"arrival":0,"duration":0,"distance":0},{"type":"job","location":[51.75268,-1.25781],"job":5,"service":0,"waiting_time":0,"arrival":0,"duration":0,"distance":0},{"type":"job","location":[51.7519,-1.26008],"job":6,"service":0,"waiting_time":0,"arrival":0,"duration":0,"distance":0},{"type":"job","location":[51.76166,-1.26804],"job":4,"service":0,"waiting_time":0,"arrival":0,"duration":0,"distance":0},{"type":"job","location":[51.73372,-1.33662],"job":3,"service":0,"waiting_time":0,"arrival":0,"duration":0,"distance":0},{"type":"job","location":[51.75782,-1.59422],"job":1,"service":0,"waiting_time":0,"arrival":0,"duration":0,"distance":0},{"type":"job","location":[51.74772,-1.23702],"job":0,"service":0,"waiting_time":0,"arrival":0,"duration":0,"distance":0},{"type":"end","location":[51.756757,-1.258567],"arrival":0,"duration":0,"distance":0}],"geometry":"lfhZ{sdpI????????????????"}]

**Comment by jcoupey** [comment]
The zero distances/travel times usually suggest that the provided locations have been snapped by OSRM to the same node on the road network.

Indeed, all locations in your input data are [in the sea](http://map.vroom-project.org/?q=a6a38cdf11e1). My guess is that you've been using lat,lon instead of lon,lat for coordinates?

**Comment by MedAlyH** [comment]
Thank you for your replay , yeah i managed to solve the issue by chnaging the order of the lat and long !
