### ISSUE TITLE
Add [time_windows] (*plural) for Vehicles

### ISSUE THREAD

**Issue by mhosman** [VROOM-Project/vroom#242]
There's a way to add multiple time_windows for a single vehicle in order to add, for example, a break time (have lunch)?.

**Comment by jcoupey** [comment]
Defining vehicle working hours as a single time window has been a deliberate choice, see https://github.com/VROOM-Project/vroom/issues/136#issuecomment-406896877 for a bit of context.

If the break location is known in advance, you can already model:

- a fixed-time break by defining one vehicle per time window and setting start/end accordingly
- a flexible break using a job with a specific skill to associate it to the targeted vehicle

Defining flexible vehicle breaks with no fixed location (i.e. taken at the right time wherever the vehicle is) is ticketed in #186. I hope to get started on that soon.

**Comment by mhosman** [comment]
Okay @jcoupey let's close this in favour of #186
