### ISSUE TITLE
Unassigned jobs should show all data for a job.

### ISSUE THREAD

**Issue by rishabhdeepsingh** [VROOM-Project/vroom#243]
Unassigned jobs are not showing all details it should display all details about the job.
[example](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#using-osrm) as given here.
```
  "unassigned": [
    {
      "id": 4,
      "location": [2.41808, 49.22619]
    }
  ]
```

**Comment by jcoupey** [comment]
To be honest, I think the sole purpose of providing the location in output is to be able to plot unassigned jobs in the frontend (I think the `unassigned` array actually started as a list of ids).

On the other hand, in a production setting, jobs ids will typically be unique identifiers from some database. I'm not sure we should really care about providing back context information that is already accessible from the client side?

**Comment by rishabhdeepsingh** [comment]
I thinking providing more information is good.
Let us say we are using Vroom as a wrapper and after that, we need to plot the data on a map. It will be better if we have more information rather than we need to again put a query on the database. This will reduce network issue.

**Comment by jcoupey** [comment]
By "client side" I meant any piece of code that generated the vroom input, that *de facto* already has access to all job descriptions without any outside database query.

As I mentioned above, I've used the `location` of unassigned jobs in output to plot them in [the frontend](https://github.com/VROOM-Project/vroom-frontend). But this is really laziness on my side, I should just have reused the existing job objects generated in javascript to perform the query. Then I could have sticked to a list of ids for the `unassigned` array without restricting possible usage.

**Comment by rishabhdeepsingh** [comment]
So, I think replacing with the original `Job` Object and `vehicle` Object is the way to go. So that we don't have to filter data again.

**Comment by jcoupey** [comment]
> replacing with the original Job Object

Technically that's indeed what you should do if you want to add more information in output. Else you might end up outputting some default values (e.g. for time windows) that are actually stored in `Job` objects but where not in input.

But again I don't think adding a lot of stuff in output just for convenience is a good idea. I can't think of a use-case where this would be mandatory (see previous comments), so I would probably not merge it in `master`.

**Comment by rishabhdeepsingh** [comment]
I think if someone wants to do computation after the output so. giving full Object will be good as he/she don't have to go through input data again which will require an additional `O(n)` complexity.
That's why I was saying replacing with the Original Object will be good.

**Comment by jcoupey** [comment]
> require an additional O(n) complexity

Yes, you want to avoid that. You need to have a constant-time access to the jobs created for the input problem, based on their id. For example in javascript, you could store a simple object using ids as keys and storing a reference to a job object as value.
