### ISSUE TITLE
API docs don't provide enough details about what `time_window` is expected to be

### ISSUE THREAD

**Issue by unguul** [VROOM-Project/vroom#251]
The API documentation tells us that `time_window` is expected to be an `array` in the form of `[start, end]`. However, it doesn't really tell us what the expected data type is and the examples are not clearly saying "this is seconds from start of day".

I understand that it is up to the client to decide how to use `time_window` as mentioned by @jcoupey at https://github.com/VROOM-Project/vroom/issues/162#issuecomment-427045576 but we could make life easier for people who are just starting to use this project (like myself) and make things a bit clearer. 

I will make a PR for this shortly.

**Comment by jcoupey** [comment]
Thanks for the suggestion and PR!
