### ISSUE TITLE
Interaction between OSRM and Vroom 

### ISSUE THREAD

**Issue by MedAlyH** [VROOM-Project/vroom#253]
Hi !

Can you please help me understand the interaction between Vroom and OSRM . what's the role of OSRM in details and why Vroom is optimizing through the travel Time and not the distance .

Can anyone Help me please .

**Comment by jcoupey** [comment]
Prior to the optimization, VROOM needs a matrix that describes travel cost between any pair of location in the problem. It can be passed directly in input like in [this example](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#using-a-custom-matrix). If not, we turn to OSRM or Openrouteservice (see various wrappers [here](https://github.com/VROOM-Project/vroom/tree/master/src/routing)) in order to [get the cost matrix](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/structures/vroom/input/input.cpp#L352).

In addition, whenever the `-g` flag is used, we also [fire route requests](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/structures/vroom/input/input.cpp#L381-L385) **after the optimization** to get extra details on each optimized route (distance, geometry).

The choice of using travel time over distance is due to the fact that routing engine usually optimize (mostly) on travel time by default. Also having travel times make it possible to monitor arrival times for the VRP variant with time windows.

**Comment by MedAlyH** [comment]
@MedAlyH 
Thank your for your replay , so if i understood well the architecture :  
1-First we send a Json file to the OSRM containing the locations of our jobs 
2-OSRM calculate the cost matrix and the geometry and return the result in a  Json File 
3-Vroom uses the cost matrix to calculate the best path through the TSP algorithm
4-Vroom send a Json file to the frontend containing the jobs ordonated and the geometry.

Please check these steps and help me understand the exchange of data between the Vroom and the OSRM . Thank you in advance

**Comment by jcoupey** [comment]
You got that right.

We have a variant for 1 and 2: using OSRM as a library (see `libosrm_wrapper` file and `-r` flag) speeds up exchanges because the matrix object can be directly retrieved as a C++ object so we save some json serialization and parsing both on OSRM and VROOM side.

**Comment by MedAlyH** [comment]
@jcoupey 
Thank you for the replay 

So if  got it right ! 

for step 1 and 2 we can either have an exchange through Json files using the osrm_routed_wrapper file or we can get the cost matrix directtly as a c++ object using the libosrm_wrapper file .

Thank you dear sir

**Comment by jcoupey** [comment]
> for step 1 and 2 we can either have an exchange through Json files using the osrm_routed_wrapper file or we can get the cost matrix directtly as a c++ object using the libosrm_wrapper file .

Exactly. Closing as answered, feel free to reopen if required.

**Comment by MedAlyH** [comment]
Hello again SIr ;

I would like to ask if at this stage : https://github.com/VROOM-Project/vroom/blob/master/src/routing/osrm_routed_wrapper.cpp#L78  the OSRM start creating the Cost Matrix Right?

THank you in advance

**Comment by jcoupey** [comment]
This is the part where we copy the OSRM matrix in `infos["durations"]` to our custom `Matrix<cost>` object.

The matrix request is fired [just above](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/routing/osrm_routed_wrapper.cpp#L54-L56).

**Comment by MedAlyH** [comment]
Hello SIr,

Can you please help me and tell me what is the cost we are calculating Here :  https://github.com/VROOM-Project/vroom/blob/master/src/problems/tsp/tsp.cpp#L118 

and can you please help me understand what we do here : https://github.com/VROOM-Project/vroom/blob/master/src/problems/tsp/tsp.cpp#L205 in the case our matix is not symmetric 
did we proceed a local_search directly without heurestics or what we do ??

Please Help me understand

**Comment by jcoupey** [comment]
The `tour` parameter describes a solution as a list of location ranks in the matrix, so `TSP::cost` just adds up matrix values to get the whole cost for the tour.

> in the case our matix is not symmetric did we proceed a local_search directly without heurestics

The solution that is used as a starting point when getting back to the asymmetric case is the one obtained after treating the symmetrized problem (or the same reversed if the cost is better).

**Comment by MedAlyH** [comment]
@jcoupey 

Thank you for your replay sir,

But excuse me i still do not get it ! if our matrix is not symmetric and we apply the local search for the symmetric matrix that we used as a starting point we will get wrong results didn't we ? 

Sorry to bother you ! but i really need to understand this point

**Comment by jcoupey** [comment]
When solving a TSP (and only for that kind of problem), switching to a symmetrized version of the problem make it necessary to store [two different matrices](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/problems/tsp/tsp.h#L33-L34).

Computing the symmetrized matrix happens [in the `TSP` constructor](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/problems/tsp/tsp.cpp#L98).

**Comment by MedAlyH** [comment]
@jcoupey 

Yeah I know that we calculate the symmetrized matrix ! i'm asking if our problem is not symmetric and we calculate the symmetric matrix and apply the algorithm and the local search then what we do to have the result for the non-symmetric matrix ? 
That's what i'm asking about 

Si notre cas n'est pas symétrique et on proccéde à le rendre symétrique qu'est ce qu'on fait aprés la résolution de sa version symétrique ! comment revernir à la version non symétrique et la résoudre !

Merci Beaucoup

**Comment by MedAlyH** [comment]
@jcoupey 

CHer Monsieur,

Est ce que tu peux m'expliquer comment on force notre solution pour le TSP pour commencer et finir du même point qui est fourni initialement ( dans mon cas c'est l'emplacement du warehouse ) et est ce que ce point rentre dans le calcul . Prière de me répondre.

**Comment by jcoupey** [comment]
> what we do to have the result for the non-symmetric matrix ?

The solution obtained after the Christofides heuristic and local search (with symmetric matrix) is then used in the asymmetric case as **the starting point** of a new local search. This last phase is triggered [here](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/problems/tsp/tsp.cpp#L212-L217) using the initial matrix so during that step all modification operators take assymetric costs into account.

@MedAlyH please stick to english in this bugtracker so that any comment and answer can be useful to anyone coming across this issue.

**Comment by MedAlyH** [comment]
@jcoupey 

OKay Thank you Sir foe your replay ! 

Can you explain to me how we force our solution for the TSP to start and finish from the same point that is provided initially (in my case it is the location of the Warehouse ) and is that point is taken into consideration when performing the TSP . Please give me an answer

**Comment by jcoupey** [comment]
> Can you explain to me how we force our solution for the TSP to start and finish from the same point that is provided initially

For a TSP, the cost of a round trip will be the same no matter where the route starts. Presenting the solution with the input start first happens [here](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/problems/tsp/tsp.cpp#L239) where `first_loc_index` is the desired tour start. The implementation details are [here](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/problems/tsp/heuristics/local_search.cpp#L772-L781).

**Comment by MedAlyH** [comment]
Hello sir, i would like to ask you if in our case to solve TSP we are using the Table service provided by OSRM or another service ? and we are using it through HTTP requests ?

**Comment by jcoupey** [comment]
Yes, the `table` OSRM endpoint is used before optimization, then `route` requests can be fired after to get detailed route geometry. There are two ways the requests can be performed (see `-r` flag):

- via HTTP [here](https://github.com/VROOM-Project/vroom/blob/3b656cb2ccb6f5adb1df98e25e7b0319f2ba129e/src/routing/osrm_routed_wrapper.cpp#L53)
- using OSRM as a C++ library [here](https://github.com/VROOM-Project/vroom/blob/3b656cb2ccb6f5adb1df98e25e7b0319f2ba129e/src/routing/libosrm_wrapper.cpp#L42)

We also have a wrapper to use [Openrouteservice](https://openrouteservice.org/) as routing engine.

For more, check the [routing folder](https://github.com/VROOM-Project/vroom/tree/master/src/routing) where everything routing-related happens.

**Comment by MedAlyH** [comment]
Hello Sir ,
Excuse me I have a question concerning the TSP ! you said "For a TSP, the cost of a round trip will be the same no matter where the route starts." can you explain me more how the choice of the start point did not affect the resolution of the TSP and thank you a lot

**Comment by jcoupey** [comment]
>  the cost of a round trip will be the same no matter where the route starts

I meant that a round trip A -> B -> C ->D -> A (presented in the output as starting from A) will have the same cost whatever the start point, e.g. C -> D -> A ->  B -> C (presented in the output as starting from C).

**Comment by MedAlyH** [comment]
Thank you , for you reply 

So it wont affect the resolution of the tsp if in each time i fix the same starting and ending point and i only change the jobs ( stops ) ?

**Comment by jcoupey** [comment]
I mean for a **given** round trip the cost is the same. `A -> B -> C ->D -> A` and `C -> D -> A -> B -> C` have same cost because the jobs have **the same ordering**, no matter the starting point (all visited edges are the same).

If you change the ordering and/or the stop locations of course the cost will be different.

**Comment by MedAlyH** [comment]
Sorry sir you still do not get me ! i meant if i start by fixing my start and ending point which is the same  ( the warehouse placement in my case ) and then i give the locations of the jobs would this affect the tsp resolution as i forced the starting and the ending point , the algorithm will not choose the starting point he will start by searching the first job

**Comment by jcoupey** [comment]
From the TSP perspective, the start of a round trip does not matter (see above), so the trip is stored as a [plain set of edges](https://github.com/VROOM-Project/vroom/blob/3b656cb2ccb6f5adb1df98e25e7b0319f2ba129e/src/problems/tsp/heuristics/local_search.h#L26). Then the [`get_tour`](https://github.com/VROOM-Project/vroom/blob/3b656cb2ccb6f5adb1df98e25e7b0319f2ba129e/src/problems/tsp/heuristics/local_search.cpp#L772-L781) function serves as a way to format a tour with whatever starting point is preferred. It's called after the TSP local search phase [here](https://github.com/VROOM-Project/vroom/blob/3b656cb2ccb6f5adb1df98e25e7b0319f2ba129e/src/problems/tsp/tsp.cpp#L239).
