### ISSUE TITLE
Problem compiling VRoom due to boost lib

### ISSUE THREAD

**Issue by didac-wh** [VROOM-Project/vroom#265]
Hi, no C++ programmer here.

I could compile boost library, VRoom, OSRM project and processed a map through the different stages.
However, when I try to execute the vroom executable it says the following:
`./vroom: error while loading shared libraries: libboost_system.so.1.71.0: cannot open shared object file: No such file or directory`

Compiled boost library is located in /usr/local/lib. I located in in more places too (/usr/local/boost_1_71_0, project_root/lib, project_root/src/lib) and recompiled every time but it says the same.
That particular file (libboost_system.so.1.71.0) exists in all those directories.
I also set permissions more open just in case vroom exectuable couldn't have access, but even 777 didn't work.
I tried to set a couple envvars with /usr/local/lib value:
`set LD_LIBRARY_PATH=/usr/local/lib
set CPLUS_INCLUDE_PATH=/usr/local/lib
`
but nothing changes either.

It's probably a dumb mistake but I can't find where's the problem.

As a side note, I could compile the project successfully in a MacBook, but now I'm working on an AWS Linux AMI.

Any help please? Thank you.

**Comment by jcoupey** [comment]
You probably need to run `ldconfig` after a manual boost install:

```
sudo ldconfig -n /usr/local/lib
```

**Comment by didac-wh** [comment]
> You probably need to run `ldconfig` after a manual boost install:
> 
> ```
> sudo ldconfig -n /usr/local/lib
> ```

Thanks for your help. That makes totally sense. However, after executing it the same problem remains (error while loading shared libraries: libboost_system.so.1.71.0: cannot open shared object file: No such file or directory)

I tried to execute your command with verbose option and the lib is indeed listed, see below:
`libboost_date_time.so.1.71.0 -> libboost_date_time.so.1.71.0
        libboost_coroutine.so.1.71.0 -> libboost_coroutine.so.1.71.0
        libboost_thread.so.1.71.0 -> libboost_thread.so.1.71.0
        libboost_contract.so.1.71.0 -> libboost_contract.so.1.71.0
        libboost_system.so.1.71.0 -> libboost_system.so.1.71.0
        libboost_context.so.1.71.0 -> libboost_context.so.1.71.0
        libboost_container.so.1.71.0 -> libboost_container.so.1.71.0
        libboost_chrono.so.1.71.0 -> libboost_chrono.so.1.71.0
        libboost_atomic.so.1.71.0 -> libboost_atomic.so.1.71.0
        libboost_wave.so.1.71.0 -> libboost_wave.so.1.71.0
        libboost_type_erasure.so.1.71.0 -> libboost_type_erasure.so.1.71.0
        libboost_timer.so.1.71.0 -> libboost_timer.so.1.71.0
        libboost_unit_test_framework.so.1.71.0 -> libboost_unit_test_framework.so.1.71.0
        libboost_prg_exec_monitor.so.1.71.0 -> libboost_prg_exec_monitor.so.1.71.0
        libboost_stacktrace_basic.so.1.71.0 -> libboost_stacktrace_basic.so.1.71.0
        libboost_stacktrace_addr2line.so.1.71.0 -> libboost_stacktrace_addr2line.so.1.71.0
        libboost_stacktrace_noop.so.1.71.0 -> libboost_stacktrace_noop.so.1.71.0
        libboost_wserialization.so.1.71.0 -> libboost_wserialization.so.1.71.0
        libboost_serialization.so.1.71.0 -> libboost_serialization.so.1.71.0
        libboost_random.so.1.71.0 -> libboost_random.so.1.71.0
        libboost_python27.so.1.71.0 -> libboost_python27.so.1.71.0
        libboost_program_options.so.1.71.0 -> libboost_program_options.so.1.71.0
        libboost_math_tr1l.so.1.71.0 -> libboost_math_tr1l.so.1.71.0
        libboost_math_tr1f.so.1.71.0 -> libboost_math_tr1f.so.1.71.0
        libboost_math_tr1.so.1.71.0 -> libboost_math_tr1.so.1.71.0
        libboost_math_c99l.so.1.71.0 -> libboost_math_c99l.so.1.71.0
        libboost_math_c99f.so.1.71.0 -> libboost_math_c99f.so.1.71.0
        libboost_math_c99.so.1.71.0 -> libboost_math_c99.so.1.71.0
        libboost_log_setup.so.1.71.0 -> libboost_log_setup.so.1.71.0
        libboost_log.so.1.71.0 -> libboost_log.so.1.71.0
        libboost_locale.so.1.71.0 -> libboost_locale.so.1.71.0
        libboost_iostreams.so.1.71.0 -> libboost_iostreams.so.1.71.0
        libboost_graph.so.1.71.0 -> libboost_graph.so.1.71.0
        libboost_regex.so.1.71.0 -> libboost_regex.so.1.71.0
        libboost_fiber.so.1.71.0 -> libboost_fiber.so.1.71.0
        libboost_filesystem.so.1.71.0 -> libboost_filesystem.so.1.71.0
`

I tried to recompile vroom (remove vroom directory, download tar, extract, go to src and make), but same error keeps happening.

**Comment by didac-wh** [comment]
I add some more details:
When compiling boost I noticed it uses a 64 bit model, and I saw I have a /usr/local/lib64 directory that was empty.
Using address-model=64 was installing the libs into /usr/local/lib anyway so I copied /usr/local/lib contents to /usr/local/lib64 and did **sudo ldconfig -n /usr/local/lib64**. Unfortunately, nothing changed, I'm still getting the same error.

**Comment by jcoupey** [comment]
The weird thing is that if you're able to build running `make`, it means that boost is successfully found at compile-time. Can you try forcing the path to your custom boost install in the makefile:

```patch
diff --git a/src/makefile b/src/makefile
index 320c437..f629843 100644
--- a/src/makefile
+++ b/src/makefile
@@ -6,7 +6,7 @@
 # Variables.
 CXX ?= g++
 CXXFLAGS = -MMD -MP -I. -std=c++14 -Wextra -Wpedantic -Wall -O3
-LDLIBS = -lboost_system -lpthread
+LDLIBS = /usr/lib/x86_64-linux-gnu/libboost_system.so -lpthread
 
 # Using all cpp files in current directory.
 MAIN = ../bin/vroom
```

(replacing `/usr/lib/x86_64-linux-gnu/libboost_system.so` with a relevant path on your system) then recompile `vroom`?

**Comment by didac-wh** [comment]
I've been trying different things during the last couple hours and finally the following worked:
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib ./vroom

(After that I set its value inside /etc/.profile to make it persitent between sessions).

During compilation it worked indeed, the problem occured only during execution.

I appreciate very much your help.

**Comment by jcoupey** [comment]
So your initial problem is now solved and you're able to run `vroom`?

**Comment by didac-wh** [comment]
Yes, I'll close the issue, hope it's useful for somebody else in the future. Thank you.

**Comment by jcoupey** [comment]
Thanks for sharing what worked for you.
