### ISSUE TITLE
Job unassigned reason?

### ISSUE THREAD

**Issue by ifle** [VROOM-Project/vroom#270]
First of all thanks for a great library. I am impressed with performance. 
How to check a reason for unassigned jobs? It’s important for customers to know the reason for unassigned jobs

**Comment by jcoupey** [comment]
There is no built-in way to provide job-level feedback for non-assignment because we look at the whole picture to decide on which solution to pick. So the "reason" for picking a solution over another (i.e. the optimization objective) currently is:

1. overall priority score is better
2. number of unassigned jobs is better (with equal value for 1.)
3. overall travel time is better (with equal value for 1. and 2.)

Of course having unassigned jobs is always related to the input constraints: capacity restrictions or incompatible (or too tight) time-windows, but it's not always that easy to come up automatically with a reason. Simple example: a job can come up as unassigned for no "obvious" reason (it could actually be handled in some route for a different solution), but if you look down the line, not including it may allow to add more other jobs in the corresponding route.

As a general rule based on the optimization objectives above, the solver will tend to set as unassigned the jobs with lowest priority, or the ones that prevent including more other jobs, or simply more costly jobs (typical situation: long travel times to reach an "isolated" job).

**Comment by ifle** [comment]
Thanks for your explanation. At the moment, we are using jsprit and it provide the unassigned reasons. 
Your are right that the reason are related to constraints like time window, capacity, skills or custom constraints. Jsprit is very flexible and we have customs constraints too.
I'm trying to compare the features sets. The performance of the vroom is amazing and I'm trying to understand if we can switch to vroom. 
For that reason I've added the vroom to our test application that can both run jsprit and vroom for comparison.

**Comment by jcoupey** [comment]
>The performance of vroom is amazing

That's nice to hear! Thanks for the feedback and context. If you're running comparison tests, I'd be really interested in the outcome for global indicators on both solution quality and computing times.

>  At the moment, we are using jsprit and it provide the unassigned reasons.

I have no clue how providing "reasons" works within jsprit, my guess would be they have some kind of heuristic way to determine the most plausible human-readable reason. The best way to learn about this would probably be to dig into the source code. Happy to hear about that too if you have time to take a look and share.

**Comment by ifle** [comment]
> That's nice to hear! Thanks for the feedback and context. If you're running comparison tests, I'd be really interested in the outcome for global indicators on both solution quality and computing times.

I'm starting playing with vroom and can compare the solution quality. The problem that I run on our real customer data and can't to share them publicly. I can share the data privately.
Another problem is that it is not always easy to compare, because we use features of jsprit which are not present in the vroom like shipments (pickup-delivery), initial route(predefined sequence of jobs) or additional distance cost for simulate the traffic.

> I have no clue how providing "reasons" works within jsprit, my guess would be they have some kind of heuristic way to determine the most plausible human-readable reason. The best way to learn about this would probably be to dig into the source code. Happy to hear about that too if you have time to take a look and share.

When the insertion of a job is rejected by some constraint it marked is unassigned and stored the constrain name.
https://github.com/graphhopper/jsprit/blob/74c3c6839bf64b6bbd73814397b06137be386a79/jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/BestInsertionConcurrent.java#L148

Jsprit has UnassignedJobReasonTracker that map constraints names to reason
https://github.com/graphhopper/jsprit/blob/74c3c6839bf64b6bbd73814397b06137be386a79/jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/UnassignedJobReasonTracker.java#L66

**Comment by ifle** [comment]
> That's nice to hear! Thanks for the feedback and context. If you're running comparison tests, I'd be really interested in the outcome for global indicators on both solution quality and computing times.

I have example of comparison between jsprit and vroom. By my opinion the jsprit solution is more accurate. How to share it?

**Comment by jcoupey** [comment]
Yes, you'd have to do the comparisons on problem instances that have the same scope in term of constraints, and the same input matrix (that's probably OK if you're using OSRM).

What you can share publicly is some insights on quality and computing times. For any other matter, you can reach me directly at contact@verso-optim.com.

Thanks for sharing the code links regarding the rejection reasons. It looks like it's only storing the reason **on the last job insertion attempt**. I didn't think it through yet, but maybe this is enough. In your experience, are the reasons computed this way always relevant from the user point of view?

**Comment by ifle** [comment]
jsprit support one reason per job. From the user point of view it's very helpful. 
It helps to customers understand why some job out of route. For our customers it's very important.

I did comparison with 600+ jobs and 40 vehicles from one of our customer. 
Jsprit created routes with 23 vehicles. vroom with 25. 
From customer view of point using of additional vehicles is very expensive. In other hand we also have customers that wants  balance the number jobs over all drivers.

**Comment by jcoupey** [comment]
Yes, for a fair comparison, you also want to make sure that the optimization objective is the same.

Our main optimization objective is minimizing overall travel duration, not number of vehicles. This is sometimes strongly related, but not always.

We have no built-in way to balance number of jobs among drivers, though there has been a related discussion back in #225.

**Comment by showkeyjar** [comment]
`number of unassigned jobs is better (with equal value for 1.)`
how to minimize unassigned jobs? and set it as the first rule?

**Comment by jcoupey** [comment]
> how to minimize unassigned jobs? and set it as the first rule?

I you set the same priority level to all jobs or don't use priorities at all, then minimizing the number of unassigned jobs is already the first rule.

**Comment by mhosman** [comment]
It would be so great to find some way to know whats the reason for unassigned jobs!
