### ISSUE TITLE
Cost vs Duration vs Service

### ISSUE THREAD

**Issue by unguul** [VROOM-Project/vroom#272]
I'm unsure what the difference between `cost`, `duration`  and `service` is. My current understanding based on the docs and examples is the following:

- `service` is time it takes to load/unload when servicing a job;
- `duration` is the time it takes for travelling to the job location;
- `cost` is the total cost for completing a particular job. i.e. `service` + `duration`;

This applies to both the summary context and the route context in the output.

However, with v1.4.0, the `cost` is equal to `duration` for both the summary and the job contexts.

I've had a quick look at the open/closed issues but did not find any information on this. I'm happy to provide a PR for clarifying this in the docs.

**Comment by jcoupey** [comment]
> `service` is time it takes to load/unload when servicing a job;
> `duration` is the time it takes for travelling to the job location;

Correct. `duration` is always a travel time (maybe it should have had a different name in the first place). Both `service` and `duration` are represented as `vroom::Duration` [internally](https://github.com/VROOM-Project/vroom/blob/70deadafbab175336bce210c6ae5232d26cd8ffb/src/structures/typedefs.h#L30).

> `cost` is the total cost for completing a particular job. i.e. service + duration;

No, `cost` here refers to the solution cost, as seen from the optimization point of view. Currently, we optimize based on total travel time so `cost` and `duration` will always be equal at `route` and `summary` level. The rationale behind having different metrics is that maybe at some point in the future they might differ (think e.g. optimizing on total travelled distance or any combination of travelled time and distance).

**Comment by unguul** [comment]
@jcoupey Thank you for clarifying that. Is it ok if I send a PR to put this information in the docs?

**Comment by jcoupey** [comment]
Yes, I guess that would make sense to mention that `cost` only refers to the solution evaluation during optimization, and that it's currently equal to `duration` in all cases.

**Comment by unguul** [comment]
@jcoupey Is there a particular reason for not including the service time in the `cost`? 

From my point of view, it would make sense to do so as certain jobs could considerably impact the `cost` of individual jobs and as such, certain jobs would be more suitable for other vehicles. 

I did take a look at previously open issues (closed and open) but have not found much on this subject.

Thank you!

**Comment by jcoupey** [comment]
> Is there a particular reason for not including the service time in the cost?

Suppose we include service time in the solution cost as the sum of all service times across assigned jobs:

- for solutions that handle all jobs, this is a fixed value so from the optimization perspective it has no impact on which solution we pick
- if not all jobs are included **and** if service times vary significantly, then yes it might impact the chosen solution and which jobs end up unassigned. But as we first try to have as few unassigned jobs as possible, we already tend to favor jobs with smaller service times as they leave more room to others.

Plus we provide a way to handle the latest situation on the modelling side with the job `priority` key.

You might be interested in checking out the actual [comparison logic](https://github.com/VROOM-Project/vroom/blob/70deadafbab175336bce210c6ae5232d26cd8ffb/src/structures/vroom/solution_state.h#L33-L54) that is used to decide which solution is "best".

**Comment by unguul** [comment]
@jcoupey Thank!
