### ISSUE TITLE
Use version 1.5 to solve version 1.4 cvrptw problem

### ISSUE THREAD

**Issue by cedric-holdy** [VROOM-Project/vroom#278]
Is it possible to use version 1.5 to solve version 1.4 cvrptw problem ?

**Comment by jcoupey** [comment]
We use semantic versioning, so yes. The `amount` key for jobs is marked as deprecated but backward compatibility is ensured. If you have your own toolchain setup to format instances and use v1.4 solutions, you should be able to upgrade seamlessly to v1.5.

You can refer to the [parsing logic](https://github.com/VROOM-Project/vroom/blob/39229cbb9aa2970d7a1994dfa9941fa3fc8b7c8e/src/utils/input_parser.cpp#L369-L385) for `delivery`, `pickup` and `amount`. TL;DR is that whenever no `delivery` or `pickup` is provided in input, then the `amount` key is used as before and you can expect the same output as with v1.4 regarding the `amount` values.

**Comment by cedric-holdy** [comment]
Thank you very much. 👍
