### ISSUE TITLE
Problem to compile Vroom - make

### ISSUE THREAD

**Issue by marek1545** [VROOM-Project/vroom#279]
Hello,
I have problem with function make. I work on debian 8. I installed osrm, download maps everthing work but I can't compile vroom. I don't have any idea how to fix this.

My console show:
g++ -MMD -MP -I. -std=c++14 -Wextra -Wpedantic -Wall -O3 -DNDEBUG -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm  -D USE_LIBOSRM=true -c main.cpp -o main.o
g++ -MMD -MP -I. -std=c++14 -Wextra -Wpedantic -Wall -O3 -DNDEBUG -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm  -D USE_LIBOSRM=true -c routing/libosrm_wrapper.cpp -o routing/libosrm_wrapper.o
routing/libosrm_wrapper.cpp: In member function ‘virtual vroom::Matrix<unsigned int> vroom::routing::LibosrmWrapper::get_matrix(const std::vector<vroom::Location>&) const’:
routing/libosrm_wrapper.cpp:46:45: error: cannot convert ‘osrm::util::json::Object’ to ‘osrm::engine::api::ResultT&’ {aka ‘mapbox::util::variant<osrm::util::json::Object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, flatbuffers::FlatBufferBuilder>&’}
   46 |   osrm::Status status = _osrm.Table(params, result);
      |                                             ^~~~~~
      |                                             |
      |                                             osrm::util::json::Object
In file included from ./routing/libosrm_wrapper.h:14,
                 from routing/libosrm_wrapper.cpp:16:
/usr/local/include/osrm/osrm.hpp:96:81: note:   initializing argument 2 of ‘osrm::engine::Status osrm::OSRM::Table(const osrm::engine::api::TableParameters&, osrm::engine::api::ResultT&) const’
   96 |     Status Table(const TableParameters &parameters, osrm::engine::api::ResultT &result) const;
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
routing/libosrm_wrapper.cpp: In member function ‘virtual void vroom::routing::LibosrmWrapper::add_route_info(vroom::Route&) const’:
routing/libosrm_wrapper.cpp:111:45: error: cannot convert ‘osrm::util::json::Object’ to ‘osrm::engine::api::ResultT&’ {aka ‘mapbox::util::variant<osrm::util::json::Object, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, flatbuffers::FlatBufferBuilder>&’}
  111 |   osrm::Status status = _osrm.Route(params, result);
      |                                             ^~~~~~
      |                                             |
      |                                             osrm::util::json::Object
In file included from ./routing/libosrm_wrapper.h:14,
                 from routing/libosrm_wrapper.cpp:16:
/usr/local/include/osrm/osrm.hpp:87:81: note:   initializing argument 2 of ‘osrm::engine::Status osrm::OSRM::Route(const osrm::engine::api::RouteParameters&, osrm::engine::api::ResultT&) const’
   87 |     Status Route(const RouteParameters &parameters, osrm::engine::api::ResultT &result) const;
      |                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
make: *** [makefile:52: routing/libosrm_wrapper.o] Error 1

**Comment by jcoupey** [comment]
The error is related to the libosrm code used, can you share the version of libosrm you have installed?

**Comment by marek1545** [comment]
Thanks for response.  I install OSRM-BACKEND 5.21.0. Is newest version osrm project.

**Comment by jcoupey** [comment]
I can't reproduce this when building against `libosrm` v5.21.0. Can you share what version of `vroom` you're trying to build, and what version of `g++` you're using?

**Comment by marek1545** [comment]
Ok. I start for begining.  I have server Plesk Onyx on Debian 8 (jessie)

I install only:  
from standard contribute 
make Version:  4.2.1
pkg-config Version:  0.28
libstxxl-dev Version: 1.4.0-3
libxml2-dev Version: 2.9.1+dfsg1-5+deb8u7
libsparsehash-dev - Version: 2.0.2-1
libbz2-dev  Version: 1.0.6-7+deb8u2
zlib1g-dev Version: 1:1.2.8.dfsg-2+b1
libzip-dev Version: 0.11.2-1.2
libgomp1 Version: 9.2.1-8
liblua5.2-dev  Version: 5.2.3-1.1
libgdal-dev Version: 1.10.1+dfsg-8+b3
libexpat1-dev Version: 2.1.0-6+deb8u6
libtbb-dev Version: 2019~U8-1
doxygen  Version: 1.8.8-5+deb8u1

Extendes
cmake -  Version:  3.10.3

From debian testing source - I must use testing contribute because in standard debian contribute g++ and gcc or libboost is to old for new version osrm. 

g++ Version: 4:9.2.1-3.1
gcc Version: 4:9.2.1-3.1
libboost-dev  Version: 1.67.0.2
libboost-filesystem-dev
libboost-thread-dev
libboost-system-dev
libboost-regex-dev
libboost-program-options-dev
libboost-iostreams-dev
ibboost-test-dev


I am very grateful for help.

**Comment by jcoupey** [comment]
Thanks for the details.

We don't have automatic Travis builds for g++-9 (yet). But I just successfully built vroom v1.5.0 against libosrm v5.21.0 using g++-9 (version 9.2.1) under Ubuntu.

Did you checkout v1.5.0 for vroom or are you trying to build an older version?

**Comment by marek1545** [comment]
Unfortunately I can't compile vroom from your advice. I reinstall server. After that I compile vroom on gcc, libboost, g++ on debian standard contribute and later I change gcc, libboost, g++ testing contribute and install osrm-backend.

Now works vroom and osrm.

But I have problem with vroom-express  node console show me. 
Mon, 28 Oct 2019 02:15:48 GMT: /bin/sh: 1: vroom: Permission denied

I compile vroom in /usr/bin/vroom, osrm in /usr/bin/osrm-backend  and vroom-express on /usr/bin/vroom-express.  I don't know what is problem - maybe chmod or  path ??

**Comment by jcoupey** [comment]
> and later I [...] install osrm-backend

If you compile vroom without `libosrm` installed, then the file `routing/libosrm_wrapper.h` (the one that links to OSRM stuff causing trouble) is not used at all. Then you won't be able to use OSRM as a library (`vroom -r libosrm`). But if you plan to run `osrm-routed` for routing this is totally fine.

> Mon, 28 Oct 2019 02:15:48 GMT: /bin/sh: 1: vroom: Permission denied

The user running `vroom-express` probably does not have execution rights on `/usr/bin/vroom`. You should check the permissions and maybe `chmod +x`.

**Comment by marek1545** [comment]
Yes. I only want use routing.

In first i was think only osrm-backend and option trip is for me good enough. But routs returning from osrm it isn't that same as return from http://solver.vroom-project.org

I add chmod 777 on vroom folder and still I have vroom: Permission denied.

Can you show me expample how I use vroom routing from bash not from vroom-express.

I'm very sorry I don't have experience with  configuration server and staff like that.
Thank you for your understanding

**Comment by jcoupey** [comment]
To use from command-line, just save your input to a json file and run `vroom` on it. See [Usage page](https://github.com/VROOM-Project/vroom/wiki/Usage) from the wiki.

**Comment by marek1545** [comment]
I very grateful is working from file. Awesome. 

Now I will try to fix vroom-express permission but I in the worst case I will use json file and vroom. 

Thank you very much for your time and patience for me.
