### ISSUE TITLE
Prioritize time windows over travelled duration

### ISSUE THREAD

**Issue by ivosabev** [VROOM-Project/vroom#282]
Is there currently a way to prioritize the vehicles to be more on time on the expense of adding more travel duration?

**Comment by jcoupey** [comment]
I'm not sure I get what you mean exactly by "more on time".

Currently if a vehicle can't make it on time for one job (read arrival at job is not inside one of the job time-windows), then the associated route is considered invalid and is discarded.

**Comment by ivosabev** [comment]
My bad, there was an error in my implementation, now it works fine and late tasks are left unassigned.
