### ISSUE TITLE
caching system

### ISSUE THREAD

**Issue by stefanocudini** [VROOM-Project/vroom#284]
this engine has any type of storage system integrated? for example caching of problem's results or other? Or each calculation simply occur in RAM each time again from zero?
Does it consume some disk space besides binaries and configurations?

**Comment by jcoupey** [comment]
No, there is no storage or caching involved when you invoke `vroom` from command-line. What happens is:
- parsing the problem from standard input or a file (using `-i`)
- computing a solution
- outputting the solution to standard output or a file (using `-o`)

While solving, RAM consumption will be dominated by holding the travel time matrix in memory so is expected to be O(number of locations).

Now a common setting is to run [vroom-express](https://github.com/VROOM-Project/vroom-express) to expose the API through http requests. In that case the wrapper actually:
- [writes](https://github.com/VROOM-Project/vroom-express/blob/e532a55bad05b82522e6c511b8ec53850b6f23f2/src/index.js#L173) the payload to disk
- [sends](https://github.com/VROOM-Project/vroom-express/blob/e532a55bad05b82522e6c511b8ec53850b6f23f2/src/index.js#L224) the solution
- [deletes](https://github.com/VROOM-Project/vroom-express/blob/e532a55bad05b82522e6c511b8ec53850b6f23f2/src/index.js#L226-L228) the payload.

So you could adjust this behaviour if you need some caching mechanism for problem input and result. Do you have some other use-case in mind?

**Comment by jcoupey** [comment]
For the sake of completeness, we have a script that allows to sort of cache the OSRM travel time matrix and embed it in the input file, see [this wiki page](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance)

**Comment by stefanocudini** [comment]
I am comparing different routing engines and cataloging their generic characteristics
so I seem to understand that a possible cache can be integrated outside the routing engine.

> For the sake of completeness, we have a script that allows to sort of cache the OSRM travel time matrix and embed it in the input file, see [this wiki page](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance)

thank you this is very interesting
