### ISSUE TITLE
API refactor

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#30]
The input should be safer (and also easier) to parse for further feature additions, dropping the query-like input to switch to json.

The syntax is yet to be defined, but should remain easy to maintain and enhance for new features.

**Comment by jcoupey** [comment]
Targeted json output solution structure:

* `solution`
    * `cost`
    * `computing_times`
        * `loading`
        * `solving`
            * `heuristic`
            * `local_search`
        * `routing` (`-g` option only).
* `routes`: array of `Route` objects

where a `Route` has the following properties:

* `steps` (array, previously `tour`)
* `locations` (array, previously `route`)
* `cost`
* `geometry` (`-g` only, previously `route_geometry`)
* `duration` (`-g` only, previously `total_time`)
* `distance` (`-g` only, previously `total_distance`)

**Comment by jcoupey** [comment]
A possible json input structure would be:

* `jobs` array of `job` objects describing the places to visit
* `vehicles` array of `vehicle` objects describing the available vehicles

where `job` objects have the following properties:
* `id` (maybe optional defaulting to the rank in the array)
* `location`
* ... (any other field required for future features)

and `vehicle` objects have the following properties:
* `id` (maybe optional defaulting to the rank in the array)
* `start_id`
* `round_trip`: boolean
* `end_id` (optional)
* ... (any other field required for future features)

**Comment by jcoupey** [comment]
For consistency, a json output should be generated with a specific `code` and `error` key when an error occur (previous post about json output structure edited accordingly).

**Comment by jcoupey** [comment]
More structured description of routes steps. Previous posts updated.

**Comment by jcoupey** [comment]
The `round_trip` flag in input can be somewhat unclear with regard to its use in conjunction with the `start` and `end` keys. And also a PITA to check for valid input.

The best thing to do would probably be to remove it altogether. In that case any combination of optional `start` and `end` keys would be valid; planning a round trip would be a matter of providing the same `start` and `end` in input.

**Comment by Drag0s** [comment]
Is there a specific reason that for job/vehicle id only can be an integer? I think it would be nice if it could accept an string too.

**Comment by jcoupey** [comment]
Thanks for stepping in on this, comments and ideas are really appreciated.

The original reason is that integers are probably the best/easiest fit for unique identification. Another point is that many queries would likely be generated from databases where jobs and vehicles would be best described by their index, especially for further solution handling.

Yet as you mention, it might prove useful (and more human-friendly) to have a simple string describing jobs or vehicles. Then what about adding a `description` key (maybe optional) in input? Whenever a `job` or `vehicle` contains a `description` string, it would be sent back in the output.

**Comment by jcoupey** [comment]
The API documentation is now included in the `docs` folder to allow updating during further development. Much more flexible than a wiki page.
