### ISSUE TITLE
Dynamic point visit-ability condition

### ISSUE THREAD

**Issue by MikeDabrowski** [VROOM-Project/vroom#304]
In my routing problem I have two groups of points (say 1-4 and A-F) where points 1-4 require certain number of points A-F visited first. I discovered VROOM via OpenRouterService API and I see that they are using older version (with `amount` and without `shipment`). If newer VROOM version is required then I think I'll be able to build from source and use it feeding it a custom matrix obtained from OpenRouterService.

Ex:
Car can get to point 1 if it visited at least one point A-F
Car can get to point 2 if it visited at least two points A-F
...

Does current vroom implementation can help in solving this problem? 
I got some few initial ideas:

1. `skills` could be used in a way that a skill should be dynamically increased when visited any A-F point. Then if point 1 requires skill 1, car would go to any A-F point and then increase its skill and come back to point 1 later.

2. The thing that changes between subsequent points is the 'cargo' the car is moving. If only there was a way to allow a car to visit the point if its cargo 'weights' certain amount required by this point.

3. As I see in the docs the `shipment` object. Maybe it could be used like 'If you pick this shipment form any point A-F only then you can go to point 1 and not necessarily right away as a next stop'.  

I don't have any real background in tackling this sort of problems so any for recommendations I'd be very grateful.

**Comment by jcoupey** [comment]
> skills could be used in a way that a skill should be dynamically increased when visited any A-F point.

Skills are a **static** description of compatibility between vehicles and jobs. "Dynamically increasing" the skills along a route is not something we can easily do because the solving process involves much more than increasing a route by sequentially adding points at the end.

> As I see in the docs the shipment object. Maybe it could be used like 'If you pick this shipment form any point A-F only then you can go to point 1 and not necessarily right away as a next stop'.

Not sure a `shipment` would be what you need as you'd have to specify a single pickup point, not a range of options.

I'm not sure to get what you mean in 2. Maybe you can provide a bit more context on your use-case to fully understand the requirements?

**Comment by MikeDabrowski** [comment]
The gist is what I wrote in first sentence of my original post. But maybe I'll rephrase it a bit.
I got few types of points: 

* start 
* finish
* regular points A-F
* special points 1-4

Start and finish are like a boundary conditions - vehicle just need to be there on start and finish of the task, and those may be one or two different locations (I don't know for sure at this point)
Special points require that in order to pick up a cargo from them, the vehicle must first visit n number of points. So to visit first point, point 1, vehicle have to visit at least one regular point before.
Regular points can be visited in any order.
Also, all points have to be visited and I need the fastest route possible.

in 2nd I thought that I need some value that is bound to the traveling vehicle and that will say if that vehicle can visit certain point or not. And also points should have some way to differentiate regular and special.
So that value will change when vehicle will visit regular point. Lets say vehicle goes to A point and picks 1unit of cargo, then point 1 has in its spec that it accepts vehicles with at least 1unit of cargo. vehicle then checks if its better to go to any other regular point or maybe to A. If it goes to ie. C point then it picks up another 1unit. Now point 1 and 2 are available.
Am I making any sense here ? :)

**Comment by jcoupey** [comment]
Thanks for your feedback. I still don't really get **why** those constraints apply to your use-case, but the short answer is that there is currently no way to handle this kind of specific situation.

There are a couple hacks you may want to try, e.g. delaying "special points" availability to leave room for regular points at the beginning of the routes. But nothing fully satisfactory I'm afraid.

**Comment by MikeDabrowski** [comment]
Thanks, I was afraid so. And those requirements are set because its a task of optimization of a kind of adventure game. That may not translate into real-world scenario of pickup/delivery. Thank you for your  input anyway :)
