### ISSUE TITLE
Add Valhalla as routing provider

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom#306]
I think Valhalla, despite its relatively poor performance compared to ORS/OSRM, would be a nice addition to Vroom's routing providers. It's really unique in terms of run-time weights & costs, no other router can match that, except for BRouter. Anyways, with Mapbox ending OSRM support in a few weeks time and fully concentrating on Valhalla, it might also be a step towards future.

Of course it's possible to add Valhalla already via custom matrices. 

Actually I think I'd like to tackle this myself, if no one else jumps for it in the next weeks. Recently started some C++ dev and this seems rather easy.

**Comment by jcoupey** [comment]
Adding support for another open-source routing engine can only make the project useful for more people so I'd be more than happy if you could contribute a wrapper for Valhalla.

Of course the impact on solving times would be significant as they would probably be mostly dominated by matrix computing times. But this is basically the same choice people are facing when picking a routing engine depending on what they want to use it for.

Technically, you can rely on how it's been done already by @sfendrich  for the Openrouteservice wrapper, see #203 and #204. Happy to help if you have any question!
