### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom#307]
I'd like to PR a Dockerfile. It's fairly useless for `vroom` itself, however, if this acts as a base image for another `vroom-express` docker image, it would be very interesting. I think it's lowering generally the barrier to just give it a quick spin. For ORS we're also using Docker to deploy vroom in production actually. So both `vroom` & `vroom-express` run on the same server, which is fine for most use cases I think. Would be nice to have it upstream:) See PR in a few mins.

**Comment by jcoupey** [comment]
Hi @nilsnolde, thanks for the input! I don't really use docker myself but I can see how many people would find it easier to go through docker to deploy the stack.

Before diving into the technical details you raise in #308, I'll start here with a few general questions:

1. How different would this be from, say https://github.com/iedmrc/vroom-docker?
2. Once the image creation process is setup, what would be the overhead in term of project maintenance? Asking mostly because I suspect we'd then get a lot of troubleshooting related to docker usage and setup itself (at least this is what I see happening on other projects bugtracker).
3. How does the routing layer come into the picture? People using a docker image would expect everything to work out of the box, but it won't unless they actually setup an OSRM or ORS stack aside.

**Comment by nilsnolde** [comment]
Hi @jcoupey ,

1. There's a lot of advantages of having the Dockerfile(s) in the source repo(s) itself: 
- it's not a monolith like the Dockerfile you pointed to, i.e. `vroom` would be its own image, which `vroom-express` can build on and one can drag in any router one wants (and is supported) via `docker-compose`
- it's super flexible when it comes to releases, i.e. each release would automatically create its own Docker image and be tagged accordingly so people don't have to work off `master` as in the above Dockerfile
- it creates more trust IMO, if the Dockerfile is in the source repo, then one knows it's not gonna get abandoned unless the project is

Tbh, we could do it without committing to this repository and still retain most of the flexibility. Our @MichaelsJP [did that](https://github.com/gis-ops/docker-valhalla) for Valhalla and it became a major job to get it right while retaining all flexibility a "native" solution would have had.

2. It's not a lot of overhead. You're right, it can become a source of support, but honestly, if the instructions are proper, people can usually figure it out themselves. That's mostly the problem with Docker documentation, no one mentions the build arguments, env variables etc. If you take Kartoza's excellent PostGIS image, there's quite some support tickets coming in, but that's a super complicated Docker build with lots of room for misinterpretation and failures. That's the busiest Docker repo I know of and considering the popularity and complexity it's still fairly quiet.

That being said, I'd be happy to take responsibility for the Docker stuff in both repos. I can write proper documentation, answer support tickets and maintain functionality. It wouldn't take me more than 2 hours a month (after initial setup), since these Docker setups are really easy! What do you think?

3. Actually I didn't even think about that.. :sweat_smile: But I think it's easy enough. All routers have their own Docker implementations, so you just add their image via `docker-compose`. We can supply a `docker-compose.yml.template` here and in `vroom-express` that shows how to include ORS or OSRM immediately. This way it's a whole lot cleaner, rather than installing fixed versions of one single router in an image, like others do, and the responsibility for the router setup will still be where it belongs: in the router's repo, not in our Dockerfile.

Maybe we even turn you into a Docker lover :grin:

**Comment by jcoupey** [comment]
Thanks for your answers, let's go on with this.

**Comment by mhosman** [comment]
A great type of Docker image could be: 

VROOM + VROOM Express + OSRM in the same image (Let's say an Ubuntu minimal), and the availability to automatically start the services every time the server starts/restarts, and only expose port 3000 (just to access VROOM Express).

**Comment by nilsnolde** [comment]
It's almost done:) https://github.com/VROOM-Project/vroom-docker. Don't use it yet, but that's the direction we're going.

We're intentionally not providing a routing engine in the same image. It's a pain to properly version stuff like that. That's what `compose` is for IMHO. I added ORS in the `docker-compose.yml` and gladly accept a contribution for OSRM:

https://github.com/VROOM-Project/vroom-docker/blob/master/docker-compose.yml

**Comment by jcoupey** [comment]
Closing as the action is now happening in the [vroom-docker](https://github.com/VROOM-Project/vroom-docker) repo.
