### ISSUE TITLE
Real-time traffic data for timed windows

### ISSUE THREAD

**Issue by darkranjha** [VROOM-Project/vroom#309]
Hi Vroom Team,

Love the solution that you have in place for route optimization. I have a project that I am working on, where the problem may have 50+ stops, and there are service level agreements for some stops that have to be considered higher priority. For example one stop, may have a delivery window of 1 hour so it needs to be prioritized over other routes. I see the time window that I can leverage, but do the route optimization algorithms consider real-time traffic data so that a route is picked from timing rather than shortest distance if there is a traffic jam on the optimized route?

**Comment by jcoupey** [comment]
No, the travel time estimates we use throughout the whole optimization phase are constant. Those travel times are retrieved in the form of a matrix from a single call to a routing engine, prior to optimization.

For several reasons, taking into account real-time traffic data to compute matrices **at scale** is already a though problem on the routing side. The first blocker for most people being access to relevant traffic data.

Also including time-dependant matrices into the optimization process would require to adjust the solving approach and add **a lot** to the algorithmic complexity, so there are currently no plans to do so.

**Comment by darkranjha** [comment]
Thanks for the prompt response and explanation Julian.
