### ISSUE TITLE
Question about multiple pickups + 1 delivery 

### ISSUE THREAD

**Issue by mhosman** [VROOM-Project/vroom#313]
How can I achieve this? I need to make let's say 10 pickups and drop all those things in one delivery location so that needs to be the last point in the node. Today an easy way is to give priorities but how about if I have other multiple jobs and pickups/deliveries in the same request?

**Comment by jcoupey** [comment]
The [`shipment`](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#shipments) object models the need to move something from one place to another. In your case, you want to move 10 things to the same delivery location, so the expected way to model this is to create 10 shipments with the same delivery coordinates.

As a result, same-location deliveries in the solution will show up as different route steps (usually in a row). This is normal behaviour because some use-cases require to be able to split the "single" delivery, think:

- capacity restrictions that require to deliver part of the pickups before going back for the rest
- time window restrictions that make it mandatory (or cheaper) to split the 10 moves
- geographical spread of vehicles that make it cheaper to split pickups between several routes

**Comment by mhosman** [comment]
Hey @jcoupey thanks for your answer. I tested for example this situation:

```
{
  "vehicles": [
    {
      "id": 1,
      "start": [-34.9073592,-56.1757016],
      "end": [-34.9073592,-56.1757016],
      "capacity": [100],
      "skills": [1, 14, 2]
    }
  ],
  "jobs": [],
  "shipments": [
    {
      "amount": [1],
      "skills": [1],
      "pickup": {
        "id": 1,
        "service": 300,
        "time_windows": [[1582907793, 1582988000]],
        "location": [-34.9008129,-56.130855]
      },
      "delivery": {
        "id": 2,
        "service": 300,
        "time_windows": [[1582907793, 1582988000]],
        "location": [-34.8835295,-56.0620188]
      }
    },
    {
      "amount": [1],
      "skills": [1],
      "pickup": {
        "id": 3,
        "service": 300,
        "time_windows": [[1582907793, 1582988000]],
        "location": [-34.9007129,-56.130855]
      },
      "delivery": {
        "id": 2,
        "service": 300,
        "time_windows": [[1582907793, 1582988000]],
        "location": [-34.8835295,-56.0620188]
      }
    },
    {
      "amount": [1],
      "skills": [1],
      "pickup": {
        "id": 4,
        "service": 300,
        "time_windows": [[1582907793, 1582988000]],
        "location": [-34.9067129,-56.110855]
      },
      "delivery": {
        "id": 2,
        "service": 300,
        "time_windows": [[1582907793, 1582988000]],
        "location": [-34.8835295,-56.0620188]
      }
    }
  ]
}
```

- One vehicle
- Three Pickup & Deliveries sharing the same delivery location with the same ID (also tested with different ID's).

Result:

- Same-location deliveries are in different route steps with "different arrivals"??

```
{
    "code": 0,
    "summary": {
        "cost": 0,
        "unassigned": 0,
        "delivery": [
            3
        ],
        "amount": [
            3
        ],
        "pickup": [
            3
        ],
        "service": 1800,
        "duration": 0,
        "waiting_time": 0,
        "computing_times": {
            "loading": 51,
            "solving": 2
        }
    },
    "unassigned": [],
    "routes": [
        {
            "vehicle": 1,
            "cost": 0,
            "delivery": [
                3
            ],
            "amount": [
                3
            ],
            "pickup": [
                3
            ],
            "service": 1800,
            "duration": 0,
            "waiting_time": 0,
            "steps": [
                {
                    "type": "start",
                    "location": [
                        -34.9073592,
                        -56.1757016
                    ],
                    "load": [
                        0
                    ],
                    "arrival": 1582907793,
                    "duration": 0
                },
                {
                    "type": "pickup",
                    "location": [
                        -34.9067129,
                        -56.110855
                    ],
                    "job": 4,
                    "service": 300,
                    "waiting_time": 0,
                    "load": [
                        1
                    ],
                    "arrival": 1582907793,
                    "duration": 0
                },
                {
                    "type": "delivery",
                    "location": [
                        -34.8835295,
                        -56.0620188
                    ],
                    "job": 2,
                    "service": 300,
                    "waiting_time": 0,
                    "load": [
                        0
                    ],
                    "arrival": 1582908093,
                    "duration": 0
                },
                {
                    "type": "pickup",
                    "location": [
                        -34.9007129,
                        -56.130855
                    ],
                    "job": 3,
                    "service": 300,
                    "waiting_time": 0,
                    "load": [
                        1
                    ],
                    "arrival": 1582908393,
                    "duration": 0
                },
                {
                    "type": "delivery",
                    "location": [
                        -34.8835295,
                        -56.0620188
                    ],
                    "job": 2,
                    "service": 300,
                    "waiting_time": 0,
                    "load": [
                        0
                    ],
                    "arrival": 1582908693,
                    "duration": 0
                },
                {
                    "type": "pickup",
                    "location": [
                        -34.9008129,
                        -56.130855
                    ],
                    "job": 1,
                    "service": 300,
                    "waiting_time": 0,
                    "load": [
                        1
                    ],
                    "arrival": 1582908993,
                    "duration": 0
                },
                {
                    "type": "delivery",
                    "location": [
                        -34.8835295,
                        -56.0620188
                    ],
                    "job": 2,
                    "service": 300,
                    "waiting_time": 0,
                    "load": [
                        0
                    ],
                    "arrival": 1582909293,
                    "duration": 0
                },
                {
                    "type": "end",
                    "location": [
                        -34.9073592,
                        -56.1757016
                    ],
                    "load": [
                        0
                    ],
                    "arrival": 1582909593,
                    "duration": 0
                }
            ]
        }
    ]
}
```

Maybe a solution is a way to create a shipment with multiple pickups and one delivery, or detect if the ID of the delivery is the same in all steps and group them.

**Comment by jcoupey** [comment]
In your solution, all `duration` keys are set to `0`, which means that all [cumulated travel times](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#steps) along the route are `0`. So it looks like the travel time matrix used for optimization is filled with zeros, an then all solutions are equivalent and cost `0`...

This is likely related to the routing layer, e.g. using OSRM with a data extract that does not contain the coordinates used in your input problem.

**Comment by mhosman** [comment]
Ok thanks @jcoupey I'lll check into this. Best regards!!!

**Comment by AhtashamImtiyaz** [comment]
> Hey @jcoupey thanks for your answer. I tested for example this situation:
> 
> ```
> {
>   "vehicles": [
>     {
>       "id": 1,
>       "start": [-34.9073592,-56.1757016],
>       "end": [-34.9073592,-56.1757016],
>       "capacity": [100],
>       "skills": [1, 14, 2]
>     }
>   ],
>   "jobs": [],
>   "shipments": [
>     {
>       "amount": [1],
>       "skills": [1],
>       "pickup": {
>         "id": 1,
>         "service": 300,
>         "time_windows": [[1582907793, 1582988000]],
>         "location": [-34.9008129,-56.130855]
>       },
>       "delivery": {
>         "id": 2,
>         "service": 300,
>         "time_windows": [[1582907793, 1582988000]],
>         "location": [-34.8835295,-56.0620188]
>       }
>     },
>     {
>       "amount": [1],
>       "skills": [1],
>       "pickup": {
>         "id": 3,
>         "service": 300,
>         "time_windows": [[1582907793, 1582988000]],
>         "location": [-34.9007129,-56.130855]
>       },
>       "delivery": {
>         "id": 2,
>         "service": 300,
>         "time_windows": [[1582907793, 1582988000]],
>         "location": [-34.8835295,-56.0620188]
>       }
>     },
>     {
>       "amount": [1],
>       "skills": [1],
>       "pickup": {
>         "id": 4,
>         "service": 300,
>         "time_windows": [[1582907793, 1582988000]],
>         "location": [-34.9067129,-56.110855]
>       },
>       "delivery": {
>         "id": 2,
>         "service": 300,
>         "time_windows": [[1582907793, 1582988000]],
>         "location": [-34.8835295,-56.0620188]
>       }
>     }
>   ]
> }
> ```
> 
> * One vehicle
> * Three Pickup & Deliveries sharing the same delivery location, skills and time windows, with the same ID (also tested with different ID's).
> 
> Result:
> 
> * Same-location deliveries are in different route steps with "different arrivals"??
> 
> ```
> {
>     "code": 0,
>     "summary": {
>         "cost": 0,
>         "unassigned": 0,
>         "delivery": [
>             3
>         ],
>         "amount": [
>             3
>         ],
>         "pickup": [
>             3
>         ],
>         "service": 1800,
>         "duration": 0,
>         "waiting_time": 0,
>         "computing_times": {
>             "loading": 51,
>             "solving": 2
>         }
>     },
>     "unassigned": [],
>     "routes": [
>         {
>             "vehicle": 1,
>             "cost": 0,
>             "delivery": [
>                 3
>             ],
>             "amount": [
>                 3
>             ],
>             "pickup": [
>                 3
>             ],
>             "service": 1800,
>             "duration": 0,
>             "waiting_time": 0,
>             "steps": [
>                 {
>                     "type": "start",
>                     "location": [
>                         -34.9073592,
>                         -56.1757016
>                     ],
>                     "load": [
>                         0
>                     ],
>                     "arrival": 1582907793,
>                     "duration": 0
>                 },
>                 {
>                     "type": "pickup",
>                     "location": [
>                         -34.9067129,
>                         -56.110855
>                     ],
>                     "job": 4,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "load": [
>                         1
>                     ],
>                     "arrival": 1582907793,
>                     "duration": 0
>                 },
>                 {
>                     "type": "delivery",
>                     "location": [
>                         -34.8835295,
>                         -56.0620188
>                     ],
>                     "job": 2,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "load": [
>                         0
>                     ],
>                     "arrival": 1582908093,
>                     "duration": 0
>                 },
>                 {
>                     "type": "pickup",
>                     "location": [
>                         -34.9007129,
>                         -56.130855
>                     ],
>                     "job": 3,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "load": [
>                         1
>                     ],
>                     "arrival": 1582908393,
>                     "duration": 0
>                 },
>                 {
>                     "type": "delivery",
>                     "location": [
>                         -34.8835295,
>                         -56.0620188
>                     ],
>                     "job": 2,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "load": [
>                         0
>                     ],
>                     "arrival": 1582908693,
>                     "duration": 0
>                 },
>                 {
>                     "type": "pickup",
>                     "location": [
>                         -34.9008129,
>                         -56.130855
>                     ],
>                     "job": 1,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "load": [
>                         1
>                     ],
>                     "arrival": 1582908993,
>                     "duration": 0
>                 },
>                 {
>                     "type": "delivery",
>                     "location": [
>                         -34.8835295,
>                         -56.0620188
>                     ],
>                     "job": 2,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "load": [
>                         0
>                     ],
>                     "arrival": 1582909293,
>                     "duration": 0
>                 },
>                 {
>                     "type": "end",
>                     "location": [
>                         -34.9073592,
>                         -56.1757016
>                     ],
>                     "load": [
>                         0
>                     ],
>                     "arrival": 1582909593,
>                     "duration": 0
>                 }
>             ]
>         }
>     ]
> }
> ```
> 
> Maybe a solution is a way to create a shipment with multiple pickups and one delivery, or detect if the ID of the delivery is the same in all steps and group them.


Hi @mhosman and @jcoupey when i try to test this example at http://map.vroom-project.org/, it doesn't show any points. Am i missing something in it?

**Comment by jcoupey** [comment]
@AhtashamImtiyaz if you're feeding the above input into the demo frontend, I'm afraid it just won't work because the frontend has no idea of the concept of `shipment`. Shipments have been introduced a few months back in `v1.6.0` and the frontend is simply stuck with just handling `job` objects.

Feel free to open a ticket for this [in the `vroom-frontend` repo](https://github.com/VROOM-Project/vroom-frontend/issues).

**Comment by passeride** [comment]
Any progress on this? 
The example does fail due to duplicate ID on shipment delivery
And with differing ID's but same location, it goes 1 pickup then one deliver and back for another
