### ISSUE TITLE
Error when running make on v1.6.0

### ISSUE THREAD

**Issue by jwld** [VROOM-Project/vroom#314]
Seeing this when running `make`. `v.1.5.0` works fine, but seeing this error with `v1.6.0`:

```
/bin/sh: pkg-config: command not found
c++ -MMD -MP -I. -std=c++14 -Wextra -Wpedantic -Wall -O3 -DNDEBUG -c routing/http_wrapper.cpp -o routing/http_wrapper.o
In file included from routing/http_wrapper.cpp:11:
In file included from /usr/local/include/boost/asio/ssl.hpp:18:
In file included from /usr/local/include/boost/asio/ssl/context.hpp:23:
In file included from /usr/local/include/boost/asio/ssl/context_base.hpp:19:
/usr/local/include/boost/asio/ssl/detail/openssl_types.hpp:23:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [routing/http_wrapper.o] Error 1
```

**Comment by jcoupey** [comment]
The `openssl/conf.h` header have been added as a requirement in `v1.6.0` for https://github.com/VROOM-Project/vroom/issues/289. Those headers are missing on your system.

If you're under debian/Ubuntu, it should be enough to simply `apt install libssl-dev`.

Please report on this so we can update the wiki instructions.

**Comment by jcoupey** [comment]
Hi @jwld any update on this?

**Comment by jwld** [comment]
Hi, sorry I was in a rush so just rolled back to 1.5 and this totally slipped my mind. I haven't tried it on our ubuntu server yet - first I'm trying to get it set up locally, which is in OS Catalina.

I've installed `openssl` using homebrew, and after installation it spits out the following warnings:
```
openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
```

I've added those 3 lines to my `bash_profile` but I'm still getting the above error. This clearly isn't anything to do with vroom, but any ideas? If not I'll dig deeper on it later on.

**Comment by jcoupey** [comment]
Thanks for your feedback, it confirms that a proper `openssl` install should fix it, I'll update the wiki accordingly.

If the lib paths are not properly set on your system, you may have more luck adding the suggested `-L` and `-I` options directly [in the makefile](https://github.com/VROOM-Project/vroom/blob/02126a885994e859bfeaf959d263933000850160/src/makefile#L8-L9).

**Comment by jwld** [comment]
Thanks, I will try that in due course!
