### ISSUE TITLE
Question: Custom Capacity Calculation

### ISSUE THREAD

**Issue by akasparas** [VROOM-Project/vroom#315]
One of my customers often transports some pallets on the second and even third "layer". Usually loads on different layers goes to different destinations. I cannot think of good limit schema with current quantity/capacity calculation method. If I'm strict on number of pallets, then second and third layers are not possible and plan becomes far from optimal. If I calculate by volume, then I risk to be too optimistic and my goods will not fit into trailer if height of pallet is a little bit more than half of trailer height.

Therefore I'm thinking about supplying heights and other parameters of every pallet and write algorithm which calculates how much this will take [most likely limit by pallet_places * trailer_height and include free space above pallets into sum of quantity used]. How badly this would affect algorithm used? How about if calculation is not commutative i.e. sum(route A-B-C-D) != sum(route A-C-B-D)?

I realize that I will have to implement myself. But this would not be a trivial task. So, before taking it I would like to know if all I'm risking is increased calculation time or will this completely ruin algorithms used. Thank you.

**Comment by jcoupey** [comment]
You could try using height as an additional `capacity` component, with each pallet holding a percentage of the total available height.

> How about if calculation is not commutative

If you have additional constraints related to loading that deeply affect capacity constraints, I'm afraid you're scratching the surface of [VRLP](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=vehicle+routing+and+loading+problem&btnG=) (vehicle routing and loading problem). A mix of usual VRP with 3D loading constraints, sometimes referred as 3D-CLP (container loading problem) in papers. This is currently beyond the scope of this project.

> all I'm risking is increased calculation time

The current capacity checks for validity happen in constant time in most situations because we maintain lots of additional information on forward and backward cumulated load and stuff. Now if simply evaluating the feasibility of a route with regard to capacity requires solving an NP-Hard problem, then computing times may not just increase, but become totally intractable.

**Comment by akasparas** [comment]
> You could try using height as an additional `capacity` component, with each pallet holding a percentage of the total available height.

I'm sorry, I don't get how this could work. Suppose, you have truck 200cm high with 3 places for pallets. That's 600 limit. And you have 5 pallets 110cm high each. Sum of quantity = 550 < 600, but physically you can fit only 3 of them. Specifying capacities for every place separately require one to know where he will put pallet first; but then he has to have solution for this problem already.

> 
> > How about if calculation is not commutative
> 
> If you have additional constraints related to loading that deeply affect capacity constraints, I'm afraid you're scratching the surface of [VRLP](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=vehicle+routing+and+loading+problem&btnG=) (vehicle routing and loading problem). A mix of usual VRP with 3D loading constraints, sometimes referred as 3D-CLP (container loading problem) in papers. This is currently beyond the scope of this project.

Thank you for pointers. I have already seen some papers on these topics. On one hand, I don't need full 3D-CLP for truck loading. More like 1.5D :-) I.e. distribution into sequence of "towers" with locations of towers in truck already known. On the other hand, authors of these papers do not share working code like you do. On third hand, I don't need full set of options and limitations with stability, rotations, etc. in mind. I just need answers to questions: can it be above floor, can something be on top of it.

> 
> > all I'm risking is increased calculation time
> 
> The current capacity checks for validity happen in constant time in most situations because we maintain lots of additional information on forward and backward cumulated load and stuff. Now if simply evaluating the feasibility of a route with regard to capacity requires solving an NP-Hard problem, then computing times may not just increase, but become totally intractable.

I don't intend to solve NP-Hard problem on each step. I have two cases:
A. When load is of just one pallet, I check could I put it on top. If I can, then I do put it here; otherwise I add free space till the roof and start to consume next pallet place. This could be done in O(1).
B. When load is of more than one pallet, I can have presorted array of "towers" to find most worthy to be split; if I find one, I put split part on the last pallet of last load and remaining part as the last for next step and all other "towers" fully consume space in between. If I can't find good candidate, I use new places for every pallet. I believe this could be done in O(log n). Presorting not included as this has to be done only once at the start. Assuming n<50 in my cases, I hope I can fit into one order of magnitude longer time.

**Comment by jcoupey** [comment]
> I have two cases

Your A/B description sounds like what you'd do to decide upon *adding* some new stuff to an existing route. This would basically cover what's happening during the heuristic phase where we build initial solutions by incrementally adding jobs.

But during the local search phase, we try applying a range of operators that match many more different situations. See [operators applied for VRPTW](https://github.com/VROOM-Project/vroom/tree/master/src/problems/vrptw/operators) or this (somehow outdated) [description](https://youtu.be/HHkwYvFMRiI?t=574).

Maybe a good workaround would be to still calculate using raw volumes, but apply a reduction factor to the overall vehicle capacity to make sure everything will fit. I did not get this a thorough though, but  perhaps depending on your pallets/trucks sizes there is a way to come up with a "not too big" reduction factor making sure the solutions don't end up being too optimistic.
Not actually a real answer to your question, but maybe worth digging before diving into a much more complex approach?

**Comment by akasparas** [comment]
Thank you, @jcoupey , for showing where dragons roost. This is exactly what this question was about.

As I cannot afford to give solution which does not fit trailer, I see two options:
a) start with some safety factor, get result, check correctness and rerun with bigger factor if results are wrong; I probably will need to do reruns anyway for #188 and to use cheaper trucks (can't find issue number)
b) (efficiently) include custom cost calculation into VRPTW too.

Which one I'll choose I still don't know--have to solve pallet assembly first. Meanwhile this question could be closed. Thanks again!

**Comment by jcoupey** [comment]
So closing here. FWIW, I've updated https://github.com/VROOM-Project/vroom/issues/188#issuecomment-602462376 with a modelling advice.
