### ISSUE TITLE
Using vroom to calculate distance matrix with multiple vehicle jons

### ISSUE THREAD

**Issue by bonanhel** [VROOM-Project/vroom#316]
Hello all!
Well, this is not an issue post, just trying to figure out if this can be done using vroom API.

Currently I am using OSRM's matrix to calculate from point to point distances for multiple vehicles.

For example I have an array with cars and from-to points
A specific point {x,y} from each car in array like :
1,{x,y}
2,{x,y}
3,{x,y}
etc..

Now I need a way to calculate distances using a specific point from vehicles multiple stop points. For example:

{x,y} from

1,{x1,y1},{x2,y2}
2.{x1,y1};{x2,y2};{x3,y3}
3.{x1,y1}
etc..

Is it possible using vroom? Currently I am trying to use skills feature.

Thanks!
Vangelis

**Comment by jcoupey** [comment]
It looks like you don't need VROOM at all if all you want to achieve is get distances from/to various points. The OSRM [`table` service ](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#table-service) handles that, maybe you need to dig the `sources` and `destinations` options to adjust from/to locations.

**Comment by bonanhel** [comment]
@jcoupey  Thanks for your reply!
I'm trying to avoid multiple server requests.

What I am trying to do...
I have a taxi dispatch system. I'm trying to find the nearest taxi from the client. Some vehicles are free, so I need to calculate distance from the client, some others are busy with known destination, so for this vehicles I need to calculate distance from there location to destination location and to the current client.

**Comment by jcoupey** [comment]
If you want to work directly with distances, just put all your "from" and "to" locations in a single OSRM `table` request, maybe using `sources` and `destinations` parameters if you want to filter some unwanted values.

Closing as this is an OSRM-related question.

**Comment by bonanhel** [comment]
Well, there wasn't a OSRM related question :) 
I will try to play with vroom shipments and  skills for filters. It seems that will do the job..

Thanks again for your time!

Regards,
Vangelis

**Comment by jcoupey** [comment]
> I will try to play with vroom shipments

If you describe your problem using the `vroom` API, then all required OSRM calls (`table` and `route` requests) will be handled internally for you so you don't have to care about this.
