### ISSUE TITLE
brew install vroom

### ISSUE THREAD

**Issue by ankane** [VROOM-Project/vroom#318]
Hi, thanks for this great library! Just wanted to let you know that it's now available on Homebrew for Mac users (no need to build from scratch).

```sh
brew install vroom
```

Ref: https://github.com/Homebrew/homebrew-core/pull/52363

**Comment by jcoupey** [comment]
Thanks @ankane for your contribution, I'll update the wiki build instructions to mention this!

Just a couple questions:

- can you confirm that the [depend rules](https://github.com/Homebrew/homebrew-core/pull/52363/files#diff-3f7cec3eedcc447300b515827338e583R7-R9) mean users won't have to bother about installing dependencies prior to running `brew install`?
- do you plan to upgrade the Homebrew repo with new vroom releases in the future?

Also nice to see the docs example used as a packaging test.

**Comment by ankane** [comment]
Sounds good.

1. Homebrew will install all dependencies, so `brew install vroom` is all Mac users need to run.
2. I don't plan to follow releases, but it should be pretty straightforward if you'd like to make this part of the release process. You'll essentially just need to update the `url` and `sha256` lines. If you decide to do this, feel free to tag me for the first one and I can assist.

**Comment by jcoupey** [comment]
Thanks for your answers.

> it should be pretty straightforward 

It is indeed a small task but I can't commit to doing this myself for each new release. The release process is already demanding enough for me as it involves many benchmarking/testing in the background and some deployment work for my own use cases.

I gladly welcome contributions that make it easier for users to get started with the project, like this one or the ongoing work of @nilsnolde on `vroom-docker`. But as a general rule of thumb I don't want to take responsibility for the maintenance of many extraneous tooling, especially if I don't use them myself.

On the Homebrew side, you've already done the hardest part so we'll probably be able to count on a couple mac users to push major releases there!

**Comment by ankane** [comment]
Sounds good, thanks @jcoupey!
