### ISSUE TITLE
Using Matrix with three vehcles response contains two vehcles only

### ISSUE THREAD

**Issue by trumboosahil** [VROOM-Project/vroom#327]
curl --header "Content-Type:application/json" --data '{"matrix":[[0,2,3,7,6,8],[4,0,6,5,8,10], [1,2,0,7,6,8], [4,11,16,0,10,9], [8,9,13,17,0,8], [2,10,16,5,8,0]],"vehicles":[{"id":0,"start_index":0},{"id":1,"start_index":0},{"id":2,"start_index":0}],"jobs":[{"id":0,"location_index":0},{"id":1,"location_index":1},{"id":2,"location_index":2},{"id":3,"location_index":3},{"id":4,"location_index":4},{"id":5,"location_index":5}]}' http://localhost:3000

All vehicles start from same location start of route

**Comment by jcoupey** [comment]
The response does not contains vehicles, but routes. It simply means that using two routes only rather than three is cheaper to handle your 6 jobs.
