### ISSUE TITLE
Seeing "too many table coordinates" OSRM error when using vroom-express server

### ISSUE THREAD

**Issue by jwld** [VROOM-Project/vroom#332]
Stress-testing our routing logic and seeing the following error:
```
data: { code: 3, error: 'OSRM table: Too many table coordinates' }
```

This is with 539 jobs. 

We're using `vroom-express` and I can see in the `config.yml` that `maxLocations` is defaulted to 1000. Is there a setting I'm missing somewhere? Or is there a hard upper limit with vroom?

**Comment by jcoupey** [comment]
There is no upper limit if you use `vroom` on the command-line. The purpose of the `vroom-express` parameter you point out is precisely to handle this kind of limitation when receiving requests.

The problem you're facing is OSRM-related as the error message you're seeing is just `vroom` reporting the error sent by OSRM. If you're running `osrm-routed`, you need to raise the max size for `table` requests using `--max-table-size`.

**Comment by jwld** [comment]
Thanks, makes sense!

Found it quite hard to find the relevant flags, but there's a list of them [here](https://github.com/Project-OSRM/osrm-backend/issues/5022#issuecomment-493959313) if anyone else comes across this.
