### ISSUE TITLE
Revamp readme

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#335]
The current readme is, hum, quite sparse on information. Considering this is the entry point for the project on GitHub, it should be improved to contain more high-level information and pointers to other resources. What should be added:

- supported problem types
- more detail on features
- supported routing engines
- the kind of tests we have in place (CI builds, runs on various benchmarks)
- more on how to get started
- ...

**Comment by nilsnolde** [comment]
+1000 :)

Also it's confusing that there's a `docs` directory where the API is documented, which IMHO belongs in the wiki. I look at that like 3 times a year and can never find it;)

**Comment by jcoupey** [comment]
I think it makes sense that the API documentation is somehow versioned along with the code so it's always consistent with whatever version is checked out. Maybe what you point out comes down to making things more clear from the wiki?

Currently the [Usage](https://github.com/VROOM-Project/vroom/wiki/Usage) page on the wiki simply links to specific versions for the docs. One option would be to have a dedicated "Documentation" page in the wiki for the last release where we paste the docs (and specify the version).

**Comment by nilsnolde** [comment]
> I think it makes sense that the API documentation is somehow versioned along with the code

Yeah, you're right of course.

> Currently the Usage page on the wiki simply links to specific versions for the docs

OMG, I really am blind.. That's my bad, sorry. Maybe just not "TL;DR", but API documentation as header. Then even I might see that there's actually a link to it;)

**Comment by jcoupey** [comment]
Hopefully the README is now more useful.
