### ISSUE TITLE
delivery jobs unassigned with multiple vehicles availables

### ISSUE THREAD

**Issue by SAGOlab** [VROOM-Project/vroom#343]
Hi there,

I'm trying to display optimization routes for multiple vehicles that need to delivery items to clients.

thake a look at this screen and code:

![Schermata da 2020-05-21 12-24-26](https://user-images.githubusercontent.com/24431313/82549952-0fa62800-9b5e-11ea-85cc-58a509d9f554.png)

**post request:**

```
const vehiclesBody = [{
        id: 1,
        profile: 'driving-hgv',
        start: [12.8059101, 43.4353756],
        end: [12.8059101, 43.4353756],
        capacity: [4],
        skills: [1, 14],
        time_window: [28800, 43200]
      },
      {
        id: 2,
        profile: 'driving-hgv',
        start: [12.8059101, 43.4353756],
        end: [12.8059101, 43.4353756],
        capacity: [4],
        skills: [2, 14],
        time_window: [28800, 43200]
      },
      {
        id: 3,
        profile: 'driving-hgv',
        start: [12.8059101, 43.4353756],
        end: [12.8059101, 43.4353756],
        capacity: [4],
        skills: [2, 14],
        time_window: [28800, 43200]
      },
      {
        id: 4,
        profile: 'driving-hgv',
        start: [12.8059101, 43.4353756],
        end: [12.8059101, 43.4353756],
        capacity: [4],
        skills: [2, 14],
        time_window: [28800, 43200]
      }
    ]
    
    this.jobsLocations = new Array();
                _.forOwn(destinatari, (value, key) => {
                  this.jobsLocations.push({
                    id: parseInt(key),
                    service: 420, // 7 minuti per consegna
                    amount: [1],
                    location: [value['long_cliente'], value['lat_cliente']],
                    skills: [1],
                    time_windows: [[32400, 36000]]
                  })
                })

      const body = {
        jobs: jobsLocations,
        vehicles: vehiclesBody,
        options: { g: true }
      }

      return this.httpClient.post<any>(this.orsEP + 'optimization', body, this.headers);
```
this peace of code return me 12 jobs:

![Schermata da 2020-05-21 12-32-49](https://user-images.githubusercontent.com/24431313/82550837-72e48a00-9b5f-11ea-988f-1807e11dec7c.png)

but when post request is done, it log in the console:

![Schermata da 2020-05-21 12-19-17](https://user-images.githubusercontent.com/24431313/82550485-e2a64500-9b5e-11ea-9e42-dac87fb3c547.png)

as you can see there are 9 jobs unassigned, so my questions are:

1. Why or how can I understand the reasons of an unassigned jobs? If I can understand the reasons I could find a way to assign all jobs.
2. Why only one vehicle is used? I mean, I have 4 vehicles, why all jobs is not distribuited between vehicles?
3. How can assign all jobs, so I can ensure all delivery?
4. In all jobs that are assigned the number of vehicles is automatically choose by algorithm?

thanks a lot.
Have a nice day.

**Comment by jcoupey** [comment]
All your jobs have a `skills: [1]` entry, so they can only be handled by the first vehicle. See the [documentation notes](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#skills) on skills.

Note that skills are optional, so if you don't have a good reason to use them you can omit all `skills` keys altogether.

**Comment by SAGOlab** [comment]
thanks a lot for your hint and for your quick response.

I've edited skill entry in jobs and something happen, but for others questions?

thanks a lot.

**Comment by jcoupey** [comment]
The solving approach tries to maximize the number of assigned jobs. If some of the jobs remain unassigned, it means we don't manage to fit them in due to the constraints (time windows, capacities, skills). So the reason is problem-dependent and lies in the way you model your specific problem instance.

In order to have all jobs included, you need to have enough available vehicles and/or loosen the constraints.

**Comment by jcoupey** [comment]
Closing as answered, feel free to re-open if required.
