### ISSUE TITLE
Optimization with 'avoid_polygons'

### ISSUE THREAD

**Issue by harshil-patel-code** [VROOM-Project/vroom#345]
In the direction API of openrouteservice, we have routing with 'avoid_polygons' option. Can we do the optimization also with similar logic ? Currently, optimization API doesn't have option to specify 'avoid_polygons'. Can we achieve this objective by any other way? I am trying to do optimization under 'Covid-19' situation and want to avoid restricted areas.

**Comment by jcoupey** [comment]
If you mean doing it at query-time, then no it's not possible. See #310 for more background on why.

If you have stable "avoid" zones, then I'd suggest to hard-code them into the routing layer prior to data preparation. You could simply drop all ways from those zones, either via the routing profile or by adding a preprocessing step to the OSM data.

Then all routing-related estimates used at the optimization level would account for the avoided zones: travel costs, route details and geometry in response etc.

**Comment by harshil-patel-code** [comment]
Thanks for explaining. I do have static 'avoid' zones. Is there any way to directly achieve the objective using ORS API (https://openrouteservice.org/dev/#/api-docs/optimization/post) ? Apologies for bugging you but I am new to this.

**Comment by nilsnolde** [comment]
No unfortunately there isn't for the reasons outlined in #310 . There's also some workarounds proposed, like using the `directions` endpoint to calculate the matrix "manually" use `vroom`s custom matrix feature. Obviously the slowest (but least effort) way to go, as those directions requests are in sum magnitudes slower than a single, matching matrix request. This is also the **only** thing that works if you intend to use the public ORS API.

For a more performant way, you'd have to set up ORS and vroom yourself, e.g. from here (not so hard if you know Docker):
https://github.com/VROOM-Project/vroom-docker

I'd follow Julien's suggestion to massage the OSM data prior to building the graphs in the local ORS backend. Use `osmium` (unless you're on Win..), it supports bbox, `poly` files or GeoJSON:
https://docs.osmcode.org/osmium/latest/osmium-extract.html

**Comment by jcoupey** [comment]
I was about to suggest using `osmium` too. You'd probably have to describe your filtering file as a multipolygon whose holes are unwanted areas.

The only potential drawback I can think of with this approach is that you'd have to be careful how your polygon cuts down the road network connectivity. But this is no different from using the `avoid_polygons` feature in ORS.

**Comment by jcoupey** [comment]
Closing as answered.

**Comment by jcoupey** [comment]
FYI, see #389.
