### ISSUE TITLE
option to require vehicles be empty during a break

### ISSUE THREAD

**Issue by FUberCab** [VROOM-Project/vroom#348]
In the use case of using the shipment functionality for multi-loaded passenger transportation, the engine will currently instruct the driver to pick up a passenger, go on break, then deliver the passenger. 

Is there an option to require vehicle be empty during breaks? Can this be added?

**Comment by jcoupey** [comment]
No, there is no such option currently.

I *think* that this could be forced in a straightforward way. You'd have to adjust validity checks in the `TWRoute::is_valid_addition_for_tw` functions: every time a break is checked for insertion (and time validity), you could add a check for the vehicle's current load and simply return `false` if it's non-empty. At first glance, I don't see any pitfalls for this simple approach but this would need testing.

Now this is a very special situation and probably related to the fact that you are dealing with passengers. Could you expand on why having a break with a non-empty vehicle is a problem? Is is a matter of not having passengers wait during the break?

**Comment by FUberCab** [comment]
Yes, Our use case involves split-shifts where a vehicle will be 'on break' for several hours amd we can't have passengers in the vehicle waiting to get dropped off. 
Presumably this would also be useful in the delivery of food or other parshable items.

**Comment by jcoupey** [comment]
> a vehicle will be 'on break' for several hours amd we can't have passengers in the vehicle waiting to get dropped off

OK. Then maybe your core problem is not having passengers staying in vehicles during breaks, but having valid situations where passengers can stay for several hours in a vehicle. I mean you might want to rule those situations out by adding bounds to the pickup/delivery time windows. This would probably solve your break problem, and also avoid situations where passengers spend a few hours in a moving vehicle before reaching their destination, just because it's cheaper that way.

**Comment by boooch** [comment]
But you can have several buses with different break timewindows.  In time when one of them have break, other can work. So timewindows for passengers as shipments may not help in this situation.

**Comment by jcoupey** [comment]
@boooch my point is that if `e` is the earliest available date for a pickup and `l` is the deadline for the matching delivery, then `l - e` is a higher bound of the time spent in the vehicle.

If you're dealing with passengers, you probably want to make sure this does not exceed whatever value is acceptable for your use-case.

**Comment by jcoupey** [comment]
Closing as stale.
