### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by valerivp** [VROOM-Project/vroom#350]
Please help.
I run:
bin/vroom -i test.txt
I get:
segmentation fault

[test.txt](https://github.com/VROOM-Project/vroom/files/4743074/test.txt)

but http://solver.vroom-project.org processes this file correctly, if header "Content-Type: application/json; charset=utf-8".
If header "Content-Type: application/json" - {"code":2,"error":"Invalid JSON object in request, please add vehicles and jobs or shipments to the object body"}

**Comment by jcoupey** [comment]
Can you confirm that you're using `v1.6.0`? If so, then you're hitting #333. The demo server currently runs `v1.7.0-rc.1` which has a fix for this bug.

**Comment by valerivp** [comment]
Thanks!
