### ISSUE TITLE
Getting "Invalid numerical value in option." on given examples

### ISSUE THREAD

**Issue by SimonDahrs** [VROOM-Project/vroom#351]
I'm trying [these examples](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#examples) and the one in the readme [here](https://github.com/VROOM-Project/vroom-express), but on all of them I get the error "Invalid numerical value in option.". 
I'm using my own hosted instances of vroom (vroom-docker) and ORS.

**Comment by jcoupey** [comment]
This error is filtered [here](https://github.com/VROOM-Project/vroom/blob/638f6d11ac29d80189c70d5c797dd6549287caaa/src/main.cpp#L110) when parsing an unexpected value from the `-t` or `-x` command-line arguments, which expect positive integer values.

```
$ vroom -t 4 -i example_2.json
[expected output]
$ vroom -t foo -i example_2.json
[Error] Invalid numerical value in option.
{"code":2,"error":"Invalid numerical value in option."}
```

So it has nothing to do with the examples, but is related to the way the `vroom` call is performed. For more, we'd need to have some context on the config changes you applied at the `vroom-docker` level.

**Comment by jcoupey** [comment]
Closing as it seems this has been answered.
