### ISSUE TITLE
Maximum distance for vehicle

### ISSUE THREAD

**Issue by boooch** [VROOM-Project/vroom#354]
Will be great  to have maximum distance for the route in vehicle config . To disallow vehicle trips more then this distance.

**Comment by jcoupey** [comment]
Related to #227. I'm flagging this as a feature request but I don't really see this happening any time soon, the major blocker being that we currently don't have a distance matrix at hand while solving.

**Comment by boooch** [comment]
But OSRM table gives us distance and time in case of --algorithm ch settings

**Comment by jcoupey** [comment]
Yes, I did not mean to imply it's impossible to get the distances and use them at some point. Just that there is currently nothing available in the codebase to do so.

**Comment by CosmoVal** [comment]
Hi, 

As I'm also interested in using constraints on max distance/duration of the routes, I was wondering if there is any update on this open issue. 

Is there any plan about considering this feature as part of the future developments?

Thanks!

**Comment by jcoupey** [comment]
I agree this is an interesting feature, along with #273.

> Is there any plan about considering this feature as part of the future developments?

It depends if we can find time and funding to work on it. If you badly need this feature and would like to make things faster, there are (at least) two ways:
- contribute code-wise;
- help to fund the work on this feature.

**Comment by CosmoVal** [comment]
Thanks for the reply. 

I would love to contribute, but I'm not production-level proficient in c++, as I'm a long-time Python user. 

However, under specific guidance and with a non-pressing timeline, I might give it a try. So my question is: how specific can you go in guiding this development? For example, do you usually point the contributors to specific parts of the codebase that need to be changed and give suggestions on how to implement the change?

**Comment by jcoupey** [comment]
I could provide some pointers if I don't go into this myself in the next milestone. But first I'd suggest to start with #273 since we currently don't store a matrix of distances while solving. Then the logic applied there could be ported for this issue.

**Comment by fsty** [comment]
Hello! 
I'm using custom cost matrix and interested in using the "max cost" as additional constraint. 
There is any updates in this issue ? 

Thank you

**Comment by jcoupey** [comment]
> There is any updates in this issue ?

Not directly. Chances are that #273 will be done before this ticket. The two approaches would be quite similar but we currently don't have all the distances at hand while optimizing.

**Comment by nemosmithasf** [comment]
Given that all carrier vehicles are actively switching to EVs, the need to model fuel/range has arguably become critical (a lot more so than when #227 was posted)

So I just wanted to throw in my support for this feature.

For those running into this problem right now, you can kind of hack it (albeit sub-optimally) by estimating the maximum time each vehicle can travel and using "time_window" to gate it. You might have to run the engine multiple times if you have different charging stations (i.e. "endpoints" for the vehicles) and pick the best outcome.

**Comment by jcoupey** [comment]
> So I just wanted to throw in my support for this feature.

Thanks for your input. As a side note: this (along with #273) requires a significant refactoring which I ticketed in #738. A good way to help speed up the dev on this feature is to have your users/company contribute by funding part of the work.

**Comment by ilibar-zpt** [comment]
I'm guessing this one would also require implementing the ability to provide distances matrix for feature completeness sake, as otherwise it would work only with `-g` flag

**Comment by ivosabev** [comment]
+1 for this feature with the same argumentation as in https://github.com/VROOM-Project/vroom/issues/354#issuecomment-1198371331. EVs are adding the need to plan for maximum distance per route due to their range constraints.

**Comment by alinaerke** [comment]
Low emission zones (LEZ) and the number of EVs are increasing all over the countries. The first question is always about the maximum distance per route. One more +1 from me.

**Comment by jcoupey** [comment]
> The first question is always about the maximum distance per route. One more +1 from me.

Thanks for the input. I was about to answer but I guess I would have rewritten pretty much [that previous comment](https://github.com/VROOM-Project/vroom/issues/354#issuecomment-1004623827). ;-)

**Comment by answerquest** [comment]
@jcoupey valid point on funding required, I agree completely. Pls share a link or pathway for contributing funding that we can use - both at individual and organisational level. Also how about posting this on https://bountysource.com/ or any similar platform?

**Comment by makeasnek** [comment]
Please do not use bountysource. Many devs have had trouble getting paid there. You can check out this lemmy community as an alternative https://lemmy.ml/c/bugbounties

For statements from devs who have been unable to cash out from bountysource see:
https://github.com/bountysource/core/issues
