### ISSUE TITLE
Skills Logic

### ISSUE THREAD

**Issue by boooch** [VROOM-Project/vroom#357]
I have 1 vehicle with skills=[143, 144] and one shipment with skills=[]
I got  response  {code: 2, error: "Missing skills."}
How do skills logic working? 
As I think - if shipment have no skills it can be distributed on any vehicle, but if shipment have any set of skills it can be distributed only on vehicle having the same subset of skills . Right?

**Comment by boooch** [comment]
Add: Solution working as I think in case if I add additional skill [0] on every vehicle and every shipment.

**Comment by jcoupey** [comment]
The skill logic is described [in the documentation](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#skills). There is no "no constraint" default behaviour when the set of skills is empty, though one may argue that the empty set is included into any other set.

The rationale is that if you have no constraints, then you should omit `skills` keys altogether for all objects. On the other hand, if you do have skills, you should have a consistent modelling and define (non-empty) `skills` arrays for all objects.

If one job/shipment may be handled by any vehicle, then indeed assigning it a specific skill value that all vehicles have will do.
