### ISSUE TITLE
Breaks ignored

### ISSUE THREAD

**Issue by luca-saggese** [VROOM-Project/vroom#360]
I'm sure I'm missing something obvious, i'm using docker image with my own ors' instance, then data i'm passing is:

{
    "vehicles": [
        {
            "id": 1,
            "start": [
                2.109511,
                41.35858
            ],
            "end": [
                2.109511,
                41.35858
            ],
            "time_window": [
                28800,
                54000
            ],
            "breaks": [
                {
                    "id": 1,
                    "service": 3600,
                    "time_windows": [
                        [
                            43200,
                            45000
                        ]
                    ]
                }
            ],
            "capacity": [
                3500,
                7300
            ]
        },

**Comment by nilsnolde** [comment]
I don't have the rights to edit your comment: please please apply proper formatting, e.g.
https://guides.github.com/features/mastering-markdown/

Every project maintainer will be forever grateful. Extra points for really thoughtful stuff like
<details>
<summary>This is a JSON</summary>
<br>
<pre>
<code>
{
  "a": "b",
  "c": "d"
}
</code>
</pre>
</details>

Use the Preview tab and ask yourself if you'd understand what you just wrote. 

Anyways, you're using docker, you're most likely using vroom v1.6.0, while breaks are a feature only available in `master` right now. You can try to build a new image with `--build-arg VROOM_RELEASE=master`. Though no guarantees, things are not necessarily working the same way as before. I know Julien deprecated some libraries over the last few months, but I'm not so sure if any were added which could break such an easy fix. Feel free to report though.

**Comment by nilsnolde** [comment]
Just remembered that Julien already gave similar advice:
https://github.com/VROOM-Project/vroom/issues/349#issuecomment-637587548

If you change the Dockerfile to include asio install it should work. You can also drop all boost dependencies, which should make it quite a bit faster and lighter weight.

**Comment by jcoupey** [comment]
I plan to do a `v1.7.0` release soon now (hopefully by next week). Once the Docker image is updated via a new `vroom-docker` matching release, breaks will be available out of the box.

**Comment by luca-saggese** [comment]
Sorry for the bad format, eill edit it when on a pc, thanks for the replies will look forward for the new build.

Thanks again for the great work

**Comment by jcoupey** [comment]
Not a problem any more using the latest Docker image.
