### ISSUE TITLE
Example 2 output doesn't match vroom 1.7 output

### ISSUE THREAD

**Issue by dtrodrigues** [VROOM-Project/vroom#361]
Running `vroom -i example_2.json` no longer produces the same output as `example_2_sol.json`:

```
$ vroom -i example_2.json | jq .routes[].steps[]
{
  "type": "start",
  "arrival": 0,
  "duration": 0
}
{
  "type": "job",
  "id": 1414,
  "service": 0,
  "waiting_time": 0,
  "job": 1414,
  "arrival": 2104,
  "duration": 2104
}
{
  "type": "job",
  "id": 1515,
  "service": 0,
  "waiting_time": 0,
  "job": 1515,
  "arrival": 4359,
  "duration": 4359
}
{
  "type": "end",
  "arrival": 5461,
  "duration": 5461
}

$ cat example_2_sol.json |  jq .routes[].steps[]
{
  "type": "start",
  "arrival": 0,
  "duration": 0
}
{
  "type": "job",
  "job": 1414,
  "service": 0,
  "waiting_time": 0,
  "arrival": 2104,
  "duration": 2104
}
{
  "type": "job",
  "job": 1515,
  "service": 0,
  "waiting_time": 0,
  "arrival": 4359,
  "duration": 4359
}
{
  "type": "end",
  "arrival": 5461,
  "duration": 5461
}
```

There looks to be an additional `id` field present in each of the job steps.

**Comment by jcoupey** [comment]
Yes, there is a difference in output with the new version, the complementary `id` field is a generic replacement for previous `job` (still present in output but deprecated).

My bad, I did not update the `docs/example_2_sol.json` as I didn't recall it was used in the homebrew formula test. I'll comment directly on the homebrew repo to see how this should be handled.

**Comment by jcoupey** [comment]
This has been temporarily solved on the homebrew side, now we need to make sure it does not happen again. Options include adding a check step in the current release process, or even better add a similar check using `example_2.json` and `example_2_sol.json` to the Travis CI builds.
