### ISSUE TITLE
optimal time slot for new job

### ISSUE THREAD

**Issue by chalioui** [VROOM-Project/vroom#367]
Suppose we have already a number of jobs, How we can propose optimal time slots for a new job ? 
Thank you

**Comment by jcoupey** [comment]
Hard to answer directly as your description is a bit sparse on what you're trying to achieve. I'm guessing you have an additional job you want to add on top of an already planned solution, correct?

**Comment by chalioui** [comment]
suppose I have already optimized the routes for my jobs of the day, and at noon I receive a call to add an new job on the top of the initial solution, what time slots should I propose to the new  job ?

**Comment by jcoupey** [comment]
By "optimal time slot" I guess you mean what arrival time for the new job, or how to order the new scheduling including the new job. What about simply solving the problem again, including the additional job?

**Comment by chalioui** [comment]
Yes, solving the problem again will work fine, thak you
