### ISSUE TITLE
Dynamic total weight of  goods for delivery

### ISSUE THREAD

**Issue by yclin0326** [VROOM-Project/vroom#368]
I have one delivery scenario like this:

- vehicle capacity: 100 (kg)
- each goods: 5 (kg)
- goods have to be put into the container
- the capacity of container is 8 goods
- each container: 10 (kg)
- container is just for bundling the goods, not for delivering to the customers

The formula is
`n * 5 + ceiling(n / 8) * 10 <= 100`
`n` is number of goods

For example, I have 9 goods, so total weight is
`9 * 5 + ceiling(9 / 8) * 10
= 45 + 2 * 10
= 65 <= 100`

Obviously, I can not deliver 17 goods, because total weight is over the capacity of one vehicle.

My question is :
How do I setup the correct input format to fit this scenario?

**Comment by jcoupey** [comment]
What about expressing your overall capacity in term of number of goods, rather than kg? From your formula, a vehicle can deliver up to 16 goods, so each vehicle would have a `capacity: [16]` and each `job.delivery` value would be expressed in number of goods.

**Comment by yclin0326** [comment]
The real scenario is: 
some goods have to be put into the container, and some goods are not. It means that there are many different types of goods. And the weight limitation is the only things we are concerned about. That's why the unit is kg, not the number of goods.

**Comment by jcoupey** [comment]
All right, I get the whole picture. Currently the capacity logic is ensuring that (component-wise) **sums** of stuff that has been picked up or is still to deliver fits into the vehicle at any step during a route. And the solving approach is such that there is no easy way to compute amounts as an arbitrary function of the weights at job level.

I guess the closest you could get right now would be to split up the container weight across goods, so each good would hold `5 + 10/8 kg` (or 6250g for the sake of using integers). Now you'd get an exact value whenever you have a multiple of 8 goods, while the sum would be underestimated with non-filled containers. As it's probably more convenient to have an overestimation for a doable route, you could mitigate that by reducing the overall vehicle capacity by a weight close to that of a single empty container.

**Comment by yclin0326** [comment]
I will try this solution. If there are another solutions, I will share it with you! Thanks a lot!

**Comment by jcoupey** [comment]
Closing now, feel free to re-open if required. Any feedback still welcome. ;-)
