### ISSUE TITLE
Endless vehicle error

### ISSUE THREAD

**Issue by wluque** [VROOM-Project/vroom#373]
Hello, I try not to specify the end of the vehicle so that it ends at the last delivery point, but in any case I get the following error

example 

{"id":1,"start":[-58.480728,-34.776424],"start_index":0,"end":[],"end_index":0,"capacity":[30],"skills":[1],"time_window":[25200,72000],"breaks":[]}

error 2 - Invalid end array.

thank you in advance

**Comment by jcoupey** [comment]
Coordinates are [lon, lat] arrays so an empty array does not make sense, hence the error.

If you want open trip optimization, you should omit the end key. The same applies to all values described as optional in the API.

**Comment by Trinity-Solucoes** [comment]
Omitting the **End** key, **vroom** throws the same error!

**Comment by jcoupey** [comment]
@Trinity-Solucoes you already started an ongoing discussion at #541 so please do not cross-post , especially since:
- this ticket is closed
- the problem here was different and a clear solution has been provided.
