### ISSUE TITLE
Relative breaks based on start of vehicle

### ISSUE THREAD

**Issue by Trollgeir** [VROOM-Project/vroom#374]
Our drivers are obligated to have a break if they've been driving for more than 4 hours (for 30 mins). 

Currently the best take I have on this is to set the slack window for breaks to: (start-time + 3 hours) to (start-time + 4 hours). The problem is that the actual start-time for the vehicles might be shifted due to optimizations..

**Comment by jcoupey** [comment]
Time constraints for `break` tasks follow the same logic than for jobs, i.e. they have a duration and a set of valid start time windows, so indeed no way to force a direct relation between start time and break time.

Your approach does provide an upper bound on travel time though and it's probably pretty good if you know in advance there will only be one break for the whole day. 
On the other hand, if the start times get shifted later in your solutions, it means that you have a problem that may not be over-constrained. In that case, maybe your best bet would be to solve the whole problem without any break, then decide afterwards where to best place mandatory breaks (if any) just by looking at the `step.duration` values.

**Comment by Trollgeir** [comment]
Thanks for your input!

The vehicles do have working-hour intervals, so I'm not adding breaks to those which cannot possibly work for at least 4 hours.
I have no guarantee of a possible 30 min gap (break interval)  between deliveries as the deliveries are time windowed, so that sounds like a very challenging post-processing job.

**Comment by Trollgeir** [comment]
Actually we noticed another issue with this.
Since all vehicles need to have a break entry - if they would be deployed - this also makes it mandatory for `vroom` to include them in the solution. This means that if I want to use as few vehicles as possible to solve the solution, I would have to pass in several jobs where I decrement the number of vehicles..

**Comment by jcoupey** [comment]
> this also makes it mandatory for vroom to include them in the solution

Not quite. Breaks are mandatory in the sense that **if** a vehicle is picked up in a solution, it **has to** have all breaks described in input. It does not mean the optimization phase won't be able to discard vehicles (even if they have breaks). In fact, providing a solution with less vehicles will happen if we consider it "cheaper" (read less overall travel time).

**Comment by jcoupey** [comment]
> if I want to use as few vehicles as possible

As a side note, you should know that we optimize on overall travel time, not on the number of vehicles. Sometimes, having one vehicle less means less travel time, but not always (think multi-depot situations where using a closer vehicle is cheaper that adding to another route).

**Comment by Trollgeir** [comment]
> > this also makes it mandatory for vroom to include them in the solution
> 
> Not quite. Breaks are mandatory in the sense that **if** a vehicle is picked up in a solution, it **has to** have all breaks described in input.

Thanks, this is valuable information :)

**Comment by jcoupey** [comment]
Back to the initial question: there is indeed no guarantee you'll be able to insert a valid break somewhere if you solve without break in the first place. So if your constraints are such that it's not possible, I'm afraid that you'll have to stick with the first approach you described for now.

**Comment by jcoupey** [comment]
Closing now, feel free to reopen if required.
