### ISSUE TITLE
Cost of disproportionate jobs-per-vehicle

### ISSUE THREAD

**Issue by Trollgeir** [VROOM-Project/vroom#377]
I've noticed that sometimes in a routing problem with 6 vehicles, 5 of them have an average of 12 stops, while the last one only has 3. Is it possible to add a cost for skewed distributions of jobs?

By example;
https://developers.google.com/optimization/routing/vrp#distance_dimension
`SetGlobalSpanCostCoefficient`

**Comment by Trollgeir** [comment]
Actually my problem might just be related to the fact that I have mandatory breaks on my vehicles, which makes it impossible for `vroom` to strip out rendundant vehicles.

**Comment by jcoupey** [comment]
No, we have no direct way to apply a penalty for this kind of soft constraint. You might be interested in https://github.com/VROOM-Project/vroom/issues/225 for a similar question on balance.

The easiest way to get a more even work balance is by adding constraints, either through capacity or vehicle time window.

> Actually my problem might just be related to the fact that I have mandatory breaks on my vehicles

No, see https://github.com/VROOM-Project/vroom/issues/374#issuecomment-669908497.
