### ISSUE TITLE
about Cmake 

### ISSUE THREAD

**Issue by rlacjfjin** [VROOM-Project/vroom#378]
Hi,
  
  I want to use cmake install vroom, how can I write the CmakeLists.txt?
  Because I use make command and failed to install.

**Comment by jcoupey** [comment]
This project does not use cmake at all, we have a `makefile` building the binary at `bin/vroom`.

By "install", I suspect you mean having the program available system-wide? In that case, what about simply adding the `bin` folder to your `$PATH`?

**Comment by rlacjfjin** [comment]
In mac, I use brew install the vroom, but I want to use code and build from source.
I checkout v1.7.0 branch, and make in src file. But meet with following error:

routing/http_wrapper.cpp:10:10: fatal error: 'asio.hpp' file not found
#include <asio.hpp>
         ^~~~~~~~~~
1 error generated.

I don't know whether my gcc has some problems.

**Comment by jcoupey** [comment]
As mentioned [on the wiki](https://github.com/VROOM-Project/vroom/wiki/Building#dependencies), you need to install `asio` on your system.

**Comment by rlacjfjin** [comment]
Thanks, 
I installed asio and openssl, and make.
But now, another error arised as following:


mkdir -p ../bin
c++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -o ../bin/vroom main.o algorithms/kruskal.o algorithms/munkres.o algorithms/heuristics/solomon.o algorithms/local_search/local_search.o algorithms/local_search/operator.o routing/http_wrapper.o routing/ors_wrapper.o routing/osrm_routed_wrapper.o problems/vrp.o problems/cvrp/cvrp.o problems/tsp/tsp.o problems/vrptw/vrptw.o problems/cvrp/operators/cross_exchange.o problems/cvrp/operators/exchange.o problems/cvrp/operators/intra_cross_exchange.o problems/cvrp/operators/intra_exchange.o problems/cvrp/operators/intra_mixed_exchange.o problems/cvrp/operators/intra_or_opt.o problems/cvrp/operators/intra_relocate.o problems/cvrp/operators/mixed_exchange.o problems/cvrp/operators/or_opt.o problems/cvrp/operators/pd_shift.o problems/cvrp/operators/relocate.o problems/cvrp/operators/reverse_two_opt.o problems/cvrp/operators/route_exchange.o problems/cvrp/operators/two_opt.o problems/tsp/heuristics/christofides.o problems/tsp/heuristics/local_search.o problems/vrptw/operators/cross_exchange.o problems/vrptw/operators/exchange.o problems/vrptw/operators/intra_cross_exchange.o problems/vrptw/operators/intra_exchange.o problems/vrptw/operators/intra_mixed_exchange.o problems/vrptw/operators/intra_or_opt.o problems/vrptw/operators/intra_relocate.o problems/vrptw/operators/mixed_exchange.o problems/vrptw/operators/or_opt.o problems/vrptw/operators/pd_shift.o problems/vrptw/operators/relocate.o problems/vrptw/operators/reverse_two_opt.o problems/vrptw/operators/route_exchange.o problems/vrptw/operators/two_opt.o structures/generic/edge.o structures/generic/matrix.o structures/generic/undirected_graph.o structures/vroom/break.o structures/vroom/job.o structures/vroom/location.o structures/vroom/raw_route.o structures/vroom/solution_state.o structures/vroom/time_window.o structures/vroom/tw_route.o structures/vroom/vehicle.o structures/vroom/input/input.o structures/vroom/solution/computing_times.o structures/vroom/solution/route.o structures/vroom/solution/solution.o structures/vroom/solution/step.o structures/vroom/solution/summary.o structures/cl_args.o utils/exception.o utils/input_parser.o utils/output_json.o utils/version.o -lpthread -lssl -lcrypto
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [../bin/vroom] Error 1


I don't know how to solve.
By the way, is OSRM package necessary?

**Comment by jcoupey** [comment]
The `asio.hpp` and `asio/ssl.hpp` includes are found because the code now compiles. But the linking error you get seems to indicate that the runtime ssl library is still missing on your system.

> By the way, is OSRM package necessary?

Please see [supported routing engines](https://github.com/VROOM-Project/vroom#supported-routing-engines) and [usage documentation](https://github.com/VROOM-Project/vroom/wiki/Usage).

**Comment by rlacjfjin** [comment]
Thanks,
I finally compiled successfully!

**Comment by jcoupey** [comment]
Glad to see it works for you!

Could you please share the commands/steps you used to install dependencies on a mac? It might be very useful for other users finding this ticket.

**Comment by rlacjfjin** [comment]
First of all, I install the package by building from sources as mentioned on the wiki.
1. git clone the source code
2. cd vroom/src and checkout branch v1.7.0
3. make

VROOM requires a compiler with support for C++17 and depends on the **libasio** and **OpenSSL** libraries.
Mac can install from home-brew, like **brew install asio**  and **brew install openssl**.  I don't know whether boost is necessary, but I installed, **brew install boost** 

In my os environment, the first error is:
error: openssl/conf.h file not found
solve:  
cd /usr/local/include  
 ln -s ../opt/openssl/include/openssl .

Then, another problem arises:
error:ld: library not found for -lssl
solve:
ln -s /usr/local/opt/openssl/lib/libcrypto.dylib /usr/local/lib/

And may also arises another problem, such as -lboost_thread  -lrt.
You can vim makefile in src and find following line:
LDLIBS += $(shell pkg-config --libs libosrm) -lboost_system -lboost_filesystem -lboost_iostreams -lboost_thread -lrt -ltbb
 In my boost, I can't find -lboost_thread instead of -lboost_thread-mt, and can't find -lrt.
So I rewrite the line as:
LDLIBS += $(shell pkg-config --libs libosrm) -lboost_system -lboost_filesystem -lboost_iostreams -lboost_thread-mt -ltbb

Retry make, that's ok!

**Comment by jcoupey** [comment]
Thanks for the feedback!

The `boost` dependency has been removed as of `v1.7.0` for `vroom` itself. The reason there are still a couple reference to `boost` libraries in the makefile is it's required when building with `libosrm` installed.

**Comment by mustafasencer** [comment]
> Then, another problem arises:
> error:ld: library not found for -lssl
> solve:
> ln -s /usr/local/opt/openssl/lib/libcrypto.dylib /usr/local/lib/

Thank you for the great and detailed explanation! Helped me a lot. I could make an addition perhaps for the `error:ld: library not found for -lssl` part of the answer. In my case I had to create an additional symbolic link `ln -s /usr/local/opt/openssl/lib/libssl.dylib /usr/local/lib/` in order for my case to compile successfully on my macOS Big Sur.
