### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by Drag0s** [VROOM-Project/vroom#38]
The  [demo page](https://map.vroom-project.org/) doesn't work. I tried both Chrome and Firefox, and clicking or uploading a file with Lat, Lng and it doesn't do nothing.

Could someone check it?

**Comment by jcoupey** [comment]
Thanks for reporting. This is probably due to the fact that the frontend has been switched to https while the solving request is still performed over http.

I won't be able to fix this before a few days, sorry for the downtime. I'll notify via this issue.
