### ISSUE TITLE
Reload on insufficient capacity

### ISSUE THREAD

**Issue by fibis** [VROOM-Project/vroom#380]
Is it possible to go back to the depot to reload the vehicle to delivery more items if the capacity of the vehicle is smaller than the amount of items that should be delivered?

**Comment by jcoupey** [comment]
If the vehicle start is the depot, any stuff delivered in a `job` is presumed loaded at the depot. But we won't generate a route that goes back and load again. You have a couple options though to model this kind of situation:

1. Provide several `vehicle` objects in input, one per route to account for reloads (not very flexible as it requires to fix timing in advance).
2. Model all your deliveries as part of a `shipment` with the pickup happening at the depot. In that case, you'll get several pickups in a row at the depot, possibly multiple times in the route depending on the capacity constraints.

**Comment by jcoupey** [comment]
Closing as answered, feel free to reopen.

**Comment by yuranov** [comment]
> If the vehicle start is the depot, any stuff delivered in a `job` is presumed loaded at the depot. But we won't generate a route that goes back and load again. You have a couple options though to model this kind of situation:
> 
> 1. Provide several `vehicle` objects in input, one per route to account for reloads (not very flexible as it requires to fix timing in advance).
> 2. Model all your deliveries as part of a `shipment` with the pickup happening at the depot. In that case, you'll get several pickups in a row at the depot, possibly multiple times in the route depending on the capacity constraints.


The second option doesn't work as expected. The result are as follows: one pickup - one delivery...one pickup - one delivery
