### ISSUE TITLE
Force only one vehicle to do all the pickups and delivery

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [VROOM-Project/vroom#381]
I have a scenario of 2 vehicles with one has 3 capacity and other vehicle has 4 capacity. There are 4 pickups and all has to be delivered at the same location. I have the following example:

> {"vehicles":[{"id":1,"start":[39.143257,21.573107],"capacity":[3]},{"id":2,"start":[39.16942,21.564066],"capacity":[4]}],"jobs":[],"shipments":[{"amount":[1],"pickup":{"id":1,"service":300,"location":[39.151816,21.577531]},"delivery":{"id":5,"service":300,"location":[39.134787,21.588555]}},{"amount":[1],"pickup":{"id":2,"service":300,"location":[39.152603,21.58039]},"delivery":{"id":5,"service":300,"location":[39.134787,21.588555]}},{"amount":[1],"pickup":{"id":3,"service":300,"location":[39.154457,21.58269]},"delivery":{"id":5,"service":300,"location":[39.134787,21.588555]}},{"amount":[1],"pickup":{"id":4,"service":300,"location":[39.158316,21.580051]},"delivery":{"id":5,"service":300,"location":[39.134787,21.588555]}}]}

The result is:

> {
>     "code": 0,
>     "summary": {
>         "cost": 1737,
>         "unassigned": 0,
>         "delivery": [
>             4
>         ],
>         "amount": [
>             4
>         ],
>         "pickup": [
>             4
>         ],
>         "service": 2400,
>         "duration": 1737,
>         "waiting_time": 0,
>         "computing_times": {
>             "loading": 4,
>             "solving": 2
>         }
>     },
>     "unassigned": [],
>     "routes": [
>         {
>             "vehicle": 1,
>             "cost": 755,
>             "delivery": [
>                 2
>             ],
>             "amount": [
>                 2
>             ],
>             "pickup": [
>                 2
>             ],
>             "service": 1200,
>             "duration": 755,
>             "waiting_time": 0,
>             "steps": [
>                 {
>                     "type": "start",
>                     "location": [
>                         39.143257,
>                         21.573107
>                     ],
>                     "load": [
>                         0
>                     ],
>                     "arrival": 0,
>                     "duration": 0
>                 },
>                 {
>                     "type": "pickup",
>                     "location": [
>                         39.152603,
>                         21.58039
>                     ],
>                     "id": 2,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "job": 2,
>                     "load": [
>                         1
>                     ],
>                     "arrival": 181,
>                     "duration": 181
>                 },
>                 {
>                     "type": "pickup",
>                     "location": [
>                         39.154457,
>                         21.58269
>                     ],
>                     "id": 3,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "job": 3,
>                     "load": [
>                         2
>                     ],
>                     "arrival": 539,
>                     "duration": 239
>                 },
>                 {
>                     "type": "delivery",
>                     "location": [
>                         39.134787,
>                         21.588555
>                     ],
>                     "id": 5,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "job": 5,
>                     "load": [
>                         1
>                     ],
>                     "arrival": 1355,
>                     "duration": 755
>                 },
>                 {
>                     "type": "delivery",
>                     "location": [
>                         39.134787,
>                         21.588555
>                     ],
>                     "id": 5,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "job": 5,
>                     "load": [
>                         0
>                     ],
>                     "arrival": 1655,
>                     "duration": 755
>                 }
>             ]
>         },
>         {
>             "vehicle": 2,
>             "cost": 982,
>             "delivery": [
>                 2
>             ],
>             "amount": [
>                 2
>             ],
>             "pickup": [
>                 2
>             ],
>             "service": 1200,
>             "duration": 982,
>             "waiting_time": 0,
>             "steps": [
>                 {
>                     "type": "start",
>                     "location": [
>                         39.16942,
>                         21.564066
>                     ],
>                     "load": [
>                         0
>                     ],
>                     "arrival": 0,
>                     "duration": 0
>                 },
>                 {
>                     "type": "pickup",
>                     "location": [
>                         39.158316,
>                         21.580051
>                     ],
>                     "id": 4,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "job": 4,
>                     "load": [
>                         1
>                     ],
>                     "arrival": 413,
>                     "duration": 413
>                 },
>                 {
>                     "type": "pickup",
>                     "location": [
>                         39.151816,
>                         21.577531
>                     ],
>                     "id": 1,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "job": 1,
>                     "load": [
>                         2
>                     ],
>                     "arrival": 804,
>                     "duration": 504
>                 },
>                 {
>                     "type": "delivery",
>                     "location": [
>                         39.134787,
>                         21.588555
>                     ],
>                     "id": 5,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "job": 5,
>                     "load": [
>                         1
>                     ],
>                     "arrival": 1582,
>                     "duration": 982
>                 },
>                 {
>                     "type": "delivery",
>                     "location": [
>                         39.134787,
>                         21.588555
>                     ],
>                     "id": 5,
>                     "service": 300,
>                     "waiting_time": 0,
>                     "job": 5,
>                     "load": [
>                         0
>                     ],
>                     "arrival": 1882,
>                     "duration": 982
>                 }
>             ]
>         }
>     ]
> }

It has distributed the task between 2 vehicles.

**Comment by jcoupey** [comment]
A way to force having just one route in output is to only input a single vehicle. Then maybe it is not doable or more expensive to handle everything.

**Comment by AhtashamImtiyaz** [comment]
In my scenario, i need to determine the best one would be to do all the tasks with inputting vehicles on different locations, I can get the expected result if i set all the vehicles capacity to be 4. Then, it returns only one vehicle that can do the task. But i am looking for a way when capacity doesn't match with any vehicle added, it should ignore and assign it to the vehicle that strictly has the capacity required

**Comment by jcoupey** [comment]
Then what about solving the same problem several times with different vehicles (one per instance) and picking the best result ?

**Comment by jcoupey** [comment]
The reason you get a solution with 2 vehicles used is probably precisely because you have vehicles with different locations. In that situation it can be cheaper (for overall travel time) to use 2 vehicles over a single vehicle. Please check and compare the cost values you get in output from the two scenarios.

**Comment by AhtashamImtiyaz** [comment]
> Then what about solving the same problem several times with different vehicles (one per instance) and picking the best result ?

Good idea. Okay thanks i will try to achieve it this way.
