### ISSUE TITLE
Can we describe multiple capacities in the array?

### ISSUE THREAD

**Issue by AhtashamImtiyaz** [VROOM-Project/vroom#382]
According to the usage api documentation, we can model capacity restrictions. But in the example, There is only 1 entry in the array. So can we model it like

In vehicle object, the restrictions:
"capacity": [
        18, 100, 600
      ],

Where 18 = no. of items, 100 = 100 KG and 600 is the total volume.

In the shipment object:
"amount": [
        1, 15, 30
      ]

Where 1 = no.of item, 15 = 15 KG and 30 = its volume

**Comment by jcoupey** [comment]
Yes, that's the point of having an array. From [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#capacity-restrictions):

>  Those arrays can be used to model custom restrictions for several metrics at once, e.g. number of items, weight, volume etc.

**Comment by AhtashamImtiyaz** [comment]
Okay thank you
