### ISSUE TITLE
Distance & duration are always 0

### ISSUE THREAD

**Issue by pastebimas** [VROOM-Project/vroom#387]
Hello,

i've started fresh vroom (1.7.0) docker instance with newest osrm. If I call osrm locally to get distances I get correct responses. Although when I try to call my vroom instance I get duration 0. With the same call, but using "solver.vroom-project.org" I get detailed responses. 
Here is the comparison of the responses: https://prnt.sc/u9oukt

I've tried to set 'geometry: true' in /conf/config.yaml but nothing changed. Here is the config: https://prnt.sc/u9oyig

What could cause this issue? Thanks

**Comment by jcoupey** [comment]
Sound like a typical *outside-the-OSRM-extract* problem, what map area are you using?

Points outside the OSM extract are just snapped to the nearest existing node by OSRM. If several input points are snapped to the same node, the optimization phase gets a trivial zero-filled matrix from OSRM.

You should be able to see the actual OSRM query performed by `vroom` (e.g. in `osrm-routed` logs) to rerun them and check.

**Comment by pastebimas** [comment]
Yeah that was the problem. I've only included "Berlin" maps because thought that it includes whole europe... (mistaken by old GPS maps naming :D) 

For anyone else that might get  to such problem, you have to download .pbf and import it:
```
wget http://download.geofabrik.de/europe/lithuania-latest.osm.pbf
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/lithuania-latest.osm.pbf
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-partition /data/lithuania-latest.osrm
sudo docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-customize /data/lithuania-latest.osrm
```

Thanks for the help!

**Comment by sabeerulhassan** [comment]
I am facing the same problem! I tried the above solution but I am still getting the distance and duration as 0 always.

I tried downloading different areas of the map and used the coordinates on the specific area, but no luck, I am always getting 0 for distance and duration.

any idea please ?

**Comment by jcoupey** [comment]
@sabeerulhassan you should test OSRM alone to make sure everything works as expected. So first check what happens if you send a simple route request to OSRM.

**Comment by sabeerulhassan** [comment]
@jcoupey  thanks for the reply.

The issue was the order of lat and lon. it's different from what we get from the maps, not sure why the order is swapped when passing to vroom.
