### ISSUE TITLE
Job Description field not being returned from API

### ISSUE THREAD

**Issue by grahas** [VROOM-Project/vroom#388]
I send the api 

`{"jobs": [{"id": 0, "description": "52 CAHILL RD", "location": [-105.57732408604633, 48.06538600676694]}, {"id": 1, "description": "5 LUSTRE RD", "location": [-105.99928881873393, 48.40759971711365]}, {"id": 2, "description": "330 ACADEMY RD", "location": [-105.92954847825804, 48.45779135857123]}, {"id": 3, "description": "320 HILL ST", "location":
[-105.64195875581605, 48.09867319613092]}, {"id": 4, "description": "321 EUREKA ST", "location": [-105.64236453401189, 48.09514604719764]}, {"id": 5, "description": "739 JOHNSON ST", "location": [-105.65148785476725, 48.10011794487223]}, {"id": 6, "description": "629 KNAPP ST", "location": [-105.64853592986988, 48.10113016081136]}, {"id": 7, "description": "120 CRESCENT DR", "location": [-105.63338390449026, 48.10051034576493]}, {"id": 8, "description": "516 DAWSON ST", "location": [-105.645793582722, 48.08750314799203]}, {"id": 9, "description": "501 EDGAR ST", "location": [-105.64501769913869, 48.085991512734914]}, {"id": 10, "description": "417 BENTON ST", "location": [-105.64383603735955,
48.08897911044073]}, {"id": 11, "description": "500 DAWSON ST", "location": [-105.64497310812816, 48.087431802375185]}, {"id": 12, "description": "710 JOHNSON ST", "location": [-105.64990041479223, 48.10068425070602]}, {"id": 13, "description": "4700 HIGHWAY 250 W", "location": [-105.69623939293963, 48.320290518487184]}, {"id": 14, "description": "5525 HIGHWAY 250 W", "location": [-105.66922169965682, 48.200951596993804]}, {"id": 15, "description": "6093 ROAD 1070", "location": [-105.56041517485168, 48.115965590016174]}, {"id": 16, "description": "413 DAWSON ST", "location": [-105.64381820095532, 48.08698589226984]}, {"id": 17, "description": "329 E PLEASANT VIEW RD", "location": [-105.84569508294797, 48.573870677194535]}, {"id": 18, "description": "260 THIEVIN RD", "location": [-106.0274703373917, 48.90054442036998]}, {"id": 19, "description": "311 DANELSON RD", "location": [-105.48842744744483, 48.88207928290767]}, {"id": 20, "description": "3791 LW 1 DR", "location": [-105.78319186348183, 48.45326091190094]}, {"id": 21, "description": "201 FAIRWEATHER ST", "location": [-105.63915844035446, 48.084943623987364]}, {"id": 22, "description": "41 CHABOT RD", "location": [-105.53130170407371, 48.85290338471496]}], "vehicles": [{"id": 0, "start": [-105.64721499999999, 48.094164], "end": [-105.64721499999999, 48.094164]}], "options": {}}`

I get back
`{'code': 0, 'summary': {'cost': 39083, 'unassigned': 0, 'service': 0, 'duration': 39083, 'waiting_time': 0, 'computing_times': {'loading': 52, 'solving': 2}}, 'unassigned': [], 'routes': [{'vehicle': 0, 'cost': 39083, 'service': 0, 'duration': 39083, 'waiting_time': 0, 'steps': [{'type': 'start', 'location': [-105.647215, 48.094164], 'arrival': 0, 'duration': 0}, {'type': 'job', 'location': [-105.64236453401188, 48.09514604719764], 'job': 4, 'service': 0, 'waiting_time': 0, 'arrival': 73, 'duration': 73}, {'type': 'job', 'location': [-105.64195875581603, 48.09867319613092], 'job': 3, 'service': 0, 'waiting_time': 0, 'arrival': 162, 'duration': 162}, {'type': 'job', 'location': [-105.63338390449026, 48.10051034576493], 'job': 7, 'service': 0, 'waiting_time': 0, 'arrival': 323, 'duration': 323}, {'type': 'job', 'location': [-105.64990041479224, 48.10068425070602], 'job': 12, 'service': 0, 'waiting_time': 0, 'arrival': 586, 'duration': 586}, {'type': 'job', 'location': [-105.65148785476724, 48.10011794487223], 'job': 5, 'service': 0, 'waiting_time': 0, 'arrival': 653, 'duration': 653}, {'type': 'job', 'location': [-105.64853592986988, 48.10113016081136],
'job': 6, 'service': 0, 'waiting_time': 0, 'arrival': 701, 'duration': 701}, {'type': 'job', 'location': [-105.66922169965682, 48.20095159699381], 'job': 14, 'service': 0, 'waiting_time': 0, 'arrival': 2011, 'duration': 2011}, {'type': 'job', 'location': [-105.69623939293965, 48.320290518487184], 'job': 13, 'service': 0, 'waiting_time': 0, 'arrival': 3273, 'duration': 3273}, {'type': 'job', 'location': [-105.78319186348185, 48.45326091190094], 'job': 20, 'service': 0, 'waiting_time': 0, 'arrival': 5716, 'duration': 5716}, {'type': 'job', 'location': [-105.92954847825804, 48.45779135857123], 'job': 2, 'service': 0, 'waiting_time': 0, 'arrival': 7499, 'duration': 7499}, {'type': 'job', 'location': [-105.99928881873392, 48.40759971711365], 'job': 1, 'service': 0, 'waiting_time': 0, 'arrival': 8980, 'duration':
8980}, {'type': 'job', 'location': [-105.84569508294796, 48.573870677194535], 'job': 17, 'service': 0, 'waiting_time': 0, 'arrival': 13342, 'duration': 13342}, {'type': 'job', 'location': [-106.0274703373917, 48.90054442036998], 'job': 18, 'service': 0, 'waiting_time': 0, 'arrival': 21443, 'duration': 21443}, {'type': 'job', 'location': [-105.48842744744483, 48.88207928290767], 'job': 19, 'service': 0, 'waiting_time': 0, 'arrival': 29338, 'duration': 29338}, {'type': 'job', 'location': [-105.53130170407373, 48.85290338471496], 'job': 22, 'service': 0, 'waiting_time': 0, 'arrival': 30297, 'duration': 30297}, {'type': 'job', 'location': [-105.57732408604632, 48.06538600676694], 'job': 0, 'service': 0, 'waiting_time': 0, 'arrival': 37075, 'duration': 37075}, {'type': 'job', 'location': [-105.56041517485168, 48.115965590016174], 'job': 15, 'service': 0, 'waiting_time': 0, 'arrival': 38211, 'duration': 38211}, {'type': 'job', 'location': [-105.63915844035446, 48.08494362398736], 'job': 21, 'service': 0, 'waiting_time': 0, 'arrival': 38724, 'duration': 38724}, {'type': 'job', 'location': [-105.64501769913868, 48.085991512734914], 'job': 9, 'service': 0, 'waiting_time': 0, 'arrival': 38810, 'duration': 38810}, {'type': 'job', 'location': [-105.64381820095532, 48.08698589226984], 'job': 16, 'service': 0, 'waiting_time': 0, 'arrival': 38847, 'duration': 38847}, {'type': 'job', 'location': [-105.64497310812816, 48.087431802375185], 'job': 11, 'service': 0, 'waiting_time': 0, 'arrival': 38862, 'duration': 38862}, {'type': 'job', 'location': [-105.64383603735956, 48.08897911044073], 'job': 10, 'service': 0, 'waiting_time': 0, 'arrival': 38900, 'duration': 38900}, {'type': 'job', 'location': [-105.645793582722, 48.08750314799203], 'job':
8, 'service': 0, 'waiting_time': 0, 'arrival': 38959, 'duration': 38959}, {'type': 'end', 'location': [-105.647215, 48.094164], 'arrival': 39083, 'duration': 39083}]}]}`

I think the description field should be returned but it isn't. Not sure if I am sending something wrong or what.

**Comment by jcoupey** [comment]
> I send the api

I guess you're using the demo server. In that case, it's normal as this server has been running `v1.7.0` for a while now and the description feature is not released yet.

I just updated the demo server to current `master` and the descriptions are showing in output.

Generally speaking, you should not rely on the demo server except for testing purposes.

**Comment by grahas** [comment]
Awesome, thank you. I was running VROOM on a google compute instance. I am currently running v1.6.0 docker image. So I can just rebuild the docker image with `docker build -t vroomvrp/vroom-docker:v1.6.0 --build-arg VROOM_RELEASE=v1.7.0 --build-arg VROOM_EXPRESS_RELEASE=v0.7.0 .`  and run a container with the new image to fix it?

**Comment by jcoupey** [comment]
Like I said, handling `description` keys is not released yet, so running `v1.7.0` won't change that. If you want to use Docker with descriptions, you'll have to point to current `master`.
