### ISSUE TITLE
vroom -h is wrong in the develop branch

### ISSUE THREAD

**Issue by chesty** [VROOM-Project/vroom#39]
Hey, love your work.

vroom -h says -a=ADDRESS -p=PORT, etc, but it should be -a ADDRESS -p PORT
 
I've been using an older version of vroom for 6 months, now I'm moving all my map stuff into docker containers, and there have been some updates to osrm and vroom since I last compiled them. I worked out osrm api changed and I need to use the vroom develop branch, but it took me a while to workout the exact command to feed into vroom. so here's an example that might help save someone a few minutes.

vroom -a 127.0.0.1 -p 5000 -m car -t 8  '{"vehicles": [{"start": [151.1237, -34.0221], "round_trip": true, "id": 1}], "jobs": [{"id": 1, "location": [151.1237, -34.0221]}, {"id": 2, "location": [151.1578653, -33.8030746]}, {"id": 3, "location": [151.1353032, -33.7160608]}]}'

I'm looking forward to see where you go with this. I started using vroom because it allowed me a to specify a start and end location, at the time osrm didn't let me do that, or I couldn't work out how to make it. Now I see we can specify multiple vehicles, which is starting getting really exciting. When we can specify a time range for a job, and have the ability to pin a job to a vehicle, we will be able to use it for even more work. 

Lots of meaty computer science concepts in this project. I'd love to help, but It's a way above my level atm.

**Comment by jcoupey** [comment]
@chesty thanks for the feedback. If you feel like it, you're welcome to issue a PR to fix the misleading `-h` output.

The documentation is indeed currently missing a working example to use with `develop` as the wiki still describes the "old" 0.3.1 API. Until the next release, the current state of the API in `develop` (still subject to potential changes) is described in ongoing #30.

Using multiple vehicles is not supported yet but the API design aim at allowing easy future integration of such new features. See the discussion at #4 for more on the current roadmap.

**Comment by jcoupey** [comment]
>vroom -a 127.0.0.1 -p 5000 -m car -t 8 '{"vehicles": [{"start": [151.1237, -34.0221], "round_trip": true, "id": 1}], >"jobs": [{"id": 1, "location": [151.1237, -34.0221]}, {"id": 2, "location": [151.1578653, -33.8030746]}, {"id": 3, >"location": [151.1353032, -33.7160608]}]}'

Slight change in the API, the `round_trip` key is removed for clarification (just use same `start` and `end` for a round trip).

Those changes should be final and are included in the v1.0.0 release candidate, see https://github.com/VROOM-Project/vroom/pull/41#issuecomment-246009069.

Also `-a` and `-p` inputs could be omitted in that case as they are the default values.
