### ISSUE TITLE
There seems to be a comparison bug in solomon.cpp

### ISSUE THREAD

**Issue by hedayat** [VROOM-Project/vroom#398]
https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/algorithms/heuristics/solomon.cpp#L44

It seems that this is supposed to be `<` rather than `<<`

**Comment by jcoupey** [comment]
Can you expand on why this may be a problem? For the record, there is no `operator<` defined for amounts, and `operator<<` implements a lexicographical comparison:

https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/structures/vroom/amount.h#L33-L52

**Comment by hedayat** [comment]
Oops, I'm really sorry. Didn't notice it is using an overloaded operator. :P
