### ISSUE TITLE
Doubt about prioritizing cars by cost

### ISSUE THREAD

**Issue by matheus-gio** [VROOM-Project/vroom#399]
I will need to modify the algorithm to adapt to my needs, but would I have any basic instructions?
The adaptation I intend to make aims to send the cost of the vehicle together in the requisition, so that different values ​​can be defined based on capacity.

I would like to thank this incredible project. Just as the project is extremely useful for many scenarios, it also has an exceptional performance.

**Comment by jcoupey** [comment]
Thanks for your feedback. How different would this be from #359?

**Comment by matheus-gio** [comment]
in fact I would like to pass parameters of minimum costs, time per minute and per kilometer. I changed the project to receive this data, but I had to change the struct of Cost which, because it is fundamental to the project, led me to n problems. In this strict that was created I received the data of duration and distance, I only made this change in osrm for now.

**Comment by jcoupey** [comment]
For now, the notion of `cost` is equivalent to the travel times we hold in the matrix retrieved from the routing engine. Decorrelating the two (e.g. via a cost per hour for vehicles) would be compatible with the current solving approach. I agree this may be an interesting addition at some point. The tricky part being that we'd have to adjust every single cost evaluation throughout the codebase.

The cost per km part is similar, with the additional restriction that for now we don't hold a distance matrix while solving.

**Comment by jcoupey** [comment]
Closing as stale.
