### ISSUE TITLE
Performance and Loading times tips

### ISSUE THREAD

**Issue by xamado** [VROOM-Project/vroom#400]
I've set up a simple docker container on my dev machine for testing purposes, and running a query with 100~ points, but noticing that most time in "computing_times" is reported under "loading". In numbers it's taking around 6 seconds in "loading" and then just a few ms for "solving".

I finally figured out this seems to be the time it takes to compute the distance matrix /table request to OSRM. And I could confirm that simply running the request against OSRM is taking a long time. Now I tried my query against the vroom demo server in the docs, and the computing times are much much more reasonable. I've been adviced that CH is much faster for table queries, but I'm wondering if this is what the vroom demo server is using? Is that the only difference or is there something else that I could be doing wrong that would slowdown the loading times so considerably?

**Comment by jcoupey** [comment]
Depending on the underlying routing engine, the time it takes to compute the travel time matrix can indeed be a bottleneck for the whole solving time.

Like you already figured out, you should definitely use CH on the OSRM side if you care about getting matrices fast. Our demo server does run on top of `osrm-routed` with CH.

> is there something else that I could be doing wrong

To answer this you'd have to compare loading times from `vroom` to the time it takes for a direct `table` request to complete. A big difference might indicate something else is wrong in your setup.

Now if you really want to push this, there are a couple steps that can be bypassed. When using OSRM as a server, the table is serialized to json in OSRM, then sent over the wire, then parsed inside VROOM. Whereas if you build `vroom` against `libosrm`, we directly access the OSRM table object from C++.

**Comment by xamado** [comment]
Yes I can confirm I already switched to CH and the loading times went down considerably. I haven't checked the difference between the OSRM reported time and the vroom reported time but I'll take a look.

I already flagged using libosrm as the next obvious step, since for my use case I don't really need them to scale as different services, so using it as a linked library instead of a separate http request makes a lot of sense. I'm gonna look into that but I haven't seen much docs or examples on containers using libosrm instead.

Thanks, at least it looks I was in the right track :)

**Comment by jcoupey** [comment]
I'm not aware of any container including the `libosrm` setup. This would probably result in a huge image, somehow defeating the purpose of containerization... Anyway, setting up the whole stack should be quite straightforward. You want to make sure `libosrm` is installed on the system prior to building `vroom`. The compilation process [checks for `libosrm`](https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/makefile#L29-L32) and acts accordingly.

Note that there is a known issue with `libosrm` interface that is broken after v5.22.0, see #344.

**Comment by xamado** [comment]
Thanks for the heads up. For the moment I can move forward with the 2 separate servers, since this already improved response times from 6 seconds to a few ms. 

I am trying to use VROOM to figure out what time slots were available for a customer to select their order delivery, and since it took 6 seconds before I was doing some heuristics to figure it out, but it reached to a point where it got so complex that I might had to aswell solve this as a linear programming problem, hence why I went back to figure out why I can't just use vroom to do it.

With the new response times this is already feasible (i need to check between 1 to 6 possible delivery options for the user to select from). I'm just making a fake order, re-running the routing, and if the order ends unassigned I assume that the routing is not possible and gray out the option for the user.

Shaving off the json serialization sounds like it would be an extra win, but for now I can wait for #344 to be solved before moving forward with it.

**Comment by jcoupey** [comment]
> but for now I can wait for #344 to be solved

Or build against any version of `libosrm` up to v5.22.0. ;-)

**Comment by xamado** [comment]
Or that, yeah :P 

On another note, why did you say that libosrm would result in a huge image?

**Comment by jcoupey** [comment]
>why did you say that libosrm would result in a huge image

That was just an (unfounded) quick though but I'm definitely not the expert in containers. If you're interested in the topic, maybe worth starting a discussion on https://github.com/VROOM-Project/vroom-docker which is where all the Docker-related stuff around VROOM happens.

Also feel free to close this ticket if the initial question is answered.
