### ISSUE TITLE
Drivers breaks are not taken into account

### ISSUE THREAD

**Issue by pastebimas** [VROOM-Project/vroom#401]
I've attached request/response example.

There are given  details about break from 13:00 to 14:00, but "jobs" arrival times are after 13:00

Is this a bug, or incorrect request data?
[results.zip](https://github.com/VROOM-Project/vroom/files/5482684/results.zip)

**Comment by jcoupey** [comment]
Can you be more specific on what exactly is wrong? Only vehicle with `id` 26 has a `breaks` key and the matching route in response does contain a break step. The other route does not have a break in it, but this is expected as the vehicle with `id` 58 does not have a `breaks` key.

**Comment by jcoupey** [comment]
@pastebimas any follow-up on this? Otherwise please close.

**Comment by pastebimas** [comment]
Is it possible or planned to have strict break hours for drivers? Because currently "break window" works as "start time of the break". If window is 09:00 - 10:00 so it can start event at 09:59 at the moment. 
Thanks

**Comment by jcoupey** [comment]
This is expected and similar to job time windows that are constraining the service *start* while actual service can go on after the end of the time window. If you want the break to end before 10:00, then you need to advance the deadline based on the service time, e.g. for a 20 minutes break, "start between 9:00 and 9:40".

**Comment by jcoupey** [comment]
Closing as answered.
