### ISSUE TITLE
How to set capacity for multiple compartements in vehicle

### ISSUE THREAD

**Issue by johky** [VROOM-Project/vroom#402]
I recently found some case that need to create json for multiple compartements in a truck, for example the truck is build half for frozen food, the other half is for dry food. How do I create create  the capacity or contraints for this situation. Assuming each had volume 3000cm3 | 3000cm3 and maximum weight is 2000kg for both... Is vroom capable to handle this situation?

**Comment by jcoupey** [comment]
As stated in [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#capacity-restrictions), you should use different components for different capacity metrics. In your case, you could describe amounts using `[frozen volume, dry volume, weight]`.

**Comment by jcoupey** [comment]
Closing as this looks answered.
