### ISSUE TITLE
Time window in shipment_step

### ISSUE THREAD

**Issue by Ahmadreza94** [VROOM-Project/vroom#404]
Hi there 
I have problem in setting time window for just pick-up shipments : 
```
{
    "vehicles": [
        {
            "id": 1,
            "start": [
                51.57548904418945,
                35.73578374211064
            ],
            "capacity": [
                10
            ]
        }
    ],
    "shipments": [
        {
            "amount": [
                1
            ],
            "pickup": {
                "id": 110,
                "description": "pickup_1",
                "service": 300,
                "location": [
                    51.572886114121275,
                    35.743706758469585
                ],
                "time_windows": [
                    28800,
                    36000
                ]
            },
            "delivery": {
                "id": 110,
                "description": "dropoff_1",
                "service": 300,
                "location": [
                    51.5342485939575,
                    35.74263541126018
                ]
            }
        },
        {
            "amount": [
                1
            ],
            "pickup": {
                "id": 5,
                "description": "pickup_2",
                "service": 300,
                "location": [
                    51.52799568837793,
                    35.74264560116295
                ],
            "time_windows": [
                36000,
                39600
            ]
            },
            "delivery": {
                "id": 7,
                "description": "dropoff_2",
                "service": 300,
                "location": [
                    51.48768899266167,
                    35.73620642640259
                ]
            }
        },
        {
            "amount": [
                1
            ],
            "pickup": {
                "id": 5,
                "description": "pickup_3",
                "service": 300,
                "location": [
                    51.48716926574706,
                    35.73696812999814
                ],
            "time_windows": [
                40000,
                50000
            ]
            },
            "delivery": {
                "id": 7,
                "description": "dropoff_3",
                "service": 300,
                "location": [
                    51.46313667297363,
                    35.74073018643231
                ]
            }
        }
    ]
}
```

**Comment by jcoupey** [comment]
Can you please provide some context to explain what your actual problem is?

**Comment by Ahmadreza94** [comment]
@jcoupey I was thought the relative time can be based on 24 hours of the day, for example 8 am will be 8*3600 = 28800 and 11 am will be 11*3600 = 39900 and put it for a pick-up and so on ... but know i realized that i should use absolute time for this case

**Comment by jcoupey** [comment]
Both options are valid, check [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#time-windows) on this.

**Comment by Ahmadreza94** [comment]
Thank for your response and great project
I have another question, I have this condition : 

- 3 shipment (pick-up and drop-off) that can be done exactly by the their orders. (pick_1,drop_1,pick_2,drop_2 , ...) 
- vehicle start location is near pick-up 1, so optimized task due the route can be like above order
- but time window of shipments are exactly reverse. it means for example : pick-up 3 time window is 7 - 7:30 am
pick-up 2 time window is 15-15:30 and pick-up 1 time window is 19 - 19:30

The expected order of pick-up and deliveries of this rout will be pick3 and 2 and 1 , due the time window, am I wrong?
but the route will be based on distance of travel, not time window

Also, I have provided an payload example : 

{
    "vehicles": [
        {
            "id": 10,
            "start": [
                51.589822,
                35.735853
            ],
            "capacity": [
                10
            ]
        }
    ],
    "shipments": [
        {
            "pickup": {
                "id": 11,
                "description": "pickup_1",
                "service": 300,
                "location": [
                    51.56390190124512,
                    35.741566174833515
                ],
                "time_window": [
                    1605812400,
                    1605814200

                ]
            },
            "delivery": {
                "id": 110,
                "description": "dropoff_1",
                "service": 300,
                "location": [
                    51.54253005981445,
                    35.741566174833515
                ]
            }
        },
        {
            "pickup": {
                "id": 5,
                "description": "pickup_2",
                "service": 300,
                "location": [
                    51.51738166809082,
                    35.73243949298462
                ],
                "time_window": [
                    1605798000,
                    1605799800
                ]
            },
            "delivery": {
                "id": 7,
                "description": "dropoff_2",
                "service": 300,
                "location": [
                    51.51738166809082,
                    35.73243949298462
                ]
            }
        },
        {
            "pickup": {
                "id": 50,
                "description": "pickup_3",
                "service": 300,
                "location": [
                    51.488542556762695,
                    35.73696812999814
                ],
                "time_window": [
                    1605769200,
                    1605771000
                ]
            },
            "delivery": {
                "id": 70,
                "description": "dropoff_3",
                "service": 300,
                "location": [
                    51.45292282104492,
                    35.747766148151086
                ]
            }
        }
    ]
}

**---- that has this result :** 


{
    "success": true,
    "status": 200,
    "data": {
        "code": 0,
        "summary": {
            "cost": 1909,
            "unassigned": 0,
            "delivery": [
                0
            ],
            "amount": [
                0
            ],
            "pickup": [
                0
            ],
            "service": 1800,
            "duration": 1909,
            "waiting_time": 0,
            "priority": 0,
            "computing_times": {
                "loading": 27,
                "solving": 1
            }
        },
        "unassigned": [],
        "routes": [
            {
                "vehicle": 10,
                "cost": 1909,
                "delivery": [
                    0
                ],
                "amount": [
                    0
                ],
                "pickup": [
                    0
                ],
                "service": 1800,
                "duration": 1909,
                "waiting_time": 0,
                "priority": 0,
                "steps": [
                    {
                        "type": "start",
                        "location": [
                            51.589822,
                            35.735853
                        ],
                        "load": [
                            0
                        ],
                        "arrival": 0,
                        "duration": 0
                    },
                    {
                        "type": "pickup",
                        "description": "pickup_1",
                        "location": [
                            51.56390190124512,
                            35.741566174833515
                        ],
                        "id": 11,
                        "service": 300,
                        "waiting_time": 0,
                        "job": 11,
                        "load": [
                            0
                        ],
                        "arrival": 435,
                        "duration": 435
                    },
                    {
                        "type": "delivery",
                        "description": "dropoff_1",
                        "location": [
                            51.54253005981445,
                            35.741566174833515
                        ],
                        "id": 110,
                        "service": 300,
                        "waiting_time": 0,
                        "job": 110,
                        "load": [
                            0
                        ],
                        "arrival": 991,
                        "duration": 691
                    },
                    {
                        "type": "pickup",
                        "description": "pickup_2",
                        "location": [
                            51.51738166809082,
                            35.73243949298462
                        ],
                        "id": 5,
                        "service": 300,
                        "waiting_time": 0,
                        "job": 5,
                        "load": [
                            0
                        ],
                        "arrival": 1611,
                        "duration": 1011
                    },
                    {
                        "type": "delivery",
                        "description": "dropoff_2",
                        "location": [
                            51.51738166809082,
                            35.73243949298462
                        ],
                        "id": 7,
                        "service": 300,
                        "waiting_time": 0,
                        "job": 7,
                        "load": [
                            0
                        ],
                        "arrival": 1911,
                        "duration": 1011
                    },
                    {
                        "type": "pickup",
                        "description": "pickup_3",
                        "location": [
                            51.488542556762695,
                            35.73696812999814
                        ],
                        "id": 50,
                        "service": 300,
                        "waiting_time": 0,
                        "job": 50,
                        "load": [
                            0
                        ],
                        "arrival": 2686,
                        "duration": 1486
                    },
                    {
                        "type": "delivery",
                        "description": "dropoff_3",
                        "location": [
                            51.45292282104492,
                            35.747766148151086
                        ],
                        "id": 70,
                        "service": 300,
                        "waiting_time": 0,
                        "job": 70,
                        "load": [
                            0
                        ],
                        "arrival": 3409,
                        "duration": 1909
                    }
                ]
            }
        ]
    }
}

**Comment by jcoupey** [comment]
The time window constraints are hard constraints, so you have a guarantee that the solution provided meet them. Then we optimize based on travel time.

So if the "geographical obvious" best route is not feasible due to time window, you'll get a different route, probably more expensive in term of travel times but that meets the timing constraints.

**Comment by Ahmadreza94** [comment]
@jcoupey but the problem is that I do not get different route based on feasible time window, its based on distance of travel, please see my result, I expected that the time window should be first constraint to check and best route should be second parameter, but it's not behave like that

**Comment by jcoupey** [comment]
The [docs state](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#shipments) that `time_windows` (plural) are *an array* of `time_window` objects. The `time_window` key you're using is simply ignored and thus no timing constraint apply.

**Comment by jcoupey** [comment]
@Ahmadreza94 any follow-up on this? Otherwise please close.

**Comment by Ahmadreza94** [comment]
@jcoupey thanks for your response, i will close it

**Comment by Ahmadreza94** [comment]
@jcoupey thanks for your response, i will close it
