### ISSUE TITLE
time traffic

### ISSUE THREAD

**Issue by NasserEspari** [VROOM-Project/vroom#407]
Hi, first thanks for your great project.
i have a problem, we want to consider real time traffic in the ETA time, for example after define points, get traffic from google instead of Osrm, is it possible? can we make some changes in C++ codes?

**Comment by jcoupey** [comment]
If what you have in mind is feeding VROOM a travel time matrix computed from an external source, then you can do this using the [matrix key](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#matrix) in input.

**Comment by jcoupey** [comment]
Closing as answered.
