### ISSUE TITLE
'Invalid profile: car' in combination with custom distance matrix

### ISSUE THREAD

**Issue by jfalameda** [VROOM-Project/vroom#408]
Hi,

I am running vroom via docker compose (vroom express 0.6.0) together with ORS. I do get regular routings to work, but when I execute a route with my own distance-time matrix I get the following error with no further explanation:

```
vroom    | Tue, 01 Dec 2020 21:52:59 GMT: [Error]
vroom    | Tue, 01 Dec 2020 21:52:59 GMT: Invalid profile: car.
```

I tried to run the example listed on the API docs with the same result.

https://github.com/VROOM-Project/vroom/blob/master/docs/example_2.json

Thanks.

**Comment by jcoupey** [comment]
You're hitting [this exception](https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/utils/input_parser.cpp#L692) while we try to define a routing wrapper to ORS with an invalid profile name (`car` is the default for OSRM profile). You should use `driving-car` for ORS (or adjust `config.yml` in `vroom-express`).

The rationale behind still defining an ORS routing wrapper with a custom matrix is that while you're bypassing the matrix computation, you may still want to use the routing to retrieve distances and route geometry (see https://github.com/VROOM-Project/vroom/issues/384#issuecomment-735792312 for more on this).

**Comment by jcoupey** [comment]
@jfalameda please close this ticket if the suggestion fixed your problem.

**Comment by jfalameda** [comment]
Yes, It did solve my issue. Thanks.

**Comment by chhass** [comment]
@jcoupey ,

I'm using VRoom with valhalla. In the config.yml, there's no valhalla option:

`router: 'osrm' # routing backend (osrm, libosrm or ors)`

And when we try to run some example, i'm receiving the same message:

```
{
    "code": 2,
    "error": "Invalid profile: car."
}
```

Some idea? Thanks!

**Comment by jcoupey** [comment]
This value in `config.yml` is only a placeholder for stuff passed on to the `vroom` system call, so you can put there [any supported value](https://github.com/VROOM-Project/vroom/wiki/Usage#complete-usage-and-options-list-for-v1120), including `valhalla`. There is a default Valhalla config further down in that same file.

Note that this is only related to `vroom-express` and has nothing to do with the core backend repo.
