### ISSUE TITLE
Please help. Buid error

### ISSUE THREAD

**Issue by valerivp** [VROOM-Project/vroom#409]
on Ubuntu, on two PC

vroom/src# make
/bin/sh: 1: pkg-config: not found
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c main.cpp -o main.o
In file included from ./structures/vroom/job.h:16:0,
                 from ./structures/vroom/solution/solution.h:15,
                 from problems/vrp.h:13,
                 from main.cpp:19:
./structures/typedefs.h:36:34: error: 'optional' in namespace 'std' does not name a template type
 using OptionalCoordinates = std::optional<Coordinates>;
                                  ^
In file included from ./structures/vroom/job.h:18:0,
                 from ./structures/vroom/solution/solution.h:15,
                 from problems/vrp.h:13,
                 from main.cpp:19:
./structures/vroom/location.h:22:3: error: 'OptionalCoordinates' does not name a type
   OptionalCoordinates _coords;
   ^
In file included from structures/vroom/input/input.h:24:0,
                 from main.cpp:22:
./structures/vroom/vehicle.h:25:8: error: 'optional' in namespace 'std' does not name a template type
   std::optional<Location> start;
        ^
./structures/vroom/vehicle.h:26:8: error: 'optional' in namespace 'std' does not name a template type
   std::optional<Location> end;
        ^
./structures/vroom/vehicle.h:34:22: error: 'optional' in namespace 'std' does not name a template type
           const std::optional<Location>& start,
                      ^
./structures/vroom/vehicle.h:34:30: error: expected ',' or '...' before '<' token
           const std::optional<Location>& start,
                              ^
In file included from main.cpp:24:0:
utils/helpers.h: In function 'vroom::Gain vroom::utils::addition_cost(const vroom::Input&, const vroom::Matrix<unsigned int>&, vroom::Index, const vroom::Vehicle&, const std::vector<short unsigned int>&, vroom::Index)':
utils/helpers.h:109:29: error: 'const struct vroom::Vehicle' has no member named 'start'
         previous_cost = m[v.start.value().index()][job_index];
                             ^
utils/helpers.h:112:36: error: 'const struct vroom::Vehicle' has no member named 'end'
         next_cost = m[job_index][v.end.value().index()];
                                    ^
utils/helpers.h:119:26: error: 'const struct vroom::Vehicle' has no member named 'end'
         auto n_index = v.end.value().index();
                          ^
utils/helpers.h:131:26: error: 'const struct vroom::Vehicle' has no member named 'start'
         auto p_index = v.start.value().index();
                          ^
utils/helpers.h: In function 'vroom::Gain vroom::utils::addition_cost(const vroom::Input&, const vroom::Matrix<unsigned int>&, vroom::Index, const vroom::Vehicle&, const std::vector<short unsigned int>&, vroom::Index, vroom::Index)':
utils/helpers.h:173:39: error: 'const struct vroom::Vehicle' has no member named 'end'
         after_delivery = m[d_index][v.end.value().index()];
                                       ^
utils/helpers.h:174:44: error: 'const struct vroom::Vehicle' has no member named 'end'
         remove_after_pickup = m[p_index][v.end.value().index()];
                                            ^
utils/helpers.h: In function 'vroom::Cost vroom::utils::route_cost_for_vehicle(const vroom::Input&, vroom::Index, const std::vector<short unsigned int>&)':
utils/helpers.h:213:19: error: 'const struct vroom::Vehicle' has no member named 'start'
       cost += m[v.start.value().index()][input.jobs[route.front()].index()];
                   ^
utils/helpers.h:223:53: error: 'const struct vroom::Vehicle' has no member named 'end'
       cost += m[input.jobs[route.back()].index()][v.end.value().index()];
                                                     ^
utils/helpers.h: In function 'vroom::Solution vroom::utils::format_solution(const vroom::Input&, const RawSolution&)':
utils/helpers.h:297:46: error: 'const struct vroom::Vehicle' has no member named 'start'
       steps.emplace_back(STEP_TYPE::START, v.start.value(), current_load);
                                              ^
utils/helpers.h:301:13: error: 'const struct vroom::Vehicle' has no member named 'start'
         m[v.start.value().index()][input.jobs[route.front()].index()];
             ^
utils/helpers.h:360:44: error: 'const struct vroom::Vehicle' has no member named 'end'
       steps.emplace_back(STEP_TYPE::END, v.end.value(), current_load);
                                            ^
utils/helpers.h:362:47: error: 'const struct vroom::Vehicle' has no member named 'end'
         m[input.jobs[route.back()].index()][v.end.value().index()];
                                               ^
utils/helpers.h: In function 'vroom::Route vroom::utils::format_route(const vroom::Input&, const vroom::TWRoute&, std::unordered_set<short unsigned int>&)':
utils/helpers.h:415:53: error: 'const struct vroom::Vehicle' has no member named 'end'
         : (v.has_end()) ? m[previous_job.index()][v.end.value().index()] : 0;
                                                     ^
utils/helpers.h:477:13: error: 'const struct vroom::Vehicle' has no member named 'start'
       ? m[v.start.value().index()][input.jobs[tw_r.route[0]].index()]
             ^
utils/helpers.h:509:44: error: 'const struct vroom::Vehicle' has no member named 'start'
     steps.emplace_back(STEP_TYPE::START, v.start.value(), current_load);
                                            ^
utils/helpers.h:530:13: error: 'const struct vroom::Vehicle' has no member named 'start'
       ? m[v.start.value().index()][input.jobs[tw_r.route[0]].index()]
             ^
utils/helpers.h:644:52: error: 'const struct vroom::Vehicle' has no member named 'end'
       ? m[input.jobs[tw_r.route.back()].index()][v.end.value().index()]
                                                    ^
utils/helpers.h:701:42: error: 'const struct vroom::Vehicle' has no member named 'end'
     steps.emplace_back(STEP_TYPE::END, v.end.value(), current_load);
                                          ^
makefile:53: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by valerivp** [comment]
vroom/src# make
/bin/sh: 1: pkg-config: not found
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDEBUG -c main.cpp -o main.o
In file included from ./structures/vroom/job.h:16:0,
                 from ./structures/vroom/solution/solution.h:15,
                 from problems/vrp.h:13,
                 from main.cpp:19:
./structures/typedefs.h:36:34: error: 'optional' in namespace 'std' does not name a template type
 using OptionalCoordinates = std::optional<Coordinates>;
                                  ^
In file included from ./structures/vroom/job.h:18:0,
                 from ./structures/vroom/solution/solution.h:15,
                 from problems/vrp.h:13,
                 from main.cpp:19:
./structures/vroom/location.h:22:3: error: 'OptionalCoordinates' does not name a type
   OptionalCoordinates _coords;
   ^
In file included from structures/vroom/input/input.h:24:0,
                 from main.cpp:22:
./structures/vroom/vehicle.h:25:8: error: 'optional' in namespace 'std' does not name a template type
   std::optional<Location> start;
        ^
./structures/vroom/vehicle.h:26:8: error: 'optional' in namespace 'std' does not name a template type
   std::optional<Location> end;
        ^
./structures/vroom/vehicle.h:34:22: error: 'optional' in namespace 'std' does not name a template type
           const std::optional<Location>& start,
                      ^
./structures/vroom/vehicle.h:34:30: error: expected ',' or '...' before '<' token
           const std::optional<Location>& start,
                              ^
In file included from main.cpp:24:0:
utils/helpers.h: In function 'vroom::Gain vroom::utils::addition_cost(const vroom::Input&, const vroom::Matrix<unsigned int>&, vroom::Index, const vroom::Vehicle&, const std::vector<short unsigned int>&, vroom::Index)':
utils/helpers.h:109:29: error: 'const struct vroom::Vehicle' has no member named 'start'
         previous_cost = m[v.start.value().index()][job_index];
                             ^
utils/helpers.h:112:36: error: 'const struct vroom::Vehicle' has no member named 'end'
         next_cost = m[job_index][v.end.value().index()];
                                    ^
utils/helpers.h:119:26: error: 'const struct vroom::Vehicle' has no member named 'end'
         auto n_index = v.end.value().index();
                          ^
utils/helpers.h:131:26: error: 'const struct vroom::Vehicle' has no member named 'start'
         auto p_index = v.start.value().index();
                          ^
utils/helpers.h: In function 'vroom::Gain vroom::utils::addition_cost(const vroom::Input&, const vroom::Matrix<unsigned int>&, vroom::Index, const vroom::Vehicle&, const std::vector<short unsigned int>&, vroom::Index, vroom::Index)':
utils/helpers.h:173:39: error: 'const struct vroom::Vehicle' has no member named 'end'
         after_delivery = m[d_index][v.end.value().index()];
                                       ^
utils/helpers.h:174:44: error: 'const struct vroom::Vehicle' has no member named 'end'
         remove_after_pickup = m[p_index][v.end.value().index()];
                                            ^
utils/helpers.h: In function 'vroom::Cost vroom::utils::route_cost_for_vehicle(const vroom::Input&, vroom::Index, const std::vector<short unsigned int>&)':
utils/helpers.h:213:19: error: 'const struct vroom::Vehicle' has no member named 'start'
       cost += m[v.start.value().index()][input.jobs[route.front()].index()];
                   ^
utils/helpers.h:223:53: error: 'const struct vroom::Vehicle' has no member named 'end'
       cost += m[input.jobs[route.back()].index()][v.end.value().index()];
                                                     ^
utils/helpers.h: In function 'vroom::Solution vroom::utils::format_solution(const vroom::Input&, const RawSolution&)':
utils/helpers.h:297:46: error: 'const struct vroom::Vehicle' has no member named 'start'
       steps.emplace_back(STEP_TYPE::START, v.start.value(), current_load);
                                              ^
utils/helpers.h:301:13: error: 'const struct vroom::Vehicle' has no member named 'start'
         m[v.start.value().index()][input.jobs[route.front()].index()];
             ^
utils/helpers.h:360:44: error: 'const struct vroom::Vehicle' has no member named 'end'
       steps.emplace_back(STEP_TYPE::END, v.end.value(), current_load);
                                            ^
utils/helpers.h:362:47: error: 'const struct vroom::Vehicle' has no member named 'end'
         m[input.jobs[route.back()].index()][v.end.value().index()];
                                               ^
utils/helpers.h: In function 'vroom::Route vroom::utils::format_route(const vroom::Input&, const vroom::TWRoute&, std::unordered_set<short unsigned int>&)':
utils/helpers.h:415:53: error: 'const struct vroom::Vehicle' has no member named 'end'
         : (v.has_end()) ? m[previous_job.index()][v.end.value().index()] : 0;
                                                     ^
utils/helpers.h:477:13: error: 'const struct vroom::Vehicle' has no member named 'start'
       ? m[v.start.value().index()][input.jobs[tw_r.route[0]].index()]
             ^
utils/helpers.h:509:44: error: 'const struct vroom::Vehicle' has no member named 'start'
     steps.emplace_back(STEP_TYPE::START, v.start.value(), current_load);
                                            ^
utils/helpers.h:530:13: error: 'const struct vroom::Vehicle' has no member named 'start'
       ? m[v.start.value().index()][input.jobs[tw_r.route[0]].index()]
             ^
utils/helpers.h:644:52: error: 'const struct vroom::Vehicle' has no member named 'end'
       ? m[input.jobs[tw_r.route.back()].index()][v.end.value().index()]
                                                    ^
utils/helpers.h:701:42: error: 'const struct vroom::Vehicle' has no member named 'end'
     steps.emplace_back(STEP_TYPE::END, v.end.value(), current_load);
                                          ^
makefile:53: recipe for target 'main.o' failed
make: *** [main.o] Error 1

**Comment by sashakh** [comment]
Hi,

On Thu, Dec 10, 2020 at 3:12 PM valerivp <notifications@github.com> wrote:

> vroom/src# make
>

It is not necessary to build as root.

/bin/sh: 1: pkg-config: not found
>

sudo apt-get install pkg-config


> g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE
> -DNDEBUG -c main.cpp -o main.o
> In file included from ./structures/vroom/job.h:16:0,
> from ./structures/vroom/solution/solution.h:15,
> from problems/vrp.h:13,
> from main.cpp:19:
> ./structures/typedefs.h:36:34: error: 'optional' in namespace 'std' does
> not name a template type
> using OptionalCoordinates = std::optional;
> ^
>

Regarding this I'm not sure, but likely you are running on some old version
of Ubuntu (with old g++). Just upgrade OS to latest and greatest (20.04 LTS
for example).

Sasha

**Comment by valerivp** [comment]
Nothing has changed in principle

make
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -c main.cpp -o main.o
In file included from ./structures/vroom/job.h:16:0,
                 from ./structures/vroom/solution/solution.h:15,
                 from problems/vrp.h:13,
                 from main.cpp:19:
./structures/typedefs.h:36:34: error: ‘optional’ in namespace ‘std’ does not name a template type
 using OptionalCoordinates = std::optional<Coordinates>;
                                  ^
In file included from ./structures/vroom/job.h:18:0,
                 from ./structures/vroom/solution/solution.h:15,
                 from problems/vrp.h:13,
                 from main.cpp:19:
./structures/vroom/location.h:22:3: error: ‘OptionalCoordinates’ does not name a type
   OptionalCoordinates _coords;

**Comment by valerivp** [comment]
I can update the system on the VM, but on the server - I can't do this

**Comment by valerivp** [comment]
Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-178-generic x86_64)

**Comment by sashakh** [comment]
On Thu, Dec 10, 2020, 19:33 valerivp <notifications@github.com> wrote:

> Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-178-generic x86_64)
>

I've got the same problem with 16.04. The upgrade (I wanted to upgrade for
many reasons) solved the problem.

Sasha

**Comment by jcoupey** [comment]
In order to drop a boost dependency, we've switched to using `std::optional` which is a thing as of C++17 (see `-std=c++17` compile flag).

My guess is that your compiler does not have (full) support for C++17, what compiler/version are you using?

If this is the case, updating the compiler may be an alternative to updating the whole system.

**Comment by sashakh** [comment]
Hi Guys,

On Thu, Dec 10, 2020, 20:40 Julien Coupey <notifications@github.com> wrote:

> If this is the case, updating the compiler may be an alternative to
> updating the whole system.
>

16.04 LTS end of life is scheduled on 2021 April 30. It is less than 5
months from now. So or so the upgrade is likely should be in your plans. )

Sasha

**Comment by nilsnolde** [comment]
> std::optional

So, were STD's mandatory in < C++17?*

<sub>first and last time I ever make any std joke esp in an issue tracker.. sorry, couldn't hold myself :joy: </sub>

**Comment by valerivp** [comment]
https://gist.github.com/jlblancoc/99521194aba975286c80f93e47966dc5

**Comment by jcoupey** [comment]
@valerivp does this means you solved the problem by upgrading your gcc version? In that case, please close the ticket.
