### ISSUE TITLE
Annotations in routing engine OSRM

### ISSUE THREAD

**Issue by wzuqui** [VROOM-Project/vroom#410]
Hello, I was wondering if there is any way to access the annotations in the OSRM routing engine. Which is available in the project-osrm: [OSRM API Doc](http://project-osrm.org/docs/v5.23.0/api/#route-service)

**Comment by jcoupey** [comment]
No, not out of the box. When all routes are decided, we fire [a routing request](https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/routing/http_wrapper.cpp#L193-L199) in `HttpWrapper::add_route_info`. Then we populate the solution with `distance` and `geometry` information, but nothing else is retained in output.

The rationale behind not providing more output is that we're mostly interested in route orders with ETA, not detailed route information. Also several routing engines have different outputs so it would not be easy to present this in a generic way.

If you badly need annotations, your options are:

- alter the existing code to add OSRM annotations in the response;
- send extra routing requests to OSRM after optimization is completed, based on the ordering of routes waypoints VROOM suggested.

**Comment by wzuqui** [comment]
thanks, i really believe i will have to send extra routing requests to OSRM

**Comment by jcoupey** [comment]
> send extra routing requests to OSRM

Then you may also consider removing the `-g` flag for `vroom` in order to skip the embedded route requests if you duplicate them later. Note that this will strip out `geometry` and `distance` keys in output.
