### ISSUE TITLE
How to allow the length of goods?

### ISSUE THREAD

**Issue by valerivp** [VROOM-Project/vroom#412]
How to describe the limitation for a machine and a product that the length of the product should be less than the length of the machine? Those. goods with a length of 6m cannot be transported in a car with a length of 4m

**Comment by jcoupey** [comment]
From the docs: "*Use skills to describe a problem where not all tasks can be served by all vehicles*".

**Comment by valerivp** [comment]
How to use the more-less skills? I realized that skills are all about entering all elements of the delivery array into the car array. Those. should I describe vehicle skills as [0, 1, 2, 3, 4, 5, 6] and delivery skills as [4]?

**Comment by jcoupey** [comment]
The way you describe skills is up to you, we use a simple integer model to leave room for custom modelling.

Basically, you want to put skills on jobs that cannot be served by all vehicles, then only matching vehicles should hold that same skill.

You can combine several skills values, keeping in mind that *a job can only be served by a vehicle that has all its required skills*, so you're doing a conjunction of constraints.
