### ISSUE TITLE
Why arrival not in timewindow?

### ISSUE THREAD

**Issue by valerivp** [VROOM-Project/vroom#414]
What am I doing wrong?
![2020-12-14_01-18-44](https://user-images.githubusercontent.com/28062383/102025837-9301c200-3dab-11eb-896a-00b93c47a41d.png)
query: [q.txt](https://github.com/VROOM-Project/vroom/files/5685643/q.txt)
result: [r.txt](https://github.com/VROOM-Project/vroom/files/5685644/r.txt)

**Comment by braktar** [comment]
The jobs, pickup and deliveries expect a set of Time windows, where the vehicle only consider only one time window

Use the key word `time_windows` instead of `time_window` for these objects. It should fix your issue
