### ISSUE TITLE
geometry field in response

### ISSUE THREAD

**Issue by alfredorico** [VROOM-Project/vroom#423]
Hi, greetings.
In  json response, what is geometry field for? How could I draw it?

Thanks a lot

**Comment by jcoupey** [comment]
Polyline encoding is explained [here](https://developers.google.com/maps/documentation/utilities/polylinealgorithm). You'll have to use a dedicated library to decode it, this is language-dependent. For example in javascript, there's https://www.npmjs.com/package/@mapbox/polyline.

**Comment by JakobMiksch** [comment]
in OpenLayers you can use [ol.format.Polyline](https://openlayers.org/en/v4.6.5/apidoc/ol.format.Polyline.html)

**Comment by jcoupey** [comment]
@JakobMiksch thanks, that's good to know, I wasn't aware of this.

@alfredorico please close this ticket if you don't have follow-up questions on the geometry field.

**Comment by alfredorico** [comment]
Thanks to every body for your comments. I'm gonna to close this ticket.
