### ISSUE TITLE
Time_windows with relative values

### ISSUE THREAD

**Issue by alfredorico** [VROOM-Project/vroom#424]
Hi, greetings.

I have doubts about time_windows with relative values. When documentation said "_[0, 14400] for a 4 hours time window starting at the beginning of the planning horizon"_ What is the meaning of "planning horizon" ?. Could you provide some more examples?.
As I do interpret, [0, 14400], it could be either "12:00 am to 4:00 am (from any day)" or  "has an availability of 4 hours of service which will be decremented by service job/shippment duration" ¿?
Suppose that _time_windows_ object is like that: [14400, 21600], what is its meaning of this range?

Thank you very much.

**Comment by NasserEspari** [comment]
Hi

I use this method,
00:00 => 0 (0 * 3600)
01:00 => 3,600 (1 * 3600)
......
04:00 => 14,400 (4 * 3600)
......
12:00 => 43,200 (12 * 3600)
......
16:00 => 57,600 (16 * 3600)

**Comment by jcoupey** [comment]
Here "planning horizon" simply stands for whatever time you choose as start of the operations. If you model a day-long problem with 0 as day start, then [0, 14400] translates to "between 0:00 and 4:00AM". But you could also decide that for your use-case the planning horizon starts at 8:00, so then [0, 14400] would translate to "between 8:00 and 12:00".

This is really a matter of taste, you simply want to use something that won't be limiting for your use-case, and of course make sure all timings a provided in a consistent way in input.

**Comment by jcoupey** [comment]
Closing as answered.
