### ISSUE TITLE
Vehicle capacity is not working.

### ISSUE THREAD

**Issue by swapnil-rampwin** [VROOM-Project/vroom#431]
we have a vehicle routing problem saying that the driver should pickup the items from warehouse and deliver them to their respective delivery addresses, for that i used the below mentioned json depicting about vehicle and shipments:

`{
  "vehicles": [
    {
      "id": 1,
      "profile":"driving-car",
      "start": [
        46.765446,
        24.612661
      ],
      "end": [
        46.765446,
        24.612661
      ],
      "capacity": [
        6
      ],
      "skills": [
        1
      ]
    },
    {
      "id": 2,
      "profile":"driving-car",
      "start": [
        46.765446,
        24.612661
      ],
      "end": [
        46.765446,
        24.612661
      ],
      "capacity": [
          6
      ],
      "skills": [
          2
      ]
    },
    {
      "id": 3,
      "profile":"driving-car",
      "start": [
        46.765446,
        24.612661
      ],
      "end": [
        46.765446,
        24.612661
      ],
      "capacity": [
          6
      ],
      "skills": [
        1,
        2
      ]
    }
  ],
"shipments":[
    {
        "amount":[1],
        "skills":[1],
        "priority":1,
        "pickup": {
            "id":1,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery": {
            "id":1,
            "service":300,
            "location":[
                46.8413059257316,
                24.7432809748658
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup": {
            "id":2,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":2,
            "service":300,
            "location":[
                46.6972928020657,
                24.6013788631059
            ]
        }
    },
    {
        "amount":[1],
        "skills":[1],
        "priority":1,
        "pickup":{
            "id":3,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":3,
            "service":300,
            "location":[
                46.6972928020657,
                24.6013788631059
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":4,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":4,
            "service":300,
            "location":[
                46.6965107004641,
                24.6583786547553
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":5,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":5,
            "service":300,
            "location":[
                46.8190007162079,
                24.6466335846897
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":6,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":6,
            "service":300,
            "location":[
                46.744499679242,
                24.6399244365295
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":7,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":7,
            "service":300,
            "location":[
                46.756000990998,
                24.8214121198607
            ]
        }
    },
    {
        "amount":[1],
        "skills":[1],
        "priority":1,
        "pickup":{
            "id":8,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":8,
            "service":300,
            "location":[
                46.81435509064,
                24.7601171999042
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":9,
            "location":[
                46.58198255,
                24.68785388
            ]
            },
        "delivery":{
            "id":9,
            "service":300,
            "location":[
                46.820717329908,
                24.684073369904
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":10,
            "location":[
                46.6992928,
                24.60137886
            ]
        },
        "delivery":{
            "id":10,
            "service":300,
            "location":[
                46.6504078012834,
                24.8241959901836
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":11,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":11,
            "service":300,
            "location":[
                46.7613517940957,
                24.7783579705136
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":12,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":12,
            "service":300,
            "location":[
                46.8065062382404,
                24.8845528790746
            ]
        }
    },
    {
        "amount":[1],
        "skills":[1],
        "priority":1,
        "pickup":{
            "id":13,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":13,
            "service":300,
            "location":[
                46.7084288374723,
                24.795328828012
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":14,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":14,
            "service":300,
            "location":[
                46.6836667220367,
                24.7243443561005
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":15,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":15,
            "service":300,
            "location":[
                46.661844727475,
                24.5902967649126
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":16,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":16,
            "service":300,
            "location":[
                46.744156356502,
                24.6235401191171
            ]
        }
    },
    {
        "amount":[1],
        "skills":[1],
        "priority":1,
        "pickup":{
            "id":17,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":17,
            "service":300,
            "location":[
                46.6802679993087,
                24.8347715870648
            ]
        }
    },
    {
        "amount":[1],
        "skills":[2],
        "priority":1,
        "pickup":{
            "id":18,
            "location":[
                46.58198255,
                24.68785388
            ]
        },
        "delivery":{
            "id":18,
            "service":300,
            "location":[
                46.8341408497397,
                24.6577772746006
            ]
        }
    }
]
}`

**The result which i am getting is :**

`{
    "code": 0,
    "summary": {
        "cost": 21074,
        "unassigned": 0,
        "delivery": [
            18
        ],
        "amount": [
            18
        ],
        "pickup": [
            18
        ],
        "service": 5400,
        "duration": 21074,
        "waiting_time": 0,
        "computing_times": {
            "loading": 129,
            "solving": 25
        }
    },
    "unassigned": [],
    "routes": [
        {
            "vehicle": 1,
            "cost": 7743,
            "delivery": [
                5
            ],
            "amount": [
                5
            ],
            "pickup": [
                5
            ],
            "service": 1500,
            "duration": 7743,
            "waiting_time": 0,
            "steps": [
                {
                    "type": "start",
                    "location": [
                        46.765446,
                        24.612661
                    ],
                    "load": [
                        0
                    ],
                    "arrival": 0,
                    "duration": 0
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 3,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 3,
                    "load": [
                        1
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 13,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 13,
                    "load": [
                        2
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 17,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 17,
                    "load": [
                        3
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 8,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 8,
                    "load": [
                        4
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 1,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 1,
                    "load": [
                        5
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "delivery",
                    "location": [
                        46.6802679993087,
                        24.8347715870648
                    ],
                    "id": 17,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 17,
                    "load": [
                        4
                    ],
                    "arrival": 3057,
                    "duration": 3057
                },
                {
                    "type": "delivery",
                    "location": [
                        46.7084288374723,
                        24.795328828012
                    ],
                    "id": 13,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 13,
                    "load": [
                        3
                    ],
                    "arrival": 4110,
                    "duration": 3810
                },
                {
                    "type": "delivery",
                    "location": [
                        46.8413059257316,
                        24.7432809748658
                    ],
                    "id": 1,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 1,
                    "load": [
                        2
                    ],
                    "arrival": 5483,
                    "duration": 4883
                },
                {
                    "type": "delivery",
                    "location": [
                        46.81435509064,
                        24.7601171999042
                    ],
                    "id": 8,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 8,
                    "load": [
                        1
                    ],
                    "arrival": 6391,
                    "duration": 5491
                },
                {
                    "type": "delivery",
                    "location": [
                        46.6972928020657,
                        24.6013788631059
                    ],
                    "id": 3,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 3,
                    "load": [
                        0
                    ],
                    "arrival": 8014,
                    "duration": 6814
                },
                {
                    "type": "end",
                    "location": [
                        46.765446,
                        24.612661
                    ],
                    "load": [
                        0
                    ],
                    "arrival": 9243,
                    "duration": 7743
                }
            ]
        },
        {
            "vehicle": 2,
            "cost": 13331,
            "delivery": [
                13
            ],
            "amount": [
                13
            ],
            "pickup": [
                13
            ],
            "service": 3900,
            "duration": 13331,
            "waiting_time": 0,
            "steps": [
                {
                    "type": "start",
                    "location": [
                        46.765446,
                        24.612661
                    ],
                    "load": [
                        0
                    ],
                    "arrival": 0,
                    "duration": 0
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 15,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 15,
                    "load": [
                        1
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 4,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 4,
                    "load": [
                        2
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 11,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 11,
                    "load": [
                        3
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 12,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 12,
                    "load": [
                        4
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 7,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 7,
                    "load": [
                        5
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 14,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 14,
                    "load": [
                        6
                    ],
                    "arrival": 1417,
                    "duration": 1417
                },
                {
                    "type": "delivery",
                    "location": [
                        46.661844727475,
                        24.5902967649126
                    ],
                    "id": 15,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 15,
                    "load": [
                        5
                    ],
                    "arrival": 2801,
                    "duration": 2801
                },
                {
                    "type": "pickup",
                    "location": [
                        46.6992928,
                        24.60137886
                    ],
                    "id": 10,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 10,
                    "load": [
                        6
                    ],
                    "arrival": 3432,
                    "duration": 3132
                },
                {
                    "type": "delivery",
                    "location": [
                        46.6965107004641,
                        24.6583786547553
                    ],
                    "id": 4,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 4,
                    "load": [
                        5
                    ],
                    "arrival": 3896,
                    "duration": 3596
                },
                {
                    "type": "delivery",
                    "location": [
                        46.6836667220367,
                        24.7243443561005
                    ],
                    "id": 14,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 14,
                    "load": [
                        4
                    ],
                    "arrival": 4867,
                    "duration": 4267
                },
                {
                    "type": "delivery",
                    "location": [
                        46.7613517940957,
                        24.7783579705136
                    ],
                    "id": 11,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 11,
                    "load": [
                        3
                    ],
                    "arrival": 5981,
                    "duration": 5081
                },
                {
                    "type": "delivery",
                    "location": [
                        46.756000990998,
                        24.8214121198607
                    ],
                    "id": 7,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 7,
                    "load": [
                        2
                    ],
                    "arrival": 7139,
                    "duration": 5939
                },
                {
                    "type": "delivery",
                    "location": [
                        46.8065062382404,
                        24.8845528790746
                    ],
                    "id": 12,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 12,
                    "load": [
                        1
                    ],
                    "arrival": 8279,
                    "duration": 6779
                },
                {
                    "type": "delivery",
                    "location": [
                        46.6504078012834,
                        24.8241959901836
                    ],
                    "id": 10,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 10,
                    "load": [
                        0
                    ],
                    "arrival": 9900,
                    "duration": 8100
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 5,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 5,
                    "load": [
                        1
                    ],
                    "arrival": 11598,
                    "duration": 9498
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 18,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 18,
                    "load": [
                        2
                    ],
                    "arrival": 11598,
                    "duration": 9498
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 6,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 6,
                    "load": [
                        3
                    ],
                    "arrival": 11598,
                    "duration": 9498
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 16,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 16,
                    "load": [
                        4
                    ],
                    "arrival": 11598,
                    "duration": 9498
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 2,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 2,
                    "load": [
                        5
                    ],
                    "arrival": 11598,
                    "duration": 9498
                },
                {
                    "type": "pickup",
                    "location": [
                        46.58198255,
                        24.68785388
                    ],
                    "id": 9,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 9,
                    "load": [
                        6
                    ],
                    "arrival": 11598,
                    "duration": 9498
                },
                {
                    "type": "delivery",
                    "location": [
                        46.6972928020657,
                        24.6013788631059
                    ],
                    "id": 2,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 2,
                    "load": [
                        5
                    ],
                    "arrival": 12927,
                    "duration": 10827
                },
                {
                    "type": "delivery",
                    "location": [
                        46.744156356502,
                        24.6235401191171
                    ],
                    "id": 16,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 16,
                    "load": [
                        4
                    ],
                    "arrival": 13618,
                    "duration": 11218
                },
                {
                    "type": "delivery",
                    "location": [
                        46.744499679242,
                        24.6399244365295
                    ],
                    "id": 6,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 6,
                    "load": [
                        3
                    ],
                    "arrival": 14203,
                    "duration": 11503
                },
                {
                    "type": "delivery",
                    "location": [
                        46.820717329908,
                        24.684073369904
                    ],
                    "id": 9,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 9,
                    "load": [
                        2
                    ],
                    "arrival": 15325,
                    "duration": 12325
                },
                {
                    "type": "delivery",
                    "location": [
                        46.8341408497397,
                        24.6577772746006
                    ],
                    "id": 18,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 18,
                    "load": [
                        1
                    ],
                    "arrival": 15854,
                    "duration": 12554
                },
                {
                    "type": "delivery",
                    "location": [
                        46.8190007162079,
                        24.6466335846897
                    ],
                    "id": 5,
                    "service": 300,
                    "waiting_time": 0,
                    "job": 5,
                    "load": [
                        0
                    ],
                    "arrival": 16468,
                    "duration": 12868
                },
                {
                    "type": "end",
                    "location": [
                        46.765446,
                        24.612661
                    ],
                    "load": [
                        0
                    ],
                    "arrival": 17231,
                    "duration": 13331
                }
            ]
        }
    ]
}`

i want to know why the capacity constraint for vehicles is not working, in the solution vehicle 2 is going to 13 
but i have fixed it to 6, please help

**Comment by jcoupey** [comment]
The capacity of a vehicle is not about the number of tasks or total deliveries on a route, it's about making sure the vehicle load does not exceed the capacity at any time during the route.

Because you're picking up and delivering stuff along the route, you can check that actual **load** never goes above 6 in your solution, as expected.

**Comment by swapnil-rampwin** [comment]
okay! is there any way where we can fix the capacity for every vehicle let's say vehicle 1 should deliver maximum 10 packages per day and minimum 1 package per day? is it possible?

**Comment by jcoupey** [comment]
That would be #421.

**Comment by swapnil-rampwin** [comment]
Hi @jcoupey  
Our use case is :
 What we have 
1. 3 warehouses, 
2. 4 drivers and 
3.  20 packages to be delivered which would be picked from these warehouses, 

The knowledge we have:
1. Package pickup(warehouse) and delivery location.
2. Capacity constraint of every vehicle.
3. Skills of driver what they can deliver what not.
4. Priority of item 

The current optimization API offers the routing but How do I make a assignment to driver sot that they pick up items from a single warehouse ?

**Comment by jcoupey** [comment]
You can tie vehicles to a given warehouse using skills, by using the same value in `shipment.skills` and `vehicle.skills`.

**Comment by jcoupey** [comment]
Closing as answered.
