### ISSUE TITLE
vroom-front is drawing a different result that gotted from curl to api solver 

### ISSUE THREAD

**Issue by alfredorico** [VROOM-Project/vroom#434]
Hi to everyone 

I'm crazy about this. With following curl, I'm obtain just one route with one vehicle to all jobs. But with vroom-front, either locally or on http://map.vroom-project.org/,  I'm getting for the same json input a totally different result. More vehicles assigned and a more congruent result. Why this is happening? How curl must be made?

`curl --header "Content-Type:application/json" \
--data '
{
  "vehicles": [
    {
      "id": 160279,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    ,        {
      "id": 207203,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    ,        {
      "id": 208661,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    ,        {
      "id": 210939,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    ,        {
      "id": 212060,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    ,        {
      "id": 226729,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    ,        {
      "id": 229885,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    ,        {
      "id": 238218,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    ,        {
      "id": 242299,
      "start": [
        -70.6692655,
        -33.4488897
      ],
      "end": [
        -70.6692655,
        -33.4488897
      ],
      "skills": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    } 
    
  ],
  "jobs": [
    {
      "id": 1,
      "service": 60,
      "priority": 1,
      "description": "5ca61059fffbe907c7ff2a05",
      "location": [-70.639389, -33.445908],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 2,
      "service": 60,
      "priority": 1,
      "description": "5ca61063fffbe907c7ff2c4d",
      "location": [-70.686888, -33.465036],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 3,
      "service": 60,
      "priority": 1,
      "description": "5ca61065fffbe907c7ff2cad",
      "location": [-70.641386, -33.472273],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 4,
      "service": 60,
      "priority": 1,
      "description": "5ca61415fffbe907ceff2be0",
      "location": [-70.62592, -33.4701],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 5,
      "service": 60,
      "priority": 1,
      "description": "5ca61422fffbe907ceff2eb8",
      "location": [-70.64043, -33.45793],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 6,
      "service": 60,
      "priority": 1,
      "description": "5ca61423fffbe907ceff2ed8",
      "location": [-70.65381, -33.43774],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 7,
      "service": 60,
      "priority": 1,
      "description": "5ca7e687fffbe91aec570892",
      "location": [-70.63017741, -33.47063651],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 8,
      "service": 60,
      "priority": 1,
      "description": "5ca7e68afffbe91aec570932",
      "location": [-70.66178164, -33.44362397],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 9,
      "service": 60,
      "priority": 1,
      "description": "5ca7e68cfffbe91aec570992",
      "location": [-70.73595066, -33.45203064],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 10,
      "service": 60,
      "priority": 1,
      "description": "5ca7e68efffbe91aec5709fa",
      "location": [-70.6739033333333, -33.4414489523809],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 11,
      "service": 60,
      "priority": 1,
      "description": "5ca7e693fffbe91aec570b12",
      "location": [-70.67806421, -33.44933778],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 12,
      "service": 60,
      "priority": 1,
      "description": "5ca7e693fffbe91aec570b16",
      "location": [-70.63941171, -33.44318221],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 13,
      "service": 60,
      "priority": 1,
      "description": "5ca7e695fffbe91aec570b6a",
      "location": [-70.6237323, -33.45607754],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 14,
      "service": 60,
      "priority": 1,
      "description": "5ca7e699fffbe91aec570c46",
      "location": [-70.6387267, -33.44081703],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 15,
      "service": 60,
      "priority": 1,
      "description": "5ca7e6a6fffbe91aec570ef6",
      "location": [-70.66871422, -33.4522563],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 16,
      "service": 60,
      "priority": 1,
      "description": "5ca7e6b4fffbe91aec5711ce",
      "location": [-70.66836356, -33.47217796],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 17,
      "service": 60,
      "priority": 1,
      "description": "5ca7e6c3fffbe91aec5714c6",
      "location": [-70.6302209, -33.4585844],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 18,
      "service": 60,
      "priority": 1,
      "description": "5ca7e6c7fffbe91aec571592",
      "location": [-70.65266975, -33.47027694],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 19,
      "service": 60,
      "priority": 1,
      "description": "5ca7e6cafffbe91aec571632",
      "location": [-70.63395392, -33.44146709],
      "skills": [
        1
      ]
      
    }
    ,        {
      "id": 20,
      "service": 60,
      "priority": 1,
      "description": "5ca7e6cbfffbe91aec571666",
      "location": [-70.67810548, -33.45289622],
      "skills": [
        1
      ]
      
    }
    
  ],
  "options": {
    "g": true
  }      
}' \
http://solver.vroom-project.org | jq`

**Comment by braktar** [comment]
Hello

vroom-frontend add a capacity constraint in order to demonstrate the capability of vroom instead of what even if multiple vehicles are defined, only one would be used. 

https://github.com/VROOM-Project/vroom-frontend/blob/3009301f44c466723b8e2f1f4dd5b032729c6b84/src/utils/solution_handler.js#L18

**Comment by jcoupey** [comment]
That would be my first guess too. I'll add that you can use your browser dev tools to check the exact request sent by the frontend and check the differences.

**Comment by jcoupey** [comment]
@alfredorico did the answers solve your problem? If so please close this ticket.

**Comment by alfredorico** [comment]
Thanks to everybody!. Essentially this line in vroom-from does the trick.
`var C = Math.ceil(1.2 * input.jobs.length / input.vehicles.length);`
