### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#436]
I've been lazily avoiding this for a while, but we're now past the official deadline for travis-ci.org shutdown. The support period has probably been somehow extended as the current build setup still works.

But things will eventually break so the move to travis-ci.com should be taken care of. My understanding of https://docs.travis-ci.com/user/migrate/open-source-repository-migration is that the move should not really change anything on our side, including still being able to use the service for free as an open-source project.

**Comment by braktar** [comment]
travis-ci.com has recently changed its billing policy, which is extremely restrictive (1,000 seconds per month) and the quality of the service is variable.

Github actions still provides a comfortable free credit for for public repositories (2,000 minutes per month).

**Comment by jcoupey** [comment]
Ah well, I was hoping to migrate without having to change too much stuff but then it looks like we'll have to make the switch.

Adjusting the current yaml config to migrate to GitHub Actions is probably not that big a deal. But since I have virtually no experience on the matter I'd gladly take views from anyone that has tried it already!

**Comment by jcoupey** [comment]
My overall feeling about CI for this repo is that triggering a build for each push in a PR branch is basically a waste of resources. That's bad, even when using a free service. We don't have an instant deployment workflow justifying to do this, and in most situations we really just need a build check upon reviewing a PR or tagging releases, maybe merge to `master`.

I took a closer look on the GA workflows/event concepts and the variety of ways to trigger CI builds. This may make it possible to have a convenient way to trigger builds only when we want to. Ideas (not sure what would be the most convenient):

- manually;
- when a review is done;
- when a specific string appears in a PR comment;
- when a dedicated label is applied;
- using a specific git tag (mandatory for releases).

**Comment by jcoupey** [comment]
In the meantime, I've made the switch to travis-ci.com. I removed older gcc and clang version checks so we're left we 2 checks out of 4 (gcc 8 and clang 6).

The 2 resulting builds (one from #451 and one from the `master` merge) seemed to consume only 90 of 10000 credits so we should be rather safe for the time being.

**Comment by jcoupey** [comment]
Update: my understanding of the Travis plans is that "Free" comes with a **one time** allocation of 10 000 credits. On the other hand, there is a concept of "OSS only credits" that are monthly renewable and might be fine for this project.

I've sent an email to Travis support based on [this FAQ](https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source). If this works out and we can keep the builds on Travis with the current setup, I'll close this ticket and forget about GitHub Actions for the time being.

**Comment by jcoupey** [comment]
OK, trying a last move toward Travis before deciding whether we should move to GitHub Actions. https://twitter.com/VroomProject/status/1372836419702562818

Maybe Travis does not care about losing projects like us. This is totally fine, I just wish they'd  acknowledge this upfront so we could save time.

**Comment by jcoupey** [comment]
Landed with #517.
