### ISSUE TITLE
Fix json file input example

### ISSUE THREAD

**Issue by negrettem** [VROOM-Project/vroom#437]
In the example you have time_window like this: time_window: [], please update because after reading here in the issues you said the syntax is time_windows: [[ ]] and this is actually working. 

Your work is amazing!!

Congrats

**Comment by jcoupey** [comment]
This is probably intended: vehicles have a single working hours slot, and tasks have a set of possible time slots. See `vehicle.time_window` and `job.time_windows` keys descriptions in the docs.
