### ISSUE TITLE
Work balance for 2 vehicles is not similar

### ISSUE THREAD

**Issue by cbeltrangomez84** [VROOM-Project/vroom#445]
Hi, I need to split a route with 10 packages using Steps (10 pickups, 10 deliveries), pickups in this case are all in the same location (warehouse) and deliveries are different points in the city.

The solving vroom process is giving me one route for vehicle A with 9 pickups and 9 deliveries, a distance of 53781, a duration of 4205 and a cost of 4205, and for vehicle B only 1 pickup and 1 deliver, a duration of 496, distance of 7351 and a cost of 496.

This solve is not balancing the work between the 2 vehicles, am I doing something wrong or there is something not working in vroom.

This is the [json](https://carlosbeltran.co/workBalance.json) used for the request:

Thanks a lot.

**Comment by jcoupey** [comment]
Two good news here: you're doing nothing wrong, and there is nothing wrong on the solving side either. What happens is probably that the solution you get is simply "cheaper" than a more balanced one.

We don't take work balance into account while solving, the optimization objective is (currently) overall travel duration.

If you want to get more balanced routes, you may consider:

- using capacity restrictions to limit the number of tasks per route (will only totally work when using jobs);
- waiting for #421 to handle a max number of tasks per vehicle with shipments;
- limiting total route length using time windows.

**Comment by cbeltrangomez84** [comment]
Thanks a lot, @jcoupey

**Comment by jcoupey** [comment]
You're welcome, please close this ticket if you think the question is fully answered.
