### ISSUE TITLE
Constraint order of existing jobs

### ISSUE THREAD

**Issue by tomjakobs1** [VROOM-Project/vroom#447]
Is there a way to constraint the order of existing jobs, and optimize with trying to put new jobs in between the existing ones?

Thanks

Tom

**Comment by jcoupey** [comment]
No, we don't have a convenient way to add constraints describing a pre-defined job ordering. Could you provide a bit of context to help understand your use-case more in-depth?

**Comment by tomjakobs1** [comment]
Example: 
A driver has a set of jobs defined, that we dont want to reorder. If a new job comes in we want to put it on the driver and optimize it so it could be executed before, in between or after the jobs he allready have. But the order of the original jobs must be locked.

**Comment by jcoupey** [comment]
> put it on the driver and optimize it

Did you actually try this scenario? Of course you'd have no guarantee on keeping the order, but if you don't have fancy constraints, I'd expect the new optimization step to do exactly just that in most cases: provide a similar solution with a new job somewhere in the middle.

A good starting point might be to evaluate how often this does not work out that way.

**Comment by tomjakobs1** [comment]
It seems like when using steps on vehicle, it does not assign orders that is not in the steps array on vehicles. It return all others as unassigned:

Here is a problem json:
{
    "vehicles": [
        {
            "id": 294,
            "start": [
                11.019075214862823,
                59.99520119118417
            ],
            "capacity": [],
            "skills": [],
            "time_window": [
                1612249200,
                1612278000
            ],
            "steps": [
                {
                    "type": "start"
                },
                {
                    "type": "job",
                    "id": 4689
                },
                {
                    "type": "job",
                    "id": 4699
                }
            ]
        }
    ],
    "options": {
        "c": true
    },
    "jobs": [
        {
            "id": 4689,
            "skills": [],
            "location": [
                11.00564,
                59.9480323
            ],
            "delivery": []
        },
        {
            "id": 4699,
            "skills": [],
            "location": [
                11.019075214862823,
                59.99520119118417
            ],
            "delivery": []
        },
        {
            "id": 4718,
            "skills": [],
            "location": [
                10.744665552195166,
                59.91241927211811
            ],
            "delivery": []
        }
    ],
    "shipments": [
        {
            "amount": [],
            "skills": [],
            "pickup": {
                "id": 4708,
                "service": 300,
                "location": [
                    11.019075214862823,
                    59.99520119118417
                ]
            },
            "delivery": {
                "id": 4709,
                "service": 300,
                "location": [
                    10.7361028,
                    59.91458960000001
                ]
            }
        },
        {
            "amount": [],
            "skills": [],
            "pickup": {
                "id": 4715,
                "service": 300,
                "location": [
                    11.019075214862823,
                    59.99520119118417
                ]
            },
            "delivery": {
                "id": 4716,
                "service": 300,
                "location": [
                    11.0191661,
                    59.9927362
                ]
            }
        },
        {
            "amount": [],
            "skills": [],
            "pickup": {
                "id": 4733,
                "service": 300,
                "location": [
                    10.8691856,
                    59.1046444
                ]
            },
            "delivery": {
                "id": 4734,
                "service": 300,
                "location": [
                    10.7361028,
                    59.91458960000001
                ]
            }
        }
    ]
}


AND THE Solution:
{
    "code": 0,
    "summary": {
        "cost": 1369,
        "unassigned": 7,
        "service": 0,
        "duration": 1369,
        "waiting_time": 0,
        "priority": 0,
        "violations": [],
        "computing_times": {
            "loading": 362,
            "solving": 0
        }
    },
    "unassigned": [
        {
            "id": 4718,
            "location": [
                10.744665552195166,
                59.91241927211811
            ]
        },
        {
            "id": 4708,
            "location": [
                11.019075214862824,
                59.99520119118417
            ]
        },
        {
            "id": 4709,
            "location": [
                10.7361028,
                59.914589600000017
            ]
        },
        {
            "id": 4715,
            "location": [
                11.019075214862824,
                59.99520119118417
            ]
        },
        {
            "id": 4716,
            "location": [
                11.0191661,
                59.9927362
            ]
        },
        {
            "id": 4733,
            "location": [
                10.8691856,
                59.1046444
            ]
        },
        {
            "id": 4734,
            "location": [
                10.7361028,
                59.914589600000017
            ]
        }
    ],
    "routes": [
        {
            "vehicle": 294,
            "cost": 1369,
            "service": 0,
            "duration": 1369,
            "waiting_time": 0,
            "priority": 0,
            "steps": [
                {
                    "type": "start",
                    "location": [
                        11.019075214862824,
                        59.99520119118417
                    ],
                    "service": 0,
                    "waiting_time": 0,
                    "arrival": 1612249200,
                    "duration": 0,
                    "violations": []
                },
                {
                    "type": "job",
                    "location": [
                        11.00564,
                        59.9480323
                    ],
                    "id": 4689,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 4689,
                    "arrival": 1612249880,
                    "duration": 680,
                    "violations": []
                },
                {
                    "type": "job",
                    "location": [
                        11.019075214862824,
                        59.99520119118417
                    ],
                    "id": 4699,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 4699,
                    "arrival": 1612250569,
                    "duration": 1369,
                    "violations": []
                },
                {
                    "type": "end",
                    "location": [
                        11.019075214862824,
                        59.99520119118417
                    ],
                    "service": 0,
                    "waiting_time": 0,
                    "arrival": 1612250569,
                    "duration": 1369,
                    "violations": []
                }
            ],
            "violations": []
        }
    ]
}

**Comment by jcoupey** [comment]
You're making things a bit confusing here as this ticket was initially about ordering while solving and you seem to be using the `plan` mode in you last comment.

> It seems like when using steps on vehicle, it does not assign orders that is not in the steps array on vehicles. It return all others as unassigned:

That's expected because if you supply vehicle steps, you are responsible for deciding what gets included in what order. The rest is *de facto* not assigned.

**Comment by jcoupey** [comment]
Closing as stale.
