### ISSUE TITLE
Multiple Jobs same location, one service-time

### ISSUE THREAD

**Issue by tezmanian** [VROOM-Project/vroom#456]
Hi, first of all thanks for this great tool.

Is it possible to set a service duration per location and not per task? Why? I've 10 jobs at the same location with different quantities but they don't fit in one vehicle so two or three vehicles are needed. If i add service duration to a task it is added task for task if more then one task is done at the loaction by one vehicle. But I need to say we need 15 minutes for location and not for task. Is there a way, I've not found yet?

**Comment by jcoupey** [comment]
Thanks for your feedback.

No, we don't have a way to do this right now. The same kind of need has been reported in #358 which is flagged as a feature request. I'm closing this as a duplicate to keep the discussion in one place, feel free to step in there to mention your use-case!
