### ISSUE TITLE
Priority for vehicles

### ISSUE THREAD

**Issue by stefanocudini** [VROOM-Project/vroom#458]
it could be interesting to introduce a _priority_ parameter associated also with each **vehicle** in such a way as to use some vehicles more.

or to make sure to use the entire fleet of vehicles in the same time between one solution and the next solution.

in a real use case it could improve the maintenance cost of the fleet of vehicles

**Comment by senhalil** [comment]
If I am not mistaken, there is already a ticket for this feature request https://github.com/VROOM-Project/vroom/issues/359

I suspect the vehicle dependent "costs" (#394, #336) might be of use achieving your goal once they are ready.
