### ISSUE TITLE
Combination Inputfile (-i parameter) with strict ending point (-e parameter) not working?

### ISSUE THREAD

**Issue by PattyDePuh** [VROOM-Project/vroom#46]
Hey everyone,
just heard of the framework few days ago and its nice to see an opensource TSP-solution, that actually beats my current internal creation by 10% better results.
Today i've been trying out the 1.0 release candidate branch and found it quite curious, that the roundtrip result and the strict end result "with -e Parameter" were the same, if you load a custom cost-matrix instead of using OSRM:
used Sample: [http://elib.zib.de/pub/mp-testdata/tsp/tsplib/tsp/swiss42.tsp](http://elib.zib.de/pub/mp-testdata/tsp/tsplib/tsp/swiss42.tsp)
Output for the default roundtrip:
' /vroom/bin$ ./vroom -i ../swiss42.tsp.txt ' 
> `{"routes":[{"steps":[{"type":"start","job":0},{"type":"job","job":32},{"type":"job","job":34},{"type":"job","job":33},{"type":"job","job":20},{"type":"job","job":35},{"type":"job","job":36},{"type":"job","job":31},{"type":"job","job":17},{"type":"job","job":7},{"type":"job","job":37},{"type":"job","job":15},{"type":"job","job":16},{"type":"job","job":14},{"type":"job","job":19},{"type":"job","job":13},{"type":"job","job":5},{"type":"job","job":26},{"type":"job","job":18},{"type":"job","job":12},{"type":"job","job":11},{"type":"job","job":25},{"type":"job","job":10},{"type":"job","job":8},{"type":"job","job":9},{"type":"job","job":41},{"type":"job","job":23},{"type":"job","job":40},{"type":"job","job":24},{"type":"job","job":21},{"type":"job","job":39},{"type":"job","job":22},{"type":"job","job":38},{"type":"job","job":30},{"type":"job","job":29},{"type":"job","job":28},{"type":"job","job":27},{"type":"job","job":2},{"type":"job","job":3},{"type":"job","job":4},{"type":"job","job":6},{"type":"job","job":1},{"type":"end","job":0}],"cost":1273,"vehicle":0}],"solution":{"computing_times":{"loading":3,"solving":0},"cost":1273},"code":0}`

And with the strict end flag:
`/vroom/bin$ ./vroom -i ../swiss42.tsp.txt -e`
> `{"routes":[{"steps":[{"type":"start","job":0},{"type":"job","job":32},{"type":"job","job":34},{"type":"job","job":33},{"type":"job","job":20},{"type":"job","job":35},{"type":"job","job":36},{"type":"job","job":31},{"type":"job","job":17},{"type":"job","job":7},{"type":"job","job":37},{"type":"job","job":15},{"type":"job","job":16},{"type":"job","job":14},{"type":"job","job":19},{"type":"job","job":13},{"type":"job","job":5},{"type":"job","job":26},{"type":"job","job":18},{"type":"job","job":12},{"type":"job","job":11},{"type":"job","job":25},{"type":"job","job":10},{"type":"job","job":8},{"type":"job","job":9},{"type":"job","job":41},{"type":"job","job":23},{"type":"job","job":40},{"type":"job","job":24},{"type":"job","job":21},{"type":"job","job":39},{"type":"job","job":22},{"type":"job","job":38},{"type":"job","job":30},{"type":"job","job":29},{"type":"job","job":28},{"type":"job","job":27},{"type":"job","job":2},{"type":"job","job":3},{"type":"job","job":4},{"type":"job","job":6},{"type":"job","job":1},{"type":"end","job":0}],"cost":1273,"vehicle":0}],"solution":{"computing_times":{"loading":0,"solving":0},"cost":1273},"code":0}`

where i thought, that the step with job-id 41 should be at the end on the second output.

I have hardly looked through the code by now; Maybe it isn't implemented yet. Maybe i don't know good enough, how to use VROOM properly. But it sure is a thing to mention and look up.

**Comment by jcoupey** [comment]
Hi, thanks for your input and interest!

The wiki usage section still describes the last stable tagged version on `master`, which is quite old now. The  `-s` and `-e` flags are now deprecated, start and end should be specified in input in the `vehicle` object. See `vroom -h` for valid flags.

I'm waiting until #41 is merged to tag v1.0.0 and update the wiki. To avoid this kind of offset in the doc, the API is now described [in the docs folder](https://github.com/VROOM-Project/vroom/tree/release-v1.0.0/docs).

Hope this makes things more clear and solves your problem!

**Comment by jcoupey** [comment]
Sorry, the above link is for json input. If you use TSPLIB format and wish to force an open trip starting at the first place, you can add a specific keyword:
```
START: 0
```

This can be used in conjonction with an `END` tag to force the end of the trip to some other place.

**Comment by PattyDePuh** [comment]
thanks for the informing.
I'm not particulary interested to load TSPLIB instances into vroom, but custom matrices in general.
Like putting an double interleaved array right next to the "vehicle" and "job" leaves in the JSON-object and using the identifiers to assign the locations/jobs/vehicles to the associated indizes, rows and columns of the matrix.
But that shall be another issue/feature, i could tackle by myself and provide if desired.

Have a nice weekend

**Comment by jcoupey** [comment]
As you figured out, for now the easiest (actually only) way to use a custom matrix is to use TSPLIB format.

Maybe allowing custom matrix in the json input might be useful. As you say, we have to be careful how this would be done (how jobs and vehicles are associated with matrix indices). Feel free to open another ticket to discuss this.

Another way to use your own matrix computing scheme would be to create your own loader (see [loaders](https://github.com/VROOM-Project/vroom/tree/release-v1.0.0/src/loaders)). Inherit from `problem_io` or maybe even `osrm_loader` and implement your own `get_matrix` function.
