### ISSUE TITLE
ORS lack of turn restrictions affect optimizations?

### ISSUE THREAD

**Issue by jaimevives** [VROOM-Project/vroom#465]
Hi:

First of all, thanks for your great work. I've installed vroom-docker and it all works like a charm. I'm still a newbie on all this, but after trying some optimizations and viewing the routes on the ORS maps, I found that ORS directions don't respect turn restrictions. My question is, how does this affect VROOM optimizations? 

Regards,

**Comment by nilsnolde** [comment]
Ha, excellent point! If I remember correctly turn restrictions are respected for matrices (which uses a different algo than standard routing). The new standard algo being used (C-ALT) can't do that yet, e.g. https://github.com/GIScience/openrouteservice/issues/807. 

So, yes, that is indeed a problem I think. One can force ORS to not use the C-ALT algorithm (e.g. by requesting alternates as the issue above), but I guess @sfendrich can say more about that, he's still working in that project. Then vroom could issue the routing request with an additional option to bypass C-ALT, at least for the time being.

**Comment by jaimevives** [comment]
> Ha, excellent point! If I remember correctly turn restrictions are respected for matrices (which uses a different algo than standard routing). The new standard algo being used (C-ALT) can't do that yet, e.g. [GIScience/openrouteservice#807](https://github.com/GIScience/openrouteservice/issues/807).
> 

  Ah... Ok, thanks for the info. I guessed it did affect the matrices too, because the times where the same, but I suppose that for the short routes I was trying it didn't make any difference in travel times.

> So, yes, that is indeed a problem I think. One can force ORS to not use the C-ALT algorithm (e.g. by requesting alternates as the issue above), but I guess @sfendrich can say more about that, he's still working in that project. Then vroom could issue the routing request with an additional option to bypass C-ALT, at least for the time being.

  Yes, requesting alternate route seems to do the trick. I also found that in some cases the problem isn't ORS, but OpenStreetMap not having the particular turn restriction.

  Thanks again...

**Comment by nilsnolde** [comment]
> I guessed it did affect the matrices too

That's very possible, I'm really not sure anymore.. But would be very crucial information. If no TR are respected in matrix, then we're lucky right now, but it's been an issue for a long time when CH was used respecting TR. Either way, you maybe best ask in the ORS repo about TR in matrix: https://github.com/GIScience/openrouteservice/issues.

**Comment by aoles** [comment]
Currently turn restrictions in ORS public API are only obeyed once the option `avoid_polygons` to avoid certain areas is enabled which triggers the A* with beeline distance approximation routing algorithm. We are well aware of the current limitations. In fact, we have finished implementing support for turn restrictions with CoreALT routing algorithm just recently and @star-pirate is about to submit a PR introducing this feature. If things go smooth we hope to release it over the next weeks. Turn restrictions with our efficient matrix algorithm (RPHAST) are still missing, however, over the next few months we will be working on integrating them as well so stay tuned!

I'm not sure what is the exact config of vroom requests is though, but maybe @sfendrich can take it from here? Cheers!

**Comment by sfendrich** [comment]
Optimization uses the matrix endpoint, i.e., RPHAST at the current public ORS-API. The geometry computation uses the directions endpoint, i.e., CALT. As detailed by @aoles above, both currently do not respect turn restrictions.

**Comment by nilsnolde** [comment]
Thanks a bunch @aoles , very informative as always:) Well, in that case, it's currently alright (for vroom..), both matrix and routing don't respect turn restrictions, so it should be consistent. But then it's been wrong initially.. ah well, no need to dwell on the past.

But since you're here @aoles: the ORS documentation seems to suggest that `continue_straight` is not available for `driving-*` profiles (important for vroom to enable u-turns).. If it's not settable by the user, what's the current default for those profiles?

**Comment by aoles** [comment]
Thanks @nilsnolde!

There has been an ongoing debate around `continue_straight`, see https://github.com/GIScience/openrouteservice/issues/176. At some point we decided to remove this parameter from the driving profiles. The reason for this it was that it requires the ability to set the bearing which is not supported by algorithms performant enough to do long distance routing such as CH and CALT. ALT which supports bearings is slower and much more memory-intensive so we are moving away from it, and A* without landmarks is just to slow. Nevertheless, at the time being the "recommended" cycling profile falls back to ALT if bearings are provided, but we might discontinue building the landmarks for it as well for the sake of reducing memory requirements. Back to u-turns: the current behavior is to compute route segments between the via points independently. This might result in a u-turn or not depending on whichever route is faster/shorter. If the cost matrix is obtained from the `matrix` endpoint there is no control over u-turns in first place, so I don't think `continue_straight` is of relevance to the optimization endpoint anyway - or am I missing sth?

**Comment by nilsnolde** [comment]
Thanks for the explanation @aoles !

> the current behavior is to compute route segments between the via points independently.

Didn't know that.. Then it's u-turn enabled I'd say;) Question is exactly for `via` points actually, sorry, should've clarified (also I had a wrong assumption in mind).. Since matrix doesn't have `via` points, the routes calculated from the matrix endpoint (in the context of optimization) are inherently u-turn enabled. And vroom returns info about the route taken for each vehicle after the optimization, which should match the sum of the durations/distances returned from the matrix service and have the most probable geometry.

**Comment by jcoupey** [comment]
@aoles you're right there is no notion of u-turns for the matrix endpoint.

VROOM does the optimization based on the matrix only, then once all routes are decided, it fires route requests to retrieve the actual geometry and additional info such as leg distances. The rationale behind allowing u-turns for those route requests is to make sure all travel times are consistent with what we have in the initial matrix request.

**Comment by aoles** [comment]
> Didn't know that.. Then it's u-turn enabled I'd say;) Question is exactly for `via` points actually, sorry, should've clarified (also I had a wrong assumption in mind).. Since matrix doesn't have `via` points, the routes calculated from the matrix endpoint (in the context of optimization) are inherently u-turn enabled. And vroom returns info about the route taken for each vehicle after the optimization, which should match the sum of the durations/distances returned from the matrix service and have the most probable geometry.

That's correct, u-turns at via points are permitted. At the moment I expect the results computed by the matrix endpoint to match the routes generated by directions. However, once turn restrictions are introduced to directions there might be a transition phase until we have a similar solution for matrix during which the output between the two endpoints will differ. (CC @HendrikLeuschner)

**Comment by jcoupey** [comment]
Closing as stale.
