### ISSUE TITLE
type vehicles profile

### ISSUE THREAD

**Issue by JonasESEO** [VROOM-Project/vroom#468]
Hello, 
In Vehicle's properties, there is a key about the profile with default value is car. I didn't find wich kind of profile can we have ? Heavy weight ? motorbike ? bike ?
What will be the difference in the output ? Duration ? Capacity ?
Can we have several vehicles with different profile ? For example, use a motorbike and car ? 

Thank you.
regards, 
Jonas

**Comment by jcoupey** [comment]
You can use any profile value at the `vroom` level, you simply have to make sure they match with something that the underlying routing layer will understand.

The difference is that we'll internally use different travel time matrices to decide on travel costs and timing constraints validity for routes.

> Can we have several vehicles with different profile ? For example, use a motorbike and car ?

That would be #394, which is currently under development.
