### ISSUE TITLE
mark single shipment_steps as already done

### ISSUE THREAD

**Issue by haraldkofler** [VROOM-Project/vroom#472]
Is it possible to optimize a partially executed shipment?

### example:
- A shipment exists of 4 shipment_steps
- the first step is finished - so I would like to mark this step, and preserve its sequence position, only 2-4 should be optimized

Is there already a way to achieve this behavior?

Thanks and best regards

**Comment by jcoupey** [comment]
Can you be a bit more specific about the context: it looks like you're trying to update a plan once part of the route has already been handled, is that correct?

**Comment by haraldkofler** [comment]
Yes, that's correct!

Basically vroom has optimized a shipment route with several steps. After executing some of the steps, a new shipment_step should be inserted. The whole shipment route should now be re-optimized, considering that the sequence of the already finished steps can not be modified anymore.

For the moment I worked around by setting the location of the already finished steps to the start location, so they will always be the first ones.

**Comment by jcoupey** [comment]
If you're launching a new round of optimization to update the plan, you'll want to use the current vehicle position as start location.

Now if a shipment has been fully completed, you can remove it altogether from the next optimization round. If a shipment consist of pickup `p` that has been performed and delivery `d` that is yet to handle, then the amount to be delivered there is already loaded at vehicle startup. So you can simply turn `d` into a `job` object with a `delivery` key holding the shipment amount.

**Comment by jcoupey** [comment]
Closing as answered.
