### ISSUE TITLE
probleme routing with bicycle profile

### ISSUE THREAD

**Issue by JonasESEO** [VROOM-Project/vroom#473]
Hi, 
I'm trying to execute Vroom with an other profile. 
I extracted OSRM-backend with new profile(bicycle), there is no error and i can run server OSRM.
Then when i execute Vroom with input example_1.json 

`./bin/vroom -a bicycle:0.0.0.0  -i example_1.json -o result.json`

I've got an error that vroom doesn't recognize the profile. 

`[Error] Invalid profile: car.`

Did I have something wrong in the run command ? Did i miss something ? Is there any file i have to modify for vroom can consider a bicycle profil and not car profile ? 

Thank you
Jonas

**Comment by jcoupey** [comment]
What you describe using `-a` and `-p` is the configuration of available servers at `vroom` level and you can actually use `-a` several times to point to various profiles/servers. For example if you have two OSRM instances running on different ports, you could pass this information as `vroom -a bicycle:0.0.0.0 -p bicycle:5000 -a car:0.0.0.0 -p car:5001`.

Now you still need to specify what profile you want to use upon solving using the `profile` key for vehicles in your input problem.

If you omit the key, the profile defaults to "car" and on the other hand defining a specific profile using `-a` also erases the default `vroom` server list ("car" pointing to OSRM on `0.0.0.0:5000`).

**Comment by JonasESEO** [comment]
Thank you for your answer.
I'm not an expert so i have some difficulties to understand.

If i understand correctly, the profile in the command option is useful just in case of multiple use. The profile have to be add in the json file input. Like this example.

`"vehicles": [
    {
      "id": 1,
      "profile": [
	"bicycle"
      ],
      "start": [
        2.35044,
        48.71764
      ],
      "end": [
        2.35044,
        48.71764
      ],
      "capacity": [
        4
      ],
      "skills": [
        1,
        14
      ],
      "time_window": [
        1600416000,
        1600430400
      ]
    }
]`

Can you confirm ? If i run this command `./bin/vroom -i example_1.json -o result.json` Vroom will take the profile write into account ?

**Comment by jcoupey** [comment]
You have to use `"profile": "bicycle" ` as the expected value is a string, not an array.

**Comment by jcoupey** [comment]
Feel free to close once this is working for you.
