### ISSUE TITLE
moving job

### ISSUE THREAD

**Issue by stefanocudini** [VROOM-Project/vroom#474]
hi @jcoupey 

I come up with an interesting use case for VROOM.
I was trying to figure out if shipments can be useful for my use case:

I need the vehicle to move an object from point A to point B(for more objects)

then for the same job, first the pickup in a point A and then the delivery in a point B is carried out

(this use case is the movement of a person over a bus)

how can i define this operation?
using a shipment that has pickup and delivery with the same ID, or can I solve with a job?

**Comment by jcoupey** [comment]
This sounds like a typical situation where you would use shipments. The `pickup` and `delivery` keys of a `shipment` objects are quite similar to a `job` (except for common values moved up to the shipment level). They're convenient to model a situation where you have to move something or someone from A to B, because they force both tasks to happen in the same route and in the right order.

**Comment by stefanocudini** [comment]
tnks, 
I had guessed that shipments are the right way, looking at some of the examples problems here:
https://github.com/VROOM-Project/vroom/blob/master/docs/example_1.json#L124
```json
"shipments": [
    {
      "amount": [
        1
      ],
      "skills": [
        2
      ],
      "pickup": {
        "id": 4,
        "service": 300,
        "location": [
          2.41808,
          49.22619
        ]
      },
      "delivery": {
        "id": 3,
        "service": 300,
        "location": [
          2.39719,
          49.07611
        ]
      }
    }
  ]
```
@jcoupey 
it is not clear to me how I can define point A and point B for the same object to be moved(I suppose with same ID)

I see belowe the IDs are different in this case, so it is not the same object to move.
in the documentation it is indicated
"An error is reported if two job objects have the same id."

I can't quite understand how I can define the displacement from point A to point B for a single object

**Comment by jcoupey** [comment]
If it does not make sense to use different ids for the pickup and delivery tasks, yes you can use the same id. What is required is that the `(task type, id)` pair is unique, so no two jobs can have the same id, not two pickups can have the same id etc.

**Comment by stefanocudini** [comment]
> If it does not make sense to use different ids for the pickup and delivery tasks, yes you can use the same id. What is required is that the `(task type, id)` pair is unique, so no two jobs can have the same id, not two pickups can have the same id etc.

in this way should plan the movement of a single object(id 3) from point A to point B?

```json
"shipments": [
    {
      "amount": [ 1 ],
      "pickup": {
        "id": 3,
        "location":  A 
      },
      "delivery": {
        "id": 3,
        "location": B
      }
    }
  ]
```

**Comment by jcoupey** [comment]
Yes, then you'll get the same id in output in the different route step objects, but (on top of ordering) you can differentiate them with their `type` key, either `pickup` or `delivery`.

**Comment by stefanocudini** [comment]
this seems to work as I expected, thanks for the clarification
