### ISSUE TITLE
Add `computing_times` specifications to API docs

### ISSUE THREAD

**Issue by wesleimp** [VROOM-Project/vroom#480]

**Comment by jcoupey** [comment]
There are a couple reasons why the `computing_times` key are not part of the API:

1. Computing times as they are measured do not convey any information on the solution itself, rather a glimpse of how the internal solving process behaves. Also they're really versatile, depending on CPU, threads etc.
2. They're here mostly for debugging/benchmarking.

It does not mean you can't rely on them to some extent for monitoring. But if for some reason we want to change the way they're reported, I don't want to be tied to a schema that would require a breaking change in version (we use semantic versioning).
