### ISSUE TITLE
Break location

### ISSUE THREAD

**Issue by stefanocudini** [VROOM-Project/vroom#483]
would it be possible to introduce a location parameter for the breaks? in addition to the _time_windows_

or can it be solved in some other way in defining input problem in the current version?

this would also be very useful in real cases:
very often the drivers of the vehicles are forced to take breaks only in specific places (for example bus sheds or specific parking lots)

what I would expect in the solution output is that if there are waiting_time between one job (in my case a shipment) and the next, the system will show me the way to the break position (obviously if this path is shorter than the waiting_time)

**Comment by jcoupey** [comment]
A break with a location is a geolocated task, so you can model it with a `job` object. You simply need to make sure it is assigned to the right vehicle, this can be achieved using `skills`.

**Comment by stefanocudini** [comment]
I would basically like to replace the waiting time with breaks located(only if waiting_time exists in solution)

but only if there are long waiting times between one ship and the next ship/job.

what you propose with jobs I believe requires running vroom in two time:

1 time to understand which and how long and exists the waiting_times
2 time repeat the same problem with the addition of geo-localized "job-breaks"

**Comment by jcoupey** [comment]
If you know in advance the location and time (constraints) for a break, then you can describe it as a job. If you want to replace some existing waiting time, it sounds more like a post-processing task once you have a solution.

**Comment by stefanocudini** [comment]
my basic case study is that the vehicles cannot wait in the location defined in the shipments/jobs (these are buses on the road)

so I would like the vehicle to return to its start (or another predefined location ) in the case of a fairly large waiting_time

**Comment by stefanocudini** [comment]
an alternative could be
a new property of the vehicle after: _start_,_end_ named _break_location_ which indicates a predefined location where the vehicle performs its breaks

but I think it makes more sense to add the location property to the break definition

**Comment by jcoupey** [comment]
The purpose of `break` objects as they are defined is precisely to hold the notion of an idle time in the middle of a route *without* a location known in advance. That's because in some situations we want the break location to be derived from the rest of the plan (think "stop for 1 hour wherever you are").

> but I think it makes more sense to add the location property to the break definition

How would that be different from defining a job?

**Comment by stefanocudini** [comment]
could it be part of a future implementation for vehicles a multiple **time_windowS**?
 ```time_windows = [[start1,end1], [start2,end2], [], ...]```
for vehicles like as shipment_step and breaks?

**Comment by jcoupey** [comment]
I can't think of a situation where the current breaks syntax would fall short while modelling start and end times with a list of vehicle time windowS would bring extra possibilities. Do you have an example in mind?

That would also impose very strong time constraints whereas breaks allow for a much greater flexibility as they can be shifted earlier or later depending on their own time window and the time constraints on surrounding tasks.

**Comment by jcoupey** [comment]
Closing as answered.
