### ISSUE TITLE
Unrelated pickups / deliveries with precedence constraints

### ISSUE THREAD

**Issue by leobudima** [VROOM-Project/vroom#486]
Hi, I am having trouble wrapping my head around a particular problem:

- vehicle is empty, and has capacity 1
- there are pickup locations where it needs to pick up items (job with pickup set to 1)
- there are locations where it needs to drop items (job with delivery set to 1), but it can, naturally, only do so if it has previously been to a pickup location

Any ideas on how this can be solved, since it seems that using shipments wouldn't work, as there are no particular pairs - any order of pickups / deliveries is fine, as long as there was any pickup before a delivery? My thoughts were around negative dimensions (no longer possible), or inverting the pickups and deliveries (pickup frees the capacity which delivery requires, but it would require vehicle to start "full")...

Another consideration is that, if there are more pickups than deliveries, the vehicle would use a depot as a delivery point, but that seems especially problematic.

Thank you!

**Comment by leobudima** [comment]
If anyone would find it useful, here's the progress in trying to model this so far:

- in order to ensure delivery comes after pickup, we have 1 constraint we can manipulate, the capacity - so if we invert the capacity logic, we can imagine that, in order to be able to do a delivery, the vehicle needs to have spare capacity that the "delivery" requires - so effectively, we are modeling the deliveries as jobs with pickup amount set to 1

-  that way, the vehicle can only do a delivery if its load is 0, which happens if it has visited a pickup, modeled as a job with delivery amount set to 1

- the problem with this is that vehicle load needs to be "full" at start of the route for this inverse logic to enforce the first stop to be a pickup (decreasing load)...

- since I don't see a way to specify initial state of vehicle load, we most likely need to take the closest pickup and fix it at the start of the route, only optimizing in Vroom the route that starts after that pickup. This will not be optimal looking at the whole picture of pickup/delivery locations, but I don't see another way of forcing pickup to come first in the route. If we would be able to somehow specify the initial state of load of the vehicle, it would also cover a case where there are more deliveries and pickups (mentioned below), and it's more optimal to do a delivery (item loaded at depot) first.

- this is all nice if there is an equal number of pickups and deliveries. However, if there are more pickups, the vehicle needs to deliver them to depot instead of next delivery location - to solve this, we can simply generate as many additional delivery jobs to depot as needed to make the number of pickups / deliveries even. Vice-versa for the case where there are more deliveries, with pickups being done from the depot

**Comment by jcoupey** [comment]
I don't really see a way to fully model this situation with the objects/constraints descriptions we have.

- you can't use shipments directly as you mentioned because that would require to decide pickup-delivery assignments prior to optimization;
- you can't use jobs with `delivery` and `pickup` keys because everything that is delivered (resp. picked up) in a route is implicitly considered loaded at route start (resp. brought back at route end).

**Comment by leobudima** [comment]
Thank you for your comment in any case! We decided that the above is too messy / compromised in terms of optimization, and not worthwhile pursuing. 

However, the idea of being able to specify the vehicle load at start of the route might be useful to other people and different use-cases in the future. 

Thanks again, closing :)

**Comment by jcoupey** [comment]
Another though on this one: you could actually start by finding a minimum weight perfect matching between your pickup/delivery location sets. That would be a way to decide how to associate pickup and delivery points beforehand, then solve as a regular problem with the matching shipments.

I don't think this would work out of the box if you have strong time window constraints though. For the record, we happen to have an in-house [implementation for Munkres](https://github.com/VROOM-Project/vroom/blob/e1fd84412847bd67b37a36a1fe10935db1e7873c/src/algorithms/munkres.h#L20-L22) algorithm to find a MWPM.
