### ISSUE TITLE
Create clients to make it easier to use

### ISSUE THREAD

**Issue by wesleimp** [VROOM-Project/vroom#488]
Common languages to implement

  - [x] Elixir - https://github.com/wesleimp/vroom-elixir
  - [x] PHP - https://github.com/webstacknl/vroom-php
  - [ ] Go
  - [ ] Rust
  - [x] C#
  - [ ] Java
  - [ ] Ruby
  - [ ] Javascript

**Comment by jcoupey** [comment]
First of all, thanks for sharing your work on the elixir wrapper with an open license. I hope this can help others get started on using the project from Elixir.

Having a list of third-party wrappers would definitely be helpful, I guess the best place for this would be to setup a dedicated page in the wiki.

**Comment by jcoupey** [comment]
I've setup a dedicated wiki page to list existing clients: https://github.com/VROOM-Project/vroom-express/wiki/Third-party-clients. It's located in the `vroom-express` repo since the various wrappers use the http interface.
