### ISSUE TITLE
[MacOS] Initial Setup Error - Failed to connect to OSRM

### ISSUE THREAD

**Issue by MohamedIhab** [VROOM-Project/vroom#493]
Hello, first of all I am very thankful for your efforts on such a project; it's truly impressive and it will help me a lot with a current project. 
I installed vroom on my MacOS using HomeBrew and when running over any input (vroom -i example1_.json) from example 1 file in the docs, it gives the following error:

```
[Error] Failed to connect to 0.0.0.0:5000
{"code":3,"error":"Failed to connect to 0.0.0.0:5000"}
```

I checked OSRM's github page and tried setting it up (assuming this was my problem) however it didn't run (not sure if I do need to setup OSRM apart from VROOM or it's already embedded within VROOM's installation?). On their page it's mentioned that currently the build fails for MacOS and Linux, so is the problem from their end?

I tried the same on an Ubuntu server and still received the same response.

Appreciate your support, thanks.

**Comment by jcoupey** [comment]
> however it didn't run (not sure if I do need to setup OSRM apart from VROOM or it's already embedded within VROOM's installation?)

The error you get is simply this: you don't have a working OSRM instance listening locally on port 5000. Setting up OSRM has to be done apart from VROOM, and you should run some test queries on your OSRM instance to make sure it's working independently from VROOM.

Closing as out of scope for this repo, you'll have more luck finding help on the OSRM-related channels.

**Comment by krypt-n** [comment]
You could try running example_2.json. The second example has an embedded distance matrix and does not require a connection to OSRM
