### ISSUE TITLE
speed_factor

### ISSUE THREAD

**Issue by vercom** [VROOM-Project/vroom#496]
Is vehicle speed_factor already implemented in latest docker version ?
I see no change in duration using this factor.

I would like to use this factor to correct duration or is there another way to correct duration with traffic information ?

**Comment by jcoupey** [comment]
The most up-to-date source for this kind of question is the changelog. The `speed_factor` change has an entry on `master` (https://github.com/VROOM-Project/vroom/blob/master/CHANGELOG.md) and [is available](https://github.com/VROOM-Project/vroom/blob/master/CHANGELOG.md) in the `release/v1.10` branch.

Now if you check the `vroom` version in the lastest stable Docker image, you'll see it's `v1.9.0` so this will only be available via Docker once a new image is built after the `v1.10.0` release is effective.

**Comment by jcoupey** [comment]
Now released and included in the latest Docker image.
