### ISSUE TITLE
VRP with custom capacity restrictions

### ISSUE THREAD

**Issue by ub-123** [VROOM-Project/vroom#499]
Hello,

First of all, great project, thanks for the hard work!

I wonder whether Vroom supports or will support more complex capacity definitions. As an example, we want to ship 4 types of products (A, B, C and D). And each vehicle has a configuration that defines how many elements of type A, B, C or D can fit on it.

I believe this is similar to the 3D-VRP in many ways (correct me if I'm wrong), where the check of whether something fits or not is not only dependant on a generic "capacity restriction" calculation, but instead relies on further knowledge about the vehicle being used, and what it's currently picked up, to decide whether the next delivery fits or not.

I don't see a way to make Vroom fit this use-case? I can think of something like this to accommodate for use-cases like this:

```
{
    "shipments": [
        {
            "pickup": {},
            "delivery": {},
            "type": 1
        },
        {
            "pickup": {},
            "delivery": {},
            "type": 2
        }
    ],
    "vehicles": [
        {
            "id": 1,
            "accepted_types": [
                [5, 2],
                [6, 0]
            ]
        }
    ]
}
```

In this case (and you may forget about the key names), we're assigning an ID to the shipment type (following the example above, product A is of type 1, and product B is of type 2, for example), and then we're defining a list of how many products of each type a vehicle may handle. This could be made into a more generic definition too. Basically, we're saying here that we may fit 5 type 1s and 2 type 2s in the vehicle, or 6 type 1s and no type 2s.

How do you feel about an addition like this @jcoupey? Do you think it may impact too much the current solution's performance? If not, and you see the value, would you be interested in me working on it (maybe if you provided some pointers)?

I believe it'd impact performance in a non-trivial way, right? For each path and pickup, you'd need to check all possible accepted types, making the problem much larger scope than it is at the moment? If so, is there any way to model something similar in Vroom?

Thank you.

**Comment by jcoupey** [comment]
You may try to take advantage of the `amount` values being described as arrays and use one component per element type. For example your vehicle would have `"capacity": [6,2]` and a shipment moving a type A (resp. B) element would have a `"amount": [1, 0]` (resp. `[0, 1]`).

I get it that this would not avoid a `[6, 2]` load but I have a feeling that if one type A element makes up for two type B elements, then there's probably another relevant metric that could be added (weight or volume?).

**Comment by ub-123** [comment]
Yea exactly my point was to avoid the `[6, 2]` issue, but you're right maybe I need to try to find another metric that'd help reducing the violations in the constraints I proposed. Thank you.
