### ISSUE TITLE
server installing problem

### ISSUE THREAD

**Issue by Akif95** [VROOM-Project/vroom#500]
Hi everyone,

I want to build a VROOM Server.

I followed the instructions. But when I execute the command I get an error stack.

`root@ip-172-31-19-230:~/vroom/src# make
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDE                                                                                                             BUG -D USE_LIBGLPK=true -c main.cpp -o main.o
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDE                                                                                                             BUG -D USE_LIBGLPK=true -c algorithms/munkres.cpp -o algorithms/munkres.o
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDE                                                                                                             BUG -D USE_LIBGLPK=true -c algorithms/kruskal.cpp -o algorithms/kruskal.o
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDE                                                                                                             BUG -D USE_LIBGLPK=true -c algorithms/local_search/operator.cpp -o algorithms/lo                                                                                                             cal_search/operator.o
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDE                                                                                                             BUG -D USE_LIBGLPK=true -c algorithms/local_search/local_search.cpp -o algorithm                                                                                                             s/local_search/local_search.o
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DNDE                                                                                                             BUG -D USE_LIBGLPK=true -c algorithms/validation/choose_ETA.cpp -o algorithms/va                                                                                                             lidation/choose_ETA.o
......

root@ip-172-31-19-230:~/vroom/src# root@ip-172-31-19-230:~/vroom/src# vroom
-bash: root@ip-172-31-19-230:~/vroom/src#: No such file or directory
root@ip-172-31-19-230:~/vroom/src# vroom: command not found
vroom:: command not found
root@ip-172-31-19-230:~/vroom/src# root@ip-172-31-19-230:~/vroom/src#
-bash: root@ip-172-31-19-230:~/vroom/src#: No such file or directory
`
The entire error stack is attached.

[stack_error.txt](https://github.com/VROOM-Project/vroom/files/6410147/stack_error.txt)

**Comment by krypt-n** [comment]
Hi,

vroom fails to compile since `-DNDE BUG` appears in the CXXFLAGS. The compiler looks for a file called `BUG`, which it cannot find. However I cannot figure out why this appears in your CXXFLAGS. Have you modified the makefile in any way?

**Comment by Akif95** [comment]
Hello, I have not done any updates on the make file.

**Comment by jcoupey** [comment]
There is definitely something weird going on with random spaces inserted. From your file:

```
-o algorithms/va lidation/choose_ETA.o
[...]
-o algorithms/heuri stics/solomon.o
[...]
-o problems/cvrp /operators/pd_shift.o
```

The valid matching files are `algorithms/validation/choose_ETA.o`, `algorithms/heuristics/solomon.o` and `problems/cvrp/operators/pd_shift.o` (no spaces in names).

**Comment by Akif95** [comment]
Thanks, Julien,

I tried reinstalling VROOM on a different server. This time I think there was no spaces issue. But despite this, the vroom command is not defined. 

The screenshots are below.

![Ekran Resmi 2021-05-03 14 13 04](https://user-images.githubusercontent.com/7771725/116896809-42491380-ac3d-11eb-9efa-8e3d2543aaac.png)


![Ekran Resmi 2021-05-03 14 14 05](https://user-images.githubusercontent.com/7771725/116896781-3e1cf600-ac3d-11eb-8949-507300549b06.png)

**Comment by krypt-n** [comment]
The vroom binary is created in the `bin` subdirectory. Try running `~/vroom/bin/vroom`

**Comment by Akif95** [comment]
> The vroom binary is created in the `bin` subdirectory. Try running `~/vroom/bin/vroom`

Unfortunately :(

![Ekran Resmi 2021-05-03 18 49 53](https://user-images.githubusercontent.com/7771725/116899741-9b667680-ac40-11eb-9fcb-9fef10c7554c.png)

**Comment by krypt-n** [comment]
Yes, it is not a directory, `~/vroom/bin/vroom/ is the vroom-executable.

You can try
```
cd ~/vroom/bin/
vroom -h
```
or
```
~/vroom/bin/vroom -h
```
(without cd'ing anywhere)

**Comment by Akif95** [comment]
Thank you very much, I'm not very good at these systems :) it worked.

**Comment by namanambavi** [comment]
> Yes, it is not a directory, `~/vroom/bin/vroom` is the vroom executable.
> 
> You can try
> 
> ```
> cd ~/vroom/bin/
> ./vroom -h
> ```
> 
> or
> 
> ```
> ~/vroom/bin/vroom -h
> ```
> 
> (without cd'ing anywhere)

Hi,
Can you please let me know how to run this as 'vroom -h' on ubuntu? It works fine when I use your command but I can't get it to work on 'vroom -h' directly. I understand it has something to do with $PATH but can you please guide?

**Comment by krypt-n** [comment]
Hi, this is not really a vroom related question.

You could add the `voom/bin` directory to your `PATH`:
https://askubuntu.com/questions/60218/how-to-add-a-directory-to-the-path?noredirect=1&lq=1

Or move the `vroom` executable to some place that is already in your `PATH`.
