### ISSUE TITLE
Vroom for pollster that makes surveys on schedules and geolocations

### ISSUE THREAD

**Issue by alfredorico** [VROOM-Project/vroom#501]
Hi,

I would like to know if vroom is a proper solution for our bussines model. Let me explain about it. We are a company with employees that make surveys of different kinds throughout city. For example we have clients (mainly banking institutions) that need to verify people asking for a new banking account, and check if they lives where they said that are living. Our pollster goes to person's house, talk with the person who needs verification, take some pictures, say goodbay and move to the next survey. Every survey could take no more than 30 minutes (it takes less time commonly). 
Most surveys must be done on schedule (specific day and time) and on specific location (lat, long). But another ones have a SLA, I mean, after requesting a survey, it must be done in 2, 3 or 4 days (SLA depends on kind of survey). Another ones must be done at whatever moment in the week on specific location (lat, long) but before sunday of current week. Another ones must be done at whatever moment on especific location (lat, long) but before end of current month.

Most pollster have a weekly schedule of availabities. For exmaple:
Jhon: 
  Monday 8am to 12pm / 4pm - 6pm
  Wensday 1pm to 5pm
  ... 
Maria
  Tuesday 9am to 3pm 
  ....
Etc
(whatever combination you could imagine, but always between 8am to 6pm) 
Another ones has no restriction of time (but always move between 8am to 6pm) 

We are in Chile, so we have pollster that only moves in certain communes, and another ones doesn't have commune restrictions

In general our model proposal for vroom is:

Vehicles: would be every pollster with "time_windows" mapping to personal schedule or without time_windows if doesn't have schedule restrictions.
We have a startting point (for every pollster). The ending point could be the same (or changed if pollster decide to overwrite it). But I don't know if could be better for vroom algorithm to setting just start point. Other than that, I would use skills to restrict pollster to certain communes.

Jobs: Every survey to do. Configured with time_windows vector matching its schedule. Setting location (lat, long) with survey info.

Some concerns:

- For pollster that only works in certain communes we could set a skill matching. The problem is that there are a lot of communes so for pollster that works everywhere, it require a vector with a lot of values (Am I right? That could be an issue? )
- For starting simple, ¿How could we planing a week?. is vroom able to organize per pollster a route that could take jobs on several days (schedule) and arranges in adequate days?
- For surveys with an SLA, is it correct to set a time_windows job with an interval over 24 hours?. For example if a survey must be done in no more than 2 days, then setting a time_windows with for example 72 hours interval, I wonder if vroom could arrange the route and setting an "arrival" value in output step with a proposed DateTime considering SLA ?. The idea is that vroom can say to pollster "For this survey (job) you can do it on Wednesday at 4pm (and survey due on Tuesday so to say)" along another jobs.
- Because of pollster works only from 8am to 6pm in a day (if doesn't have schedule) or with an schedule as described above. Do I must set breaks objects for every pollster on blocks from 6pm to 8am (night) ? (in the easiest of cases ). And what about pollster with schedules? (seems terrific to setting a lot of break objects) 

Please my apologize for the longer explanation and hoping your recomendations about it.

Greetings.

**Comment by jcoupey** [comment]
It's not easy (nor really the right place) to provide comprehensive feedback on a very specific use-case: the way you choose how to describe the optimization constraints is highly dependent on your own business logic. But from what I can tell you seem to have already come up with ways to translate that. Your best bet is to try and see whether the solutions fit your needs.

On the specific technical concerns:

1. Setting huge vectors for skills would not be a problem and would not add much overhead because we do [a single pass](https://github.com/VROOM-Project/vroom/blob/e1fd84412847bd67b37a36a1fe10935db1e7873c/src/structures/vroom/input/input.cpp#L432-L453) on those to store vehicle to jobs compatibility that can be efficiently used down the line.
2. You can definitely use breaks to model night rests and achieve planning on a week horizon. Note that in that case the night rest will happen "on the fly" at whatever location the vehicle is depending on previous/next jobs.

**Comment by alfredorico** [comment]
Thanks by your comments @jcoupey. 

Any comments about third point?. I think this is important for trying achieve a planing week. For example, a job with time_windows with for example 72 hours interval, vroom output assign a Timestamp on a specific day for the job to be done inside that interval? 

Thank you very much!...

**Comment by jcoupey** [comment]
I don't see any problem with translating SLA into various time windows. Whatever the reason behind setting time window constraints on tasks, you'll have the guarantee that any optimized task will match those constraints (or show up as unassigned).

**Comment by jcoupey** [comment]
Closing as answered.
