### ISSUE TITLE
Please an explanation about "matrices"

### ISSUE THREAD

**Issue by alfredorico** [VROOM-Project/vroom#504]
Hi, 

Could any one explain to me how to use "matrices" ? I don't understand what is for. What is the meaning of "duration" key and what represent the positions of array. 

```
"matrices": {
    "car": {
        "durations": [[0, 14], [21, 0]]
    },
    "bike": {
        "durations": [[0, 57], [43, 0]]
    }
}
```

Thanks in advance by your comments.

**Comment by jcoupey** [comment]
Using the `matrices` key only makes sense if you want to bypass the routing engine to retrieve the travel durations. In that case you have to provide directly yourself the values you'd like taken into account.

The above example simply means the travel duration between places with `location_index` 0 and 1 will be `matrices.car.durations[0][1] = 14` for a vehicle with `"profile": "car"` and  `matrices.car.durations[0][1] = 57` for a vehicle with `"profile": "bike"`.

**Comment by jcoupey** [comment]
@JonasESEO did you try running `vroom` on your latest example?
