### ISSUE TITLE
vroom/libvroom_examples/libvroom.cpp compiling error

### ISSUE THREAD

**Issue by toohes** [VROOM-Project/vroom#510]
vroom/libvroom_examples/libvroom.cpp(218,42): error C2664: 'vroom::Matrix<vroom::Cost>::Matrix(size_t)': cannot convert argument 1 from 'initializer list' to 'size_t'

**Comment by krypt-n** [comment]
Yep, seems like my recent changes to the Matrix class caused this. The linked pull request should fix the compilation error
