### ISSUE TITLE
max additional duration shipment

### ISSUE THREAD

**Issue by vercom** [VROOM-Project/vroom#520]
Hello,
is it possible to have a constraint on max additional duration while adding steps to a route.

e.g.   
max additional time = 10 minutes
 Passenger at position A  has destination  AIRPORT with direct time from A to AIRPORT  50 minutes
          If we pickup another passenger at POINT B I want to implement a restriction that   route A -> B -> AIRPORT won't take longer    than  60 minutes.

**Comment by jcoupey** [comment]
No, there is no way to define such a constraint directly. But depending on the situation you may be able to achieve the expected result by using time windows, either on the vehicle, or on pickup to A and/or delivery to the airport.
