### ISSUE TITLE
Does VROOM support gRPC?

### ISSUE THREAD

**Issue by CHOMNANP** [VROOM-Project/vroom#521]
I'm looking into integrate VROOM to my application. I'm looking for alternative option such gRPC rather https.
Do VROOM support gRPC?

**Comment by jcoupey** [comment]
No, we don't provide support for gRPC. There are already quite a few ways to use the project:

- as a standalone application with `vroom` system calls;
- from C++ (see https://github.com/VROOM-Project/vroom/blob/master/libvroom_examples/libvroom.cpp);
- using http (see also https://github.com/VROOM-Project/vroom-express/wiki/Third-party-clients).
