### ISSUE TITLE
Is it possible to generate route without providing drivers?

### ISSUE THREAD

**Issue by CHOMNANP** [VROOM-Project/vroom#523]
Hi, we're in a scenario where we would not consider about the driver location. We'd like to define the route first. Then we will assign the nearest driver later.

Let say we have 200 jobs in the city, then we want to know how many trip shall we use. Then we will assign nearest driver accordingly.

Does this doable in VROOM?

**Comment by jcoupey** [comment]
No, this is not possible but you can do something similar with open trip optimization by providing only a `start` or an `end` location per vehicle (at least one is required).

> Then we will assign nearest driver accordingly.

Frankly I'm not sure this is such a good idea. You may find a solution that is very good without taking start/end into account, but that will turn out to be arbitrarily bad when doing that final matching step.

On the other hand, if you only provide vehicle starts, the optimization will order tasks in a way that makes sense based on all available vehicles start points *and* make the decision regarding which vehicles should be used.

**Comment by jcoupey** [comment]
Closing as answered.
