### ISSUE TITLE
Add number of routes to output

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#524]
When debugging/working on instances, it's often useful to compare number of routes in solutions. Of course this info is only a `jq '.routes | length'` call away, but it would be nice to have it directly available as `summary.routes`. This would also be similar to how we report the unassigned tasks and their number in summary.

**Comment by Yash-Goyal007** [comment]
I want to work on this issue!!!!

**Comment by jcoupey** [comment]
@Yash-Goyal007 thanks for offering to help! This is mostly a matter of storing the value in the `Summary` object on the C++ side and adding it in the json output. You can re-use the same existing logic as with the current `unassigned` value.

- adding a member for number of routes in `Summary` would happen [here](https://github.com/VROOM-Project/vroom/blob/master/src/structures/vroom/solution/summary.h);
- passing the value for `Summary` would happen in [the `Solution` ctor](https://github.com/VROOM-Project/vroom/blob/7be0b4ffb38015543229bd50e7f7082388c0e62e/src/structures/vroom/solution/solution.cpp#L18-L37);
- serializing the `Summary` object happens [here](https://github.com/VROOM-Project/vroom/blob/7be0b4ffb38015543229bd50e7f7082388c0e62e/src/utils/output_json.cpp#L115).
