### ISSUE TITLE
Use fallback for `time_window`

### ISSUE THREAD

**Issue by wesleimp** [VROOM-Project/vroom#526]
Let's thinking about a scenario where I have some priority to deliver orders, and those orders need to be delivered in a 15 minutes time window. Is it possible to use some fallback in case of the time window is not reached?

For example, 15 minutes with 30 minutes as a fallback.

```json
{
  ...
  "time_window": [0, 900, 1800]
}
```
or
```json
{
  ...
  "time_window": [[0, 900], [900, 1800]]
}
```

If it's not possible, is there some other way to do that with VROOM?

**Comment by jcoupey** [comment]
No, there is no such thing as a fallback extended time window in the model, and TW constraints are hard constraints for the optimization. A task either ends up as planned (in that case the timing matches one of its TW) or as unassigned.

What you could do is evaluate different options by submitting the same task with various TW lengths in different optimization runs. In that case you'd have to build the business logic yourself around the solving engine.

**Comment by wesleimp** [comment]
Hmmm, I gotcha. 

Thanks for your help, @jcoupey. I really appreciate it.
