### ISSUE TITLE
is Service Time is include in time window ?

### ISSUE THREAD

**Issue by JC-Conserto** [VROOM-Project/vroom#531]
Hi, i have a question about the time windows.

I have a time_windows and service for a Shipment. In the same time, i have a vehicle that have not time_windows. How is calculate the arrival ?

Example :
input : 
```
  "delivery": {
      "id": 201,
      "location_index": 10,
      "description": "PREF01-85-4--4-5_1042",
      "service": 2400,
      "time_windows": [
          [
              1484681100,
              1484720100
          ]
      ]
  }
```

output : 
```
{
        "type": "delivery",
        "description": "PREF01-85-4--4-5_1042",
        "id": 201,
        "service": 2400,
        "waiting_time": 0,
        "job": 201,
        "load": [
            0
        ],
        "arrival": 1484718300,
        "duration": 31620,
        "violations": []
    },
```

Is arrival take time service in count ? Is Service time is include with time_window for calculate arrival time ?

Thanks

**Comment by jcoupey** [comment]
No, service time is not necessarily fully included in the provided time window. For example if you provide a 8:00-10:00 TW for a task with a 10 minutes service time, performing the task at 9:59 up to 10:09 is considered valid. If you want the make sure the tasks **ends** before 10:00, then you simply have to provide a 8:00-9:50 TW in the first place.

Also note that `arrival` is not always the time at which a task starts. The actual guarantee we provide is that `arrival + waiting_time` is included in the provided TW.

**Comment by jcoupey** [comment]
Closing as answered.

**Comment by stefanocudini** [comment]
@jcoupey thanks for your always accurate answers

I had a doubt about this:
> performing the task at 9:59 up to 10:09 is considered valid.

if there is a second task to be performed later in the solution it will always be allocated after 10 minutes of service right?
In this case after 10:09
