### ISSUE TITLE
Task priority weighting

### ISSUE THREAD

**Issue by AlanWithaB** [VROOM-Project/vroom#532]
Hi there - can you clarify how the task priority works and if there's any weighting between the values or if it's just a linear ranking?

E.g. will VROOM prefer a task with priority "6" over one with priority "5" at the same strength as it does a task of priority "60" over one with "5"?

And how does priority interact with a custom cost matrix? When does priority take precedence over cost minimization?

**Comment by jcoupey** [comment]
When providing no priority at all, VROOM will try to maximize the number of tasks included in the solution, then reduce operational costs. The notion of priority extends this to "maximize the sum of priorities over included jobs".

From your examples: including two tasks with priority 5 would take over including a single task with priority 6. Including 11 tasks with priority 5 (i.e. priority sum of 55) would not take over including a task with priority 60. Two equivalent solutions in term of priority sum (12 tasks with priority 5 or a single task with priority 60) are distinguished based on other costs.

Maybe we should make that more clear [here](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#task-priorities), PR for this kind of improvements are always welcome!

**Comment by jcoupey** [comment]
Looks like this has been answered.
