### ISSUE TITLE
Multiple fuel types per fuel delivery truck and different fuel drop offs 

### ISSUE THREAD

**Issue by nassery318** [VROOM-Project/vroom#533]
Hi, I want to model fuel trucks that houses multiple fuels types in their compartment using VROOM - for instance a truck has total capacity of 10000 liters and that total capacity is divided to premium = 3000 liters, super = 4000 liters and regular = 3000 liters (they are stored in different compartments of the same truck).  This vehicle will drop off different fuel types (premium, super and regular) in different locations - and each of the location requiring different types of fuel. how do I incorporate this please ? 

I have shown a sample body request below which entails the total truck capacity - how do I break this down? and also how do I assign different fuel types for different delivery locations ?     Thanks in advance!

{
	'jobs': [{
		'id': 1,
		'location': [-79.41546036, 43.78031178],
		'amount': [1000]
	}, {
		'id': 2,
		'location': [-79.35897821, 43.79709677],
		'amount': [1000]
	}, {
		'id': 3,
		'location': [-79.35386678, 43.79465965],
		'amount': [1000]
	}, {
		'id': 4,
		'location': [-79.39610752, 43.80306374],
		'amount': [2500]
	}, {
		'id': 5,
		'location': [-79.35021569, 43.71854372],
		'amount': [200]
	}, {
		'id': 6,
		'location': [-79.38326489, 43.74124235],
		'amount': [800]
	}, {
		'id': 7,
		'location': [-79.37341095, 43.72389356],
		'amount': [1200]
	}, {
		'id': 8,
		'location': [-79.33321995, 43.71545272],
		'amount': [1100]
	}, {
		'id': 9,
		'location': [-79.28593106, 43.73334953],
		'amount': [2000]
	}, {
		'id': 10,
		'location': [-79.29143659, 43.76348994],
		'amount': [2200]
	}, {
		'id': 11,
		'location': [-79.28429411, 43.78711105],
		'amount': [1600]
	}, {
		'id': 12,
		'location': [-79.31849123, 43.77679483],
		'amount': [2000]
	}, {
		'id': 13,
		'location': [-79.345028, 43.77721077],
		'amount': [1300]
	}, {
		'id': 14,
		'location': [-79.38093353, 43.65662265],
		'amount': [800]
	}, {
		'id': 15,
		'location': [-79.36566134, 43.6601383],
		'amount': [1000]
	}, {
		'id': 16,
		'location': [-79.40357258, 43.6473973],
		'amount': [600]
	}, {
		'id': 17,
		'location': [-79.37586147, 43.64175712],
		'amount': [2000]
	}, {
		'id': 18,
		'location': [-79.39302036, 43.68771547],
		'amount': [1400]
	}, {
		'id': 19,
		'location': [-79.44791447, 43.69774307],
		'amount': [1100]
	}],
	'vehicles': [{
		'id': 0,
		'profile': 'car',
		'start': [-79.40285987, 43.75149056],
		'end': [-79.40285987, 43.75149056],
		'capacity': [10000]
	}, {
		'id': 1,
		'profile': 'car',
		'start': [-79.40285987, 43.75149056],
		'end': [-79.40285987, 43.75149056],
		'capacity': [10000]
	}, {
		'id': 2,
		'profile': 'car',
		'start': [-79.40285987, 43.75149056],
		'end': [-79.40285987, 43.75149056],
		'capacity': [10000]
	}, {
		'id': 3,
		'profile': 'car',
		'start': [-79.40285987, 43.75149056],
		'end': [-79.40285987, 43.75149056],
		'capacity': [10000]
	}, {
		'id': 4,
		'profile': 'car',
		'start': [-79.40285987, 43.75149056],
		'end': [-79.40285987, 43.75149056],
		'capacity': [10000]
	}, {
		'id': 5,
		'profile': 'car',
		'start': [-79.40285987, 43.75149056],
		'end': [-79.40285987, 43.75149056],
		'capacity': [10000]
	}],
	'options': {
		'g': 'true'
	}
}

**Comment by jcoupey** [comment]
All amount-related keys (`capacity`, `pickup`, `delivery`, `amount`) are arrays. This is a design choice that allows to define per use-case relevant metrics for capacity limitations, one per coordinate.

In your example, you could decide to describe amounts as `[premium, super, regular]`, you just have to make sure the description is consistent across vehicles/tasks.

**Comment by nassery318** [comment]
Appreciate it! sorry I am still a bit confused - I tried it and got an error, I might have done it wrong. Could you please show me by writing that for one of the vehicles shown above and the delivery shown as well?
