### ISSUE TITLE
Multi-stop P&D modeling

### ISSUE THREAD

**Issue by johnvencky** [VROOM-Project/vroom#536]
Hi!

We are trying to model FTL shipment with multiple non-breakable steps -- `A->B->C->D`.  Currently vroom only supports shipments with a single `pickup` and `delivery` locations.

Since vroom uses time-based matrices for solutions, my current idea is to take advantage of `service` variable to model this.

I.e., pickup would be A, delivery would be D, and service = time_duration(A, B, C, D) - time_duration(A, D) -- calculated manually with OSRM.

```
  "shipments": [
    {
      "pickup": {
        "id": 1,
        "location": A
      },
      "delivery": {
        "id": 2,
        "location": D,
        "service": time_duration(A, B, C, D) - time_duration(A, D)
      }
    }
  ]
```

Is that a good idea to model such a solution or is there a better way?  Any plans to support multi-stop P&D pairs in the future?

Thanks!

**Comment by jcoupey** [comment]
Hard to tell what is the best way without a comprehensive view of your use-case, but it sounds like your suggestion would result in consistent timing. The drawback is that you would not be able to force timing constraints on D without a translation (and not at all on B and C). Also of course you would not get the `A->B->C->D` geometry in the answer.

> Any plans to support multi-stop P&D pairs in the future?

No, there is currently no plan to support this kind of "chained" jobs.

**Comment by johnvencky** [comment]
Thanks for your reply @jcoupey
