### ISSUE TITLE
Same vehicle constraint Implementation

### ISSUE THREAD

**Issue by prince4249** [VROOM-Project/vroom#540]
Hi Julien,
I thoroughly went through the vroom documentation but couldn't really find the solution to my use case. 
So, consider a situation where we have 3 sets of locations. A set , A_1 set, and B set. A and A_1 are the counterpart of each other and B is totally independent. let's consider we have [1 ,2 , 3 , 4, 5] locations in set A and [1_1, 2_1, 3_1, 4_1 ,5_1 ] locations in set A_1. 

We want a vehicle that visits location 1 should visit location 1_1.  Similarly for other locations in A and A_1.

Any suggestions are highly appreciated. Thanks

**Comment by jcoupey** [comment]
Can you expand a bit on the real-life situation behind this scenario?

**Comment by prince4249** [comment]
Yea Sure. It's just that we want the same vehicle to visit a pair of locations.

**Comment by jcoupey** [comment]
Yes I got that, my question was rather on why you need this to happen. There may be different answers to the underlying need. You could e.g. model the pairs as a `shipment`, or use skills to make sure they're grouped in the same vehicle.

**Comment by prince4249** [comment]
Ok Julien. 
So, let me take you through my use case. I have some sets of locations where we have drop request, some have just pickup requests and some set of locations have both drop and pickup requests.Now, the constraint is we will facilitate all drop jobs before pickup jobs . So, due to this constraint, I have to come back to such locations where we have both drop and pickup requests to do pickup jobs. Another constraint is we have to do pickup and drop jobs of a location via the same vehicle. To re-visit the visited node  i.e. to complete the pickup jobs at that location , I have created duplicate nodes of them. 
Drop stuffs are brought from depot locations and pickup stuffs are brought back to depot at the end. 

If you find any point not understandable , do let me know. Thanks

**Comment by jcoupey** [comment]
Your best bet is probably to use skills: that is assign the same skill to both jobs that need to be visited by the same vehicle. The limitation here is that you need to decide before-hand which vehicle will do the jobs (and get the matching skill). There is no such thing as a "same vehicle" constraint across jobs.

**Comment by prince4249** [comment]
But the problem in using skills is I have 10 such for example and vehicles required is just 7 . Now beforehand, I dont know which vehicle will visit which set of locations. How can one figure out that whether vehicle 1 will visit location 1 or 2 , or it will visit both the location in an optimized solution? Pre-defining the particular vehicles with a particular location might force the solver to result in an infeasible solution too. There is this feature in Google OR tools to imply soft constraint for same vehicle to visit a set of locations if not , the penalty will be applied.

**Comment by jcoupey** [comment]
> I dont know which vehicle will visit which set of locations

Yes, this is exactly the "limitation" I pointed out in my previous comment when mentioning skills. I'm afraid we don't have a way around that with the current model.

**Comment by prince4249** [comment]
Ok Julien, thanks.I think we should integrate this feature in vroom's next version.

**Comment by jcoupey** [comment]
> I think we should integrate this feature in vroom's next version.

This is an open-source project, so please feel free to implement it. If you do, we'd gladly re-open this ticket and review any PR.
