### ISSUE TITLE
"Error: Invalid end array" when omitting "End" key on vehicle.

### ISSUE THREAD

**Issue by Trinity-Solucoes** [VROOM-Project/vroom#541]
Hello, 
        I'm facing error when sending a this json to Vroom. On of the Vehicles just has the Start key, becouse it's not a round trip problem.  

{
   "jobs":[
      {
         "id":2840,
         "description":"FERNANDESALMEIDAFABIO",
         "location":[
            -23.636821,
            -46.602416
         ],
         "priority":0
      },
      {
         "id":2841,
         "description":"ABCD INFOCELL",
         "location":[
            -23.5111835,
            -46.855827000000005
         ],
         "priority":0
      },
      {
         "id":2842,
         "description":"MAGAZINE TOTAL10",
         "location":[
            -23.563169,
            -46.535208
         ],
         "priority":0
      },
      {
         "id":2843,
         "description":"FRPE8796484",
         "location":[
            -23.647099,
            -46.663997
         ],
         "priority":0
      }
   ],
   "vehicles":[
      {
         "id":19,
         "start":[
            -8.11019115994966,
            -34.898294687413745
         ],
         "capacity":[
            9000,
            200,
            15,
            200000
         ]
      },
      {
         "id":12,
         "start":[
            -8.11019115994966,
            -34.898294687413745
         ],
         "end":[
            -8.11019115994966,
            -34.898294687413745
         ],
         "capacity":[
            100,
            100,
            5,
            1000
         ]
      },
      {
         "id":15,
         "start":[
            -8.11019115994966,
            -34.898294687413745
         ],
         "end":[
            -8.11019115994966,
            -34.898294687413745
         ],
         "capacity":[
            1000000,
            1000000,
            4100,
            100000
         ]
      }
   ],
   "options":{
      "g":true
   }
}

**Comment by krypt-n** [comment]
I can't reproduce the problem with your json file locally. How are you passing it to vroom?

**Comment by Trinity-Solucoes** [comment]
I've managed to make it work. Thanks.

**Comment by jcoupey** [comment]
@Trinity-Solucoes could you please share how you made it work (or what was the initial problem) as this would be useful for anyone coming across this ticket?
