### ISSUE TITLE
osrm-text-instructions integration

### ISSUE THREAD

**Issue by matheuss-leonel** [VROOM-Project/vroom#542]
Hello guys!

I've a self-hosted vroom + osrm and I would like to pipe the "steps" (yes, the json field) result from **osrm** (not vroom) to "[osrm-text-instructions](https://github.com/Project-OSRM/osrm-text-instructions)".

I understand that vroom will ask osrm for the matrix, run the algorithm and return the solution, but it seems that the "steps" field from vroom is missing some navigation data, required by "osrm-text-instructions". Is there a way to add these information from the osrm "steps" field to vroom "steps" field?

One solution to this problem is to pipe the solution from vroom to osrm again, just to get all the navigation information that is being omitted, but the final route can diff from the vroom solution, breaking it. Maybe I'm wrong, don't know, can you help me?

Didn't find any related issue/doc

**Comment by matheuss-leonel** [comment]
Thanks for listening, @jcoupey !

> That's probably your best bet. The `routes[].steps` arrays have all required data to build the routing request. If you're concerned about having the same request sent twice to OSRM, you can run VROOM without `-g` to avoid it altogether and handle it yourself directly.
 
Just one more thing: I don't get why omitting `-g` will avoid the duplication of the request. Can you explain it a little bit further?
 
> I don't see why, provided you're doing the exact same request. For that, you can lookup your OSRM logs, or see how we build and use the route request [here](https://github.com/VROOM-Project/vroom/blob/7be0b4ffb38015543229bd50e7f7082388c0e62e/src/routing/osrm_routed_wrapper.cpp#L26-L52) and [here](https://github.com/VROOM-Project/vroom/blob/7be0b4ffb38015543229bd50e7f7082388c0e62e/src/routing/http_wrapper.cpp#L211-L212).

Well, you're right, it's expected that the final route (by osrm) use the same weights that it returned to vroom in the first request (in the matrix). I got it right?

Thanks!

**Comment by jcoupey** [comment]
> why omitting -g will avoid the duplication of the request

VROOM will fire a matrix request prior to optimization, then decide on the routes. Once the solution is found, and if `-g` is provided, then a route request is sent per used vehicle to populate the geometry and distance info. If you run your own OSRM request after that, it will basically duplicate the one sent by VROOM for each route so you may want to avoid the latter.

>it's expected that the final route (by osrm) use the same weights

If you're doing the request against the same OSRM server, then you're fine as long as you make sure the options passed are the same. Check the `extra_args` value in the above link, or just inspect the route requests generated by VROOM in your OSRM logs.

**Comment by matheuss-leonel** [comment]
Got it!

Thanks!
