### ISSUE TITLE
Getting very strange Polyline 

### ISSUE THREAD

**Issue by Trinity-Solucoes** [VROOM-Project/vroom#543]
Hello,
        I'm sending the following request to vroom, but it is returning a very wrong polyline. It's a roundtrip route but vroom returns a route ending in wrong place. Please, look at the file attached, the picture shows the returned polyline plotted on OpenStreetMap. We've tried to run the request on openrouteservice.org playgroud api looking to find if there was a problem with our server installation, but got the same polyline from ORS.
 
 Thanks.

![image (8)](https://user-images.githubusercontent.com/51826551/124520706-95694f00-ddc3-11eb-8545-76094573a361.png)

{
   "jobs":[
      {
         "id":3162,
         "description":"BASSELMOHAMMAD",
         "location":[
            -46.57793,
            -23.580039
         ],
         "delivery":[
            1,
            1,
            1,
            1
         ],
         "priority":0
      },
      {
         "id":3163,
         "description":"ZOPOELETRO",
         "location":[
            -46.405955,
            -23.579427
         ],
         "delivery":[
            1,
            1,
            1,
            1
         ],
         "priority":0
      },
      {
         "id":3164,
         "description":"MIBUY-IMPORTS",
         "location":[
            -46.563848,
            -23.5662
         ],
         "delivery":[
            1,
            1,
            1,
            1
         ],
         "priority":0
      }
   ],
   "vehicles":[
      {
         "id":19,
         "description":"pdg1998",
         "start":[
            -46.57793,
            -23.580039
         ],
         "end":[
            -46.57793,
            -23.580039
         ],
         "capacity":[
            9000,
            200,
            15,
            200000
         ]
      }
   ],
   "options":{
      "g":true
   }
}

**Comment by Orthae** [comment]
I guess the issue here is that the polyline returned in JSON contains escaped "\" so if you are using raw string remember to replace "\\" with "\".

**Comment by Trinity-Solucoes** [comment]
Thank you very much.
