### ISSUE TITLE
Modeling question: vehicle shift and driving time

### ISSUE THREAD

**Issue by CosmoVal** [VROOM-Project/vroom#544]
Hi, 

I'm facing a vehicle routing problem (with pick up and delivery) where each vehicle works on a **shift of 15 hours**, but it can only **drive 9 hours** in that timeframe. In other words, activities such as load, unload and waiting time don't consume the 9 hours driving bucket, but must happen during the 15 hours shift.

My idea is to have a time window that is 15 hours large, but then I don't know how to enforce the 9 hours driving constraint. 

Do you have any idea on how can I model this situation?

Thanks

**Comment by jcoupey** [comment]
Looks like you need #273. Closing as duplicate.
