### ISSUE TITLE
Best Way to display output file? [Discussion]

### ISSUE THREAD

**Issue by Cichx** [VROOM-Project/vroom#546]
I understand that I could use the frontend-server, however I'm wondering if there's a recommended workflow for displaying the output files (e.g. [this](https://github.com/VROOM-Project/vroom/blob/master/docs/example_1_sol.json)  one)?
My first thought was to re-structure the output file to a "geojson" format and display e.g. via a [webinterface](http://geojson.io), but I'm sure, there are better solutions...

Thank you for your reply!

**Comment by jcoupey** [comment]
The response does contain all basic information for displaying the routes (see `geometry` key) and steps, e.g. with markers based on their location.

The way you display the solution is up to you and somehow out of scope for this repo. You may want to check out open-source mapping libraries such as Leaflet (used under the hood by the frontend) or OpenLayers.

**Comment by Cichx** [comment]
Thanks for your fast and helpful reply!
