### ISSUE TITLE
Add multiple delivery points for each pickup

### ISSUE THREAD

**Issue by hacen-ai** [VROOM-Project/vroom#550]
My senario:
I have pickup-and-delivery problem.
As follow:
1) I want to to add support for multiple delivery points for each pickup.
Any suggestion?

**Comment by jcoupey** [comment]
If you have a delivery, the corresponding load is picked up at some place and our API only allows to describe this 1:1 relation. The way you can handle your situation is to define one `shipment` object per delivery. The fact that you'll have multiple pickups with the same location is not a problem: if the constraints allow for it, they'll be (most probably) grouped in the same route as consecutive steps in the solution.

**Comment by hacen-ai** [comment]
Thank you @jcoupey  for your insights

**Comment by jcoupey** [comment]
Closing as answered.
