### ISSUE TITLE
Can we add alternative delivery point

### ISSUE THREAD

**Issue by hacen-ai** [VROOM-Project/vroom#552]
Hello,
Let suppose we have multiple depots A,B, C and we have a pickup-delivery task from point (1) wich is very close to depot A and delivery point close to C. Can we add the possibility that a vehicule can pickup item from (1) and depose it in depot B (or C) and then another vihecule delivery it from depot B and delivery it to the client in (2).
PS: Sorry for my bad english

**Comment by jcoupey** [comment]
There is no way to model a temporary drop-off for something picked up later by another vehicle. The `shipment` objects only model a single pickup & delivery situation.

What you could try is model this with two shipments, using time windows to make sure the first drop-off happens before the second pickup. This would not be very flexible as you'd have to decide on times, and also you may run in situations where one out of the two shipments is unassigned.

**Comment by jcoupey** [comment]
Closing as stale.
