### ISSUE TITLE
Is it possible to force an order between jobs

### ISSUE THREAD

**Issue by phauly** [VROOM-Project/vroom#554]
Can I say that job 4 must be served after job 3?

This is useful to model facts such as "after doing this job in this location, the vehicle must go this other location for doing this other job"

**Comment by jcoupey** [comment]
There is no direct way to set precedence constraints between regular `job` objects. You could achieve this effect by forcing other constraints in the model, such as time windows, but this would not be very flexible.

>  after doing this job in this location, the vehicle must go this other location

This sounds very close to a pickup & delivery scenario (except maybe there is nothing to pick). So depending on your actual need, you could use `shipment` objects that embed the notion of a precedence constraint between two tasks.

**Comment by phauly** [comment]
Thanks a lot!

I will try to create a json for modelling this constraint. I have some problems in understanding how to model things and I'm making a lot of try (edit json, upload on online demo) and error and many small progresses. Of course, if you are so fast in doing it and are willing to share a json that model 3 jobs (1, 2 and 3) and the constraint (job 3 must follow job 2) that would be awesome! ;)

**Comment by jcoupey** [comment]
>Thanks a lot!

Happy to help, especially if the suggestion works for you.

> Of course, if you are so fast in doing it and are willing to share a json

This is an open-source project so if you want to use it on your own, you'll have to learn how to by digging through the documentation and using [the provided examples](https://github.com/VROOM-Project/vroom/tree/master/docs).

Also coming up with a relevant model for your use-case would probably require more than a few words about what you're trying to achieve. That's the kind of work you can expect from a support contract.

**Comment by phauly** [comment]
Absolutely, you are right and thanks for your reply! 

I'm digging through the 3 examples and modifying them. Thanks for your reply!

**Comment by phauly** [comment]
I'm not reopening the issue but I just would like to let you know I modeled in this way.

Vehicle has "capacity": [10]

And then there are many pairs of shipments with "amount": [10] and as pickup the first location and as delivery the second location. 
I think it works.

When I will have to add triplets (sequences of 3 locations) or more, I will think about it again ;))

**Comment by jcoupey** [comment]
Thanks for the follow-up! With this setting, you'll only get `pickup, delivery, pickup, delivery, ...` sequences (no mix due to capacity) so your task pairs will always be done in a row.

**Comment by phauly** [comment]
> so your task pairs will always be done in a row.
Yes, this was what I wanted to achieve!!! Thanks for a great project!!!
