### ISSUE TITLE
I have built vroom and libvroom_example. Could you help me have a try without http_wrapper?

### ISSUE THREAD

**Issue by newforrestgump001** [VROOM-Project/vroom#562]
./libvroom-example 
[Error] Failed to connect to localhost:5000
I have built vroom and libvroom_example. Could you help me have a try without http_wrapper?

**Comment by krypt-n** [comment]
`example_1.json` has no embedded cost matrix. Hence vroom will try to contact an osrm server at `0.0.0.0:5000` to retrieve cost information. You can change this default behavior with the `-r`, `-p` and `-a` flags to contact other kinds of servers elsewhere.

However you could also try running `example_2.json` which contains an embedded cost matrix.
```
vroom -i docs/example_2.json
```

**Comment by newforrestgump001** [comment]
@jcoupey Thanks for your kind help!

**Comment by jcoupey** [comment]
All credit goes to @krypt-n on that one. ;-)

**Comment by newforrestgump001** [comment]
@krypt-n @jcoupey  Sincere thanks for both of you!~~
