### ISSUE TITLE
min tasks 

### ISSUE THREAD

**Issue by noamanemobidata** [VROOM-Project/vroom#567]
Hi there! Thank you for this great work! There is a plan to add a feature (constraint)  that allows to set a minimum number of tasks per vehicle just like max_tasks  ?

**Comment by jcoupey** [comment]
No to mention the fact that such a constraint can't be a hard one (a min number of tasks can not always be guaranteed), I'm curious about the kind of context where this would be useful/required? Can you elaborate a bit on your use-case?

**Comment by noamanemobidata** [comment]
I found an answer in the discussion #329 
thank you once again for this work
