### ISSUE TITLE
Vehicle return

### ISSUE THREAD

**Issue by ilibar-zpt** [VROOM-Project/vroom#574]
Hi!
We have a case for taking into account return time of each vehicle.
Current documentation says that it is possible to configure custom `steps` for `vehicles`, and there is and `end` type, but it does **not** say that a `job` `id` can be assigned to an `end` type of `vehicle_step` (have to specify job to set a location).

Is there a specific reason for such limitation, could it be implemented?
Maybe there's some other way to account for vehicle return in the output?

**Comment by jcoupey** [comment]
> taking into account return time of each vehicle.

This normally happens out-of-the-box by setting an `end` key for vehicles, check out https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#vehicles and the note on vehicle locations.

**Comment by ilibar-zpt** [comment]
nice!
