### ISSUE TITLE
Enforce shipments to be made by the same vehicle

### ISSUE THREAD

**Issue by stefanhahmann** [VROOM-Project/vroom#576]
Hi,

I have an use-case where a service time is triggered after a vehicle has made a shipment requiring a particular skill. However, the service time is the same, if this vehicle makes 1 or many shipments requiring that skill, since the service is only needed before a shipment requiring a different skill is performed by that vehicle.

Thus it would make sense, if a vehicle preferably makes those shipment requiring that specific skill even though other vehicles would also be able to make these shipments, since they also have this skill.

I am wondering, if there is any way to model this use case with the current API?

**Comment by jcoupey** [comment]
> a service time is triggered after a vehicle has made a shipment requiring a particular skill

Can you expand on the context and maybe give an example to clarify? In particular, it's not clear for me *when* this additional service time takes place since a shipment is made up of two separate pickup and delivery tasks that are not guaranteed to happen in a row.

**Comment by stefanhahmann** [comment]
The context is the transport of patients (from/to e.g. hospital/elderly home/doctor) that we try to model as shipments in vroom. If these patients have e.g. certain infections/diseases, which we try to model as skill or in a capacity array, it is necessary to clean/desinfect the vehicles before other patients that do not have this type of infection/disease are transported with the same vehicle. We are trying to model the time needed for desinfection/cleaning the vehicle as a service time in vroom. However, if multiple patients with the same infection are transported in a row, desinfection/cleaning is only required once after all transports. Thus, depending on the length of the required service time, it would make sense, if we could somehow enforce that the same vehicle does multiple pickup/deliveries requiring the same skill, since in that case service times can be reduced and thus the overall transport times can be reduced.

**Comment by jcoupey** [comment]
OK, this is like an additional task that is not in input but should be added only once after a set of shipments. I'm afraid we don't have a way to handle that in a generic manner. Adjusting the service time can be a good approximation but as you pointed out you don't know whether/when to apply the "extended" service time.

We've recently implemented something for a similar need in #547. But it's related to same-location tasks, not same-skill tasks so it won't be of any help in your situation.

**Comment by jcoupey** [comment]
Closing as stale.
