### ISSUE TITLE
bool flag 'use_libosrm' missing in cl_args_t

### ISSUE THREAD

**Issue by PattyDePuh** [VROOM-Project/vroom#58]
While trying to proceed with #47 i tumbled over an exception, that the 'use_libosrm' flag was missing in 
https://github.com/VROOM-Project/vroom/blob/master/src/structures/typedefs.h#L30
used in 
https://github.com/VROOM-Project/vroom/blob/master/src/utils/input_parser.cpp#L32
preventing to compile on the master-branch.

@jcoupey I don't know, if it is intended or not, if LibOSRM is still a thing. 
My guess is, that was a mistake, that the bool variable is missing, so i have added it into the struct, but without an activation flag.
[Foundable in this branch](https://github.com/PattyDePuh/vroom/tree/libosrm_struct_adition)

**Comment by jcoupey** [comment]
Oops, this got lost during the last merge to `master`. Yes this flag is still relevant and correspond to the `-l` command-line argument to use `libosrm` over `osrm-routed`.

Should be ok now with the last commit, thanks for reporting!
