### ISSUE TITLE
Job or Shipment

### ISSUE THREAD

**Issue by myrondeliverone** [VROOM-Project/vroom#597]
I have two questions.

When should you use a **Job** in a routing request and when should you use a **Shipment**? My company only does deliveries and we work out of one distro center. 

The second question is there a community group for VROOM? That way I can search for information there.

**Comment by jashwant** [comment]
@jcoupey , To keep things simpler, can we convert all jobs (pickups and deliveries) as shipments with same pickup and same delivery location?

**Comment by jcoupey** [comment]
> To keep things simpler

If you mean keeping your input model simpler, then sure you'll only have a single type of objects (shipments) if converting jobs. But then as stated above _"you're making it more complex by doubling the number of tasks involved"_ which really does not help on the solving side.

**Comment by jashwant** [comment]
Thanks for quick reply. This clears my confusion.
