### ISSUE TITLE
Error while compiling with mingw32-make

### ISSUE THREAD

**Issue by phreephree** [VROOM-Project/vroom#60]
Hello,
Error while compiling with mingw32-make:
Main.cpp: 14: 30: fatal error: boost / log / core.hpp
The folder "boost" is yet added to the folder "src"
Thank you for your help,
cordially

**Comment by jcoupey** [comment]
Hi, I know nothing about using mingw32-make or compiling and linking on windows, but it seems like the boost library is simply not found.

You probably have to put it at some "usual" place so it can be found in the default path for libraries, or provide the specific folder containing the headers to your compiler. Check out the `-I` and `-L` compilation options.

**Comment by phreephree** [comment]
Hi,
Thanks,
Its ok with Linux and libboost.
