### ISSUE TITLE
max_tasks not working

### ISSUE THREAD

**Issue by amks1** [VROOM-Project/vroom#600]
Hi, 
I'm testing vroom using vroom-docker on my server. Routing engine is OSRM. I specified 101 `jobs` and 4 `vehicles`, each with `max_tasks` set as 26. 

The output I got has the following number of `steps` per `route`:
```
Vehicle 1: 86
Vehicle 2: 18
Vehicle 3: 3
```

Why isn't `max_tasks` working? I provided the same `start` for all vehicles and no `end`.

**Comment by amks1** [comment]
@jcoupey @nilsnolde 
I was just playing around a bit, and noticed that `max_tasks=1` does not work when there is only one vehicle and several jobs. Instead it routes all the jobs to the vehicle provided.

**Comment by jcoupey** [comment]
>  does not work when there is only one vehicle 

That's probably #603, now fixed.

**Comment by amks1** [comment]
Nice, is there a docker image yet?
