### ISSUE TITLE
Problem with optimize output (own customized backend)

### ISSUE THREAD

**Issue by npantazis** [VROOM-Project/vroom#605]
Hi,

I'm currently using the optimization part from own customized backend but i'm facing a problem when using time windows.
I have attached a request [example](https://github.com/VROOM-Project/vroom/files/7459100/request.txt) with 43 jobs with time window from 00:00 to 23:59 except one (id: 30321, time window : 13:00-14-00).

Also, vehicle time window is from 09:00-23:00.

The problem is that the start time is not 09:00 but about 10:00 in contrast with your service with same request where the start time is correct.
Also, the ordering optimization is different.

I have attached the output from [my server](https://github.com/VROOM-Project/vroom/files/7459110/Response.own.server.txt) and also [yours](https://github.com/VROOM-Project/vroom/files/7459111/Response.openrouteservice.txt) from openrouteservice (https://api.openrouteservice.org/optimization) where openrouteservice reference to your code for optimization.

Here i have [config](https://github.com/VROOM-Project/vroom/files/7459123/config.txt) from my server.

Can you help me?

Thank you in advance

**Comment by kchronisdev** [comment]
Hi, have tou tried to restart your pc?

**Comment by jcoupey** [comment]
Thanks for the detailed description. Unfortunately, there is not much we can do related to the routing setup: we don't operate the Openrouteservice optimization endpoint. It's the other way around: the ORS team deploy VROOM on top of ORS to provide this endpoint.

What you can do is provide a reproducible instance (see https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) to illustrate the mismatch between what you get and what you expect.

**Comment by npantazis** [comment]
Hi @jcoupey 

Issue resolved by upgrading ORS & VROOM to the latest versions.

ORS version 6.3.2 --> 6.6.1
vroom-express@0.7.0 --> 0.9.0

Thank you for your time
