### ISSUE TITLE
Let VROOM group duration (as optional) based on same contiguous location

### ISSUE THREAD

**Issue by mhosman** [VROOM-Project/vroom#608]
Let's say I have 100 jobs and 3 of them have the same location and are optimized by VROOM to be done in a row, in the same stop. There are also other scenarios that we have jobs with the same location but are not part of the same stop, but let's talk about the first scenario (1 stop). Now let's say each job duration is 5 minutes. Right now VROOM is gonna return the three jobs and is gonna put 5 minutes per each job.  The idea/suggestion is to put 5 minutes for the same stop (all this 3 jobs together).

**Why?**
Sometimes you have pickups, deliveries, jobs, etc, from distinct orders and same locations, but and you don't know when you should group them or not (this is done by VROOM). So... maybe for those scenarios, it could be great to group those values.

**Comment by jcoupey** [comment]
This has been discussed in #358 and we introduced the notion of "setup" time for that exact purpose in #547. See https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#task-setup-times.

**Comment by mhosman** [comment]
Thank you @jcoupey !!!!
