### ISSUE TITLE
Better filtering for invalid json input

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#61]
Some checks are missing in `input_parser`, e.g. providing a string as vehicle or job `id` triggers a `rapidjson` assert. An explicit error message should be reported.

**Comment by PattyDePuh** [comment]
Shall it be added in the #59 branch or seperately?

**Comment by jcoupey** [comment]
@PattyDePuh I did come across the missing checks while browsing through your commits so I added this ticket as a reminder. 
Doesn't seem a huge priority to me so we can just wait until #59 gets merged, but if you feel like it, please feel free to add the error checks in the PR!
