### ISSUE TITLE
Maximum number and size of files to be read with vroom::vroom() from drive?

### ISSUE THREAD

**Issue by smalldatalooser** [VROOM-Project/vroom#611]
I just tried using` vroom(fs::dir_ls(path))` for reading csv files inside a local directory. 
There are quite a lot of files (1000 files, 3000 rows , 3 columns) which take about 50Mb as a Data Frame when read in R with a for loop and rbind + read_csv. However vroom lets me know that too many files are open with the error message: 

> Error in file(con, "rb") : cannot open the connection                                                                                                                                                                            
> In file(con, "rb") :
> 'some_csv_file.csv':
> Too many open files

Is this behaviour intended?
And do you know the maximum number/size of Data which can be read with the vroom function?

I hope this is the right place to ask this but i am quite sure that i used the function correctly.

**Comment by jcoupey** [comment]
For the record, this was probably intended for https://github.com/r-lib/vroom

**Comment by smalldatalooser** [comment]
Indeed! I recognized just after posting. 
Apologies and blame on me!. 
Please feel free to delete or keep it.
