### ISSUE TITLE
Question about vehicle_step 

### ISSUE THREAD

**Issue by mhosman** [VROOM-Project/vroom#613]
Great release! Just wanted to ask about vehicle_step. What is it for? The description in the documentation was not entirely clear to me. What types of data are service_at, service_after and service_before?

Thank you so much!

**Comment by jcoupey** [comment]
The `service_*` values are timestamps, they should be homogeneous to values used in time windows. Did you check out [this part of the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#in-plan-mode) about plan mode?

**Comment by mhosman** [comment]
Got it! Thank you @jcoupey, closing!
