### ISSUE TITLE
Maximum distance between jobs

### ISSUE THREAD

**Issue by SirTypesALot** [VROOM-Project/vroom#614]
Hi, I was wondering if there is a way to set a maximum limit on the distance between jobs? If you could point me where to look at and modify it in the source code I would be very grateful.

**Comment by jcoupey** [comment]
Do you mean you'd like the optimization process to discard jobs that are "too far away"? If so, did you consider applying a pre-processing step and filter out those jobs prior to submitting the problem?

**Comment by mufassir-khan** [comment]
Modifying your distance/duration matrix accordingly. @SirTypesALot
