### ISSUE TITLE
Dynamically add Jobs throughout the day

### ISSUE THREAD

**Issue by robert-hopla** [VROOM-Project/vroom#615]
Hello, we want to do multi driver pickups.

it is okay that the route of individual vehicles changes (apart from current job), but we do not want to re-assign jobs <> vehicles.

Jobs can be added throughout the day, and when a job is added, we want to pass:

1 vehicle = force this job to this vehicle
multiple vehicles = assign to the most optimal vehicle from selection
no vehicle = assign to most optimal vehicle from fleet (all vehicles)
once a job is assigned to a vehicle, unless it is rejected by the vehicle, it should remain with that vehicle…

when we assign a new job to a vehicle we will re-optimize their route to include the new job.

we could even potentially re-optimize the route after completing each job, but i guess that is only interesting if traffic is taken into account? is it?

Any help on getting this started would be highly appreciated

**Comment by jcoupey** [comment]
Closing as answered over on the ORS forum (https://ask.openrouteservice.org/t/vroom-or-ors-dynamic-routes/3343). TL;DR you can use skills in the subsequent calls.
