### ISSUE TITLE
Vehicle steps in solving mode

### ISSUE THREAD

**Issue by radilaci** [VROOM-Project/vroom#616]
Hi! Thank you for your work!

I try to use vehicle steps in solving mode in order to specify an initial route for the vehicle. I am using v1.11.0.
I have six jobs (taken from example 3 in the docs folder, removed time windows and capacities) and one vehicle with steps: start, job 1, job 2, job 3, end.
As you can see in the solution, vehicle steps are not taken into account.
What am I missing?
Thanks in advance for your help.

[test.txt](https://github.com/VROOM-Project/vroom/files/7602580/test.txt)
[test_solution.txt](https://github.com/VROOM-Project/vroom/files/7602582/test_solution.txt)

**Comment by jcoupey** [comment]
Using the `vehicle.steps` key in solving mode is not about forcing the ordering **in output**, it's about forcing the search to start from your own provided solution. In particular the initial ordering can be changed in any way that improves the solution.

Depending on what you're trying to achieve, you may want to use `plan` mode instead. More on the differences for this key depending on the mode [in the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#vehicle-steps).

**Comment by radilaci** [comment]
Hi Julien,
Thanks for your reply. Now I understand what `vehicle.steps` is. I'm afraid plan mode does not help me either.
Our scenario is: we have 5 jobs, 2 jobs are already served / visited, a new job comes into the database, so we are trying to find a new solution in which the first two jobs remain "untouched".
How can I achieve it? Any help would be highly appreciated.

**Comment by radilaci** [comment]
Ok, thank you for your response.
