### ISSUE TITLE
Getting unexpected results with respect to optimization

### ISSUE THREAD

**Issue by krashish8** [VROOM-Project/vroom#618]
I ran sample queries (a.k.a. toy examples) to check the optimization of VROOM. I felt one of the results was quite unexpected than the general result.

**To reproduce**:
* First query: [vroom_1.json](https://gist.github.com/krashish8/794f3d5bdc68006533554ad1646d49b4#file-vroom_1-json) with solution [vroom_1_sol.json](https://gist.github.com/krashish8/794f3d5bdc68006533554ad1646d49b4#file-vroom_1_sol-json)
* Second query: [vroom_2.json](https://gist.github.com/krashish8/794f3d5bdc68006533554ad1646d49b4#file-vroom_2-json) with solution [vroom_2_sol.json](https://gist.github.com/krashish8/794f3d5bdc68006533554ad1646d49b4#file-vroom_2_sol-json)

---

This is the first query, with start = 0 and end = 3, and two jobs 1414 and 1515.
Total Cost = 197000+2256+3152 = 202408

![image](https://user-images.githubusercontent.com/39548570/144189321-ec09f138-6a1d-4e67-bbd8-60033b776aa8.png)

It is obvious that a cost-effective solution would be to use the indirect route 0 -> 3 -> 1 which is very cheap than other routes 0 -> 1 or 0 -> 2. So, the best solution would be to follow the route: 0 (start) -> 3 -> 1 (job) -> 2 (job) -> 3 (end)

Although the cost 0 -> 3, 3 -> 1, or 1 -> 2 is exaggerated, a similar cost could be present in the real world. An indirect route through an excellent quality road with less traffic could have a smaller cost than a direct route with bad roads and heavy traffic.

Is this because the vehicles only visit a node with some job/shipment rather than a node with nothing? Are the indirect types of routes not supported by VROOM? 

---

To test indirect routes, I placed one job with id 1212 at node 3, with everything else remaining the same.

This is the second query. Here, the Total Cost = 1+3+22+1102 = 1128, which is far less than the total cost of the first query.

![image](https://user-images.githubusercontent.com/39548570/144189398-81a25457-641d-4ce3-83b6-57cfbc48bae6.png)

The vehicle could have followed a similar route in the first query to get a better result.

I understand that it is possible that adding some additional job/shipment can reduce the overall cost because it's all about optimization. But, such a large cost reduction in a small example is not what someone would expect in a general sense.

Are the results because of some optimization constraints or something else? Can something be done to improve this or support indirect routes?

**Comment by jcoupey** [comment]
Thanks for providing illustrations, this makes it much easier to figure out your example.

Your first illustration looks like it provides costs from job to job but it's more of a routing graph actually. It's somehow confusing since all "route nodes" are also jobs, but the edges do not represent the actual costs you should feed for solving. I mean we're mixing the "optimization level" view with the "road network" view.

When we fire the matrix request to the underlying routing engine, it returns a matrix of *cost-efficient* travel times from/to all jobs. My point is that you should run a many-to-many algorithm on your initial graph to come up with the job-to-job costs. In that case the 0->1 cost would be 1 + 3 = 4 in the first place.

Put it differently: using indirect routes does not happen at optimization level, but it's fine since it happens at routing level.

**Comment by krashish8** [comment]
So, do you mean that - even though the direct cost from 0 to 1 is 210400, at the routing level, it will actually return the "minimum" cost for a pair of nodes? So, at the routing level, the cost from 0 to 1 would be 1 + 3 = 4 instead.

And, this minimum cost is then passed to the optimization level to get the solution?

**Comment by jcoupey** [comment]
From the cost matrix point of view, there is no notion of "direct cost", each value should hold the minimum cost from getting from one place to the other. All the considerations regarding which route is actually followed is embedded in this value but is strictly a routing matter.

To be more precise, I mean the matrix used:
```
        [0,210400,197000,1],
        [2103,0,22,3152],
        [197,2256,0,1102],
        [1299,3,1102,0]
```
is not representative of actual job to job costs, it should be:
```
        [0,4,1103,1],
        [219,0,22,1124],
        [197,1105,0,1102],
        [1299,3,25,0]
```
where costs for 0->1, 0->2 and 1->0 are respectively 3 + 1, 1 + 1102, 22 + 197 etc.

Starting from your routing graph, this is what we'd get from a matrix request to the routing engine.

**Comment by krashish8** [comment]
Thank you for the detailed explanation. This was very helpful!
