### ISSUE TITLE
Demo Server: request with explicit vehicle profile fails with 403 forbidden

### ISSUE THREAD

**Issue by luzzi8** [VROOM-Project/vroom#619]
Hi there,

the demo server wiki [1] suggests an example request like

```
curl --header "Content-Type:application/json" --data '{"vehicles":[{"id":0,"start":[2.3526,48.8604],"end":[2.3526,48.8604]}],"jobs":[{"id":0,"location":[2.3691,48.8532]},{"id":1,"location":[2.2911,48.8566]}],"options":{"g":true}}' http://solver.vroom-project.org
```

According to API doc [2] it should also be possible to set the vehicle "profile" explicitly, e.g.

```
curl --header "Content-Type:application/json" --data '{"vehicles":[{"id":0,"profile":"car","start":[2.3526,48.8604],"end":[2.3526,48.8604]}],"jobs":[{"id":0,"location":[2.3691,48.8532]},{"id":1,"location":[2.2911,48.8566]}],"options":{"g":true}}' http://solver.vroom-project.org
```

However such a request fails with 403 forbidden. I also tried other profiles like "bike", "bicycle", "foot" with the same error.

Is this an intentional limitation? Or am I doing something wrong with the request?

Thank you very much!

[1] https://github.com/VROOM-Project/vroom/wiki/Demo-server
[2] https://github.com/VROOM-Project/vroom/blob/master/docs/API.md

**Comment by jcoupey** [comment]
The API link you point is the documentation for the software, not the demo server. So while it's technically possible to use multiple profiles, it requires several routing stacks which the demo server does not provide.

The demo runs a world-wide OSRM car profile, which is already somehow expensive to maintain. Note that the data is largely outdated (the purpose is to showcase the optimization, not the OSM freshness) an it comes without any uptime guarantee.

If you want to work with multiple profiles you can either deploy your own stack, or use a paid service as the one we provide at [Verso](https://verso-optim.com/).

**Comment by jcoupey** [comment]
Closing as answered.

**Comment by luzzi8** [comment]
Thank you for your reply, it answered the question.
