### ISSUE TITLE
Sequential shipment constraint

### ISSUE THREAD

**Issue by Conway6288** [VROOM-Project/vroom#620]
Have read through similar questions and haven't found a concrete solution, I need to perform two stops one after the other.

**Use case:**
Driver goes to site A and collects waste bags for disposal, they then have to go to site B directly after the pickup to dispose of those bags. If I have other jobs on the route, they cannot be between the pickup and delivery points of the shipment. Effectively the shipment needs to function as a single job with two locations.

**What I have tried:**
I have used a shipment object with site A as the pickup and site B as the delivery. This means that site B always comes out after site A in the route but not necessarily directly after. Along with the shipment object, there are standard jobs that do not do anything fancy they're purely deliveries. Playing with the time windows for the shipment is difficult as the opening times for both the pickup and disposal site need to be observed. 

[As discussed on this issue](https://github.com/VROOM-Project/vroom/issues/554), I have tried using a capacity constraint on the vehicle. As I understand it, if I was only doing this sort of shipment on a route I could mark the vehicle capacity as 1 and each shipment amount as 1. That way you wouldn't be able to start another shipment until the previous shipment is completed. This doesn't work when the "task pairs" (as they're described) are mixed with standard jobs.

I am hoping I have missed something in the documentation but it seems like it is not possible to route this scenario? Any advice is welcomed and thanks in advance.

**Comment by jcoupey** [comment]
I agree the solution proposed over in #554 only works with shipment-only instances and I see no way to extend this approach to a mix including jobs.

> the shipment needs to function as a single job with two locations.

This makes me think that you could probably hack your model to turn your shipment into a regular job if you're prepared to get your hands dirty (read mess with the travel time matrix). The idea would be to:

1. Compute yourself the travel time matrix including both A and B and locations
2. Define your A->B steps as a single job in input and adjust the matrix accordingly to account for getting to A and coming from B.
3. Solve
4. Post-process to add the real A->B steps

All the fun is in step 2, which would require to:
- assign the "mixed" job to a custom new line in the matrix where times "to" are times to A and times "from" are times from B
- adjust service time for the job to be pickup duration + time from A to B + delivery duration
- adjust the job time window to match your needs for pickup and delivery (this part is left to the reader).
