### ISSUE TITLE
Issue with time window constraints

### ISSUE THREAD

**Issue by vssalcedo** [VROOM-Project/vroom#624]
Hi there, recently I tried to optimize a route with time_windows constraints but it seems is not working properly in some cases.

I'm using a VROOM instance on top of OSRM.

**Reproducible demo:**  
```
{
  "vehicles": [
    {
      "id": 0,
      "start": [ -3.7024083, 40.6025767 ],

      // This time_window is to make sure all jobs are assigned to this vehicle
      "time_window": [ 1639051189, 2638893881 ] 
    }
  ],
  "jobs": [
    {
      "id": 0,
      "location": [ -3.5102705, 40.6955292 ],
      "time_windows": [ [ 1639051200, 1639053600 ] ]
    },
    {
      "id": 1,
      "location": [ -3.6880372, 40.4256549 ],
      "time_windows": [ [ 1639065600, 1639069200 ] ]
    },
    {
      "id": 2,
      "location": [ -3.6073436, 40.6910292 ],
      "time_windows": [ [ 1639069200, 1639072800 ] ]
    },
    {
      "id": 3,
      "location": [ -3.6040527, 40.0305018 ]
    }
  ],
  "options": { "g": false }
}
```

The response is:

```
{
    "code": 0,
    "summary": {
        "cost": 10234,
        "unassigned": 0,
        "service": 0,
        "duration": 10234,
        "waiting_time": 11619,
        "computing_times": {
            "loading": 47,
            "solving": 1
        }
    },
    "unassigned": [],
    "routes": [
        {
            "vehicle": 0,
            "cost": 10234,
            "service": 0,
            "duration": 10234,
            "waiting_time": 11619,
            "steps": [
                {
                    "type": "start",
                    "location": [
                        -3.7024083,
                        40.6025767
                    ],
                    "arrival": 1639051392,
                    "duration": 0
                },
                {
                    "type": "job",
                    "location": [
                        -3.5102705,
                        40.6955292
                    ],
                    "job": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "arrival": 1639053600,
                    "duration": 2208
                },
                {
                    "type": "job",
                    "location": [
                        -3.6880372,
                        40.4256549
                    ],
                    "job": 1,
                    "service": 0,
                    "waiting_time": 9838,
                    "arrival": 1639055762,
                    "duration": 4370
                },
                {
                    "type": "job",
                    "location": [
                        -3.6073436,
                        40.6910292
                    ],
                    "job": 2,
                    "service": 0,
                    "waiting_time": 1781,
                    "arrival": 1639067419,
                    "duration": 6189
                },
                {
                    "type": "job",
                    "location": [
                        -3.6040527,
                        40.0305018
                    ],
                    "job": 3,
                    "service": 0,
                    "waiting_time": 0,
                    "arrival": 1639073245,
                    "duration": 10234
                }
            ]
        }
    ]
}
```

If we take a look at the response object, the job with id = 1 has an arrival timestamp of `1639055762`. However, if we look into the request object, this job has a time_window of `[ 1639065600, 1639069200 ]`. Which doesn't contain the arrival timestamp.

The same issue happens with the job with id = 2.

I tried to play with other examples and some of them work as expected (If the timestamp cannot be fulfilled then the job is moved into the unassigned array). But others like the above example are not working properly.

My guess is that I'm doing something wrong with the request object. 

Looking forward to your help.
Thank you very much in advance!

**Comment by jcoupey** [comment]
We guarantee that all tasks **start** within the provided time window and there is a subtle difference between `arrival` and task start time. In general task start is `arrival + waiting_time`, in you case for job 1 `1639055762 + 9838 = 1639065600` which is the earliest possible date (start of TW).

In short: due to some timing constraint, the vehicle arrives early for job 1 and waits there until it's doable. In your example there is no way to do otherwise due to the disjoints TW provided in input.

**Comment by vssalcedo** [comment]
Hi @jcoupey thanks for your quick reply. Now I understand.

Is there a possibility to force VROOM to do another job instead of waiting for the current one until it's doable?

I provide a simple example:
Let's say we want to optimize 3 stops: A, B, C

The fastest route possible with the following time windows constraints is:

**A:** TW(9:00pm-10:30pm) Arrival= 9:32pm
**B:** TW(None) Arrival = 10:13pm
**C:** TW(10:50pm-11:50pm) Arrival = 11:10pm

However, **VROOM** makes this optimization:

**A:** TW(9:00pm-10:30pm) Arrival= 9:32pm
**C:** TW(10:50pm-11:50pm) Arrival = 10:50pm (Waits until time Window start)
**B:** TW(None) Arrival = 11:50pm

As you can see, VROOM does C before B although B doesn't have any window constraints and can be perfectly done before C to minimize the total time spent on the route.

We are making use of this great project to optimize carrier routes. So it's critical for us to have this feature to allow them to finish a route ASAP.

Thank you.

**Comment by jcoupey** [comment]
The general rule is that we pick the cheapest route we can find (read smallest travel time) and that is valid with regard to the constraints. And waiting time is not part of the cost evaluation, see #596.

> The fastest route possible 

I think in your example you actually mean "the route that ends the soonest" which is a different objective. My bet is that the solution provided by VROOM ends later, but is cheaper with regard to overall travel time, that being our optimization objective.

If you want the routes to end earlier, this can be translated as a constraint in the vehicle `time_window` deadline. You may also be interested in #466.

**Comment by vssalcedo** [comment]
Thanks for your suggestion! I'll give it a try.
