### ISSUE TITLE
Shipment without explicit start/end points

### ISSUE THREAD

**Issue by mj-amp** [VROOM-Project/vroom#626]
I would like to ask about the following **use case**: 

I'm trying to optimise a city bikes network. 

I need to take 4 bikes from A and from B. 
I need to deliver 4 bikes to C and to D. 
My truck can carry 10 bikes.  Any bike can go anywhere. 

Is there are a way in shipment not to specify explicitly that the bike 01 from A should go to C etc- as they can be shipped to any station? 

Thanks

**Comment by jcoupey** [comment]
No, defining a shipment requires to match a pickup and a destination location. This information has to be provided in input, there is no way around that.

**Comment by mj-amp** [comment]
Thanks :)
