### ISSUE TITLE
How to calculate the cost matrix once for multiple sessions?

### ISSUE THREAD

**Issue by napo** [VROOM-Project/vroom#629]
I have a vroom instance linked to openrouteservice
I have a fleet with 10 vehicles that have to serve a 35,000 point zone.
My solution takes 90 minutes to complete the calculation.
I was wondering if I can only calculate the distance matrix once (extracting it from ORS) and then proceed by calling vroom-express passing the computed matrix and the new points to move.
It's possible? How should I behave?

**Comment by jcoupey** [comment]
Yes, this is possible. You can compute the matrix yourself and embed the result in your problem with [the `matrices` key](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#matrices).

We even have a handy python script that will do exactly this for you, see this [wiki page](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance).

**Comment by napo** [comment]
Amazing!
Thanks a lot for the answer and also for the script.
I have tried it now and it is ok.
My only real problem: I hoped that the calculation with vroom was lighter, instead I see that, to find the solution, it always takes 90 minutes.
I admit that the matrix is very complex: 35,000 x 35,000
Suggestions?
Thank you

**Comment by jcoupey** [comment]
>  I hoped that the calculation with vroom was lighter

You're only saving the time it takes to compute the matrix, but not changing the actual solving duration. Probably worth it anyway (how long does a 35,000-matrix takes to compute using ORS?).

Now for the solving time you're definitely hitting the combinatorial nature of the VRP. Think of it, 90 minutes is not that bad for a 35,000 location instance...

The first easy options to tune computing time are:
- reducing exploration level using `-x`
- setting a timeout using  `-l`

Then there would probably be some more on the modelling side be that would be really dependent on the type of problem and the kind of constraints you have.

**Comment by napo** [comment]
Amazing!
I used vroom with the parameter  "-x' the with value 0.
If I use the vroom-express with ors as backend, the time for the calculation is less as 22 minutes.
The creation of the matrix with the script [add_ors_matrix.py](https://github.com/VROOM-Project/vroom-scripts/blob/master/src/add_ors_matrix.py) need 20 seconds.
Then using only the matrix, from the command line, and always with the parameter "-x 0" the calculation time is reduced to about 5 minutes and 30 seconds.
In this case I don't have the calculation of the geometries (which I can still obtain with several calls to ORS).
In any case I have to understand how to optimize.
I was thinking about reducing the number of points across [network-based spatial clusters](https://geoffboeing.com/2018/04/network-based-spatial-clustering/) (many of the points I have to locate are very close to each other) and then apply vroom in specific cases.

**Comment by jcoupey** [comment]
Any cluster-based approach you can use prior to solving will definitely drastically cut down the computing time. On the other hand when solving sub-problems as independent instances, you're also reducing the flexibility and the accessible solutions.

Closing here since the initial concern has been answered.
