### ISSUE TITLE
heterogenous fleet

### ISSUE THREAD

**Issue by mgalati13** [VROOM-Project/vroom#630]
Can vroom handle heterogenous (with respect to capacity) fleet? I see that each Vehicle object is asking for a capacity, but when I add a vehicle with differing capacity I get an error about "Inconsistent capacity length".

**Comment by mgalati13** [comment]
Never mind. I was using it wrong. Is there a mailing list for vroom? Or, are git issues the best way to communicate questions?

**Comment by jcoupey** [comment]
We don't have a mailing list so yes, the best way to discuss stuff is on this bugtracker. There are already quite a number of questions/discussions available in tickets to browse from.
