### ISSUE TITLE
interrupt handler

### ISSUE THREAD

**Issue by mgalati13** [VROOM-Project/vroom#632]
Would it be possible to add an interrupt handler (probably the best approach would be a callback that returns true or false set by the user) to allow the user to stop the execution? It could be checked similar to how Timeout is checked. 

This would allow the user to interrupt a long running search but still get back the best result found so far (similar to how Timeout works).

**Comment by jcoupey** [comment]
I get the idea and need behind this, can you elaborate on how you think we could do this technically in the C++ code?

**Comment by mgalati13** [comment]
Sure. Let me play around with it this week and I'll implement something basic and show you - then you can decide how to add it officially. The basic idea is just to send in a callback (function pointer in C, or whatever is equivalent in C++) which is checked periodically like time is checked to stop progress.

Thanks!

**Comment by jcoupey** [comment]
Closing as stale, feel free to re-open with new input if required.
