### ISSUE TITLE
Updating the exception class

### ISSUE THREAD

**Issue by jonathf** [VROOM-Project/vroom#639]
Topic for discussion.

How do we feel about refactoring the current implementation of `Exception`?

1. Could we add a `what` method to the exception? It is required if `pybind11` is to retrieve the underlying error message. This is as far as I can tell also idiomatic C++.

2. How do we feel about adding three subclasses: `InputException InternalException RoutingExeption` which hardcodes `ERROR` in their constructors? (Or perhaps deprecate the `ERROR` enum if it is no longer needed.) We then use the specific exceptions around in the codebase. It also works better on the Python side of things where the visual error representation is quite important.

3. An idea BTW that also is perhaps worth considering: Adding a `unsigned exit_code` attribute to the exception directly.
This way you can do:
    ```cpp
    } catch (const vroom::Exception& e) {
         std::cerr << "[Error] " << e.message << std::endl;
         vroom::io::write_to_json({e.error_code, e.message},
                             false,
                             cl_args.output_file);

    ```
    and you can replace:
    ```cpp
    //auto error_code = vroom::utils::get_code(vroom::ERROR::ROUTING);
    auto error_code = vroom::RoutingException().error_code
    ```
    `get_code` then becomes obsolete and can be removed.

**Comment by jcoupey** [comment]
Thanks for the suggestion. It would totally make sense to have dedicated subclasses for different kind of exceptions. I have the same feeling that in this case we could remove the `ERROR` enum altogether. Then removing the need for an external function to retrieve the code would also be much clearer.

**Comment by jcoupey** [comment]
Done in #641. Thanks @jonathf the exception logic is clearer and easier now!
