### ISSUE TITLE
Transferring pyvroom

### ISSUE THREAD

**Issue by jonathf** [VROOM-Project/vroom#645]
@jcoupey, to be able to transfer pyvroom to an organization, I need to be a member of said organisation with the access to create repositories.

Is it possibe to get access to the organization so I can transfer the repo?
Feel free to remove me afterwards if you don't want me there.

Alternatively I could transfer the repo to you personally, but that would require a double transfere which I think is a tad bit more messy.

**Comment by jcoupey** [comment]
Looks like the transfer is now effective! :tada: 

I did retrieve your membership for the whole organization, but upgraded your role from Write to Maintain for the `pyvroom` repo.
