### ISSUE TITLE
Assign New Points To Routes

### ISSUE THREAD

**Issue by lgmadurange** [VROOM-Project/vroom#646]
I Just Want To Know Is There Any Way That We Can Re Assign New Points To Already Available Routes...

As An Example (Pickup Points) - First We Calculare From All Available Vehicles And All Available Pickup Requests From Customers And Get Best Routes For Each Vehicle Through Vroom, Then Vehicles Going To Complete Those Pickups.

Meanwhile When i Receive A New pickup Request, i want to assign that new pickup request to the one of best already generated routes. (old route pickup points should not want to change, only want to assign new pickup request to best already generated route.) 

*Additionally I Have The Realtime GPS Locations Of The Pickup Vehicles, So It's Better That if i can assign that new pickup point using gps also.

**Comment by SirTypesALot** [comment]
The first problem we have to deal with is what defines as a "best route", either lowest route cost, lowest route completion time, or any other heuristic factor.

**Comment by lgmadurange** [comment]
> The first problem we have to deal with is what defines as a "best route", either lowest route cost, lowest route completion time, or any other heuristic factor.

best route means what is the lowest route compilation time from tha already generated routes.

**Comment by jcoupey** [comment]
What you can do is submit a new problem instance containing both already assigned tasks and new tasks in order to get an updated plan. Without additional constraints, it's possible that the new plan changes significantly from the previous one, for example if it's better overall that some tasks change vehicle or a different ordering is picked. Some ways to limit changes are:

1. if you need to make sure the new plan does not re-assign previously assigned tasks to other vehicles, you can pin them to a given vehicle by using `skills`.
2. as of `v1.11`, you can seed the search with the previous solution using `vehicle.steps` (see https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#in-solving-mode). This can help to get a "not too different" updated plan, but note that it comes at the cost of potentially missing other better solutions.

**Comment by lgmadurange** [comment]
> What you can do is submit a new problem instance containing both already assigned tasks and new tasks in order to get an updated plan. Without additional constraints, it's possible that the new plan changes significantly from the previous one, for example if it's better overall that some tasks change vehicle or a different ordering is picked. Some ways to limit changes are:
> 
> 1. if you need to make sure the new plan does not re-assign previously assigned tasks to other vehicles, you can pin them to a given vehicle by using `skills`.
> 2. as of `v1.11`, you can seed the search with the previous solution using `vehicle.steps` (see https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#in-solving-mode). This can help to get a "not too different" updated plan, but note that it comes at the cost of potentially missing other better solutions.

if i send another requests with old and new points with categorize them by skill , then think i'm assign additional 1 capacity to every old routes vehicles, then the new point is added to the first sending route, not for the best suitable route.

**Comment by jcoupey** [comment]
> then the new point is added to the first sending route, not for the best suitable route

I'm not sure I get what you mean here, what is the exact problem? Do you have a minimum working example of old and new input and output to illustrate?

**Comment by lgmadurange** [comment]
> > then the new point is added to the first sending route, not for the best suitable route
> 
> I'm not sure I get what you mean here, what is the exact problem? Do you have a minimum working example of old and new input and output to illustrate?

just like this, there is already generated route list, and i want to add the new pickup point to one of nearest route from that already generated route.

**Comment by jcoupey** [comment]
It's not really possible to help you without a precise description of what you see as a problem. Again, please share a minimum working example of old and new input and output to illustrate.

**Comment by lgmadurange** [comment]
as i figure out , i want is check the nearest vehicle from new pickup point, is there any way to check nearest vehicle point from that new pickup point. (i have vehicle location cordinates)

**Comment by jcoupey** [comment]
> check nearest vehicle point from that new pickup point. (i have vehicle location cordinates)

You don't need `vroom` for that, you can do it yourself with a single many-to-one request to the routing engine. Then you'll have all travel info from any vehicle location to your new pickup point and can make your own decision.

**Comment by lgmadurange** [comment]
may i know that how can i get that from osrm routing engine, do i have to send multiple requests to get the distance to each and every vehicle, or is there any requesting way that i can get the distance to one point to every vehicle from one single request ?

**Comment by jcoupey** [comment]
That's beyond the scope of this repo since it's purely routing-related. If you're using OSRM, you want to use the [table service](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#table-service).
