### ISSUE TITLE
vroom-front generates a better result than from vroom-backend

### ISSUE THREAD

**Issue by bouhirmani** [VROOM-Project/vroom#649]
Hi to everyone,

I can't understand why I get a better result from  [vroom-fontend](http://map.vroom-project.org/) than my _vroom-back_ setup with docker.
I'm getting for the same Json input a totally different result more congruent result. Why this is happening? 
As you can see in the right photo below,the green route is weird and completely incoherent, while, in the left photo, the routes are suitable.
**I'm using Vroom v1.11.0 with latest OSRM-backend**

![image](https://user-images.githubusercontent.com/12233826/149044815-a40568d9-c37e-4996-9f9a-24e257fe1e24.png)

here is my json: 
`{"vehicles":[{"id":0,"end":[-4.96039,34.00777],"capacity":[13],"time_window":[0,2700],"end_index":21},{"id":1,"end":[-4.96039,34.00777],"capacity":[13],"time_window":[0,2700],"end_index":21},{"id":2,"end":[-4.96039,34.00777],"capacity":[13],"time_window":[0,2700],"end_index":21}],"jobs":[{"id":85,"pickup":[1],"location":[-5.03111,34.04009],"location_index":0,"description":"85","service":0},{"id":78,"pickup":[1],"location":[-4.97815,34.01672],"location_index":1,"description":"78","service":0},{"id":71,"pickup":[2],"location":[-5.00657,34.01815],"location_index":2,"description":"71,72","service":0},{"id":90,"pickup":[1],"location":[-5.00999,34.00697],"location_index":3,"description":"90","service":0},{"id":66,"pickup":[1],"location":[-4.99723,34.0239],"location_index":4,"description":"66","service":0},{"id":86,"pickup":[2],"location":[-5.00865,34.04032],"location_index":5,"description":"86,87","service":0},{"id":89,"pickup":[1],"location":[-5.01077,34.00188],"location_index":6,"description":"89","service":0},{"id":70,"pickup":[1],"location":[-5.00323,34.01388],"location_index":7,"description":"70","service":0},{"id":68,"pickup":[2],"location":[-4.987,34.01968],"location_index":8,"description":"68,69","service":0},{"id":91,"pickup":[2],"location":[-5.01847,34.01681],"location_index":9,"description":"91,92","service":0},{"id":67,"pickup":[1],"location":[-4.98981,34.02445],"location_index":10,"description":"67","service":0},{"id":95,"pickup":[1],"location":[-5.05452,34.02216],"location_index":11,"description":"95","service":0},{"id":93,"pickup":[1],"location":[-5.02422,34.02908],"location_index":12,"description":"93","service":0},{"id":73,"pickup":[3],"location":[-5.00442,34.02632],"location_index":13,"description":"73,74,75","service":0},{"id":81,"pickup":[2],"location":[-5.01322,34.06098],"location_index":14,"description":"81,82","service":0},{"id":79,"pickup":[2],"location":[-4.99065,34.0333],"location_index":15,"description":"79,80","service":0},{"id":83,"pickup":[2],"location":[-5.03098,34.05752],"location_index":16,"description":"83,84","service":0},{"id":94,"pickup":[1],"location":[-5.02589,34.03118],"location_index":17,"description":"94","service":0},{"id":76,"pickup":[2],"location":[-4.97189,34.01316],"location_index":18,"description":"76,77","service":0},{"id":64,"pickup":[2],"location":[-4.97896,34.00942],"location_index":19,"description":"64,65","service":0},{"id":88,"pickup":[1],"location":[-5.01285,33.99964],"location_index":20,"description":"88","service":0}],"matrices":{"car":{"durations":[[0,1205,556,691,739,298,781,680,990,410,880,619,271,508,463,1082,414,283,1355,1327,828,1426],[1110,0,674,697,503,1105,787,485,446,769,454,1343,957,679,1061,419,1428,1061,161,304,806,328],[603,623,0,265,222,628,378,246,550,249,442,838,354,168,1003,530,939,458,774,745,425,978],[801,811,355,0,496,1022,133,314,741,446,732,1033,647,516,1201,785,1137,751,961,786,180,777],[658,484,263,354,0,683,464,241,323,432,218,891,443,252,1058,303,995,547,591,565,512,797],[274,1113,576,876,613,0,966,865,951,585,842,838,293,439,643,774,563,343,1305,1277,1013,1510],[885,738,449,93,588,1110,0,258,684,544,824,972,732,625,1285,878,1222,836,816,694,88,690],[626,505,182,194,361,854,307,0,443,272,599,863,476,342,1026,653,962,580,622,593,335,826],[906,160,470,483,349,1151,562,288,0,565,461,1138,753,601,1188,405,1242,857,309,282,610,514],[416,725,198,265,425,644,377,245,669,0,662,654,269,404,804,715,743,373,876,847,424,1080],[938,265,505,514,256,908,604,323,104,597,0,1171,700,416,1148,379,1274,804,415,387,645,619],[615,1630,941,921,1125,915,1016,1077,1405,798,1291,0,656,956,776,1360,683,760,1748,1487,991,1553],[241,932,343,534,528,360,624,523,809,271,701,480,0,361,633,776,572,108,1082,1170,671,1403],[597,735,189,434,342,659,528,414,690,422,580,832,385,0,997,634,933,489,886,857,575,1090],[515,1309,999,1147,1139,686,1236,1135,1171,855,1061,788,713,1116,0,826,230,675,1309,1499,1284,1459],[963,535,547,703,358,727,793,573,381,776,277,1166,718,358,717,0,948,848,600,683,840,749],[422,1534,869,1017,1053,650,1107,1005,1370,726,1219,664,584,883,280,1026,0,626,1659,1615,1154,1864],[320,1135,451,622,634,404,712,610,914,349,804,559,104,469,677,879,651,0,1286,1257,759,1490],[1293,162,857,880,665,1253,702,667,636,952,618,1550,1140,818,1209,569,1433,1244,0,325,683,240],[1211,296,774,624,588,1440,534,585,559,869,745,1453,1057,827,1398,674,1521,1161,120,0,516,335],[929,802,495,139,634,1154,46,304,731,422,870,904,775,671,1329,924,1266,879,759,637,0,635],[1465,352,1029,801,839,1667,711,840,810,1124,806,1525,1312,1204,1397,759,1775,1416,225,385,692,0]]}}}`

Backend response: 
`{"code":0,"summary":{"cost":6123,"routes":3,"unassigned":0,"delivery":[0],"amount":[0],"pickup":[32],"setup":0,"service":0,"duration":6123,"waiting_time":0,"priority":0,"violations":[],"computing_times":{"loading":0,"solving":90}},"unassigned":[],"routes":[{"vehicle":0,"cost":2574,"delivery":[0],"amount":[0],"pickup":[12],"setup":0,"service":0,"duration":2574,"waiting_time":0,"priority":0,"steps":[{"type":"start","location":[-5.05452,34.02216],"setup":0,"service":0,"waiting_time":0,"load":[0],"arrival":0,"duration":0,"violations":[]},{"type":"job","description":"95","location":[-5.05452,34.02216],"id":95,"setup":0,"service":0,"waiting_time":0,"job":95,"load":[1],"arrival":0,"duration":0,"violations":[]},{"type":"job","description":"85","location":[-5.03111,34.04009],"id":85,"setup":0,"service":0,"waiting_time":0,"job":85,"load":[2],"arrival":615,"duration":615,"violations":[]},{"type":"job","description":"86,87","location":[-5.00865,34.04032],"id":86,"setup":0,"service":0,"waiting_time":0,"job":86,"load":[4],"arrival":913,"duration":913,"violations":[]},{"type":"job","description":"73,74,75","location":[-5.00442,34.02632],"id":73,"setup":0,"service":0,"waiting_time":0,"job":73,"load":[7],"arrival":1352,"duration":1352,"violations":[]},{"type":"job","description":"71,72","location":[-5.00657,34.01815],"id":71,"setup":0,"service":0,"waiting_time":0,"job":71,"load":[9],"arrival":1541,"duration":1541,"violations":[]},{"type":"job","description":"66","location":[-4.99723,34.0239],"id":66,"setup":0,"service":0,"waiting_time":0,"job":66,"load":[10],"arrival":1763,"duration":1763,"violations":[]},{"type":"job","description":"67","location":[-4.98981,34.02445],"id":67,"setup":0,"service":0,"waiting_time":0,"job":67,"load":[11],"arrival":1981,"duration":1981,"violations":[]},{"type":"job","description":"78","location":[-4.97815,34.01672],"id":78,"setup":0,"service":0,"waiting_time":0,"job":78,"load":[12],"arrival":2246,"duration":2246,"violations":[]},{"type":"end","location":[-4.96039,34.00777],"setup":0,"service":0,"waiting_time":0,"load":[12],"arrival":2574,"duration":2574,"violations":[]}],"violations":[]},{"vehicle":1,"cost":2526,"delivery":[0],"amount":[0],"pickup":[12],"setup":0,"service":0,"duration":2526,"waiting_time":0,"priority":0,"steps":[{"type":"start","location":[-5.01322,34.06098],"setup":0,"service":0,"waiting_time":0,"load":[0],"arrival":0,"duration":0,"violations":[]},{"type":"job","description":"81,82","location":[-5.01322,34.06098],"id":81,"setup":0,"service":0,"waiting_time":0,"job":81,"load":[2],"arrival":0,"duration":0,"violations":[]},{"type":"job","description":"83,84","location":[-5.03098,34.05752],"id":83,"setup":0,"service":0,"waiting_time":0,"job":83,"load":[4],"arrival":230,"duration":230,"violations":[]},{"type":"job","description":"94","location":[-5.02589,34.03118],"id":94,"setup":0,"service":0,"waiting_time":0,"job":94,"load":[5],"arrival":856,"duration":856,"violations":[]},{"type":"job","description":"93","location":[-5.02422,34.02908],"id":93,"setup":0,"service":0,"waiting_time":0,"job":93,"load":[6],"arrival":960,"duration":960,"violations":[]},{"type":"job","description":"91,92","location":[-5.01847,34.01681],"id":91,"setup":0,"service":0,"waiting_time":0,"job":91,"load":[8],"arrival":1231,"duration":1231,"violations":[]},{"type":"job","description":"70","location":[-5.00323,34.01388],"id":70,"setup":0,"service":0,"waiting_time":0,"job":70,"load":[9],"arrival":1476,"duration":1476,"violations":[]},{"type":"job","description":"90","location":[-5.00999,34.00697],"id":90,"setup":0,"service":0,"waiting_time":0,"job":90,"load":[10],"arrival":1670,"duration":1670,"violations":[]},{"type":"job","description":"89","location":[-5.01077,34.00188],"id":89,"setup":0,"service":0,"waiting_time":0,"job":89,"load":[11],"arrival":1803,"duration":1803,"violations":[]},{"type":"job","description":"88","location":[-5.01285,33.99964],"id":88,"setup":0,"service":0,"waiting_time":0,"job":88,"load":[12],"arrival":1891,"duration":1891,"violations":[]},{"type":"end","location":[-4.96039,34.00777],"setup":0,"service":0,"waiting_time":0,"load":[12],"arrival":2526,"duration":2526,"violations":[]}],"violations":[]},{"vehicle":2,"cost":1023,"delivery":[0],"amount":[0],"pickup":[8],"setup":0,"service":0,"duration":1023,"waiting_time":0,"priority":0,"steps":[{"type":"start","location":[-4.99065,34.0333],"setup":0,"service":0,"waiting_time":0,"load":[0],"arrival":0,"duration":0,"violations":[]},{"type":"job","description":"79,80","location":[-4.99065,34.0333],"id":79,"setup":0,"service":0,"waiting_time":0,"job":79,"load":[2],"arrival":0,"duration":0,"violations":[]},{"type":"job","description":"68,69","location":[-4.987,34.01968],"id":68,"setup":0,"service":0,"waiting_time":0,"job":68,"load":[4],"arrival":381,"duration":381,"violations":[]},{"type":"job","description":"64,65","location":[-4.97896,34.00942],"id":64,"setup":0,"service":0,"waiting_time":0,"job":64,"load":[6],"arrival":663,"duration":663,"violations":[]},{"type":"job","description":"76,77","location":[-4.97189,34.01316],"id":76,"setup":0,"service":0,"waiting_time":0,"job":76,"load":[8],"arrival":783,"duration":783,"violations":[]},{"type":"end","location":[-4.96039,34.00777],"setup":0,"service":0,"waiting_time":0,"load":[8],"arrival":1023,"duration":1023,"violations":[]}],"violations":[]}]}`

Thanks in advance and have a great day.

**Comment by jcoupey** [comment]
If you lookup the POST data sent by the frontend, you'll see that jobs and vehicles are copied over but the `matrices` key is not passed through so the travel times are recomputed on the frontend side with a different OSRM stack and OSM extract.

The solution is not better, it's just different because the underlying routing values differ.

**Comment by bouhirmani** [comment]
Thank you for your reply,
But for the route in the green color, How can we understand this strange behavior, it's looping twice to pickup the jobs in the middle , As you can see bellow: 
Is there a way to improve this behavior?


![image](https://user-images.githubusercontent.com/12233826/149124156-9cccd85b-b955-4bd4-8d10-1827089bf5a0.png)

Thanks in advance and have a great day.

**Comment by braktar** [comment]
It seems that points number 4 and 5 are projected on one side of the RN4 which have two lanes separated by a median street. So they can only be reached by the closest lane. So instead of making a turn around at a cross of the RN4 a shortest route is performing 3 and then 4 and 5. Usually, such detour is easily balanced by the time past by the driver to try to cross such large road safely.

**Comment by bouhirmani** [comment]
In my Jobs, I pickup people who can cross the road, they can walk to the other side of the road, is there any way to tell Vroom to consider this option, pickup people on the opposite road instead of adding a round trip ?

Thanks in advance

**Comment by bouhirmani** [comment]
Is there any answer for my last question plz ?

**Comment by jcoupey** [comment]
No, there is no way to change that. The coordinates you're providing are snapped to the road network by whatever underlying routing engine you use. VROOM will only make its best to reduce overall travel time based on the computed matrix translated from the described problem. In other words, if a person crosses the road to be picked up on the other side, then you're basically solving a different problem.

**Comment by jcoupey** [comment]
Closing as answered.
