### ISSUE TITLE
Amounts in Shipments

### ISSUE THREAD

**Issue by fsty** [VROOM-Project/vroom#650]
Hi! I have a use case where the driver has to put "return" packages in the pickup location before loading new ones. Can we define amount at the pickup/delevery level instead of the shipment level  ?

**Comment by jcoupey** [comment]
Shipments model a typical pickup-and-delivery situation where you move some stuff from pickup to delivery. This is why the `amount` key is at shipment level.

In your case, you could model the return as an additional `job` object located at the same place.

**Comment by fsty** [comment]
Thanks for the quick answer! and yes I'm using `job` today to model retrun
