### ISSUE TITLE
Update libosrm version in CI

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#651]
We currently check builds against v5.25.0 of libosrm, but v5.26.0 has been released a while back. We should update to trigger caching a new libosrm version for the GitHub Actions workflow.

**Comment by gauravagrwal** [comment]
Hi @jcoupey, I would to take this.
Just to confirm here we need to update the version of libosrm to v.5.26.0 in the workflow file ?

**Comment by jcoupey** [comment]
Yes, then we'd have to make sure the new version is properly cached for subsequent workflow runs.

**Comment by gauravagrwal** [comment]
@jcoupey, I believe the new version will be cached as for caching we are using osrm-tag which now has the updated version.

**Comment by jcoupey** [comment]
Landed with #652.
