### ISSUE TITLE
Using `unsiged int` for `violoation.types` instead of `std::unordered_set<VIOLATION>`?

### ISSUE THREAD

**Issue by jonathf** [VROOM-Project/vroom#653]
Could we perhaps consider represent violations as `unsigned int`(or even `usigned char`):
```
unsigned int VIOLATION_LEAD_TIME = 1;
unsigned int VIOLATION_DELAY = 2;
unsigned int VIOLATION_LOAD = 4;
unsigned int VIOLATION_MAX_TASKS = 8;
...
```
The idea is that each violation is represented with a single bit at various positions (base 2).

Doing this, we get:
* No violations is `violation.types = 0;` (we could perhaps add a `NO_VIOLATION = 0;` for readability).
* adding violations is done with e.g. `violations.types |= VIOLATION_LEAD_TIME`.
* The case-switch used to extract violation type in `output_json` can be replaced with e.g. `if (type & VIOLATION_LEAD_TIME)`.

This should be both faster and require less memory on the C++ end as unordered_sett is pretty much garantied to require a pointer to memory ouside of the struct they reside in. But at the same time, I also doubt we'll see any speed or memory improvements in practice as this is tiny and it does not represent a bottleneck.

On the plus-side though, violations can with this be referenced by the buffer-protocol which makes the Python interface potentially much nicer.

**Comment by jcoupey** [comment]
I get the idea of packing stuff in a memory-saving data structure, but as you mention this is not going to make much difference here as the violations are not critical memory-wise and in the way there's used. Then there are two things that we'd break with such a change:
- we'd drop the use of an `enum class` which is the idiomatic way for this kind of stuff;
- using violations in client code (with `&` and `|=`) would now require to understand the inner packing details.

For those reasons I don't think it's a good idea to change the current behavior in C++. Now in order to make things accessible for the Python bindings, maybe we can provide a getter returning this kind of encoded value for an `unordered_set` and put it behind a compile flag?

**Comment by jonathf** [comment]
Fair enough. One of the things that allowed me to make the pyvroom wrapper so easily in the first place was how idiomatically and simple you have structured the code. Deviating like I'm proposing is counter to those ideas, so I totally understand.

Regarding a getter.

If we give up on the idea of having contiguous memory for the structs and instead want to use getters, then it has to be in such a way that it is done on an array level. Something like putting some methods (behind compile flags) on `Solution` that extract vectors of properties from `std::vector<Route>` or `std::vector<Job>`.

Could that work?

This approach kind of assumes that we are able to convert an array of structs where we ignore some of the elements that are pointers, since we really do not want to make a extraction method for every single property in the nested `Solution` struct. I imagine this is possible, but I'll have to look into it.

**Comment by jonathf** [comment]
Pybind11 understands unordered_set and enums just fine, and in a pure python setting, this would also be a natural approach if I were to create vroom in pure python.

Python is a great language for many things, but it is slow.

The current implementation first do a cast from C++ to Python for every object in `Solution`. Afterward we loop through it and copy it back to C with numpy, before presenting the numpy-python object to the user. And this is slow. Not only because of Python, but the copying element-for-element in and out of the extension environment has a lot of extra overhead. We are only talking about ~100 ms in practice, but it is not nothing, I'd like to improve on it if I can.

The fastest and most elegant solution would be as I initially propose to have a `std::vector<Route>` and `std::vector<Job>` to be contiguous in memory, since then we can bypass the need to go through Python for Numpy to access all the data. It will then be zero-copy and ready-to-go with a pointer and some metadata.

Since contiguous memory is out of the question, the second idea is to copy the missing data in C++ into contiguous vectors and present it to numpy. One loop-through and one copy in C++ is still hell of faster than anything Python can do.

But as I am writing this I realizing this getter code does not need to live in vroom. If we take contiguous memory of the table, we can place this code inside the C++ binding layer in pyvroom. I am therefore closing this issue for now.
