### ISSUE TITLE
can vroom handle vehicle dependent costs?

### ISSUE THREAD

**Issue by mgalati13** [VROOM-Project/vroom#654]
Can vroom handle vehicle dependent costs?

The API I am using now is set_costs_matrix - but this is constant for each vehicle.

**Comment by jcoupey** [comment]
We handle *profile*-dependent costs:

https://github.com/VROOM-Project/vroom/blob/ae413af69663c3ce1c67b134f48b647920f97837/src/structures/vroom/input/input.h#L104

so all vehicles with the same profile share the same costs. This being said, there is nothing preventing you from assigning each vehicle its own profile, provided you feed all the matching matrices.

Another way to adjust costs (actually rather travel times) is the `speed_factor` key that applies at vehicle level.

**Comment by jcoupey** [comment]
Closing as answered.
