### ISSUE TITLE
Automatic code formatting

### ISSUE THREAD

**Issue by jcoupey** [VROOM-Project/vroom#66]
There is currently no way to ensure that code format is consistent throughout the code-base. We should set up a script to provide both a formatting reference and an automated tool. Using `clang-format` sounds like a good option.

**Comment by PattyDePuh** [comment]
Welcome back and thanks for the merge, (finally)  👍 
to automate code format consistency is something i never thought before, that it even exist.
After rushing over the documentation of `clang-format` it might be our choice of tool.
