### ISSUE TITLE
can explicit cost matrix be reused for duration matrix?

### ISSUE THREAD

**Issue by mgalati13** [VROOM-Project/vroom#662]
In the case when the duration matrix is the same as the cost matrix (e.g., Solomon VRPTW instances), we don't need a duration matrix.

I tried to pass just the cost matrix, but got an error about invalid profile. Is it possible to just set_costs_matrix, or do you always need set_durations_matrix as well?

**Comment by jcoupey** [comment]
> we don't need a duration matrix

I would state it the other way around: we always need a duration matrix to account for time windows validity and report ETA. It's just that costs are identical to durations in that case.

So you'll indeed get an error if you don't provide durations, but you can omit setting the cost matrix, we'll default to using the durations matrix as cost matrix. This happens in `set_vehicles_costs` (which you don't have to worry about calling yourself):

https://github.com/VROOM-Project/vroom/blob/abc6c77710ddeac8e07fe264492d8c640b70212b/src/structures/vroom/input/input.cpp#L529-L536

**Comment by mgalati13** [comment]
OK. Got it. Thank you!
