### ISSUE TITLE
Can VROOM add a start cost for a vehicle?

### ISSUE THREAD

**Issue by eray94** [VROOM-Project/vroom#663]
Hello,

I have been using VROOM for a while now and I would like to thank you for your efforts.

I was wondering, is it possible to add a cost to the start step? As far as I understand now, we can change the arrival when a time window is given on the vehicle, but the duration(cost) always remains 0.

I want to add a start cost for the relevant vehicle. The work around I could find was to use the shipment structure instead of jobs and add the cost to the cost_matrix[vehicle_start_index, pick_up_index]. For a system with a single pick up point, this approach worked pretty well. But I'm trying to ensure that pick up is done on any vehicle, I mean pick up can be done on any vehicle. When I add imaginary pick up points for each vehicle, I am stuck with the problem that the location index in the pickup object is a single point and the relevant order is only pickable for one vehicle. For this reason, the shipment structure is not very suitable for my problem.

Adding a value to the cost_matrix[vehicle, vehicle] is not worked. I think calculation directly start from vehicle to job and continue with other jobs. 
Starting from here, I was able to reach a solution like this: 
I think I can manipulate the cost matrix just adding the "start cost" to all vehicle rows' job columns (cost_matrix[vehicle_indexes][:,job_indexes]). 

This simply solves the problem but it seems like a pretty dirty solution to me, do you know of a more naive way of doing this with VROOM?

To be more specific, is it possible to add a duration (cost) in this field?

{ "type": "start",
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "load": [
                        6
                    ],
                    "arrival": 0,
                    "duration": 0,
                    "violations": [] }

Thanks in advance!

**Comment by jcoupey** [comment]
Can you explain what exactly is the need behind this? Is it rather a matter of cost or duration?

If you want to account for the time it takes to load a vehicle at startup then what about simply pushing the availability date of the vehicle later via its time window?

**Comment by eray94** [comment]
It is related with cost. The time window approach you mentioned works very efficiently in adding the load time of the vehicle, but it has no direct cost effect.

I would like to assign an initial cost to each vehicle. My purpose in doing this is to inject the other information I have into the cost matrix. Using time window is not work here because as long as vehicles can satisfy the time window constraint, there will be no differences among vehicles in terms of cost.

For a toy example:
Cost Matrix:
        V1 V2   J1  
V1.   0.   0.   4
V2.   0.   0.   5
J1    4.   5.   0

Assume that there is no time window or capacity related limitation.
Here, I would like to indicate that using Vehicle_1 has cost: 3 and Vehicle_2 has cost: 1, so using Vehicle_2 for Job_1 will be cheaper. I mentioned the way of doing this in my previous comment but I wonder can it be done in a different way. Because, there is a start step which always have 0 cost. Is there any way to change start step cost ?

**Comment by jcoupey** [comment]
If you mean you want to favor using some vehicles over others because they have different fixed costs, then this is ticketed in #528.
