### ISSUE TITLE
Make cleaner separation between parser and main.

### ISSUE THREAD

**Issue by jonathf** [VROOM-Project/vroom#665]
Currently the main interface creates CLArgs to parser arguments, which (depending on input) get passed down into the vroom machinery.
For the most part this is done cleanly in such a way that you don't need CLArgs to use any machinery, with input parser being the only exception.

I propose we make the interface cleaner by keeping CLArgs contain to the main file and just passing it's attribute along explicitly.

**Comment by jcoupey** [comment]
Yes, makes perfect sense.

**Comment by jonathf** [comment]
Before mergin though (or after for that matter), I am wondering if I need to make an adjustment here.

The problem I am realizing I will be faced with is that as soon as sub-class Input, using the parser will be unavailable.
So to be able to subclass Input, I either need to copy content over, or make my own parser.

A better solution, I think, is to initialize Input in `main` and only pass `input` and `input_str` to the parser function. That way, any subclass of Input can also use the parser to fill in content from json.

Sounds good?

**Comment by jcoupey** [comment]
What would be the need behind inheriting from `Input`?

**Comment by jonathf** [comment]
I subclass the C++ classes in Python to add lots of extra Python features which is a lot more difficult to do from pure C++.

**Comment by jcoupey** [comment]
I have no problem to use another approach and maybe you can sketch that in a separate PR, but I fear that you won't be able to create an `Input` object outside of the parsing code since the ctor requires to know the size of the amounts arrays in the first place.

**Comment by jcoupey** [comment]
This has been merged with #666, thanks @jonathf.
