### ISSUE TITLE
Corrupt or lossy polyline from vroom

### ISSUE THREAD

**Issue by andre-kotze** [VROOM-Project/vroom#674]
Using OSRM and VROOM front-ends I get brilliant-looking linestrings, but the encoded polyline output from OSRM and VROOM decodes to a degraded linestring. i.e. the geometries generated from routing plot perfectly to the ways, but the geometry decoded from "encoded polyline" format are almost completely wrong, going through street blocks and into the river in some instances. This is what decoded polyline looks like (in Lisbon):
![image](https://user-images.githubusercontent.com/78106172/153909899-9da26edc-f153-4f62-9ede-5a4aca2acdf5.png)
I get exactly the same weird polyline using @mapbox/polyline decoder, Google's Interactive Polyline Encoder Utility, and ST_LineFromEncodedPolyline function in PostGIS...

Here is the OSRM geometry for the same request (but not the same as the first image), with decoded polyline on the left and geojson on the right:
![image](https://user-images.githubusercontent.com/78106172/153912652-70725be1-e754-4a0c-b483-82412d8dc19d.png)
They start out identical, but then the polyline deviates extremely...

In OSRM, it's possible to specify the output geometry type. The resulting GeoJSON is flawless. Is it possible to do the same thing in VROOM, to get a GeoJSON geometry result instead of encoded polyline? Or is there something I'm missing with the decoding process? Thanks!

**Comment by andre-kotze** [comment]
I have just tried a different encoder, the one from PostGIS. Taking:
`SELECT ST_AsEncodedPolyline(ST_GeomFromGeoJSON('<<the GeoJSON output from OSRM>>'))`
yields a different encoded polyline. And decoding that again gives the correct geometry:
![image](https://user-images.githubusercontent.com/78106172/153964395-bc3cdc7a-4a3e-48b9-849c-2e890153b232.png)
So it seems to me that the OSRM polyline encoder is at fault? Please help

**Comment by jcoupey** [comment]
The `route.geometry` keys are indeed encoded polylines and we don't have an option to return a geojson-like array of coordinates. 

What is puzzling me here is that we're only passing the OSRM polyline output to the route geometry without any treatment inside VROOM. This means that you should normally be able to debug (or reproduce) this at the OSRM level.

A few ideas to move forward:

- lookup OSRM logs and reproduce route requests to make sure outputted polylines match between VROOM and OSRM;
- check that you're able to decode raw polylines from OSRM;
- check out the `precision` parameter you're using for decoding;
- check out how the decoding happens [in `vroom-frontend`](https://github.com/VROOM-Project/vroom-frontend/blob/master/src/utils/data_handler.js#L835);
- check that there is no character escaping problem anywhere in your toolchain.

**Comment by Orthae** [comment]
Could you provide the polyline? I'm assuming this issue is caused by passing the string with escape characters as raw string. If you remove escape characters, it should behave fine.

Here is similar issue: https://github.com/VROOM-Project/vroom/issues/543

**Comment by SrNetoChan** [comment]
@andre-kotze If you solved your problem, it's a good practice to close the ticket.

**Comment by andre-kotze** [comment]
Thanks @jcoupey , @Orthae , @SrNetoChan it is in fact the same issue as #543 , I had tried already to remove escape characters but I was removing all backslashes (including the required ones). Parsing the polylines from json (as opposed to copying and pasting raw strings) solved the problem... Thanks a lot!
