### ISSUE TITLE
Vroom does not choose the closest vehicle

### ISSUE THREAD

**Issue by seriousTom** [VROOM-Project/vroom#677]
Hi, I have a strange problem, I don`t know is it a problem or just how vroom works. I have two vehicles - Vehicle A and Vehicle B and two cities - City A and City B.  And Vehicle A start/end locations are in the City A and Vehicle B start/end locations are in the City B. And I have all orders located in City B. So logically thinking on route optimization Vehicle B should be used to deliver orders because it is in the same city. But Vehicle A is used instead who is in another city. Unless I pass Vehicle B first to the vehicles array. I noticed that Vroom uses vehicles in a row I pass to vehicles array and ignore the distance to the orders location. Is it possible to change that behavior? Maybe my request is bad?

My request:
`
{
    "vehicles": [
        {
            "id": 142,
            "start": [
                25.6379788,
                55.5086936
            ],
            "end": [
                25.6379788,
                55.5086936
            ],
            "capacity": [
                10000,
                30
            ],
            "time_window": [
                28800,
                82800
            ]
        },
        {
            "id": 143,
            "start": [
                25.6379788,
                55.5086936
            ],
            "end": [
                25.6379788,
                55.5086936
            ],
            "capacity": [
                10000,
                30
            ],
            "time_window": [
                28800,
                82800
            ]
        }
    ],
    "jobs": [
        {
            "id": 44799,
            "location": [
                23.9003266,
                54.8979619
            ],
            "service": 600,
            "time_windows": [
                [
                    28800,
                    82800
                ]
            ],
            "delivery": [
                1,
                1
            ]
        },
        {
            "id": 44800,
            "location": [
                23.9575474,
                54.8615219
            ],
            "service": 600,
            "time_windows": [
                [
                    28800,
                    82800
                ]
            ],
            "delivery": [
                462,
                1
            ]
        },
        {
            "id": 44801,
            "location": [
                23.9003266,
                54.8979619
            ],
            "service": 600,
            "time_windows": [
                [
                    28800,
                    82800
                ]
            ],
            "delivery": [
                1,
                1
            ]
        },
        {
            "id": 44802,
            "location": [
                23.9313357,
                54.9058503
            ],
            "service": 600,
            "time_windows": [
                [
                    28800,
                    82800
                ]
            ],
            "delivery": [
                1,
                1
            ]
        },
        {
            "id": 44803,
            "location": [
                23.9575474,
                54.8615219
            ],
            "service": 600,
            "time_windows": [
                [
                    28800,
                    82800
                ]
            ],
            "delivery": [
                1,
                1
            ]
        },
        {
            "id": 44804,
            "location": [
                23.9003266,
                54.8979619
            ],
            "service": 600,
            "time_windows": [
                [
                    28800,
                    82800
                ]
            ],
            "delivery": [
                1,
                1
            ]
        }
    ],
    "shipments": [],
    "options": {
        "g": true
    }
}`

**Comment by jcoupey** [comment]
Both vehicles in your request are absolutely identical (except for the id). In this case using one or the other does not really matter.
