### ISSUE TITLE
how to avoid toll 

### ISSUE THREAD

**Issue by simpian** [VROOM-Project/vroom#678]
in ORSM, there is an exclude flag to exclude toll from routing, how do I pass that through vroom?

**Comment by jcoupey** [comment]
There is no built-in way to pass extra routing parameters trough VROOM. If you always need to exclude tolls, you have several options:

- configure your OSRM extract step to exclude toll roads in the first place;
- have your OSRM instance default to excluding tolls for all requests;
- add the parameters directly [in the `OsrmRoutedWrapper` constructor](https://github.com/VROOM-Project/vroom/blob/06af8717ec292a13ce2f7a9a541e41180b9c56da/src/routing/osrm_routed_wrapper.cpp#L22-L23).

**Comment by simpian** [comment]
i'm currently using docker-compose to set up vroom instance, is there a parameter for avoiding tolls?

**Comment by jcoupey** [comment]
Not at VROOM level, you have to set this in some way at the OSRM level (see suggestions above).

**Comment by simpian** [comment]
ok, thanks for answering my questions, i will modify car.lua to avoid tolls in this case.
