### ISSUE TITLE
problem with break

### ISSUE THREAD

**Issue by napo** [VROOM-Project/vroom#681]
I have 4 deliveries very close to each other (4 points within 200 meters).
I have a vehicle that leaves from a place about 25 minutes away from the delivery area and returns in another to about 20 minutes.
The vehicle's time_window variable is set in the range 7:30 - 17:45 with a break from 12:30 to 13:45.
The solution I receive from vroom places me the departure of the vehicle 20 minutes before the break and from here - during the time slot of the break - it proposes the 4 deliveries (about 4 minutes of activity) and subsequent return.
What I would have expected is that the break isn't even considered as everything can be done before the break.
I can understand that it is preferable to propose to arrive in the delivery area, take advantage of the break and then start the deliveries. 
Except that, in this case, the solution suggest to work (delivery and return) in the time window for the break.
You can find my json here - https://gist.github.com/napo/e2f588a2c424c82f23038886f47d2ef7#file-delivery_in_break_window-json

**Comment by jcoupey** [comment]
> What I would have expected is that the break isn't even considered as everything can be done before the break.

Breaks are mandatory, which means they will always be inserted in routes in output.

In your example, the break is the only step that has a constraining time window so it "attracts" the tasks around it time-wise. If you want to have the break ignored, you can simply resolve without the break and you'll then get a planning starting ASAP.

**Comment by napo** [comment]
Thanks @jcoupey for the answer and I understand your point.
What for me is a surprise is that the solution declares to work during the breaking time.
If vroom i"attracts" the tasks around the break time, my expectation is to see the vehicle to  work for the needed time  for the delivery, stop before after the breaking time, and later reach the stop point.
In this case the solution is to work inside the time window dedicated to the break.

**Comment by jcoupey** [comment]
It's hard to see what you precisely mean without a solution, and the one I could get myself may be different from yours depending on the underlying routing stack.

Can you share [a standalone problem instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) and point exactly to the arrival time that puzzles you in the solution?

**Comment by napo** [comment]
@jcoupey the file is here https://gist.github.com/napo/8dcffd99b06556cee7ec7a8aec7d7d6f#file-input_breaks-json 
How can see the time window for the break is from 12:30 to 13:45.
The solution shows these arrivals for each step:
1. 12:06:57
2. 12:30:00
3. 12:31:15
4. 12:31:45
5. 12:32:36
6. 12:32:58
7. 12:32:59
8. 12:52:33

The point 1 is the start, the point 8 is the end, all the intermediates points are the jobs ... and the activity is proposed during the break time.<Br/>
Ok that the overlap with the break is only of 3 minutes, but my expectation is to see the begin of the activity after the break or some minutes before.

**Comment by jcoupey** [comment]
I don't really get what you consider wrong here: break starts exactly at 1646047800 which is the earliest possible time based on its time window. Then it lasts for 75 seconds (`service` value), then the vehicle moves on to other tasks.

Or were you expecting a 75 *minutes* break?

**Comment by napo** [comment]
Thanks!
You solved my issue.
