### ISSUE TITLE
Calculate route with multiple pick-up and delivery points with a single vehicle 

### ISSUE THREAD

**Issue by neosaldina** [VROOM-Project/vroom#687]
Well, I believe the title is self explanatory.... 
Even so, I will explain 

I have 3 pickup points:
Pickup  id 1: 
- Delivery Id 100
- Delivery Id 200
- Delivery Id 300

Pickup  id 2: 
- Delivery Id 150
- Delivery Id 250
- Delivery Id 350

Pickup  id 3: 
- Delivery Id 550
- Delivery Id 650
- Delivery Id 750

let's assume my start point is at pickup 1 
Pickup point 2 is between deliverys 200 and 300, and the other deliveries are much further away from delivery 300 

So I imagine the best route would be: 
- pickup Id 1:
- do delivery 100
- do delivery 200
- pickup id 2
- do delivery 300
- do delivery 250
- do delivery 150
- pickup id 3
- do delivery 750
- do delivery 350
- do delivery 550
- do delivery 650

The route cargo, and the courier has a lot of space to make this deliverys
So, How I could calculate such kind of route ?

I've read and reread the documentation but I can't formulate a json that provides the rules to do this type of calculation 

Thanks

**Comment by bencz** [comment]
@neosaldina 
Make something like this:

```
{
  "vehicles": [
    {
      "start": [
        -46.755563223706545,
        -23.52408993487887
      ],
      "capacity": [
        200
      ],
      "id": 1
    }
  ],
  "shipments": [
    {
      "amount": [
        1
      ],
      "pickup": {
        "id": 101,
        "description": "Pickup - 101",
        "location": [
          -46.755563223706545,
          -23.52408993487887
        ]
      },
      "delivery": {
        "id": 1,
        "location": [
          -46.75669025258469,
          -23.523709768243975
        ],
        "description": "Delivery - 1"
      }
    },
    {
      "amount": [
        1
      ],
      "pickup": {
        "id": 102,
        "description": "Pickup - 102",
        "location": [
          -46.755563223706545,
          -23.52408993487887
        ]
      },
      "delivery": {
        "id": 2,
        "location": [
          -46.759336900563824,
          -23.5228701245364
        ],
        "description": "Delivery - 2"
      }
    },
    {
      "amount": [
        1
      ],
      "pickup": {
        "id": 103,
        "location": [
          -46.75832493974105,
          -23.523192084115454
        ],
        "description": "Pickup - 103"
      },
      "delivery": {
        "id": 3,
        "location": [
          -46.764488458289556,
          -23.52119062985865
        ],
        "description": "Delivery - 3"
      }
    },
    {
      "amount": [
        1
      ],
      "pickup": {
        "id": 104,
        "description": "Pickup - 104",
        "location": [
          -46.75832493974105,
          -23.523192084115454
        ]
      },
      "delivery": {
        "id": 4,
        "description": "Delivery - 4",
        "location": [
          -46.88394454360685,
          -23.50431139185641
        ]
      }
    }
  ]
}
```

**Comment by jcoupey** [comment]
You indeed have to model each flow with a `shipment` object, so in your case 3 x 3 = 9 shipments.

> So I imagine the best route would be:

From the VROOM point of view, you'd have one task per pickup with all 3 pickups happening at the same place. So provided you have enough capacity/time, the solution route steps would actually look like:

- pickup for 100:
- pickup for 200:
- pickup for 300:
- do delivery 100
- do delivery 200
- pickup for 150
- pickup for 250
- pickup for 350
- do delivery 300
- do delivery 250
- do delivery 150
- pickup for 550
- pickup for 650
- pickup for 750
- do delivery 750
- do delivery 350
- do delivery 550
- do delivery 650

**Comment by bencz** [comment]
@jcoupey This could be interesting feature ... allow multiple deliveries from a single pickup, something like: 

```
    {
      "amount": [1],
      "pickup": {
        "id": 104,
        "description": "Pickup - 104",
        "location": [
          -46.75832493974105,
          -23.523192084115454
        ]
      },
      "deliverys":[ {
        "id": 4,
        "description": "Delivery - 4",
        "location": [
          -46.88394454360685,
          -23.50431139185641
        ]
      },
     {
        "id": 5,
        "description": "Delivery - 4",
        "location": [
          -46.88394454360685,
          -23.50431139185641
        ]
      }]
```

**Comment by jcoupey** [comment]
@bencz I don't think it would bring anything in term of modeling options over having two separate shipments.
