### ISSUE TITLE
avoid tolls

### ISSUE THREAD

**Issue by phiavogadro** [VROOM-Project/vroom#688]
It can be done with osrm on a request basis :
http://YOURIP:5000/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true&exclude=toll

please not that The server behind router.project-osrm.org can no longer support excludes due to capacity; You will have to use your own instance where you can enable exclude classes.

is there a way to pass exclude parameters from vroom ?

thanks !

**Comment by jcoupey** [comment]
TL;DR there is currently no way to do this at VROOM level but you can make it the default on your OSRM instance.

I'm closing this ticket in favor of #584 containing answers and pointers to options to manage this kind of need.
