### ISSUE TITLE
/bin/sh: vroom: command not found

### ISSUE THREAD

**Issue by usman-xs4arabia-dev** [VROOM-Project/vroom#689]
I have installed vroom successfully but when I try to run curl command I'm getting this error.

**Comment by nilsnolde** [comment]
how did you "install" it? AFAIK there's no install target in the makefile. and just compiling doesn't install (installation is copying relevant files to well-known locations), so likely your executable is still in `./bin/vroom` [as per docs](https://github.com/VROOM-Project/vroom/wiki/Building)?

**Comment by usman-xs4arabia-dev** [comment]
> 

Yes I just compiled it using make command. And my executable is still in ./bin/vroom. Btw where should I place those executable files? I haven't found any specific documentation regarding to this.

**Comment by nilsnolde** [comment]
it's standard linux stuff: executables need to be in a $PATH folder if you want to call them without the full path. I usually put a symlink to /usr/local/bin. note, that's out-of-scope for this repo, but with those hints you'll manage.
