### ISSUE TITLE
Latest Master branch: gives me "Invalid vehicle"

### ISSUE THREAD

**Issue by DDAK** [VROOM-Project/vroom#694]
**Issue:**
When using [example_2.json](https://github.com/VROOM-Project/vroom/blob/master/docs/example_2.json) calling latest vroom built using latest master branch, I get `'{"code":2,"error":"Invalid vehicle."}\n'`. This example used to work previously.

**Comment by jcoupey** [comment]
This example still works for me at aa3a1ee. Besides we have [a CI check](https://github.com/VROOM-Project/vroom/blob/aa3a1eeae2252544c85da354c6cb8415280eb988/.github/workflows/vroom.yml#L34) on this example so we should have noticed a break.

Maybe this is related to the build changes in #604. Can you make a fresh new build to check, running `make clean` then `make`?

If you're at aa3a1ee, you should not be able to build without the cxxopts submodule. I think you need to run:

```
git submodule init
git submodule update
```

**Comment by DDAK** [comment]
hi @jcoupey,

Thanks for the prompt reply. Yes, [aa3a1eeae,]( https://github.com/VROOM-Project/vroom/commit/aa3a1eeae2252544c85da354c6cb8415280eb988) breaks my build with following error: 
```
#7 1.712  #include "../include/cxxopts/include/cxxopts.hpp"
#7 1.712           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#7 1.712 compilation terminated.
#7 1.717 make: *** [makefile:76: main.o] Error 1
------
executor failed running [/bin/sh -c git clone --depth 1 https://github.com/VROOM-Project/vroom.git &&     mkdir vroom/bin &&     cd vroom/src &&     make &&     cp ../bin/* /usr/local/bin &&     strip /usr/local/bin/*]: exit code: 2
```
I think is related to the cxxopts submodules.  

As of now, I am using the per-merge version. However, I have tracked that to `headers` missing in the `post.request()` I was making. headers should be
`headers = {
  'Content-Type': 'application/json'
}` and passed explicitly.  

Thanks for your prompt reply.
