### ISSUE TITLE
Question: possible to have more steps in shipments?

### ISSUE THREAD

**Issue by ThomasRambaud** [VROOM-Project/vroom#704]
Hello,
Thanks for your awesome solution!

This is more a question than an issue: is it possible to have more steps in shipments than just pickup and delivery? 
Sometimes, after the delivery, our vehicles has to go back to the pickup location.

Like : 
pickup -> delivery -> pickup

I was hoping that we could set more steps in shipments. Or to have jobs with job dependencies.

Your input would be welcome!
Thank you

**Comment by braktar** [comment]
Hi ! 
There is currently not "relation" concept except the shipment within VROOM.
Nevertheless, you can guide the resolution to have two shipments consequently in the same route. You can define a setup duration on the second pickup. This will have for consequence to increase the insertion cost of this second shipment except right after the first one.

```
"shipments": [
    {
      "amount": [
        1
      ],
      "pickup": {
        "id": 4,
        "service": 300,
        "location": [
          2.41808,
          49.22619
        ]
      },
      "delivery": {
        "id": 3,
        "service": 300,
        "location": [
          2.39719,
          49.07611
        ]
      }
    }, {
      "amount": [
        1
      ],
      "pickup": {
        "id": 5,
        "setup": 300,
        "location": [
          2.39719,
          49.07611
        ]
      },
      "delivery": {
        "id": 6,
        "service": 300,
        "location": [
          2.41808,
          49.22619
        ]
      }
    }
  ]
```

**Comment by ThomasRambaud** [comment]
Thank you @braktar for your answer. But I think your solution is not reliable as it only works in this specific scenario with 2 shipments (my problem involves hundreds of shipments), and the service duration trick might negatively affect the solution quality and ETAs. 

My take is that it's not possible with Vroom at the moment, can anyone confirm?

**Comment by braktar** [comment]
There is currently no feature to force two shipments to belong to the same route

**Comment by ThomasRambaud** [comment]
Thank you @braktar for your answer, my question is not to have two shipments belong to the same route. 
My question is to have a job being done after one another (to modelize a shipment roundtrip: pickup -> delivery -> back to pickup). It seems that it's not possible but I'd like confirmation.

**Comment by braktar** [comment]
Oh, sorry, for the partial answer. Here are more details: 
A prerequisite to have a pickup -> delivery -> 2nd pickup is to be allowed to force multiple jobs or shipments to belong to the same route. The second prerequisite is to force an ordered set of jobs to be performed in a given order. 

None of these two constraints is currently possible through VROOM. The only exception is the shipment which only link one pickup and one delivery

**Comment by ThomasRambaud** [comment]
Alright, thanks for your input @braktar :) It's clear
I close the issue, have a nice day!

**Comment by jcoupey** [comment]
This is kind of similar to #581 that has a bit more context on (lack of) precedence constraints.
