### ISSUE TITLE
Vehicles with OR conditional skills

### ISSUE THREAD

**Issue by nahueldaima** [VROOM-Project/vroom#705]
We have a case on which our vehicles can change its own skills based on some configuration and we are having problems mapping this behaviour on the optimization input.

Let's say we have a vehicle that can carry products on up to 3 different temperatures (0, 10 and 20 degrees).  That means that or either can transport all products of one of the temperatures,  or products with two different temperatures, or with any temperature. And we have 2 vehicles in total.

We would like to know if we can get from the optimization process a way of understanding what's the best configuration we have to give to the vehicle in order to delivery the products. Something like, for the given input the best solution is to have one vehicle with temperature 0 and 10, and another with temperature 20.

Is this possible?

**Comment by jcoupey** [comment]
>We would like to know if we can get from the optimization process a way of understanding what's the best configuration we have to give to the vehicle

If all vehicles can handle any temperature, you don't need the optimization process to know that the best configuration (in term of overall solution cost) is to allow all temperatures for all vehicles. That would amount to not providing skills at all, and would be the way to have the most flexible model, hence the lowest cost. Unless you have some other constraints or requirement that make it impossible or undesirable to do things this way...

**Comment by nahueldaima** [comment]
Thanks!
Let me give a more specific example to try to show my point of view:

We have 3 different room temperature on a vehicle: T1, T2 and T3 that represents a capacity to transport packages on those temperatures.
Let's say that a vehicle has a maximum capacity of 100 packages in total.

We will have vehicles that can handle only one temperature. So the configuration will be:
 T1, T2, T3
[100, 0, 0]
[0, 100, 0]
[0, 0, 100]
 
We also have trucks that can be customizables to have either one or other configurations, always exclusive one from the other:
[100, 0, 0] or [50, 50, 0]
[100, 0, 0] or [0, 100, 0]
 
From these last configurable trucks, we need to know which configuration its the more optimal for the global solution.
Is this possible?

**Comment by jcoupey** [comment]
No, that is not possible since the fleet description - in this case available capacity by room - has to be an input of the optimization process. You'll have to come up with your own business logic to decide on the configuration outside VROOM.

**Comment by nahueldaima** [comment]
Ohh ok, thank you!! Have a nice day!
