### ISSUE TITLE
have delivery amount greater that vehicule capacities

### ISSUE THREAD

**Issue by bastiennoellaposte** [VROOM-Project/vroom#708]
I have to deliver 30 units to a location, using multiple vehicules with capacity = 20.
If i create one job (with delivery = 30), i get no solution.
If i create 30 jobs (with delivery = 1 for each), i get a solution but with a long computing time 
Is there any clever way to do this ?
thanks for your help

**Comment by bastiennoellaposte** [comment]
merci !

**Comment by bastiennoellaposte** [comment]
actually, i think the solution can be suboptimal if i devote full_load vehicle to the jobs. example below : 
![image](https://user-images.githubusercontent.com/84443345/166739585-1a786c7d-0275-4e37-b10c-47908ec6c94c.png)

**Comment by jcoupey** [comment]
Using `0` for the origin, the cost of a valid solution with destination `1` appearing in two jobs with delivery 20 and 10 would be:

- full-load trip to 1 (load 20): `0-1 + 1-0`;
- the rest (load 3 + 10 + 4): `0-2 + 2-1 + 1-3 + 3-0`.

If we forget about asymmetric costs for edges, this is the exact same cost as your example with a 15 + 15 splitting.

**Comment by bastiennoellaposte** [comment]
you re right again
thanks for your help
