### ISSUE TITLE
Time constraints not met

### ISSUE THREAD

**Issue by komorekm** [VROOM-Project/vroom#712]
I have created a simple scenario where one vehicle has to pick up two packages form distinct location and deliver them to two distinct locations. If I add time constraints to the pickup and delivery of the corresponding shipment, the result I get does not satisfy the time constraints. Any idea what I am doing wrong? 

#### Some information regarding my setup:
The parameter set for the packages:
 | parameter | package A | package B |
| ------ | ------ | ------ | 
| pickup | [14.015862, 53.731345]  | [13.994314, 53.500274] |
| delivery | [14.262296, 53.626128] | [14.213590, 53.457247] |
| time_window  pickup | [36000, 39600] | [43200, 50400] |
| time_window  delivery | [39600, 43200] | [54000, 70000] |

The vehicle and starts and ends at [13.37335, 54.12017] and can serves the whole day (setting `time_window` to [0, 86400])
The JSON I send: [vroom-data.txt](https://github.com/VROOM-Project/vroom/files/8686775/vroom-data.txt)
The response I get: [response.txt](https://github.com/VROOM-Project/vroom/files/8691074/response.txt)

**Comment by jcoupey** [comment]
As per [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#shipments), shipment steps have an optional `time_windows` (plural) key that is *"an array of `time_window` objects describing valid slots for job service start"*. So you have to provide an array of arrays.

You current `time_window` (singular) keys are ignored at pickup/delivery level.

**Comment by komorekm** [comment]
Thanks! This was the error.
