### ISSUE TITLE
Change types to uint64

### ISSUE THREAD

**Issue by nurikk** [VROOM-Project/vroom#715]
Hi, there
i've noticed that in typedef
https://github.com/VROOM-Project/vroom/blob/c238bf6d0590ea384bcc9a3aa84ca9f4fdde1099/src/structures/typedefs.h#L38

capacity is defined as `int64_t` (signed) but in input_parser 
https://github.com/VROOM-Project/vroom/blob/c238bf6d0590ea384bcc9a3aa84ca9f4fdde1099/src/utils/input_parser.cpp#L70

It's retrieved as `GetUint` unsigned

Additionally I changed Cost/Distance types to uint64 to enable support for larger problems instances with tasks on greater distance

**Comment by jcoupey** [comment]
I just commented [the ongoing discussion](https://github.com/VROOM-Project/vroom/pull/716#pullrequestreview-978252552) on the `Capacity` side.

Regarding `Cost` and `Distance`, the only situation where I've had to switch to `uint64_t` is for a specific huge instance from TSPLIB. I'm not really fond of raising the size for some specific situation if it add a computational burden for "normal" problems. Did you somehow benchmark switching from `uint32_t` to `uint64_t`?

**Comment by nurikk** [comment]
> Thanks for opening a dedicated ticket! I just commented [the ongoing discussion](https://github.com/VROOM-Project/vroom/pull/716#pullrequestreview-978252552) on the `Capacity` side.
> 
> Regarding `Cost` and `Distance`, the only situation where I've had to switch to `uint64_t` is for a specific huge instance from TSPLIB. I'm not really fond of raising the size for some specific situation if it add a computational burden for "normal" problems. Did you somehow benchmark switching from `uint32_t` to `uint64_t`?

Can I use this scrip for benchmark?
https://github.com/VROOM-Project/vroom-scripts/blob/master/benchmarks/compare_to_BKS.py

**Comment by jcoupey** [comment]
> Can I use this scrip for benchmark?

Yes, though you don't necessarily need to run it yourself, this script is called from the `benchmarks/*/run.sh` scripts.

**Comment by jcoupey** [comment]
Closing as this was discussed in #716, now closed.
