### ISSUE TITLE
Trips that take maximum capacity of a vehicle

### ISSUE THREAD

**Issue by fbaierl** [VROOM-Project/vroom#718]
Hello,

we are working on a scenario, in which we are transporting people and customers can order two types of rides:

- private rides: trip can never be combined with other trips
- pooled rides: trip can be combined with other trips if certain time-restraints allow it

Both types of rides are serviced by the same fleet of vehicles. I was wondering if there is a way to model the capacity restraints so that a 'private trip' always takes up a vehicles maximum capacity.

This would be trivial if our fleet was homogeneous, but unfortunately our vehicles have different capacities (5-seater, 8-seater, 30-seater, etc.). So basically, we would need to input something like "for this trip, take up all of the space of the vehicle that vroom selects".

If vroom is unable to handle this type of constraint, we would need to manually check for vehicles for a private trip, and make that trip immutable for this vehicle (using the vehicles max capacity) before giving the problem to vroom, which might lead to very suboptimal solutions. 

One other idea of mine was to ask OSRM first for the private ride, so we get the exact time it will take and ask vroom specifically for that without time margins. If we then set a service time of > 0 min for pooled rides, vroom will not be able to combine this trip with other tripstrips, correct? The drawback here is that we cannot have any flexibility for the starting time of the trip.

Related issues:

https://github.com/VROOM-Project/vroom/issues/705

The solution proposed there only works with fixed capacities (homogeneous fleet) if I am not mistaken.

https://github.com/VROOM-Project/vroom/issues/569

**Comment by jcoupey** [comment]
> So basically, we would need to input something like "for this trip, take up all of the space of the vehicle that vroom selects".

You're correct in assuming there is no direct way to express this.

> This would be trivial if our fleet was homogeneous

On the other hand you probably don't way to "waste" a 30-seater for a private trip. My point being: if you only allow private trips to be handled by vehicles with the lowest existing capacity, then you can apply the "trivial" approach of private trips filling up all the capacity.

**Comment by jcoupey** [comment]
@fbaierl any feedback on how/if you solved this on your side? Also feel free to close if this is not relevant any more.

**Comment by fbaierl** [comment]
Hello @jcoupey, we have not gotten around to solving this issue yet since we prioritized other features first. We will likely have to deal with this problem next year.

**Comment by jcoupey** [comment]
OK, so let's close for now. Feel free to reopen later with new input.
