### ISSUE TITLE
Infeasible route for vehicle

### ISSUE THREAD

**Issue by Kirbylix** [VROOM-Project/vroom#719]
hi,

I don't really understand it:
I have a vehicle with a time_window from 8-19 (11 hours). 
When I want to optimize the route I get the following error: "Infeasible route for vehicle 6".
If I increase the working time from 7 to 22 (13 hours), the route is successfully optimized with: 
duration: 15562 & service 2600 => 18162 sec (~ 5 hours)

how can it not drive the 5 hours in the 11 hours but in the 13 hours ?

attached the request.
[infeasible_route_for_vehicle.txt](https://github.com/VROOM-Project/vroom/files/8859201/infeasible_route_for_vehicle.txt)

thanks for the answer

**Comment by jcoupey** [comment]
You're passing a `vehicle.steps` list in input which is a way to force the optimization to start the search from the custom solution described by the jobs ordering.

> When I want to optimize the route I get the following error: "Infeasible route for vehicle 6".

It does not mean there is no solution under 11 hours, it means that your **initial** solution is not doable under 11 hours.

Why are you submitting vehicle steps in the first place? If there is no specific reason for forcing an initial route, you should remove the `steps` key and you'd get a (probably better) solution without touching the initial time window.
