### ISSUE TITLE
Vehicle visit same location multiple times

### ISSUE THREAD

**Issue by geekbuddy75** [VROOM-Project/vroom#720]
Hi 

Scenario:Multiple drop at single location (single location having multiple orders)

We getting solution where for single location vehicle gets visited multiple time. There is not time window constraints for location visits. This is surely not desired and expected solution. 

Appreciate help here.

**Comment by jcoupey** [comment]
This sounds a lot like #621 so I'm closing this as duplicate. If you think your problem is different than the one described and discussed over there, please re-open with new input on how it differs and a minimum working example to reproduce the problem.
