### ISSUE TITLE
example1 leaves job with id 6 unassigned

### ISSUE THREAD

**Issue by AckerdesignerXIV** [VROOM-Project/vroom#722]
I tried to set up VROOM and build a OSRM server running on the same machine, on the default port (5000), with the map Ile-de-France-latest from [geofabrik](https://download.geofabrik.de/europe/france/ile-de-france.html) and the default car.lua profile from OSRM.

Then I built VROOM and tested it using example_1.json, and got the following result:
[test_result.txt](https://github.com/VROOM-Project/vroom/files/8878126/test_result.txt), where job 6 is unassigned. Any ideas for what the reason could be are highly appreciated. Which was the OSRM map and profile used to generate example_1_sol.json ?
Thank you!

**Comment by jcoupey** [comment]
As stated in the [API reference](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#examples), those are **possible** outputs and results will be highly dependent on the underlying routing engine and profile adjustments.

In the situation of the first example where timing constraints are quite tight, the change in number of assigned job is probably related to an increase in travel times estimates.

**Comment by AckerdesignerXIV** [comment]
Thanks for pointing the tight time window out. By increasing the time window end of the second vehicle to 1600432400 instead of 1600430400 I was able to find a solution assigning all jobs.
