### ISSUE TITLE
Jobs with AnyOf skills

### ISSUE THREAD

**Issue by phat96** [VROOM-Project/vroom#727]
We have zones in map and vehicles expertise in some zones. Example: Vehicle A can perform well in zone 1, 2; Vehicle B can perform well in zone 3. We can model this problem with skills in documentation.

And then, there is a complicated case where a job belongs to an overlapping area of zone 2 and 3. So, this job could be handled by a vehicle has skill as zone_2, or zone_3. Do we have any ways to model this case?

**Comment by jcoupey** [comment]
What about using a new skill for "this job is in both zone 2 and zone 3" and adding that skill to vehicles A and B and all jobs in the overlapping area? The initial "zone 2" skill meaning would change to "this job is in zone 2 but not in zone 3".

**Comment by phat96** [comment]
yup, that's a good idea. Thanks
