### ISSUE TITLE
Longitude, Latitude order in Coordinates is not obvious

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#730]
`Coordinates` is defined as `std::array<Coordinate, 2>`, which does not inform on the order of the coordinate pair. Is it (Lat, Lon) or (Lon, Lat)? At first I made a mistake and provided the coordinates in incorrect order.

The situation could be improved by adding e.g. an enum: `enum { LON_INDEX = 0, LAT_INDEX = 1};`, or better yet, by defining coordinates as a struct with named members.

**Comment by jcoupey** [comment]
Landed with #731.
