### ISSUE TITLE
What is exactly being optimized?

### ISSUE THREAD

**Issue by RegularnaMatrica** [VROOM-Project/vroom#734]
Hi, great tool! I have few questions and I hope this is the right place to ask them. I've tried to search for the answers but couldn't find them (sorry if they've been already answered):

1. What is exactly being optimized:
  - travel time (duration) 
  - total time (ex. duration + service)
  - cost matrix

2. In case of capacity/time window for vehicle when it is not possible to visit all jobs:
  - is the number of visited locations maximized?

**Comment by jcoupey** [comment]
The current optimization objectives are (by order of predominance):

1. Sum of priorities for assigned tasks
2. Number of assigned tasks
3. Cost

If you don't use `priority` keys at all, 1. is not relevant. So yes we try to maximize the number of assigned tasks, and then at equal number of assigned tasks reduce cost.

Now for the notion of cost: if you feed your own `costs` matrix in input we use those values (whatever they actually represent). If you don't, we currently use travel times internally as costs. This may be refined in the future as we have a few tickets around related topics.

**Comment by RegularnaMatrica** [comment]
Thank you for the answer, I was hoping for such behavior.
