### ISSUE TITLE
Paper describing the heuristics used in VROOM?

### ISSUE THREAD

**Issue by mgalati13** [VROOM-Project/vroom#735]
Is there a paper that describes which heuristics are used inside VROOM?

**Comment by saurabh119** [comment]
Hi @jcoupey, I have been going through the code myself and noticed that some heuristic is present in the local search step also. Can you please throw some light on this code?

Thanks in advance.

https://github.com/VROOM-Project/vroom/blob/18c4290090370d71f7f2397c954d11e3a1e49e8d/src/algorithms/local_search/local_search.cpp#L1840-L1864

**Comment by jcoupey** [comment]
The local search process is fired by calling `run_ls_step` from the higher-level `run` function. What happens after a local search step is completed and we reached a local minima is that we try to "shake" the current solution by removing jobs that are good candidates for re-insertion in other routes (that's `remove_from_route`). Then the solution is filled up again with a heuristic process similar to the one used to compute initial solutions, see call [to `try_job_additions`](https://github.com/VROOM-Project/vroom/blob/18c4290090370d71f7f2397c954d11e3a1e49e8d/src/algorithms/local_search/local_search.cpp#L1856-L1857) right below, and we move on to another local search phase.

**Comment by saurabh119** [comment]
Awesome! Thank you so much for the response.

**Comment by jcoupey** [comment]
Closing here as there is nothing actionable. Writing a research paper is outside the scope of this repo. ;-)

**Comment by PawelGradek** [comment]
Hi @jcoupey could you please provide the source (for example article, book) for modification of Solmon l1 heuristic that was used for  `basic `and dynamic_`vehicle_choice heuristics`? Could you please explain what is the general difference in `basic` and `dynamic_vehicle_choice` implementation?

**Comment by PawelGradek** [comment]
could you please provide the source (for example article, book) for modification of Solmon l1 heuristic that was used for `basic` and `dynamic_vehicle_choice` heuristics? Could you please explain what is the general difference in `basic` and `dynamic_vehicle_choice` implementation?

**Comment by PawelGradek** [comment]
Could you please provide the source (for example article, book) for modification of Solmon l1 heuristic that was used for `basic` and `dynamic_vehicle_choice` heuristics? Could you please explain what is the general difference in `basic` and `dynamic_vehicle_choice` implementation?

**Comment by PawelGradek** [comment]
Hi @jcoupey. Could you please provide the source (for example article, book) for modification of Solmon l1 heuristic that was used for `basic` and `dynamic_vehicle_choice` heuristics? Could you please explain what is the general difference in `basic` and `dynamic_vehicle_choice` implementation?

**Comment by jcoupey** [comment]
The `basic` heuristic is loosely adapted from the Solomon I1 heuristic. There is no paper or article describing it, but you can spot the differences by looking at the implementation. The main idea we kept from the initial I1 paper is the notion of insertion "regret". On the other hand, the heuristic has been extended to account for other stuff we have to deal with that are not present in the initial VRPTW setup such as additional constraints, using shipments etc.

The `dynamic` approach is somehow a generalization of the previous we designed for situations where pre-ordering vehicles *a priori* for route building leads to poor solutions, typically multiple depot instances. In this case, the next vehicle to use is decided dynamically upon each route completion based on the remaining vehicles and tasks.
