### ISSUE TITLE
'vroom' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by MohithReddy1** [VROOM-Project/vroom#743]
What are the endpoints of the vroom docker image for optimization for multiple points routing? 

For the docker image, I am integrating with ORS, and the status for http://localhost:3000/health is 500.

And when I run the vroom express server I am getting the error "vroom is not recognized as an internal or external command,
operable program or batch file". 

Please provide the exact solution as soon as possible.

**Comment by nilsnolde** [comment]
wrong repo, please re-open here: https://github.com/VROOM-Project/vroom-docker

wrong tone: "as soon as possible" (maybe lost in translation? in your favor I'll assume so.)

very incomplete description: what did you try? describe your setup (docker-compose.yml, commands..) etc..

btw, `vroom is not recognized as an internal or external command, operable program or batch file` sounds veeery much like a windows shell error. you're sure you're running a docker container or are you trying vroom-express locally on your machine?  very different things

**Comment by jcoupey** [comment]
I was just about to close based on "wrong tone". Let's assume this is just a clumsy translation problem, so closing based on "wrong repo".
