### ISSUE TITLE
Task setup time is not applied to the first task at the same place

### ISSUE THREAD

**Issue by neemanjabu** [VROOM-Project/vroom#745]
Task setup time is not applied to the first task at the same place if a vehicle starts at the same location where tasks start (in a case when vehicle.start coordinates are the same as shippment_step.location or job.location coordinates).
version v1.12.0

**Comment by jcoupey** [comment]
It's not a bug, it's a feature. ;-)

The docs [state that](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#task-setup-times) *the total "action time" for a task is [...] `service` only if performing a new task at the previous vehicle location*. This applies to the situation where the previous vehicle location is the vehicle start, so no `setup` time applied.

If you want to account for some loading time, you can push the vehicle time window start a bit later.

**Comment by leobudima** [comment]
If you want to use setup time for loading at driver start location (i.e. depot), and are using location_index for distance matrix, you can simply provide different values for start_index (driver) and location_index (job/shipment) even if coordinates are actually the same -> the locations will have 0 cost between them so nothing changes in the route, and this will actually make Vroom apply setup time at start location.
