### ISSUE TITLE
plan mode -c on MacOS

### ISSUE THREAD

**Issue by phat96** [VROOM-Project/vroom#746]
Hi,
When I installed Vroom on Macos through `brew install vroom`, I can't use plan mode -c due to **VroomException: [Error] VROOM compiled without libglpk installed.**

How can I install libglpk on MacOS? Can we also make libglpk installed when running `brew install`?

**Comment by jcoupey** [comment]
It looks like no-one bothered to add `libglpk` as a dependency in the brew formula, yet. The usual process for updates and changes like this is that it should happen downstream, see https://github.com/Homebrew/homebrew-core/search?q=vroom&type=issues for examples of PR handling version changes and fixes.

Probably your best next move is to open a ticket at https://github.com/Homebrew/homebrew-core/ linking to this one.

**Comment by sashakh** [comment]
Ховешь меня увиеть? _Я хо-у лицо увибедеть!

**Comment by sashakh** [comment]
Сама решай! )
