### ISSUE TITLE
Clarifying documentation: how exactly do "jobs" work (vs shipment)

### ISSUE THREAD

**Issue by nemosmithasf** [VROOM-Project/vroom#748]
I think it's worth adding a blurb in the documentation distinguishing `jobs` vs `shipment`; because right now, I don't think there's anything which informs people of the difference.

Furthermore, after reading #597; I'm curious, how does VROOM determine which `jobs` are loaded onto which vehicle at the start? Does it use the `lonlat` of the order and vehicles? Or am I misunderstanding what `jobs` are?

**Comment by jcoupey** [comment]
That's right, the difference between `job` and `shipment` objects is somehow implicit with the set of available keys, we could definitely improve the description.

> how does VROOM determine which jobs are loaded onto which vehicle

Everything that has to be delivered in jobs for a given route is loaded at the vehicle start (and we guarantee this does not exceed vehicle `capacity`).

**Comment by nemosmithasf** [comment]
Just to clarify the second question, how does VROOM determine which orders at loaded onto which vehicle?

For example, if we have 2 vehicles with 2 orders on 2 jobs; how does VROOM know which order is on which vehicle?

**Comment by jcoupey** [comment]
> For example, if we have 2 vehicles with 2 orders on 2 jobs; how does VROOM know which order is on which vehicle?

That's the core purpose of the solving engine: decide how to assign tasks to vehicles and order them in routes so that constraints are met and overall cost (so far travel time) is minimized.

For this we have some heuristics in place and a local search phase to improve initial solutions.

**Comment by nemosmithasf** [comment]
Sorry, I think I'm misunderstanding what `jobs` are (which I guess supports the point about documentation).

From my understanding, "jobs" refer to orders that are already on a vehicle at the beginning of the trip- as a result, they only need to be delivered (as oppose to picked up and then delivered).

If that interpretation is correct, right now, I don't think the request explicitly specifies which orders are held by which vehicle.

So far example, if we want to model a simple trip where there's 2 vehicles that's already holding 2 orders at the start:
```
Vehicle A holds Order A
Vehicle B holds Order B
```

How does VROOM know that `Vehicle A` is holding `Order A`, and that `Vehicle B` isn't holding `Order A` instead?

I'm assuming VROOM uses starting location, but the problem is, when `Vehicle A` and `Vehicle B` are at the same location (i.e. the same depot), then VROOM wouldn't be able to use location to infer ownership.

Am I misunderstanding what `jobs` are or perhaps just misunderstanding the API?

**Comment by jcoupey** [comment]
We don't have a notion of "order" but you got the picture right: stuff delivered in jobs is loaded at the beginning of the route.

> How does VROOM know that Vehicle A is holding Order A, and that Vehicle B isn't holding Order A instead?

I don't really get your point, the purpose of VROOM is precisely to *decide* on which vehicle should handle which task.

The decision is based on:
- matching constraints such as capacity, time windows etc.;
- reducing overall cost.

So yes locations are used because they imply the costs for going from/to any place. If the fleet is totally homogeneous (same locations and constraints), then which vehicles are used and which are not may be arbitrary.

**Comment by nemosmithasf** [comment]
Oh, I think I understand now. This is where the misunderstanding was (and why I think better documentation is probably necessary):

I assumed a `job` refers to a delivery where the product is already on the vehicle at the start. But (and can you confirm?) a `job` really just refers to "some vehicle needs to visit this location".

It's probably better to think of it from a mental model perspective as modelling service calls (e.g. a plumber needs to visit this house, it doesn't matter which plumber) than delivery of goods per-se.

I think #597 and the snipper about `It is assumed that all delivery-related amounts for jobs are loaded at vehicle start` in the current API can cause some confusion because it makes people assume it is designed to model delivery (as opposed to it being just one use-case)
