### ISSUE TITLE
Force vehicle_step order 

### ISSUE THREAD

**Issue by fbaierl** [VROOM-Project/vroom#753]
I think I may have misunderstood how exactly `vehicle_step`s are treated. My expecation was that if I give vehicle-steps to a vehicle, it will plan them in that order and use the remaining time-slots to plan the other given shipments.

As such I created an input like this:

- 1 vehicle (vehicle0)
- 6 vehicle steps
- 1 shipment (which clashes with my vehicle steps, so it should be 'unassigned')

```JSON
{
  "vehicles": [
    {
      "id": 0,
      "description": "vehicle0",
      "start": [
        12.304373066846503,
        51.62270653765847
      ],
      "end": [
        12.304373066846503,
        51.62270653765847
      ],
      "capacity": [7],
      "skills": [],
      "time_window": [
        1644188400,
        1644274740
      ],
      "breaks": [],
      "steps": [
        {
          "id": 0,
          "type": "job"
        },
        {
          "id": 1,
          "type": "job"
        },
        {
          "id": 2,
          "type": "job"
        },
        {
          "id": 3,
          "type": "job"
        },
        {
          "id": 4,
          "type": "job"
        },
        {
          "id": 5,
          "type": "job"
        }
      ]
    }
  ],
  "shipments": [
    {
      "amount": [3],
      "skills": [],
      "pickup": {
        "id": 7,
        "service": 120,
        "location": [
          12.175563,
          51.694164
        ],
        "time_windows": [
          [
            1644199440,
            1644199440
          ]
        ],
        "description": "pickup|1001"
      },
      "delivery": {
        "id": 7,
        "service": 120,
        "location": [
          12.219437,
          51.715622
        ],
        "time_windows": [
          [
            1644198918,
            1644198918
          ]
        ],
        "description": "delivery|1001"
      }
    }
  ],
  "jobs": [
    {
      "id": 0,
      "pickup": [0],
      "delivery": [0],
      "description": "",
      "location": [
        12.304373066846503,
        51.62270653765847
      ],
      "timeWindow": [
        [
          1644197801,
          1644197801
        ]
      ]
    },
    {
      "id": 1,
      "pickup": [0],
      "delivery": [0],
      "description": "",
      "location": [
        12.219437,
        51.715622
      ],
      "timeWindow": [
        [
          1644198798,
          1644198798
        ]
      ]
    },
    {
      "id": 2,
      "pickup": [2],
      "delivery": [0],
      "description": "pickup|5",
      "location": [
        12.219437,
        51.715622
      ],
      "timeWindow": [
        [
          1644198918,
          1644198918
        ]
      ]
    },
    {
      "id": 3,
      "pickup": [0],
      "delivery": [2],
      "description": "delivery|5",
      "location": [
        12.175563,
        51.694164
      ],
      "timeWindow": [
        [
          1644199440,
          1644199440
        ]
      ]
    },
    {
      "id": 4,
      "pickup": [0],
      "delivery": [0],
      "description": "",
      "location": [
        12.175563,
        51.694164
      ],
      "timeWindow": [
        [
          1644199560,
          1644199560
        ]
      ]
    },
    {
      "id": 5,
      "pickup": [0],
      "delivery": [0],
      "description": "",
      "location": [
        12.304373066846503,
        51.62270653765847
      ],
      "timeWindow": [
        [
          1644200803,
          1644200803
        ]
      ]
    }
  ]
}
```

The result I get from that is:

```JSON
{
    "code": 0,
    "summary": {
        "cost": 2678,
        "routes": 1,
        "unassigned": 2,
        "delivery": [
            2
        ],
        "amount": [
            2
        ],
        "pickup": [
            2
        ],
        "setup": 0,
        "service": 0,
        "duration": 2678,
        "waiting_time": 0,
        "priority": 0,
        "distance": 42492,
        "violations": [],
        "computing_times": {
            "loading": 3,
            "solving": 0,
            "routing": 2
        }
    },
    "unassigned": [
        {
            "id": 7,
            "location": [
                12.219437,
                51.715622
            ],
            "type": "delivery",
            "description": "delivery|1001"
        },
        {
            "id": 7,
            "location": [
                12.175563,
                51.694164
            ],
            "type": "pickup",
            "description": "pickup|1001"
        }
    ],
    "routes": [
        {
            "vehicle": 0,
            "cost": 2678,
            "description": "vehicle0",
            "delivery": [
                2
            ],
            "amount": [
                2
            ],
            "pickup": [
                2
            ],
            "setup": 0,
            "service": 0,
            "duration": 2678,
            "waiting_time": 0,
            "priority": 0,
            "distance": 42492,
            "steps": [
                {
                    "type": "start",
                    "location": [
                        12.304373066846504,
                        51.62270653765847
                    ],
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "load": [
                        2
                    ],
                    "arrival": 1644188400,
                    "duration": 0,
                    "violations": [],
                    "distance": 0
                },
                {
                    "type": "job",
                    "location": [
                        12.175563,
                        51.694164
                    ],
                    "id": 4,
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 4,
                    "load": [
                        2
                    ],
                    "arrival": 1644189627,
                    "duration": 1227,
                    "violations": [],
                    "distance": 22379
                },
                {
                    "type": "job",
                    "description": "delivery|5",
                    "location": [
                        12.175563,
                        51.694164
                    ],
                    "id": 3,
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 3,
                    "load": [
                        0
                    ],
                    "arrival": 1644189627,
                    "duration": 1227,
                    "violations": [],
                    "distance": 22379
                },
                {
                    "type": "job",
                    "description": "pickup|5",
                    "location": [
                        12.219437,
                        51.715622
                    ],
                    "id": 2,
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 2,
                    "load": [
                        2
                    ],
                    "arrival": 1644190087,
                    "duration": 1687,
                    "violations": [],
                    "distance": 28951
                },
                {
                    "type": "job",
                    "location": [
                        12.219437,
                        51.715622
                    ],
                    "id": 1,
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 1,
                    "load": [
                        2
                    ],
                    "arrival": 1644190087,
                    "duration": 1687,
                    "violations": [],
                    "distance": 28951
                },
                {
                    "type": "job",
                    "location": [
                        12.304373066846504,
                        51.62270653765847
                    ],
                    "id": 0,
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 0,
                    "load": [
                        2
                    ],
                    "arrival": 1644191078,
                    "duration": 2678,
                    "violations": [],
                    "distance": 42492
                },
                {
                    "type": "job",
                    "location": [
                        12.304373066846504,
                        51.62270653765847
                    ],
                    "id": 5,
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "job": 5,
                    "load": [
                        2
                    ],
                    "arrival": 1644191078,
                    "duration": 2678,
                    "violations": [],
                    "distance": 42492
                },
                {
                    "type": "end",
                    "location": [
                        12.304373066846504,
                        51.62270653765847
                    ],
                    "setup": 0,
                    "service": 0,
                    "waiting_time": 0,
                    "load": [
                        2
                    ],
                    "arrival": 1644191078,
                    "duration": 2678,
                    "violations": [],
                    "distance": 42492
                }
            ],
            "violations": [],
            "geometry": "_razH{dbjAk@_GCS_A\\s@XMDSPMDKByAXSBe@Bk@HWHFl@LpAZtC@LDh@d@rEFl@x@bIJfAN|Ar@hHBPV`Cv@dIr@bIJ~@R~BFp@f@dFJv@NfBRtBJpBBlA@d@ErAGz@Iz@Y~BM|@G\\CTCJ[hB_@tBi@dDeAvGId@Kz@G^QZKRKFM@YF_Ai@mC_Be@Yi@Oo@Kk@Em@HoKnC_EdAeEvAeDlAaDpAYPiCxAiCbBcDnCqAlAoArAaAhAi@r@m@|@_@h@i@v@aBpCiC~EeS~e@gChGaChGaAvC{@`Dw@bDs@jDg@xCa@|C[xC[hDQtCQdDYtIo@~RMpGAtBBvCdAba@TzCJdAPdAVjB^nBbAzEXtAf@dCb@xBRbAHZZ|AH`@f@jCVxAd@nCb@nCl@~Dn@dFxN|zABVn@zGh@xEj@lGNxADb@JbAd@pFLlAl@pGnFzj@j@zHLbBZbGJ~CHtCDlB@Zz@Jd@FtALt@TRLTVLRH\\Fb@Bh@Ah@Ih@Od@S\\UPSF[F{@FwGqB}@WeCs@yEqAeVsGqKwBcLoBeNkB}NcBc[iDcBSkiAaMqC[ysB_Uw@Isp@oHyASg@Eu@Iys@yHaA}@g@u@Wg@YgAOeBGaA_@aBq@}@_Ag@oASaA??h@AhFAdEApCAtJ?B?Do@ntCCbCn@?b@E`LaCzFmAzG{AbRyDfAfQLtBBjA?zAGhP?fC@nADbADx@Hf@J`ARdATbA`@pAf@jAd@v@p@dAn@bAp@jAf@bA^lAf@|BVhBRbCJ~@jDy@fBe@rDeAXAGuG?oB???nBFtGY@sDdAgBd@kDx@K_AScCWiBg@}B_@mAg@cAq@kAo@cAq@eAe@w@g@kAa@qAUcASeAKaAIg@Ey@EcAAoA?gCFiP?{ACkAMuBgAgQcRxD{GzA{FlAaL`Cc@Do@?Y@WJUNc@NqNfDy@Lo@Dc@CaASkBc@c@Gm@?wADoAD_EPqALS@u@J}@JwAPgGn@gELm@?k@IUE_@OM]Bi@HcFHeDVyNbDgcBTqMAqBO{DQiCO}AMuAKyAIsAEmAEgB?cA?wA@}@DgB?CPgF@UFmBFoBNgCRaCRuBPcBPuAT{AV_BXcBPPRFpASrE{@DfAZdD??[eDEgA@m@ReJRc@OwGGsCWw@rBiDb@m@d@aANo@r@}Gd@eFhB}TnFko@pEyi@N_BrD{CxM}KlMoKbEkDpAeA`EeDjB_BnTsQjSuPt@o@r@i@|AmAXUJIBCHGZYp@e@\\Uf@Y`@Qb@SdAe@lCoA|FmCb@SzBkAj@]XOd@OfA[JELGNMLON[HWHYJk@Hw@Dw@FyBBm@VwO@q@Fo@D[F]H]Xu@Ti@BCDGJKLCTKXK\\MtBg@pBc@dD{@lDu@`@I~A]HCzBi@\\ITGbCk@n@OdAWZIbAUrASRCp@EjAI|AIt@CbAORCd@IxBa@z@Qz@O\\EhAKp@?p@@z@D~@D|AF^BpAD`AGlAILAxAKtBS\\CDA`@CZGn@UrC}Al@_@^SXMTGf@Kp@C\\@^DtAP`BTNBNDLDNFNHLJHH`AlAX\\f@f@XRTNbA^RJfDb@fCVRBtBKb@KXI`@WJIhAs@p@g@^U\\QHC^O~Am@hCu@dBc@NCfAO~@C^?xAJf@FpDZb@F`E\\`AJjAVd@LFBZHZL\\P|@`@h@VzAt@p@\\BSPuAh@sEBKP_A@CVm@DK~GgOf@kAdBkDNY\\w@h@eAtAkCn@sAl@qAx@aB\\c@vU_WTUhFsFnEsEx@}@^s@^q@Tg@Te@Tm@JUXk@|@kBl@yAVa@Za@v@_AhAy@vCmB`EuCn@c@pB{A~@w@jE}CJGHI\\Q`A_@^MtAc@d@Ot@OpGaCxNqF|@]TKHC\\O^O^OdAc@~@[rGaCdBo@jFoBzEeBh@U^MlEaB|@]~DwAfBq@PGEi@AM[uCMqAGm@VIj@Id@CRCxAYJCLET?bC{@j@~F????"
        }
    ]
}
```

**My Problem:** the vehicle steps are not executed in the order I have given them to the vehicle. Is there a way to force the order given in the input? The time-window restrictions are not taken into account either, so I think I have a general misunderstanding of how the vehicle steps work.

**Comment by jcoupey** [comment]
Vehicle `steps` order is used differently depending on context, see [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#vehicle-steps).

Using `steps` in normal solving mode does not give a guarantee that the provided ordering will be matched in output. It is simply a way to seed the search with your own "manual" solution, but the solving path followed starting from there may change the order if it is interesting cost-wise.

**Comment by fbaierl** [comment]
Alright, since I don't think planning mode is what we want to use, I will find another way of handling this. Thank you for your quick answer.

**Comment by nemosmithasf** [comment]
Hah, it's funny, I ran into this exact same misunderstanding today.

Out of curiosity, what is the purpose of `steps` in normal mode? Is it a matter of optimization (i.e. if we have a rough idea of the solution, it solves faster)?

**Comment by jcoupey** [comment]
It can be useful in a situation where you have a huge instance and an existing solution. It's faster then to update the existing plan with a few extra tasks without going through the whole solving process again.

**Comment by nemosmithasf** [comment]
Hey @jcoupey, to follow-up on your explanation, is it only for huge instances where there is a speed advantage? Or would smaller instances benefit too? Is the speed difference expected to be significant?

I'm currently trying to implement a continuous/dynamic routing model with VROOM (i.e. updates the route every time a new item is added). It requires a bit of hacking, but VROOM seems to be pretty well adapted for it.

The primary bottle neck however is speed; the model takes about 50s to run with continuous routing vs about 10 seconds without it. Would feeding VROOM the prior solution help for moderately large instances? In my test model, I'm using 2 vehicles and roughly 40 tasks at its greatest extant.

**Comment by jcoupey** [comment]
> is it only for huge instances where there is a speed advantage? Or would smaller instances benefit too? Is the speed difference expected to be significant?

The difference in computing time would probably grow with the size of your input, but this is really dependent on the whole setup and constraints so you probably want to try and see.

> In my test model, I'm using 2 vehicles and roughly 40 tasks at its greatest extent.

If you need 50 seconds (or even 10) for a solution with only 40 tasks and 2 vehicles, then there is probably something wrong in your model.

**Comment by nemosmithasf** [comment]
The model consists of many VROOM call because of the continuous updating.

For those who stumble upon this in the future, after a lot of trying, I've concluded the following about hacking VROOM for continuous routing:

1. It's not possible out of the box, because VROOM doesn't support the idea of "orders held by an entity", meaning you can't update the route of an entity already holding an order. You would have to pre-process or post-process your data to prevent this from happening. By doing so, you can get something resembling continuous routing, but not "true" continuous routing.

**Comment by jcoupey** [comment]
> VROOM doesn't support the idea of "orders held by an entity"

Yes it does by simply defining one skill per vehicle.

> meaning you can't update the route of an entity already holding an order

You can pin tasks to a given vehicle using skills.

**Comment by nemosmithasf** [comment]
The problem is even if you use skills, there's no guarantee VROOM will re-assign the already held order to the courier because of capacity constraints

For example, if CourierA with `Capacity=1` is holding OrderA (with `priority=1`) and linked by a skill. If OrderB is added with `priority=10`; VROOM will assign OrderB to courierA and ignore OrderA.

**Comment by jcoupey** [comment]
> there's no guarantee VROOM will re-assign the already held order

If you want to avoid already assigned orders ending up unassigned in the next optimization round, you simply need to make sure those are provided with a higher `priority` value than new orders.

In your example, since OrderB should not be removed from the plan, you want to submit it with the highest `priority` value.

**Comment by jcoupey** [comment]
> there's no guarantee VROOM will re-assign the already held order

If you want to avoid already assigned orders ending up unassigned in the next optimization round, you simply need to make sure those are provided with a higher `priority` value than new orders.

In your example, since OrderB should not be removed from the plan, you want to submit it with the highest `priority` value.

**Comment by fbaierl** [comment]
This is a great idea, thank you @jcoupey for explaining this approach.

I am also dealing with continous planning and solved it differently:
- pre-process all "bookings" to not include scheduled ones that are already "immutable" (one hour before departure)
- start the shift of a vehicle after the last immutable booking

This, however, has many obvious drawbacks, so I think we will switch to your suggested approach.

**Comment by nemosmithasf** [comment]
I tried that too; I had all already held orders at 100 priority, and unheld orders between 0-10. However, this isn't robust. Especially when you also add in distance limits (expressed as time-windows), because sometimes VROOM will choose 10x10 orders rather than 1x10 due to how the distances worked out.

**Comment by fbaierl** [comment]
> VROOM will choose 10x1 orders rather than 1x10 due to how the distances worked out.

You mean that Vroom will sometimes choose 10 lower prio orders ("1") instead of 1 higher prio order ("10")? Is that also happening with a priority of 100? So is it possible that vroom will rather do 10 orders of prio 1, than 1 order with prio 100?

**Comment by nemosmithasf** [comment]
Sorry, I got my numbers mixed up, I meant `10x10` vs `1x100`. Its especially pronounced with time-windows, but its possible even without it.

**Comment by nemosmithasf** [comment]
And don't get me wrong @jcoupey @fbaierl , if you do the necessary post/post-process, the results are still decent. Definitely better than static routing. It's just not as simple as re-calling VROOM every time you add an order to the model.

**Comment by jcoupey** [comment]
> So is it possible that vroom will rather do 10 orders of prio 1, than 1 order with prio 100?

We aim at maximizing the priority score, that is the sum of all priorities for assigned tasks. So if we have to choose between both we'll always favor 1 order with priority 100 (score = 100) over 10 orders of priority 1 (score = 10). It would take 100 orders of priority 1 to replace 1 order with priority 100.

> 10x10 vs 1x100

This should be quite rare if you carefully choose your priority thresholds.

The main problem would be if we don't find the solution with higher priority, but it should be rather unlikely after the fix we made for #319, especially if the higher priority comes with less tasks assigned.

> It's just not as simple as re-calling VROOM every time you add an order to the model.

Well, if you have a dynamic problem, requirements/constraints naturally change over time, so the problem description you have to use as input is expected to evolve accordingly.

**Comment by nemosmithasf** [comment]
> This should be quite rare if you carefully choose your priority thresholds.
This is true, but the problem is that it breaks the model if it happens.

**Comment by fbaierl** [comment]
> 1x100

Is there a reason you can't use priority 0 (default) instead of 1-10 for the "unheld" shipments?

**Comment by nemosmithasf** [comment]
Because you still need to prioritize the unheld shipments (internally within the set)

**Comment by fbaierl** [comment]
Sure, but starting at 0 would lessen the possibility of the problem occuring.

In our case, at the moment, we don't need to prioritize the non-held shipments, so I guess priority = 0 would work perfectly for us. This thread has been very helpful. Thanks @jcoupey @nemosmithasf

**Comment by fbaierl** [comment]
Unfortunately, I encountered another roadblock concerning the dynamic updating of routes. 

After calculating routes, I want to "freeze" some of them in the next scheduling run, and plan the other ones around it. I tried implementing this using priority=100 and unique skills like described above.

The problem, however, is e.g. for a shipment, I get the following route:

```
        t1                t2                 t3
start --> pickup --> drop-off --> end
```

Now, if I want to "freeze" those trips, I somhow need to tell vroom to keep those. I tried using jobs for that approach, but unfortunately, for jobs the API states:

> It is assumed that all delivery-related amounts for jobs are loaded at vehicle start, while all pickup-related amounts for jobs are brought back at vehicle end.

Which is not true in my case. And I can't model those trips as shipments either, because after pooling together multiple shipments in the first scheduler run, I cannot model that as "frozen" shipments for the second run.

Any idea on how to solve this?

**Comment by stewgloves** [comment]
@fbaierl  did you ever have any success with this?

**Comment by fbaierl** [comment]
I am still working on it, but I think I found a solution.

In our application, we interprete vehicle result-steps as rides for the vehicle. Some of those rides, we then "freeze" around an hour before they are supposed to be executed.

When querying vroom again, I have two sets of rides: frozen ones and not-yet-frozen ones.

For the not-yet-frozen ones, I create shipments with time-windows, priority = 0 and without skills.
For the frozen ones, I create shipments with with unique skills (only one vehicle has these skills), 'tight' time-windows and priority = 100.

Additionally, for all frozen rides without passengers, I create two jobs at the start and end. I also do these for any stops on a frozen ride where no passenger enters or exits. This way, I can get the exact same drives back.
