### ISSUE TITLE
API clarification: does priority influence visit order?

### ISSUE THREAD

**Issue by nemosmithasf** [VROOM-Project/vroom#756]
I think it's worth remarking in the API docs (and can you confirm?) that priority only influences whether a task is selected, but not the order in which tasks are completed.

e.g. A vehicle can visit a job with priority 0 before priority 100, as long as there's no other constraints.

**Comment by jcoupey** [comment]
That's correct, priority has nothing to do with time of service which is rather related to time windows. We already have [this paragraph](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#task-priorities) explaining the purpose of `priority` keys in the docs.

**Comment by nemosmithasf** [comment]
Thanks for confirming. I imagine it might be a good idea to explicitly remark upon it, because I think most people's intuition would suggest that priority implies differentiating the order (i.e. higher priority tasks should come first) rather than just its inclusion.
