### ISSUE TITLE
Vehicle's vehicle_step not respected

### ISSUE THREAD

**Issue by SirTypesALot** [VROOM-Project/vroom#757]
Hello,

I am experimenting a test case here where it would consists of two vehicles located on each side of a city, and four shipments spread out throughout the city.

I would like to force vehicle 2 to perform shipment 4, I intend on doing this by giving vehicle 2 a `vehicle_step` of type `pickup` and `delivery` with shipment id 4. However, the response that the engines returns isn't respecting the `vehicle_step` that I've putted in.

I've attached the API payload below, if you could help me debug what's going wrong I would be very thankful for it.

{"shipments": [{"pickup": {"id": 1, "description": "Pickup Order 1", "location": [13.3827182, 52.5514448], "service": 120}, "delivery": {"id": 1, "description": "Drop Off Order 1", "location": [13.3969376, 52.54848109999999], "service": 120}, "amount": [1], "skills": [1]}, {"pickup": {"id": 2, "description": "Pickup Order 2", "location": [13.3827182, 52.5514448], "service": 120}, "delivery": {"id": 2, "description": "Drop Off Order 2", "location": [13.4216507, 52.5438791], "service": 120}, "amount": [1], "skills": [1]}, {"pickup": {"id": 3, "description": "Pickup Order 3", "location": [13.344422, 52.501226], "service": 120}, "delivery": {"id": 3, "description": "Drop Off Order 3", "location": [13.344422, 52.501226], "service": 120}, "amount": [1], "skills": [1]}, {"pickup": {"id": 4, "description": "Pickup Order 4", "location": [13.2972068, 52.5117996], "service": 120}, "delivery": {"id": 4, "description": "Drop Off Order 4", "location": [13.3180201, 52.49819419999999], "service": 120}, "amount": [1], "skills": [1]}], "vehicles": [{"id": 1, "description": "Apotheke am Sophie-Charlotte-Platz", "start": [13.2975184, 52.511747], "end": [13.2975184, 52.511747], "capacity": [5], "skills": [1], "time_window": [1659340800, 1659369600]}, {"id": 2, "description": "Herz Apotheke", "start": [13.3827993, 52.55144], "end": [13.3827993, 52.55144], "capacity": [5], "skills": [1], "time_window": [1659340800, 1659369600], "steps": [{"type": "pickup", "id": 4}, {"type": "delivery", "id": 4}]}]}

**Comment by jcoupey** [comment]
Please check #753.

> I would like to force vehicle 2 to perform shipment 4

That's a constraint you can typically describe using skills.
