### ISSUE TITLE
VROOM compiled without routing support?

### ISSUE THREAD

**Issue by Fleron** [VROOM-Project/vroom#760]
I've tried running vroom CLI with valhalla running on localhost:8002 in a docker container (**vroom-docker without the vroom-express**). It seems that whichever way i try to run i get `{"code":3,"error":"VROOM compiled without routing support."}` which I have trouble trying to troubleshoot.

**commandline**: `vroom -r valhalla -p bicycle:8002 -a bicycle:localhost -i testfile.json`

where testfile just contains: 
`{"vehicles":[{"id":0,"start":[5.916236035538789,49.86000627408201],"end":[5.916236035538789,49.86000627408201],"profile":"bicycle"}],"jobs":[{"id":0,"location":[6.237586120935036,49.67728970653097]}]}`

Is there something i'm missing in regards to installing vroom? I've tried installing and reinstalling in a few different ways but end up in the same error.

Most thankful for any help I can get.

**Comment by Orthae** [comment]
I have checked, and the build is working fine for me. Can you describe your process of installing vroom?

I also don't understand the part below, are you running some kind of dockerized vroom version like vroomvrp/vroom-docker? This image is essentially a vroom-express, that image still should work fine I have check v1.12.2 tag, and it has been compiled with proper flags.
> vroom-docker without the vroom-express

**Comment by Fleron** [comment]
Sorry for unclear instructions. Yes Im running a dockerized version of vroom which is a stripped down version of vroomvrp/vroom-docker. Should that error only be reachable if compiling with certain flags set?
```
FROM debian:bullseye-slim as builder

WORKDIR /

RUN echo "Updating apt-get and installing dependencies..." && \
  apt-get -y update > /dev/null && apt-get -y install > /dev/null \
  git-core \
  build-essential \
	g++ \
  libssl-dev \
	libasio-dev \
  libglpk-dev \
	pkg-config

ARG VROOM_RELEASE=v1.12.0

RUN echo "Cloning and installing vroom release ${VROOM_RELEASE}..." && \
    git clone  --recurse-submodules https://github.com/VROOM-Project/vroom.git && \
    cd vroom && \
    git fetch --tags && \
    git checkout -q $VROOM_RELEASE && \
    make -C /vroom/src -j$(nproc) && \
    cd /
```

**Comment by Orthae** [comment]
Yes, this error is related to compiling vroom with -DUSE_ROUTING=false, the dockerfile you posted should work fine, it is compiling with -DUSE_ROUTING=true flag. When you build, do you also get the following flag?
```
g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/cl_args.cpp -o structures/cl_args.o
```
I have tested in inside container, and it is working perfectly.
``` 
root@7bd75d2884db:/vroom/bin# ./vroom -r valhalla -p bicycle:443 -a bicycle:valhalla1.openstreetmap.de -i testfile.json
{"code":0,"summary":{"cost":20005,"routes":1,"unassigned":0,"setup":0,"service":0,"duration":20005,"waiting_time":0,"priority":0,"violations":[],"computing_times":{"loading":523,"solving":0}},"unassigned":[],"routes":[{"vehicle":0,"cost":20005,"setup":0,"service":0,"duration":20005,"waiting_time":0,"priority":0,"steps":[{"type":"start","location":[5.916236035538789,49.86000627408201],"setup":0,"service":0,"waiting_time":0,"arrival":0,"duration":0,"violations":[]},{"type":"job","location":[6.237586120935036,49.67728970653097],"id":0,"setup":0,"service":0,"waiting_time":0,"job":0,"arrival":9657,"duration":9657,"violations":[]},{"type":"end","location":[5.916236035538789,49.86000627408201],"setup":0,"service":0,"waiting_time":0,"arrival":20005,"duration":20005,"violations":[]}],"violations":[]}]}
```
Are you running it from inside the container?

**Comment by jcoupey** [comment]
> Are you running it from inside the container?

Good point, you first want to make sure you're not calling another `vroom` lying somewhere else on your system.

As pointed above, the default is to set `USE_ROUTING` to `true`, can you post the output of the build command from your docker setup?

```
make -C /vroom/src -j$(nproc)
```

**Comment by jcoupey** [comment]
cc @nilsnolde this smells somehow a bit like https://github.com/VROOM-Project/pyvroom/issues/60...

**Comment by nilsnolde** [comment]
Hmm, I can’t see how vroom can even get executed if it’s still inside /vroom. It’s not being installed in the Dockerfile, also no Path appended or so. My best guess is also that you’re not actually executing the command inside the container and have a stray vroom exe flying around (or the Dockerfile and/or command you show are incomplete).

**Comment by jcoupey** [comment]
Closing as stale.
