### ISSUE TITLE
Starting and ending the task in the first and last stop

### ISSUE THREAD

**Issue by fernandogonazales** [VROOM-Project/vroom#761]
Hi every one ! 

It is possible to start and end the trip of a vehicle at its first and last stop? I mean I wouldn't introduce a start and end location  to the vehicle. 

I am trying to do it by giving that array empty  as the following code: 

payload["vehicles"].append({
            "id": route["ID"][0].item(), 
            "description": route["UNE"][0],
            "speed_factor": route["speed_factor"][0].item() 
                                      })

However, I got and error. 

Best regards, 
Fernando

**Comment by fernandogonazales** [comment]
I have a docker imagen installed locally. I am reading an example in C  and says the following:



![image](https://user-images.githubusercontent.com/105509609/184171938-5c37fb7c-16b5-417f-8232-2c2199556c25.png)


what do you mean with std? 

Thank you !

**Comment by saurabh119** [comment]
According to the [API documentation](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#vehicle-locations), providing at least one of start and end is required. But there is a workaround present to achieve this using custom matrices. Set the start_index and end_index row/column to `0` in the cost/duration matrix. By doing this, VROOM will still have the start and/or end available for the vehicle and the ordering of the stops will not be dependent on the start/end. So the first stop will be the start and the last stop will be the end.

> what do you mean with std?

std is the namespace containing the C++ standard library.

**Comment by fernandogonazales** [comment]
Thank you @saurabh119  Im cheking this  now

**Comment by jcoupey** [comment]
It's indeed currently mandatory to provide at least one location (`start` or `end`) for vehicles. The historical reason for this is that it was mandatory in the first place for the initial TSP implementation predating the VRP solving code.

Now it would probably be possible to get rid of this restriction. If you want to play with this idea, you could simply remove [this exception](https://github.com/VROOM-Project/vroom/blob/d51ec0427444121b994422e68e0c8f54431393ff/src/structures/vroom/vehicle.cpp#L40-L43).  At first sight, I *think* it would be pretty similar to the above suggestion of "cheating" the start cost with a custom matrix.

On the other hand, it's certain that having no start **and** no end for a vehicle would mess with some parts of the solving strategy: for example the route seeding happening in the basic heuristic uses the cost of inserting a single job in an empty route. That cost is zero with no start and no end so the seeding rounds will probably end up adding random jobs. Also the dynamic heuristics uses similar costs to decide on which vehicle to use next.

I'm curious: can you elaborate on the use-case you're having that would require to define no location for vehicles?

**Comment by jcoupey** [comment]
Closing as answered.

**Comment by danielcxt** [comment]
It would be nice if there was a way to override only certain entries in the matrix calculated by the routing engine. I'd like to be able to override only the costs to/from the start and end points.

**Comment by danielcxt** [comment]
@jcoupey, since OSRM only accepts GET requests, is there code for handling matrix construction when the OSRM request URL would be longer than the URL length limit if all of the locations (from shipments/jobs/vehicles) were included in the URL?

**Comment by jcoupey** [comment]
That is definitely not a Vroom concern. You'll find some info on that from various discussions on the OSRM bugtracker. TL;DR OSRM is not imposing any technical limitation to request length, but the various tools you use to handle the requests might, so you want to configure those.
