### ISSUE TITLE
Vehicle limits on delivery locations

### ISSUE THREAD

**Issue by ilibar-zpt** [VROOM-Project/vroom#763]
Suppose a problem:
- set of vehicles of different sizes (weight, height, width, etc)
- set of delivery locations with different size allowances
- to be able to deliver with vehicle A to location B it requires `A.size <= B.size`

I thought about modelling it with skills, e.g. given:
- All uniq possible size values = 1,2,3,4,5
- A.size = 3; so A.skills = 3,4
- B.size = 4; so B.skills = 4,3,2,1
- but it wouldn't work because it is required that all B.skills are included in A.skills

Is there any way to implement this constraint using existing input options?

**Comment by ilibar-zpt** [comment]
I think it's doable via capacity/amount vectors, will post here later

**Comment by ilibar-zpt** [comment]
Given:
- Set of vehicles (V) by size = [1,2,3]
- Set of deliveries locations (D) by vehicle size limits = [1,2,3]

Model:
- For each vehicle size add extra capacity/delivery dimension
- For vehicle of size N set extra capacity of index >= N to big integer (indicates that vehicle can fit into own limit and bigger ones)
- For shipment to delivery of size limit N set extra delivery of index = N to 1 (indicates that shipment requires at most this size)

Example:
- V1.capacity = [999,999,999]; V2.capacity = [0,999,999]; V3.capacity = [0,0,999]
- S1.delivery = [1,0,0]; S2.delivery = [0,1,0]; S3.delivery = [0,0,1]
- S1 fits into V1 only (vehicle of size 1 can deliver to location with vehicle size limit 1)
- S2 fits into V2 and V1
- S3 fits into V1, V2, V3 (any vehicle up to size 3 can deliver to location with vehicle size limit 1)

**Comment by ilibar-zpt** [comment]
Works only for discrete values of size limits, but since each problem has a finite number of vehicles it shouldn't be a problem.
Will reopen just in case there's some other suggestions or use cases (e.g. minimum size limit instead of maximum)

**Comment by jcoupey** [comment]
In don't get why you can't do this simply using skills?

>S1 fits into V1 only (vehicle of size 1 can deliver to location with vehicle size limit 1)
>S2 fits into V2 and V1
>S3 fits into V1, V2, V3 (any vehicle up to size 3 can deliver to location with vehicle size limit 1)

This can be achieved with:
- a skill that only V1 has, set to S1;
- a skill that both V1 and V2 have, set to S2;
- no skill set to S3 (fits into any vehicle).

**Comment by ilibar-zpt** [comment]
You're right
