### ISSUE TITLE
Cost matrix is also multiplied with speed_factor

### ISSUE THREAD

**Issue by vladretca** [VROOM-Project/vroom#767]
Hi

I have a question about this line. It looks like if a cost for distances is provided, that is also multiplied by the vehicle's speed_factor. Shouldn't only the time be multiplied? The distances do not change if you are faster or slower.

https://github.com/VROOM-Project/vroom/blob/d51ec0427444121b994422e68e0c8f54431393ff/src/structures/vroom/cost_wrapper.cpp#L18

Many thanks

**Comment by jcoupey** [comment]
There are (currently) two possible situations:

1. no custom cost matrix is provided, then we fallback to using (scaled) travel times as cost, this is why `discrete_cost_factor` has the same default value than `discrete_duration_factor` in the constructor you point out. In this situation the `speed_factor` is expected to scale travel times, but also cost values in the same way.
2. a custom cost matrix is provided, in which case the scaling should indeed only apply to travel times. This is why we have a way to update the `discrete_cost_factor`: upon solving, `Input::set_vehicles_costs` is called and if a custom matrix exists, the value is set back to 1 here:

https://github.com/VROOM-Project/vroom/blob/d51ec0427444121b994422e68e0c8f54431393ff/src/structures/vroom/input/input.cpp#L553-L557

**Comment by jcoupey** [comment]
Closing as answered.
