### ISSUE TITLE
unassigned tasks when capacity is available

### ISSUE THREAD

**Issue by stewgloves** [VROOM-Project/vroom#769]
Hello, 

Really great project. I am running VROOM with OSRM on Docker. I am using a custom time-matrix, time constraints for each job and 13 vehicles each with 50 package capacity. 

I actually have two questions here: 
1 . When in planning mode, when passing `options: {c: true}` , all tasks show as unassigned? (example request is same as below but with the added `options` passed in)
2. Why in Solving mode when I have 15 vehicles and 20 jobs, does it return 2 tasks as unassigned? I would have assumed here it would utilise another vehicle in order to ensure all deliveries are made. (examples below)

example request - [example_request.txt](https://github.com/VROOM-Project/vroom/files/9432693/example_request.txt)
example response - [example_response.txt](https://github.com/VROOM-Project/vroom/files/9432694/example_response.txt)

Also, I am slightly confused as to the use case for Plan mode vs Solving mode. Is Plan mode used if for example, I have a vehicle that has a route to deliver 5 packages and we want to then confirm if we can give them another package to deliver? 

Any input here would be much appreciated.

**Comment by jcoupey** [comment]
> When in planning mode, when passing options: {c: true} , all tasks show as unassigned? (example request is same as below but with the added options passed in)

When using plan mode, you have to pass in input the ordered list of tasks via `vehicle.steps`.

> Why in Solving mode when I have 15 vehicles and 20 jobs, does it return 2 tasks as unassigned? I would have assumed here it would utilise another vehicle in order to ensure all deliveries are made. (examples below)

Using spare vehicles to assign more tasks should be the normal behavior. If this does not happen and you have enough capacity, then this is probably related to timing constraints. Did you check consistency with the time windows for unassigned jobs, i.e. are the jobs actually doable?

> Also, I am slightly confused as to the use case for Plan mode vs Solving mode

Plan mode will schedule routes that you provide yourself (and give feedback on potential constraints violations) while the default VRP solving mode will provide a solution (decide tasks allocation and ordering) that matches all constraints.

**Comment by jcoupey** [comment]
We have another place in the docs where [vehicle steps](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#vehicle-steps) are explained.

It looks like you re-opened by mistake, shall we close this ticket?

**Comment by stewgloves** [comment]
Sorry @jcoupey I closed it prematurely. If you have any more thoughts on the unassigned it would be much appreciated.

**Comment by jcoupey** [comment]
> Are there any other reasons why it may not utilise the other vehicles?

No, it's probably simply impossible based on your input. Any constraint you use in input (capacity, skills, max tasks, time windows etc.) can be a reason for ending up with unassigned jobs. You need to check the constraints associated to unassigned jobs to understand why they can't even fit in an empty vehicle.

**Comment by stewgloves** [comment]
OK thanks. It is odd as I can rule out capacity, skills and max tasks. If I set the time_windows to be 9AM -8PM for the Jobs it can complete 3 of those previously 6 unassigned tasks. It only utilises 6 of the 19 vehicles (that all have same contraints) provided. It would appear 3 tasks are just impossible to complete but for no clear reason.

**Comment by jcoupey** [comment]
> for no clear reason

Hum... In the problem you shared in the original post, job 5907 should start after 1651424400 so it cannot end before 1651424400 + 240 (service time). This is beyond the deadline for time window end of your vehicles.
