### ISSUE TITLE
Custom costs matrix 

### ISSUE THREAD

**Issue by fsty** [VROOM-Project/vroom#791]
Hi there, 

I want to optimize a mileage cost per car using a customized cost matrix. 
Here is an example with 2 cars and n jobs: 
![image](https://user-images.githubusercontent.com/55999494/192321351-95ebd5cb-c3fb-48a3-9727-3718448dc7d1.png)
s_i : starting location for car i 
e_i : end location for car i 
j_i : location of job i 

d: cost function 
I know the cost for d(e_i, *) and d(s_i,*) but I don't know what to put for d(j_x, j_y) since I don't know which car is going to make the trip.

**Comment by jcoupey** [comment]
A single matrix is related to a single profile (or car in your situation), so you have to provide different matrices to account for different costs.

> I don't know which car is going to make the trip

Precisely, you have to describe the cost for *each* vehicle (using two matrices in your example), then the optimization will decide which trip is taken by which car.

**Comment by fsty** [comment]
very clear, thanks!
