### ISSUE TITLE
Timeout option has no effect

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#792]
It seems that timeout option (the third parameter to `vroom::Input::solve` function or `--limit` command-line parameter to the stand-alone binary) has no effect.

I have a problem that takes about 45 minutes to solve using vroom. I tried to use the timeout option to see how much the results will differ if I want to have the results earlier. I tried passing the timeout (1000 and then 600 seconds), but even with it I still had to wait 45 minutes for the results.

I tried binary built using:
 * latest master ([b0fcb1b](https://github.com/VROOM-Project/vroom/commit/b0fcb1b0a3f726eb78e15e8d055f6f3b34c68ca0))
 * v1.12.0 release
 * v1.11.0 release (when the option was introduced)

I tried the three binaries on Manjaro.

Can someone please confirm (@jcoupey maybe)? I can give some more details if needed and am willing to try and investigate more.

**Comment by jcoupey** [comment]
FWIW, the idea in #509 could also reduce the heuristic computing times by an order of magnitude, especially for big instances.

**Comment by kkarbowiak** [comment]
Thanks for the comments.

I think I mostly understand how the timeout works and I do realise the timeout does not affect heuristics (it was clearly stated in https://github.com/VROOM-Project/vroom/issues/594#issuecomment-945460160).

I will check the computing time with `-l 0` and will try to measure the heuristics phase.

**Comment by kkarbowiak** [comment]
Alright, I repeated the computation
 * with no `-l` it took 39 min 21 sec (vroom reports 4'107 loading and 2'357'703 solving times)
 * with `-l 0` it took 36 min 10 sec (4'161 loading and 2'166'669 solving)

and the optimisation results do differ.

So it seems that indeed it was the heuristics phase that consumed this much time.

@jcoupey Do you have any insights on under which conditions the heuristic phase can take this much time (as opposed to being near negligible with regards to time used by local search)? Do you think it might be beneficial to have separate entry for heuristics in computing times in summary?

**Comment by jcoupey** [comment]
> Do you have any insights on under which conditions the heuristic phase can take this much time

I'd say mostly problem size (that is number of jobs and number of steps for the computed routes), but having specific constraints may also enter into play.

Can you by any chance share the instance you're using, either here or privately?

**Comment by kkarbowiak** [comment]
Sorry for slow response. I think I will be able to share something.

Meanwhile, I had a look at [`cvrp.cpp`](https://github.com/VROOM-Project/vroom/blob/master/src/problems/cvrp/cvrp.cpp) and [`vrptw.cpp`](https://github.com/VROOM-Project/vroom/blob/master/src/problems/vrptw/vrptw.cpp). In both, the `solve` function splits work to available threads and each of the threads runs a loop. Each loop iteration runs a heuristic and then local search.

I added some log messages and confirmed that the local search steps for lower ranks do execute before heuristics for higher ranks. The timeout would work better if all the heuristics were allowed to finish before starting local search. I will prepare a modification and see how it fares. In my opinion it should work, but perhaps there are some other considerations I did not think of.

**Comment by jcoupey** [comment]
Ah right I get it now: all local searches are stopped as expected, but all the heuristic processes scheduled for a single thread are done no matter what.

> The timeout would work better if all the heuristics were allowed to finish before starting local search.

I guess that would be the best way to fix this timeout problem. Actually I nearly did that recently in #750, see comments in the ticket and associated PR for why I finally reverted some of the changes.

**Comment by jcoupey** [comment]
@kkarbowiak can you confirm that #807 does fix the problem? Also happy to get any feedback on the changes over there.

**Comment by kkarbowiak** [comment]
> @kkarbowiak can you confirm that #807 does fix the problem? Also happy to get any feedback on the changes over there.

Yes, it does. With #807 all the heuristics complete strictly before the local search phase. Having in mind that the timeout does not affect the heuristics phase, it works as advertised.

I also observed a ~10% improvement in solving time, but this is based on limited testing and may not be representative.

Let me also comment on the PR.
