### ISSUE TITLE
Invalid Routing Response

### ISSUE THREAD

**Issue by LeoAlle** [VROOM-Project/vroom#801]
Hi, 
i'm trying to use VROOM with 1000 jobs, but i continue to receive the same error message which is [Error] Invalid routing response. {"code":3,"error":"Invalid routing response."}.
I've already changed max-table-size value, but nothing change.
Is there something i'm missing?

Thanks!

**Comment by jcoupey** [comment]
This error shows up when the response from the routing engine cannot be used by VROOM, so there is not much we can do to help without access to your routing stack. You should check the routing logs:
- are there any errors?
- spot the matrix/route request triggering the problem and send that in isolation (outside VROOM) to inspect the response.

**Comment by nilsnolde** [comment]
Ah that sounds like this: https://github.com/Project-OSRM/osrm-backend/issues/6402

Are you using OSRM 5.27.0 which was release a few days ago? Then it's a OSRM bug and you'll need to wait or use 5.26.0. 

What Julien meant: your OSRM installation might log errors, so you'll need to inspect that. Or send the same request that VROOM is sending to OSRM backend directly, without VROOM in the middle. OSRM will respond with a HTTP response (and error), while VROOM won't show that to you but raise its own exception. So cut out the middleman. Anyways, it's most likely the new bug in 5.27.0.

**Comment by LeoAlle** [comment]
Yes I'm using OSRM v5.27.0.

**Comment by LeoAlle** [comment]
How can I change it?

**Comment by LeoAlle** [comment]
Yes, I'm using OSRM v5.27.0. How can I change it?

**Comment by nilsnolde** [comment]
Look the osrm repo, there’s many instructions you can follow, it’s out of scope for VROOM.
