### ISSUE TITLE
Named constants for number of threads and exploration level

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#805]
The default number of threads is 4 and the default exploration level is 5, but named constants for those values are missing and the magic numbers are used in several places (in `libvroom.cpp` and `main.cpp`).

I propose to add named constants and use them instead.

BTW, the allowed values for exploration level (0..5) do not seem to have any meaning that could be conveyed by an enumeration, do they?

**Comment by jcoupey** [comment]
Makes sense, thanks for the suggestion and PR.

> the allowed values for exploration level (0..5) do not seem to have any meaning that could be conveyed by an enumeration, do they?

No, these are plain number that translate to both a wider (more initial solutions) and deeper (more local search steps) search.
