### ISSUE TITLE
Minimizing time rather than distance travelled

### ISSUE THREAD

**Issue by nemosmithasf** [VROOM-Project/vroom#809]
If I understand correctly, VROOM now supports using time rather than distance as its optimizing criteria. Would this theoretically mean that it's possible to minimize for time rather than distance in the future?

**Comment by jcoupey** [comment]
We've always been using travel time as the main optimization objective, not distance. In fact, we don't even have distances internally currently. And distances are not reported unless you use `-g` which triggers an additional routing request **after** solving.

**Comment by jcoupey** [comment]
Currently, using the script described in https://github.com/VROOM-Project/vroom/issues/466#issuecomment-949579856 is your best bet to switch to a "smallest completion time" objective using VROOM.

**Comment by nemosmithasf** [comment]
Thanks again for your help
