### ISSUE TITLE
Jobs plan for a month in advance

### ISSUE THREAD

**Issue by noelbank00** [VROOM-Project/vroom#810]
Hi! I would like to ask for your help. I have a car that is in use between 8 AM and 4 PM. There are tasks it should do. I would like to calculate how it can distribute (in order and in days) it’s tasks in advance. It is possible with your application, or could you help me how to do that?

My vroom settings look like: 

cliArgs:
  geometry: false # retrieve geometry (-g)
  planmode: true # run vroom in plan mode (-c) if set to true
  threads: 4 # number of threads to use (-t)
  explore: 5 # exploration level to use (0..5) (-x)
  limit: '100mb' # max request size
  logdir: '/..' # the path for the logs relative to ./src
  logsize: '5M' # max log file size for rotation
  maxlocations: 1000 # max number of jobs/shipments locations
  maxvehicles: 200 # max number of vehicles
  override: true # allow cli options override (-c, -g, -t and -x)
  path: '' # VROOM path (if not in $PATH)
  port: 3000 # expressjs port
  router: 'osrm' # routing backend (osrm, libosrm or ors)
  timeout: 300000 # milli-seconds
  baseurl: '/' #base url for api

My request:
[request.log](https://github.com/VROOM-Project/vroom/files/9913932/request.log)

And my response: 
[response.log](https://github.com/VROOM-Project/vroom/files/9913938/response.log)

Thank you for your reply in advance.

**Comment by jcoupey** [comment]
If you want an automated dispatch/ordering, you want to use the default solving mode, not "plan" mode. This is the reason you're getting empty routes here since for "plan" mode. as you're not providing the expected ordering in `vehicle.steps`

**Comment by noelbank00** [comment]
@jcoupey thanks :)

**Comment by noelbank00** [comment]
@jcoupey Hello 

Hello, again me.
I use the system as you said and works well, if every day lenght is same.

Have a car for every day, but however if there is a day (eg Tuesday) that is longer than the others then the system only adds work for Tuesdays. Why is this? And how can I solve it?

Request:

[last.log](https://github.com/VROOM-Project/vroom/files/9985102/last.log)


Image:
![image](https://user-images.githubusercontent.com/63310862/201220995-ce29a1fe-9eda-4b42-9900-4cce02fa35bf.png)

Thank you. :)

**Comment by jcoupey** [comment]
> if there is a day (eg Tuesday) that is longer than the others then the system only adds work for Tuesdays. 

This is simply due to the fact that using longer days produces cheapest routes overall. It will typically happen in a situation where you have an excess of resources compared to the workload. You can probably simply reduce your planning horizon (i.e. include less vehicles) to make sure the workload fills the available days.

**Comment by jcoupey** [comment]
Closing as answered.
