### ISSUE TITLE
Multiple Availabilities Spanning Weeks or Months

### ISSUE THREAD

**Issue by jasondandy** [VROOM-Project/vroom#811]
Hello, 

I have a need for scheduling a single vehicle several days to even weeks and months in advance, based on customer availability. Is this possible with Vroom? 

It would appear that I can set multiple `time_windows` for different jobs (customers), so I am assuming I could say available between [15:00, 17:00] Monday and [16:30, 19:00] Tuesday (with times and dates converted to the correct timestamps), but am I able to say that a vehicle is available between [08:00, 20:00] Monday, Tuesday, Wednesday, unavailable on Thursday, etc etc...?

Would I just set this with `time_windows` for the `break` object for my vehicle? 

I just want to make sure this is possible before going too deep down a rabbit hole and wasn't sure where else to post. 

Thank you!

**Comment by jcoupey** [comment]
> but am I able to say that a vehicle is available between [08:00, 20:00] Monday, Tuesday, Wednesday, unavailable on Thursday, etc etc...?

No since a vehicle can only have one `time_window`. You could either:
- duplicate the vehicle for each available day using the relevant time window (note that this requires that you know in advance what is the start/end point for each day);
- use a single vehicle object and model nights off using breaks.

**Comment by jasondandy** [comment]
I have a follow up question: Is it possible to choose or set a location that breaks should be taken from? I was able to optimize my route, however the vehicle is not returning to the office at the end of each day/shift. Currently, if I end a shift at location 8, I will start the next day at location 8, traveling to location 9.

**Comment by jcoupey** [comment]
> set a location that breaks should be taken from

The point of the breaks implementation is precisely to no have a location attached so they are taken whenever/wherever it is best based on surrounding tasks. In order to define a vehicle break with a fixed location, you can define several vehicles with disjoint time windows and the end/start locations matching the break location. Or if you need more timing flexibility, you can model those breaks as regular jobs.

**Comment by jcoupey** [comment]
Closing as answered.

**Comment by drutkoowski** [comment]
> • duplicate the vehicle for each available day using the relevant time window (note that this requires that you know in advance what is the start/end point for each day);
> • use a single vehicle object and model nights off using breaks.

Correct me if I'm wrong, but I did something similar using vehicle breaks, suppose we are to optimize routes for 4 days ahead (10-04-2024 - 14-04-2024), vehicle is available every day between 8 am and 4 pm, so I create breaks between working hours. When I give such a payload to vroom, it says that after making a 30-minute route 10-04-2024 it should take all breaks until 14-04, so it suggests ending the route on 14-04, why?

**Comment by drutkoowski** [comment]
> • duplicate the vehicle for each available day using the relevant time window (note that this requires that you know in advance what is the start/end point for each day);
> • use a single vehicle object and model nights off using breaks.

Correct me if I'm wrong, but I did something similar using vehicle breaks, suppose we are to optimize routes for 4 days ahead (10-04-2024 - 14-04-2024), vehicle is available every day between 8 am and 4 pm, so I create breaks between working hours (for every day). When I give such a payload to vroom, it says that after making a 30-minute route 10-04-2024 it should take all breaks until 14-04, so it suggests ending the route on 14-04, why?

VROOM payload: https://pastebin.com/SwLcaEy8

**Comment by jcoupey** [comment]
> so it suggests ending the route on 14-04, why?

Breaks are mandatory in our modeling, so they'll be part of the route you get in solutions no matter if there are tasks after or between breaks. In a context with routes that are very partially filled, you may want to remove extra breaks as a post-processing step.

**Comment by drutkoowski** [comment]
Thank you for the explanation. So what is the best way to plan routes for several days when it comes to vehicle payload? Creating separate "vehicle" for each day (duplication) or using breaks and post-processing the result? Are these the only options?

**Comment by jcoupey** [comment]
Creating several vehicles is a good way to do it. No need for break post-processing if some days are not used, and it may have advantages in term of internal search:  we do not have to decide on break positioning, the solutions have shorter routes (even if more of them) which may help in term of algorithmic complexity. Also it's possibly easier to perform various local search moves on several distinct routes than on a single huge route spanning multiple days.

I would recommend doing just this if you can, but as pointed out in https://github.com/VROOM-Project/vroom/issues/811#issuecomment-1300429612 it is not always possible or flexible enough.

**Comment by drutkoowski** [comment]
Great input here, it explains a lot. I just wanted to make sure that I am not missing some obvious solution for that problem. 
Thank you for your time!
