### ISSUE TITLE
What is vroom priority?

### ISSUE THREAD

**Issue by MoeinSHprogrammer** [VROOM-Project/vroom#815]
Hello, I want to know what is vroom's priority for collecting pickup jobs by vehicles? Is it to collect more weight or collect more jobs? If there is an article in this field so that I can master the details of vroom, please introduce me. thanks

**Comment by jcoupey** [comment]
We do have a documentation explaining basic stuff around API fields. Searching for "priority" in there would lead you to [this explanation](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#task-priorities).

**Comment by MoeinSHprogrammer** [comment]
thanks jcoupy
This is not the answer to my problem.
if I have many jobs with same priority and a vehicle can't pick all them up so vroom tries to aggregate a lot of job or fewer jobs with large weights?

**Comment by jcoupey** [comment]
We try by order of importance to:

1. maximize overall priority score (sum of assigned jobs priorities).
2. maximize number of assigned jobs.
3. minimize total solution cost.

> if I have many jobs with same priority and a vehicle can't pick all them up so vroom tries to aggregate a lot of job or fewer jobs with large weights?

This has nothing to do with weights or any sort of capacity. If you have a lot of jobs with same priority and not all can fit in, then you'll get a solution trying to maximize the number of assigned jobs (criteria 2. above).
