### ISSUE TITLE
Decoupling `Amount` from solving code

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#823]
I would like to decouple `Amount` class from the solving algorithm. Separating the two should make the code easier to maintain, but also to extend.

Right now, the `Amount` class (and associated `AmountExpression`) handles two states: no amount defined (an 'empty' amount), or an amount with some values. This could be simplified by making `Job`s and `Vehicle`s keeping amount wrapped in `std::optional`.

Also, the `Amount` class exposes its number of dimensions and gives access to each of them. This access is used by both json input/output code and the solving algorithm. I would like to change it so that once an amount is constructed, there is no need to inspect its internal structure until it's time to serialise it to json.

My previous PR (#782) was a step in this direction, but there were some concerns, so I needed to rethink it.

To achieve the above goal, the `Amount` class needs to provide some additional operations:

- consistency check (check whether two amounts have the same number of dimensions)
  This would simplify code in https://github.com/VROOM-Project/vroom/blob/master/src/structures/vroom/input/input.cpp#L117-131
  from:
  ```c++
  // Ensure delivery size consistency.
  const auto& delivery_size = job.delivery.size();
  if (delivery_size != _amount_size) {
    throw InputException(
      "Inconsistent delivery length: " + std::to_string(delivery_size) +
      " instead of " + std::to_string(_amount_size) + '.');
  }

  // Ensure pickup size consistency.
  const auto& pickup_size = job.pickup.size();
  if (pickup_size != _amount_size) {
    throw InputException(
      "Inconsistent pickup length: " + std::to_string(pickup_size) +
      " instead of " + std::to_string(_amount_size) + '.');
  }
  ```
  to something like this:
  ```c++
  // Ensure delivery amount consistency.
  _zero_amount.check_consistency(job.delivery);
  // Ensure pickup size consistency.
  _zero_amount.check_consistency(job.pickup);
  ```
  And the code in https://github.com/VROOM-Project/vroom/blob/master/src/structures/vroom/input/input.cpp#L241-247
  from:
  ```c++
  // Ensure amount size consistency.
  const auto& vehicle_amount_size = current_v.capacity.size();
  if (vehicle_amount_size != _amount_size) {
    throw InputException(
      "Inconsistent capacity length: " + std::to_string(vehicle_amount_size) +
      " instead of " + std::to_string(_amount_size) + '.');
  }
  ```
  to:
  ```c++
  // Ensure amount consistency.
  _zero.amount.check_consistency(vehicle.capacity);
  ```
- update to maximum (given another amount, set maximum value to each of the components)
  This would change code in https://github.com/VROOM-Project/vroom/blob/master/src/structures/vroom/raw_route.cpp#L119-122
  from:
  ```c++
    // Handle max component-wise.
    for (std::size_t r = 0; r < _zero.size(); ++r) {
      peak[r] = std::max(peak[r], _current_loads[s][r]);
    }
  ```
  to:
  ```c++
  peak.update_to_maxed(_current_loads[s]);
  ```
  and similar for code in https://github.com/VROOM-Project/vroom/blob/master/src/structures/vroom/raw_route.cpp#L130-133
- a way to determine maximum number of amouns a capacity can hold
  This should partially replace or at least simplify logic in https://github.com/VROOM-Project/vroom/blob/master/src/structures/vroom/input/input.cpp#L566-629
  It may be a bit trickier as vehicle-to-job compatibility also comes into play, but should be doable.

Any thoughts?

**Comment by kkarbowiak** [comment]
I think the above changes can be introduced separately. I will provide draft of pull requests, so the impact is more clearly visible.

**Comment by jcoupey** [comment]
I get the point of separating client code and internal representation, but at first sight I wonder if it is really worth the trouble here.

1. The `Amount` implementation has literally remained untouched since @krypt-n introduced the CRTP back in the days, a great computing time boost for capacity handling. I wouldn't dream to change it unless we have a huge change coming in how we model capacities which I don't see coming any time soon. My point here is that it is thus not a huge burden to maintain existing client code.
2. I don't see *huge* benefits for `Amount`-using client code (but maybe I'm wrong here). Of course the changes you list are actual examples of client code simplification. But having to access all components does not really sound like a bit deal: first it is aligned with our json API, and then one may argue that e.g. looping over components to max stuff is more self-explanatory than calling `peak.update_to_maxed(_current_loads[s]);`.

You mention maintaining and extending the code, do you have other situations in mind where this would help significantly?

> This could be simplified by making Jobs and Vehicles keeping amount wrapped in std::optional.

We have to be careful here since the overhead of using `std::optional` (testing whether amounts are present and accessing the actual value) could be significant as amounts are heavily used in capacity validity checks which are hot parts since they are heavily used in the core local search loops. I also wonder how this would play along with the CRTP.
A nice thing about the current implementation is that all amount comparisons still work as expected for empty amounts in particular, so we never have to add some boilerplate to actually check whether amounts are empty or not.

**Comment by kkarbowiak** [comment]
Thank you for having a look and the comments.

> I get the point of separating client code and internal representation, but at first sight I wonder if it is really worth the trouble here.
> 
>     1. The `Amount` implementation has literally remained untouched since @krypt-n introduced the CRTP back in the days, a great computing time boost for capacity handling. I wouldn't dream to change it unless we have a huge change coming in how we model capacities which I don't see coming any time soon. My point here is that it is thus not a huge burden to maintain existing client code.

Understood. Indeed, looking at file history shows that there have been hardly any changes in the last three years.

And I also immediately recognised the CRTP as a way to improve performance by eliminating memory allocations in intermediate computations.

>     2. I don't see _huge_ benefits for `Amount`-using client code (but maybe I'm wrong here). Of course the changes you list are actual examples of client code simplification. But having to access all components does not really sound like a bit deal: first it is aligned with our json API, and then one may argue that e.g. looping over components to max stuff is more self-explanatory than calling `peak.update_to_maxed(_current_loads[s]);`.

It depends. In some cases it is beneficial to see the implementation to know what is going on. In other cases, naming the activity is better, but only if you can find a good name (e.g. I would much prefer to see an invocation of `std::find` than a raw loop doing the search). Perhaps a name better than `update_to_maxed` would be more convincing, but I was not able to come up with any.

> 
> You mention maintaining and extending the code, do you have other situations in mind where this would help significantly?

Yes. My ultimate goal is to change capacity/amount handling to support more complex cases that cannot be modeled by component-wise sum (even in combination with skills). A simple example would be two load types that cannot be shipped together in the same vehicle at the same time.

The current implementation maps very well to the json interface, but those who use VROOM as a library could have access to a richer interface. Allowing the users to override the behaviour of capacity/amount could extend the range of problems solvable with VROOM, but I have little idea what the real demand for this would be.

> > This could be simplified by making Jobs and Vehicles keeping amount wrapped in std::optional.
> 
> We have to be careful here since the overhead of using `std::optional` (testing whether amounts are present and accessing the actual value) could be significant as amounts are heavily used in capacity validity checks which are hot parts since they are heavily used in the core local search loops. I also wonder how this would play along with the CRTP. A nice thing about the current implementation is that all amount comparisons still work as expected for empty amounts in particular, so we never have to add some boilerplate to actually check whether amounts are empty or not.

I don't know the quality of implementation of `std::optional`. It should not use dynamic memory allocation (although I don't think this is mandated by the standard), and be rather fast, but we can only be sure if we measure the overhead.

Yes, I realise that conflating the two states (no amount defined and some-dimensional amount) actually simplifies the comparison code.

**Comment by jcoupey** [comment]
> In some cases it is beneficial to see the implementation to know what is going on. In other cases, naming the activity is better

Sure, and it is usually a matter of trade-off and choice. But I think you got my main point: I don't see a *huge* benefit of another layer of abstraction for `Amount` if only for the sake of refactoring, especially if it takes dev time with the risk of reducing efficiency.

> A simple example would be two load types that cannot be shipped together in the same vehicle at the same time.

Now refactoring to allow introducing a new feature is different, maybe we should see the matter in the light of how you think extending the capacity for this purpose could happen? Feel free to open a dedicated ticket for this!

**Comment by jcoupey** [comment]
Closing as stale. @kkarbowiak feel free to re-open at some point if you think we should revive that discussion.
