### ISSUE TITLE
Stopping criteria

### ISSUE THREAD

**Issue by LeoAlle** [VROOM-Project/vroom#824]
Hi, 
are there any other stopping criteria (different than the time limit: flag -l)? 
If yes, how can I use them (or see which ones the algorithm is currently using)?

**Comment by LeoAlle** [comment]
Yes, i've already checked the -x flag. I saw that it takes 5 as default value (best solution quality in theory). 
But if I give my instance in input with no time limit and -x set by default at 5 I still continue to get a bad solution. 
The reason why I know it's not a good solution is because I've first divided the instance in 3 sub-instances and solved them. 
If I give the algorithm the complete instance I get a worse solution: almost double cost than the sum of the cost of the 3 sub-instances.
That's the reason why I've thought about the possibility of having some stopping criteria already set.

**Comment by jcoupey** [comment]
> If I give the algorithm the complete instance I get a worse solution: almost double cost than the sum of the cost of the 3 sub-instances.

This sounds like an optimization problem and now I'm curious. Can you share your problem instance along with the 3 sub-instances?

**Comment by LeoAlle** [comment]
Hi @jcoupey,
I've attached the instances. Let me know about the results you obtain with them.
My results are 125 routes as sum of the routes of the 3 subinstances (cost/distance = 66446001) and 140 routes (cost/distance = 132232857) for the complete instance. It's almost double.
Thanks.
[Instances.zip](https://github.com/VROOM-Project/vroom/files/9978759/Instances.zip)

**Comment by LeoAlle** [comment]
If you can share with me the complete results in .json files would be perfect,
Thanks.

**Comment by jcoupey** [comment]
Thanks for sharing the data but it is not really possible to debug as is: since there are no locations provided and everything in the sub-instances is renumbered (pickup and delivery `id` and `location_index`) it is not even possible to match shipments between your initial instance and the sub-instances.

In fact, it's pretty sure that your sub-instances are not an exact split of the initial instance since the number of shipments do not match:
```
$ jq '.shipments | length' Subinstance_*.json 
90
65
63
$ jq '.shipments | length' Complete_instance.json 
217
```

Could you keep the same matrices in the sub-instances and the same `id` and `location_index` for pickups and deliveries in the remaining shipments? That way just by diffing the files we could first make sure there is no splitting problem.

Side note: your matrices all have a first line and column filled with zero which means that the cost from vehicle start to any location and from any location to vehicle end is zero. Is this intended?

**Comment by LeoAlle** [comment]
I'm sorry, my mistake. The subinstance with 65 shipments has only 64 of them. I've attached it again corrected.
I'm sure there are no splitting problems now.
[subinstance_corrected.zip](https://github.com/VROOM-Project/vroom/files/9979740/subinstance_corrected.zip)

**Comment by LeoAlle** [comment]
To facilitate everything I'm attaching here how I convert the location index. 
Let me know 👍.
[Conversione location index.xlsx](https://github.com/VROOM-Project/vroom/files/9979967/Conversione.location.index.xlsx)

**Comment by jcoupey** [comment]
> To facilitate everything I'm attaching here how I convert the location index.

This is not of much help since:
1. I'd have to work it out manually (or come up with some automation on my side to untie your own internal logic);
2. there would be still no simple way to assert that the splitting is done right when it comes to the matrices;
3. the ranges you have in your spreadsheet do not even cover all your sub-instances ids!

> i'd like to leave these location_indexes

I get it that it would probably require extra work for you to provide a "clean" input that is using the same matrices/ids/location_index values across all instances. But not doing it amounts to ask me to do the same kind of work myself (for free) on your behalf. I simply don't have time to do it.

**Comment by LeoAlle** [comment]
Ok @jcoupey, but how is it possible to use the same location_index passing from the complete instance to subinstances? 
For example, if my location index "1" in the complete instance is not present in one of the shipments in one of the subinstances, is it possible to give the algorithm an input file where the location_index is not starting from "1"? If i understand correctly how to build the input file with custom matrices, I've associated the location index with the line in the matrix where to find distances and travel times from that point to all of the others. Obviously I've also had to cut the matrices passing from the complete instance to subinstances.
That's the reason why i had to change location index when it comes to subinstances.

Maybe I didn't understand something. If you can clarify this point for me I'd be grateful.

**Comment by LeoAlle** [comment]
The only way to mantain the location index is by giving always the same duration and costs matrices in the input file even if there are some unecessary points because they are not in any shipment. 
Or am I wrong about that?

**Comment by jcoupey** [comment]
> The only way to mantain the location index is by giving always the same duration and costs matrices in the input file

Yes, this is what I meant by "using the same matrices across all instances".

> even if there are some unecessary points because they are not in any shipment.

Having unused lines/columns in the matrices is not a problem. Again in that case the sub-instances should be the same as the complete instance with just some of the shipments removed. This way we can just diff inputs to spot what is removed in sub-instances.

**Comment by LeoAlle** [comment]
Ok, I thought that would be a problem for the algorithm. 
I'm going to correct my location_index, create new corrected input files for the complete instance and subinstances (with the same complete matrices) and share them with you as soon as I've finished. 
So that we can then check the results.

**Comment by LeoAlle** [comment]
Hi @jcoupey, as you suggested I've cleaned the input files. Now the results are different. The sum of the cost of the 3 subinstances is higher than  the cost of the complete instance. So it was an input problem. Thank you for your support.

Anyway, If it's possible, I'd like to get back the results from you too in order to eliminate every possible mistake.
So I've attached the new input files.
[Instances.zip](https://github.com/VROOM-Project/vroom/files/9988252/Instances.zip)

**Comment by LeoAlle** [comment]
Now with the same matrix across all instances I don't get a correct value for the cost and the duration of a single route though.

**Comment by LeoAlle** [comment]
Hi @jcoupey, here are the new input files corrected. 
Let me know.
[instances.zip](https://github.com/VROOM-Project/vroom/files/9991134/instances.zip)

**Comment by jcoupey** [comment]
From what I can tell when solving all instances using v1.12.0: the solution for the complete instance costs 58464582 for 125 routes. It looks like individual solutions for the sub-instances do produce a valid solution for the initial complete problem. This solution has 120 routes and costs 58293991.

It's a bit counterintuitive that splitting the problem in 3 and combining the solutions produce a slightly better output but that's probably simply a matter of how the various searches behave in this specific situation. I wouldn't draw any generic conclusion here as we're talking about a +0.29% cost increase (far from the "double cost" you mentioned earlier).

My guess is that on this specific example, the splitting logic do result in more constrained problems that somehow manage to reach solutions with less vehicles overall.

**Comment by LeoAlle** [comment]
Ok these are the same results I get now. Thank you.
I will try the algorithm with a similar instance and if you are interested I will let you know if the results are of the same type or not.

**Comment by jcoupey** [comment]
Closing as there is not much actionable here, but please report back if you run some other similar tests, that's always interesting.
