### ISSUE TITLE
time_windows constraint not respected for vehicule start

### ISSUE THREAD

**Issue by phiavogadro** [VROOM-Project/vroom#825]
Hello to all let's say it's 11am. 
I plan some jobs with one single vehicule and i enter a starting hour at 11am for this véhicule, then some jobs starting from 11am too.
say first job is one hour trip. I would expect the start to be at 11 and arrival at 12
Nope issue is that i have a start at 9:55 and arrival at first job at 11:15

any idea ?

**Comment by jcoupey** [comment]
It's only possible to play guesses without the actual input you're using. Can you share your json problem instance and solution?

**Comment by phiavogadro** [comment]
yes please find request and answer attached

thanks Julien

Régis ROBERT
Tél : 0606 473 713


Le mer. 9 nov. 2022 à 17:27, Julien Coupey ***@***.***> a
écrit :

**Comment by jcoupey** [comment]
Looks like the attached files do not go through when replying to a GitHub issue by email. You'll have to comment on the GH issue directly.

**Comment by phiavogadro** [comment]
[answer.txt](https://github.com/VROOM-Project/vroom/files/9974340/answer.txt)
[request.txt](https://github.com/VROOM-Project/vroom/files/9974341/request.txt)
here they are !

**Comment by phiavogadro** [comment]
Ok so to resume for the vehicle time constraint to work, you need only 1 time slot AND simple [] around; Great to know. Thanks Julien i will try !

**Comment by phiavogadro** [comment]
seems ther's a problem elswere. Answers keeps on starting jobs before time windows for jobs & véhicule please see
[request.txt](https://github.com/VROOM-Project/vroom/files/9981421/request.txt)
[answer.txt](https://github.com/VROOM-Project/vroom/files/9981424/answer.txt)

**Comment by jcoupey** [comment]
There are several problems in your files:

- you still have a `time_windows` (plural) key for the vehicle;
- the ids in the solution steps do not match the ones from the input: for example there is a job 5738 in solution that is not present in input!

You probably have the inputs and outputs mixed up across several problems somehow. Please share a [reproducible problem instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance).

**Comment by phiavogadro** [comment]
sorry i don't understand did you open the latest request.txt ? (the fist one is wrong but i corrected it bases on your advices) 
first request line is 
{"vehicles":[{"id":180,"start":[5.81972,47.18014333333333],"end":[5.81972,47.18014333333333],"time_windows":[1668089182,1668117262],"description":"telephone r"}]
 1 time slot AND simple [] around is a plural key ? why ?
i found no explanation on the doc https://github.com/VROOM-Project/vroom/blob/master/docs/API.md for plural vs single time_windows key
i'am lost there... could you explain ? to me the time key for vehicules is like example on https://github.com/VROOM-Project/vroom/blob/master/docs/example_1.json

thanks for help

**Comment by jcoupey** [comment]
The correct key for vehicles is `time_window` (no 's' at the end) and the value is an array of size 2. The correct key for jobs is `time_windows` (plural) and the value is an array of arrays of size 2.
