### ISSUE TITLE
Limit on how many locations to visit 

### ISSUE THREAD

**Issue by ky4mail** [VROOM-Project/vroom#830]
Hello,
Im wondering if would be possible to configure limit on how many locations can be visited by vehicle. I know there is a limit on jobs count. However, limiting locations is very important on long hauls because we may have multiple orders (jobs) to the same destination but need to limit location count to visit. The reason is, generally, carriers do not want to have long trips with many stops.
Thank you for amazing work and consideration of my question.

**Comment by jcoupey** [comment]
No, we don't have such a limitation in place. Do you have a strong reason for having multiple jobs at the same location? If you could group same-location orders in a single job, you could use the `max_tasks` key out of the box, while reducing the complexity of the optimization problem you're submitting.

**Comment by SkyTik** [comment]
@jcoupey I'm running into this problem: I have a lot of items for a location that, if I sum their weight into a job, would be over any vehicle's capacity. So, I have to split them into smaller jobs need to limit the visited locations of a vehicle.
