### ISSUE TITLE
Optimize Sequence of jobs

### ISSUE THREAD

**Issue by phat96** [VROOM-Project/vroom#833]
Hi,

I am having a scenario that I would like to optimize sequences of jobs. Example:
sequence 1: PU -> DO -> PU
sequence 2: DO -> DO -> PU -> PU
sequence 3: PU -> DO -> PU -> DO

Can we have a mechanism to link jobs to each other to form a sequence like above. And if vroom fail to handle 1 job in sequence, we will let the whole sequence be dropped?

Thanks,

**Comment by jcoupey** [comment]
I'm not sure I get you right: if you have fixed sequences of jobs, it does sound like there is nothing to optimize. A predefined sequence/route is either valid or not depending on the constraints. Can you elaborate a bit on your explanation and use-case to clear things up?

**Comment by phat96** [comment]
I could have multiple sequences in 1 problem so I need to optimize to place sequences somewhere in drivers' time windows.

Ex: 
I have 20 pairs of pickup-dropoff, 10 sequences of jobs, 5 drivers.
Each job in sequence has time windows, constraint about capacity, skills,... 
I require all jobs in 1 sequence must be done in order and by only 1 driver. In the middle of sequence, a driver can go somewhere else to do other jobs, as long as he handle all jobs in 1 sequence successfully.

use-case example: 
- A driver pickup all packages from hub and then delivering them to customers (PU -> DO -> DO -> DO).
- A driver pickup from hub A then deliver to hub B, pickup from B then deliver to hub C with constraint that PU A -> DO B must be done first (PU - DO - PU - DO).
- Some kind of business requirements that forces a sequence of jobs must be done with order, by 1 driver.

**Comment by jcoupey** [comment]
Thanks for the explanation. No, we have no way to link tasks in this way and create sequences that would be either all performed or not.

> A driver pickup all packages from hub and then delivering them to customers (PU -> DO -> DO -> DO).

If you still want the drop-offs optimized, that would not even be a "sequence" relation. So this is not about ordering but rather about a "should be done by the same driver" need. The closest you can get to this with VROOM is by using `skills`.

> Some kind of business requirements that forces a sequence of jobs must be done with order, by 1 driver.

Off the top of my head, I can't think of any real-life situation with this kind of requirement, can you explain the core business need here?

**Comment by phat96** [comment]
Thanks for your answer, I guess find another way to deal with this sequence. 
A incomplete solution would be assigning manually vehicles to a sequences of jobs first, then send the rest of jobs and remaining vehicles to Vroom to optimize.

> Off the top of my head, I can't think of any real-life situation with this kind of requirement, can you explain the core business need here?
Look like they just want to force some vehicles to do a sequence of jobs. This is indeed not really make sense in VRP. I will share more if I have information about their requirements. 
I will close the issue for now
