### ISSUE TITLE
Input file format

### ISSUE THREAD

**Issue by LeoAlle** [VROOM-Project/vroom#839]
Hi,
I have to solve a CVRPTW and I've modelled it in 2 different ways (2 different input files): 

- using shipments so that the pickup point is always the same for every shipment and the delivery point always changes;
- using jobs by defining only deliveries and having all the vehicles starting and ending from a point "0" representing the depot;

I don't see the difference between the 2 way of modeling the problem, but I get very different results in terms of output. 
Is it normal or am I missing something?
Which is the correct way to model this kind of problem where there is only one depot (pickup point) and many delivery points?

**Comment by LeoAlle** [comment]
Thank you @jcoupey. 
It seems to be the case. I'm going to model using jobs instead of shipments when the problem is not a PDP for the next times.

In this kind of input format, if the vehicles have different costs, but I've used the cost matrix to model distances between locations is there a way to consider also this aspect of the problem?
For example, I have vehicles with a greater capacity but also an higher cost to be used and I would like to consider also this in the solution I get.

**Comment by jcoupey** [comment]
See #788 for recent enhancements of the cost model.

**Comment by LeoAlle** [comment]
Ok Thanks @jcoupey.
