### ISSUE TITLE
Does not return result for small number of jobs

### ISSUE THREAD

**Issue by ky4mail** [VROOM-Project/vroom#841]
Hello,
I'm attaching small examples where one is working fine, another does not return results at all. I'm not sure if that is side effect of Windows compilation, but I have successfully solve 1000 shipments problem (if use shipments instead of delivery jobs).
[jobs_ok.json.txt](https://github.com/VROOM-Project/vroom/files/10156862/jobs_ok.json.txt)
[jobs_noresult.json.txt](https://github.com/VROOM-Project/vroom/files/10156863/jobs_noresult.json.txt)

**Comment by jcoupey** [comment]
Can you be a bit more specific about what you mean by not return result: do you get no output? if so what is the return code? do you get a regular response with empty routes?

**Comment by ky4mail** [comment]
I have no output at all. No result code.

**Comment by jcoupey** [comment]
By return code, I don't mean the value for `code` in the json output but the actual process error code as seen from the system. In bash you can get that back with `echo $?` after running the command.

Using v1.12.0, I'm getting normal outputs from both your files:

```
$ vroom -i jobs_ok.json | jq .summary
{
  "cost": 11027,
  "routes": 8,
  "unassigned": 0,
  "delivery": [
    181,
    156917
  ],
  "amount": [
    181,
    156917
  ],
  "pickup": [
    0,
    0
  ],
  "setup": 0,
  "service": 0,
  "duration": 10029,
  "waiting_time": 0,
  "priority": 0,
  "violations": [],
  "computing_times": {
    "loading": 0,
    "solving": 16
  }
}
$ vroom -i jobs_noresult.json | jq .summary
{
  "cost": 11149,
  "routes": 8,
  "unassigned": 0,
  "delivery": [
    191,
    165042
  ],
  "amount": [
    191,
    165042
  ],
  "pickup": [
    0,
    0
  ],
  "setup": 0,
  "service": 0,
  "duration": 10140,
  "waiting_time": 0,
  "priority": 0,
  "violations": [],
  "computing_times": {
    "loading": 0,
    "solving": 16
  }
}
```

What version are you using?

**Comment by nilsnolde** [comment]
Maybe it'd also be worth sharing how you built the Windows binaries. Also for others who'd like to build on Win. I have a stale branch to add CMake support, so platform stuff would be easier, but didn't touch that in ages and there's no interest in the upstream project. I mean it apparently compiled, but Windows support is not tested in any way yet. It might hit a segfault or so, MSVC C++ STL seems to be fairly different from the GNU one (in my limited experience). Best/safest is probably to use WSL2 on Windows, which works really well these days, and compile with Linux.

**Comment by ky4mail** [comment]
The exit code in both is 0 means no errors. I had tried current master and v1.12.0.
After compilation in Debug mode, the following error appears:

`Assertion failed: a.size() == b.size(), file vroom-master\src\structures/vroom/amount.h, line 164`

**Comment by ky4mail** [comment]
Thank you both for looking into this.
