### ISSUE TITLE
Date Based Optimization Instead of Priority

### ISSUE THREAD

**Issue by eolli** [VROOM-Project/vroom#843]
Our use case for VROOM is for service optimization of jobs over many days. The job priorities does not give the granularity of control we are looking for in this use case. 

I believe the ideal solution for optimizing services is more date driven than priority based. When scheduling, we utilize the following dates: 

- Due date (longest time to complete)
- Exact date (To coincide with equipment rental)
- Earliest date (to account for material lead time)

If there were ideas on how best to implement this type of logic, I’m willing to put some resources towards helping to implement.

**Comment by jcoupey** [comment]
Looks like you need to use time windows constraints, did you try that yet?
