### ISSUE TITLE
Can´t build vroom. It stops due to some kind of exception.

### ISSUE THREAD

**Issue by DaftDanieh** [VROOM-Project/vroom#844]
Hi, 
I´ve been for the last week trying to compile vroom in an Ubuntu 22.04 , with no result sadly. The console always shows a huge message I really can´t understand, generating only a vroom executable file (size=1,7MB) that I can´t do anything with.  I´m pretty new to  C++ compiling, so maybe it is just a simple thing that I can´t really see. OSRM is already installed in its latest version btw. Here is the output:

----------------------------------------------------------------

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c main.cpp -o main.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c algorithms/kruskal.cpp -o algorithms/kruskal.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c algorithms/munkres.cpp -o algorithms/munkres.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c algorithms/heuristics/heuristics.cpp -o algorithms/heuristics/heuristics.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c algorithms/local_search/local_search.cpp -o algorithms/local_search/local_search.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c algorithms/local_search/operator.cpp -o algorithms/local_search/operator.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c algorithms/validation/check.cpp -o algorithms/validation/check.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c algorithms/validation/choose_ETA.cpp -o algorithms/validation/choose_ETA.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c routing/http_wrapper.cpp -o routing/http_wrapper.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c routing/ors_wrapper.cpp -o routing/ors_wrapper.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c routing/osrm_routed_wrapper.cpp -o routing/osrm_routed_wrapper.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c routing/valhalla_wrapper.cpp -o routing/valhalla_wrapper.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrp.cpp -o problems/vrp.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/cvrp.cpp -o problems/cvrp/cvrp.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/tsp/tsp.cpp -o problems/tsp/tsp.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/vrptw.cpp -o problems/vrptw/vrptw.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/cross_exchange.cpp -o problems/cvrp/operators/cross_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/intra_cross_exchange.cpp -o problems/cvrp/operators/intra_cross_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/intra_exchange.cpp -o problems/cvrp/operators/intra_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/intra_mixed_exchange.cpp -o problems/cvrp/operators/intra_mixed_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/intra_or_opt.cpp -o problems/cvrp/operators/intra_or_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/intra_relocate.cpp -o problems/cvrp/operators/intra_relocate.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/intra_two_opt.cpp -o problems/cvrp/operators/intra_two_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/mixed_exchange.cpp -o problems/cvrp/operators/mixed_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/or_opt.cpp -o problems/cvrp/operators/or_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/pd_shift.cpp -o problems/cvrp/operators/pd_shift.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/relocate.cpp -o problems/cvrp/operators/relocate.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/reverse_two_opt.cpp -o problems/cvrp/operators/reverse_two_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/route_exchange.cpp -o problems/cvrp/operators/route_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/swap_star.cpp -o problems/cvrp/operators/swap_star.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/two_opt.cpp -o problems/cvrp/operators/two_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/cvrp/operators/unassigned_exchange.cpp -o problems/cvrp/operators/unassigned_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/tsp/heuristics/christofides.cpp -o problems/tsp/heuristics/christofides.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/tsp/heuristics/local_search.cpp -o problems/tsp/heuristics/local_search.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/cross_exchange.cpp -o problems/vrptw/operators/cross_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/intra_cross_exchange.cpp -o problems/vrptw/operators/intra_cross_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/intra_exchange.cpp -o problems/vrptw/operators/intra_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/intra_mixed_exchange.cpp -o problems/vrptw/operators/intra_mixed_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/intra_or_opt.cpp -o problems/vrptw/operators/intra_or_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/intra_relocate.cpp -o problems/vrptw/operators/intra_relocate.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/intra_two_opt.cpp -o problems/vrptw/operators/intra_two_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/mixed_exchange.cpp -o problems/vrptw/operators/mixed_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/or_opt.cpp -o problems/vrptw/operators/or_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/pd_shift.cpp -o problems/vrptw/operators/pd_shift.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/relocate.cpp -o problems/vrptw/operators/relocate.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/reverse_two_opt.cpp -o problems/vrptw/operators/reverse_two_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/route_exchange.cpp -o problems/vrptw/operators/route_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/swap_star.cpp -o problems/vrptw/operators/swap_star.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/two_opt.cpp -o problems/vrptw/operators/two_opt.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c problems/vrptw/operators/unassigned_exchange.cpp -o problems/vrptw/operators/unassigned_exchange.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/generic/edge.cpp -o structures/generic/edge.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/generic/matrix.cpp -o structures/generic/matrix.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/generic/undirected_graph.cpp -o structures/generic/undirected_graph.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/break.cpp -o structures/vroom/break.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/cost_wrapper.cpp -o structures/vroom/cost_wrapper.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/job.cpp -o structures/vroom/job.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/location.cpp -o structures/vroom/location.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/raw_route.cpp -o structures/vroom/raw_route.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/solution_state.cpp -o structures/vroom/solution_state.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/time_window.cpp -o structures/vroom/time_window.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/tw_route.cpp -o structures/vroom/tw_route.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/vehicle.cpp -o structures/vroom/vehicle.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/input/input.cpp -o structures/vroom/input/input.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/input/vehicle_step.cpp -o structures/vroom/input/vehicle_step.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/solution/computing_times.cpp -o structures/vroom/solution/computing_times.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/solution/route.cpp -o structures/vroom/solution/route.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/solution/solution.cpp -o structures/vroom/solution/solution.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/solution/step.cpp -o structures/vroom/solution/step.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/solution/summary.cpp -o structures/vroom/solution/summary.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/vroom/solution/violations.cpp -o structures/vroom/solution/violations.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c structures/cl_args.cpp -o structures/cl_args.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c utils/exception.cpp -o utils/exception.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c utils/input_parser.cpp -o utils/input_parser.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c utils/output_json.cpp -o utils/output_json.o

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -c utils/version.cpp -o utils/version.o

mkdir -p ../bin

g++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -D USE_LIBGLPK=true -o ../bin/vroom main.o algorithms/kruskal.o algorithms/munkres.o algorithms/heuristics/heuristics.o algorithms/local_search/local_search.o algorithms/local_search/operator.o algorithms/validation/check.o algorithms/validation/choose_ETA.o routing/http_wrapper.o routing/ors_wrapper.o routing/osrm_routed_wrapper.o routing/valhalla_wrapper.o problems/vrp.o problems/cvrp/cvrp.o problems/tsp/tsp.o problems/vrptw/vrptw.o problems/cvrp/operators/cross_exchange.o problems/cvrp/operators/intra_cross_exchange.o problems/cvrp/operators/intra_exchange.o problems/cvrp/operators/intra_mixed_exchange.o problems/cvrp/operators/intra_or_opt.o problems/cvrp/operators/intra_relocate.o problems/cvrp/operators/intra_two_opt.o problems/cvrp/operators/mixed_exchange.o problems/cvrp/operators/or_opt.o problems/cvrp/operators/pd_shift.o problems/cvrp/operators/relocate.o problems/cvrp/operators/reverse_two_opt.o problems/cvrp/operators/route_exchange.o problems/cvrp/operators/swap_star.o problems/cvrp/operators/two_opt.o problems/cvrp/operators/unassigned_exchange.o problems/tsp/heuristics/christofides.o problems/tsp/heuristics/local_search.o problems/vrptw/operators/cross_exchange.o problems/vrptw/operators/intra_cross_exchange.o problems/vrptw/operators/intra_exchange.o problems/vrptw/operators/intra_mixed_exchange.o problems/vrptw/operators/intra_or_opt.o problems/vrptw/operators/intra_relocate.o problems/vrptw/operators/intra_two_opt.o problems/vrptw/operators/mixed_exchange.o problems/vrptw/operators/or_opt.o problems/vrptw/operators/pd_shift.o problems/vrptw/operators/relocate.o problems/vrptw/operators/reverse_two_opt.o problems/vrptw/operators/route_exchange.o problems/vrptw/operators/swap_star.o problems/vrptw/operators/two_opt.o problems/vrptw/operators/unassigned_exchange.o structures/generic/edge.o structures/generic/matrix.o structures/generic/undirected_graph.o structures/vroom/break.o structures/vroom/cost_wrapper.o structures/vroom/job.o structures/vroom/location.o structures/vroom/raw_route.o structures/vroom/solution_state.o structures/vroom/time_window.o structures/vroom/tw_route.o structures/vroom/vehicle.o structures/vroom/input/input.o structures/vroom/input/vehicle_step.o structures/vroom/solution/computing_times.o structures/vroom/solution/route.o structures/vroom/solution/solution.o structures/vroom/solution/step.o structures/vroom/solution/summary.o structures/vroom/solution/violations.o structures/cl_args.o utils/exception.o utils/input_parser.o utils/output_json.o utils/version.o -lpthread -lssl -lcrypto -lglpk

mkdir -p ../lib

ar cr ../lib/libvroom.a main.o algorithms/kruskal.o algorithms/munkres.o algorithms/heuristics/heuristics.o algorithms/local_search/local_search.o algorithms/local_search/operator.o algorithms/validation/check.o algorithms/validation/choose_ETA.o routing/http_wrapper.o routing/ors_wrapper.o routing/osrm_routed_wrapper.o routing/valhalla_wrapper.o problems/vrp.o problems/cvrp/cvrp.o problems/tsp/tsp.o problems/vrptw/vrptw.o problems/cvrp/operators/cross_exchange.o problems/cvrp/operators/intra_cross_exchange.o problems/cvrp/operators/intra_exchange.o problems/cvrp/operators/intra_mixed_exchange.o problems/cvrp/operators/intra_or_opt.o problems/cvrp/operators/intra_relocate.o problems/cvrp/operators/intra_two_opt.o problems/cvrp/operators/mixed_exchange.o problems/cvrp/operators/or_opt.o problems/cvrp/operators/pd_shift.o problems/cvrp/operators/relocate.o problems/cvrp/operators/reverse_two_opt.o problems/cvrp/operators/route_exchange.o problems/cvrp/operators/swap_star.o problems/cvrp/operators/two_opt.o problems/cvrp/operators/unassigned_exchange.o problems/tsp/heuristics/christofides.o problems/tsp/heuristics/local_search.o problems/vrptw/operators/cross_exchange.o problems/vrptw/operators/intra_cross_exchange.o problems/vrptw/operators/intra_exchange.o problems/vrptw/operators/intra_mixed_exchange.o problems/vrptw/operators/intra_or_opt.o problems/vrptw/operators/intra_relocate.o problems/vrptw/operators/intra_two_opt.o problems/vrptw/operators/mixed_exchange.o problems/vrptw/operators/or_opt.o problems/vrptw/operators/pd_shift.o problems/vrptw/operators/relocate.o problems/vrptw/operators/reverse_two_opt.o problems/vrptw/operators/route_exchange.o problems/vrptw/operators/swap_star.o problems/vrptw/operators/two_opt.o problems/vrptw/operators/unassigned_exchange.o structures/generic/edge.o structures/generic/matrix.o structures/generic/undirected_graph.o structures/vroom/break.o structures/vroom/cost_wrapper.o structures/vroom/job.o structures/vroom/location.o structures/vroom/raw_route.o structures/vroom/solution_state.o structures/vroom/time_window.o structures/vroom/tw_route.o structures/vroom/vehicle.o structures/vroom/input/input.o structures/vroom/input/vehicle_step.o structures/vroom/solution/computing_times.o structures/vroom/solution/route.o structures/vroom/solution/solution.o structures/vroom/solution/step.o structures/vroom/solution/summary.o structures/vroom/solution/violations.o structures/cl_args.o utils/exception.o utils/input_parser.o utils/output_json.o utils/version.o

-------------------------------
Libs installed (version: latest available in Ubuntu 22.04):
libssl-dev, libasio-dev, build-essential, git, cmake, pkg-config, doxygen, libboost-all-dev, libtbb-dev, lua5.2, liblua5.2-dev, libluabind-dev, libstxxl-dev, libstxxl1v5, libxml2, libxml2-dev, libosmpbf-dev, libbz2-dev, libzip-dev, libprotobuf-dev

Thanks for reading this issue, have a good one!

**Comment by nilsnolde** [comment]
> I´ve been for the last week trying to compile vroom in an Ubuntu 22.04

And you succeeded! What did you expect to happen?

Did you try executing the `vroom` executable? That and the vroom library is the only output of compilation (usually is for C++ projects). Try `./vroom -h`:)

**Comment by DaftDanieh** [comment]
HAHAHA no waay. Didn´t thought about the -h. I was only executing it like ./vroom and nothing happened. Thank you for your answer!

**Comment by jcoupey** [comment]
Looks like we can close now. ;-)
