### ISSUE TITLE
Overlapping time windows

### ISSUE THREAD

**Issue by josephpeterson-dev** [VROOM-Project/vroom#845]
{"code": 2, "error": "Unsorted or overlapping time-windows."}
I keep getting this error (for only one of my hundreds of requests).
Vroom/OSRM will not tell me if it is an appointment or route or which id of the entity it is.
I wrote a script to ensure each window appears inside the time horizon for the day and they (breaks) do not overlap. 
I cant seem to figure out what could be causing this and would love your help.
Here is the request I am sending:
https://drive.google.com/file/d/12nLFNhGjwUZu8OLHI79v3nlrvfUr0XEd/view?usp=sharing

**Comment by Orthae** [comment]
One of the tasks have two same time windows, which causes the time-window overlap.
```        
{
	"id": 26748246,
	"time_windows": [
		[
			1670617800,
			1670622300
		],
		[
			1670617800,
			1670622300
		]
	],
	"skills": [
		1006,
		1001
	],
	"service": 3600,
	"location": [
		-82.341774,
		27.86904
	],
	"description": "Initial Service",
	"priority": 100,
	"delivery": [
		1
	],
	"setup": 300
}
```

**Comment by jcoupey** [comment]
Grepping for the error message though the code leads to this check:

https://github.com/VROOM-Project/vroom/blob/16c0e9c045d2d41611ddfebe946ff7424da61327/src/utils/helpers.h#L375-L387

You could adjust it to output more info about the time windows themselves, or use that exact same logic in your script.
