### ISSUE TITLE
Constraints violation

### ISSUE THREAD

**Issue by LeoAlle** [VROOM-Project/vroom#849]
Hi,
Are TW-contraints and capacity constraints soft or hard?
If soft, which is the max. percentage violation the solver accepts?

**Comment by jcoupey** [comment]
Hard: quoting the docs, time windows describe "valid slots for task service start", so the constraints are either met or not.

**Comment by LeoAlle** [comment]
And what about capacity constraints?

**Comment by LeoAlle** [comment]
Ok @jcoupey, thanks a lot.
