### ISSUE TITLE
Only single vehicle is assigned

### ISSUE THREAD

**Issue by unitedadi** [VROOM-Project/vroom#850]
Hello , i am using openrouteservice to access Vroom. I have mentioned two vehicles with strict time_window , but no matter what combination i use , only one vehicle is assigned. what am i doing wrong?

`{
    "vehicles": [
        {
            "id": 1,
            "profile" : "driving-car" ,
            "description" : "Bivek",
            "start": [54.369423 ,24.469901],
            "end": [54.369423 ,24.469901] ,
            "capacity": [100, 100]
        },
        {
            "id": 2,
            "profile" : "driving-car" ,
            "description" : "edward",
            "start": [54.500459 ,24.410319],
            "end": [54.500459 ,24.410319],
            "capacity": [100, 100]
        }
    ],
    "shipments": [
        {
            "id": 1,
            "pickup" : {
                "id" : 1,
                "location" : [54.3548463 , 24.4789258],
                "time_window" : [7, 30, 7, 31]
            },
            "delivery" : {
                "id" : 1,
                "location" : [54.55441927542401 , 24.40708355049081] ,
                "time_window" : [7, 30, 7, 31]
            }
        },
        {
            "id": 2,
            "pickup" : {
                "id" : 2,
                "location" : [54.357353, 24.477356],
                "time_window" :[7, 30, 7, 31]
            },
            "delivery" : {
                "id" : 2,
                "location" : [54.361202 , 24.490808],
                "time_window" : [7, 30, 7, 31]
            }
        },
        {
            "id": 3,
            "pickup" : {
                "id" : 3,
                "location" : [54.374847, 24.467962],
                "time_window" :[7, 30, 7, 31]
            },
            "delivery" : {
                "id" : 3,
                "location" : [54.3212269 , 24.4593307],
                "time_window" : [7, 30, 7, 31]
            }
        }
    ]
}
`
Any help will be appreciated. Thank you

**Comment by jcoupey** [comment]
If we reach out to a good and valid solution using a single vehicle, it will (generally) be cheaper than other solutions that use two (you're saving going back and forth from start/end for one of the vehicles). So you're not doing anything wrong, it's probably simply the result of the best solution having just one route, not two.

**Comment by unitedadi** [comment]
Thanks for the swift reply. Here in the given example , i have made time_window exactly same for all the shipments , still one vehicle is assigned to all the shipments. This was the reason which got me wondering as one vehicle will not be able to do all the jobs with the given time constraints.

**Comment by jcoupey** [comment]
Tasks can have multiple time windows so the syntax is `time_windows` (plural) which is an array of arrays. Your `time_window` keys on `pickup` and `delivery` objects are simply ignored.
