### ISSUE TITLE
How vroom calculate route duration for the distance ?

### ISSUE THREAD

**Issue by lgmadurange** [VROOM-Project/vroom#853]
I just Want To Know That How vroom Generate Route Duration For The Distance, What Is The Vehicle Driving Speed (km/h) That Vroom Used To Calculate The Duration To Complete The Route ?

**Comment by jcoupey** [comment]
VROOM has no knowledge of any driving speed at the routing level. All durations/distances calculations are done prior to solving. At VROOM level, we get a matrix of travel times in input, either using one of the [supported routing engines](https://github.com/VROOM-Project/vroom#supported-routing-engines), or by reading the [`matrices` values](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#matrices) if present in input.

**Comment by lgmadurange** [comment]
Got The Idea! Thanks
