### ISSUE TITLE
route duration on OSRM to VROOM

### ISSUE THREAD

**Issue by MoeinSHprogrammer** [VROOM-Project/vroom#854]
Hi 
I want to know where the OSRM response to vroom is received? which file code? I want to change the durations returned from OSRM so that this change is applied in the vroom calculations (multiply the durations by 1.3) and I don't know in which part of the code this multiplication should be done so that it is applied to the entire vroom calculation process.

**Comment by nilsnolde** [comment]
Doesn’t „speed_factor“ do what you want?

**Comment by MoeinSHprogrammer** [comment]
> Doesn’t „speed_factor“ do what you want?

Can you tell me how to do this with "speed factor"? The default value for SPEED FACTOR is one. How much should it change to be equivalent to multiplying DURATION by 1.3?

**Comment by nilsnolde** [comment]
1/1.3?!?!

**Comment by MoeinSHprogrammer** [comment]
> 1/1.3?!?!

Imagine that the duration will be 550. I want it to be 715 using the speed factor. (550*30% (550) =715). In this case, what value should the speed factor take?

**Comment by nilsnolde** [comment]
Fearing a rabbit hole of similar questions, I'll leave it to you to figure that out.

**Comment by jcoupey** [comment]
Closing as answered.
