### ISSUE TITLE
Update GitHub Actions

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#857]
There is a note saying that Node.js 12 actions are deprecated (see [Annotations](https://github.com/VROOM-Project/vroom/actions/runs/3694932899)). This includes `actions/checkout` and `actions/cache`.

A simple fix is to update both to `v3`.

**Comment by jcoupey** [comment]
Thanks for spotting and submitting a PR.

**Comment by jcoupey** [comment]
Done in #858.
