### ISSUE TITLE
Low performance on machine with many threads

### ISSUE THREAD

**Issue by nemosmithasf** [VROOM-Project/vroom#861]
I'm running VROOM in docker with 30 threads, and I was surprised to find that it doesn't fully take advantage of all the threads. On average, each thread is at about 20% utilization- and my time-to-completion for 2 threads vs 30 threads are identical (though in the 2-thread scenario, it ends up utilizing 100% of the CPU).

I have the `-t` parameter configured to 30; is this actually detrimental? Would I be better off running 30 different instances of VROOM and trying to balance the calls, as opposed to one instance with many threads?

![Screenshot 2023-01-10 at 7 26 34 PM](https://user-images.githubusercontent.com/14184529/211689928-2ea9d138-b8f8-41ad-a418-c7798bfd5a4f.png)

**Comment by jcoupey** [comment]
The number of threads *allowed* is controlled by the `-t` parameter but not all are necessarily used depending on exploration level. Can you share the full command you're running, your `vroom` version and [a standalone version](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) of your problem instance? 

> Would I be better off running 30 different instances of VROOM and trying to balance the calls

This does not really make sense if we're talking about solving a single problem.
