### ISSUE TITLE
How to minimize route crossing

### ISSUE THREAD

**Issue by tomita-tomita** [VROOM-Project/vroom#862]
We are using vroom and valhalla in docker. 
In some requests we noticed some route crossings, we added time windows in each task, but the crossing keeps appearing.
Is there any setting to decrease this crossover?

![image](https://user-images.githubusercontent.com/19315422/212094947-daff6722-b3e7-4189-8a60-954f348e1bc8.png)

`{
	"vehicles": [		
		{
			"id": 1,
			"description": "v1",
			"start": [
				-46.830962,
				-23.228301
			],
			"end": [
				-46.830962,
				-23.228301
			],
			"capacity": [
				4000
			]
		},
		{
			"id": 2,
			"description": "v2",
			"start": [
				-46.830962,
				-23.228301
			],
			"end": [
				-46.830962,
				-23.228301
			],
			"capacity": [
				4000
			]
		}
	],
	"jobs": [
		{
			"id": 1,
			"description": "J01",
			"service": 0,
			"delivery": [
				1579
			],
			"location": [
				-46.464535,
				-23.135624
			]
		},
		{
			"id": 2,
			"description": "J02",
			"service": 0,
			"delivery": [
				208
			],
			"location": [
				-46.397369,
				-23.182663
			]
		},
		{
			"id": 3,
			"description": "J03",
			"service": 0,
			"delivery": [
				229
			],
			"location": [
				-46.395423,
				-23.164247
			]
		},
		{
			"id": 4,
			"description": "J04",
			"service": 0,
			"delivery": [
				619
			],
			"location": [
				-46.565881,
				-23.122789
			]
		},
		{
			"id": 5,
			"description": "J05",
			"service": 0,
			"delivery": [
				413
			],
			"location": [
				-46.804281,
				-23.017563
			]
		},
		{
			"id": 6,
			"description": "J06",
			"service": 0,
			"delivery": [
				310
			],
			"location": [
				-46.544925,
				-22.955944
			]
		},
		{
			"id": 7,
			"description": "J07",
			"service": 0,
			"delivery": [
				1031
			],
			"location": [
				-46.540504,
				-22.943652
			]
		},
		{
			"id": 8,
			"description": "J08",
			"service": 0,
			"delivery": [
				413
			],
			"location": [
				-46.528993,
				-22.960256
			]
		},
		{
			"id": 9,
			"description": "J09",
			"service": 0,
			"delivery": [
				310
			],
			"location": [
				-46.587723,
				-22.780574
			]
		},
		{
			"id": 10,
			"description": "J10",
			"service": 0,
			"delivery": [
				83
			],
			"location": [
				-46.580494,
				-23.13246
			]
		},
		{
			"id": 11,
			"description": "J11",
			"service": 0,
			"delivery": [
				186
			],
			"location": [
				-46.501662,
				-23.105462
			]
		},
		{
			"id": 12,
			"description": "J12",
			"service": 0,
			"delivery": [
				225
			],
			"location": [
				-46.357239,
				-23.052655
			]
		},
		{
			"id": 13,
			"description": "J13",
			"service": 0,
			"delivery": [
				246
			],
			"location": [
				-46.703636,
				-23.085626
			]
		},
		{
			"id": 14,
			"description": "J14",
			"service": 0,
			"delivery": [
				309
			],
			"location": [
				-46.71254,
				-23.13585
			]
		},
		{
			"id": 15,
			"description": "J15",
			"service": 0,
			"delivery": [
				226
			],
			"location": [
				-46.395755,
				-23.182641
			]
		},
		{
			"id": 16,
			"description": "J16",
			"service": 0,
			"delivery": [
				864
			],
			"location": [
				-46.395614,
				-23.160873
			]
		},
		{
			"id": 17,
			"description": "J17",
			"service": 0,
			"delivery": [
				165
			],
			"location": [
				-46.395055,
				-23.159554
			]
		},
		{
			"id": 18,
			"description": "J18",
			"service": 0,
			"delivery": [
				62
			],
			"location": [
				-46.559528,
				-23.099577
			]
		},
		{
			"id": 19,
			"description": "J19",
			"service": 0,
			"delivery": [
				145
			],
			"location": [
				-46.270391,
				-22.932536
			]
		},
		{
			"id": 20,
			"description": "J20",
			"service": 0,
			"delivery": [
				83
			],
			"location": [
				-46.722104,
				-23.035683
			]
		},
		{
			"id": 21,
			"description": "J21",
			"service": 0,
			"delivery": [
				161
			],
			"location": [
				-46.388752,
				-23.171853
			]
		}
	]
}`

**Comment by jcoupey** [comment]
From your screenshot it looks like the two vehicles are simply using the same main roads to reach out to neighboring areas. In order for this not to happen, a single vehicle would have to serve all zones in the screenshot, which is probably not possible due to timing or capacity restrictions.

Can you share the solution you'd expect to get on this example (ordered list of jobs for vehicles)?
