### ISSUE TITLE
HOWTO: convertible vehicle load capacity / capacity-usage dependant service time penalties

### ISSUE THREAD

**Issue by mbachem-rvk** [VROOM-Project/vroom#865]
HI there,

I am facing a vehicle with convertible passenger slots. Using the second dimension in a [4,1] capacity makes the vehicle loose a seat in the first dimension. I will address this by running vroom twice if the full load of [4,1] is reached somewhere in the solution. Then I reduce the capacity of that very vehicle to [3,1] and re-run vroom. Is there a way to do it in one vroom-call?

Related to that, when using the second dimension, I need to increase the pickup/delivery service time dramatically. Again, I can handle this by consecutive vroom calls, using different vehicle timeslots with different service-time penalties.
Would be great if I could define a service penalty as absolute offset, plus seperate faktors for seperate dimensions.

Thanks for your awesome work! looking forword to read the code...

cheers,
  Martin

**Comment by jcoupey** [comment]
> Using the second dimension in a [4,1] capacity makes the vehicle loose a seat in the first dimension

Sounds like a `[1, 1]` amount for the task then?

> Related to that, when using the second dimension, I need to increase the pickup/delivery service time dramatically.

I don't really see the problem here. The service time is not described at vehicle level depending on its capacity, but at job/shipment level. You can simply adjust the service time depending on the `amount` component used at task level.

**Comment by mbachem-rvk** [comment]
many thanks for your reply.

yes, the shipment would be [1,1] for a a single passenger having a wheelchair. a [4,1] vehicle then would have a [2,0] capacity left, for the wheelchair slot (sometimes) is just a convertibale passenger seat slot, instead of an exclusive seat.

and yes, your right, as I can specifiy the service time per shipment, there is no problem at all with extra service time penalty for wheelchair pickup/delivery jobs.

**Comment by mbachem-rvk** [comment]
could be fun to try creating a patch giving kind of a cross-talk possibility, having dimension X consuming additional space in dimension Y with faktor K in [1..n] ;)
(if there is no other way already included)

**Comment by jcoupey** [comment]
Closing as answered.
