### ISSUE TITLE
Equal jobs distribution for jobs in given time frame

### ISSUE THREAD

**Issue by Fusix** [VROOM-Project/vroom#867]
Hey there,

we are trying to implement vroom for efficient routes und job distribution to vehicles/employees. We want to plan future jobs for the vehicles. One constraint should be that the amount of jobs should approximately equally distributed among all available vehicles.
So here is our example scenario to describe the problem. We tried modeling this in two ways. In both cases there are 2 vehicles and 50 open jobs with a service duration of 1 hour. Most of the jobs are in the city and some are outside. One employee is starting their day in the city and the other one in an outer district. At the end of the day the vehicle should return back home in time until the end of their shift. The next month should be planned.

1. One vehicle per day, brakes for already planned events, time windows for working hours

  |    start   | employeeId | total |
  |:----------:|:----------:|:-----:|
  | 2023-01-01 | 1          | 1     |
  | 2023-01-01 | 2          | 7     |
  | 2023-01-02 | 2          | 7     |
  | 2023-01-03 | 2          | 8     |
  | 2023-01-04 | 2          | 8     |
  | 2023-01-05 | 2          | 7     |
  | 2023-01-06 | 2          | 9     |
  | 2023-01-07 | 2          | 3     |

2. one vehicle with a time window for all days of the month (start: 1st of month, end: last day of month), brakes for planned events, breaks for time outside working hours (nights)

|    start   | employeeId | total |
|:----------:|:----------:|:-----:|
| 2023-01-01 | 1          | 14    |
| 2023-01-01 | 2          | 10    |
| 2023-01-03 | 2          | 7     |
| 2023-01-04 | 2          | 7     |
| 2023-01-05 | 2          | 7     |
| 2023-01-06 | 2          | 4     |
| 2023-01-07 | 2          | 1     |

Both solutions complete the jobs in a week but the work is not equally distributed. How to model that particular case to get a good result between best routes with shortest overall time and equal work for all vehicles? I also read about #329. So this must be possible for both solutions with a capacity restriction. The first solution is the preferred solution as breaks don't have to be overused to model the time off work.

I am grateful for the discussion and future ideas on how this can be achieved.

Thank you for your help!

**Comment by jcoupey** [comment]
As a general comment, the `max_tasks` key can sometimes help to force some kind of balance.

> Both solutions complete the jobs in a week but the work is not equally distributed

Can you elaborate on what you exactly mean by "not equally distributed"? Or even better yet provide an actual example of input/output along with what difference you'd expect for an "equally distributed" solution?

**Comment by Fusix** [comment]
Hey @jcoupey thanks for your reply.

As above solution 1. is preferred as it is simpler, I will elaborate on this one. 
Given the [input-1673973284416.json](https://github.com/VROOM-Project/vroom/files/10437324/input-1673973284416.json.txt) file and producing the [output-1673973284416.json](https://github.com/VROOM-Project/vroom/files/10437323/output-1673973284416.json.txt) we get the following vehicle distribution:

|    start   | employeeId | total |
|:----------:|:----------:|:-----:|
| 2023-01-01 | 1          | 7     |
| 2023-01-01 | 2          | 8     |
| 2023-01-02 | 2          | 7     |
| 2023-01-03 | 2          | 7     |
| 2023-01-04 | 2          | 8     |
| 2023-01-05 | 2          | 7     |
| 2023-01-07 | 2          | 6     |

As we can see if all jobs have a duration of 1 hour there is a maximum of 8 jobs possible per vehicle per day including driving times in between. To use the full potential of the fleet it would be better if vehicle/employee 2 (in the city) would get as much jobs as it can and then use the other vehicles. From day 2 on only vehicle 2 is used and vehicle 1 get's no jobs assigned.
So how to achieve the described behaviour? 

When `max_tasks` is set to e.g. `5` we get the following distribution of jobs to the vehicles/employees:

|    start   | employeeId | total |
|:----------:|:----------:|:-----:|
| 2023-01-01 | 1          | 5     |
| 2023-01-01 | 2          | 5     |
| 2023-01-02 | 2          | 5     |
| 2023-01-03 | 2          | 5     |
| 2023-01-04 | 2          | 5     |
| 2023-01-05 | 2          | 5     |
| 2023-01-06 | 2          | 5     |
| 2023-01-07 | 2          | 5     |
| 2023-01-08 | 2          | 5     |
| 2023-01-09 | 2          | 5     |

**Comment by jcoupey** [comment]
Vehicle 1 has a different start/end so it is better suited to serve *a few* of the jobs you have. This is why one slot for vehicle 1 is used (and only one).

I'm not 100% sure I get what you expect but if you were to switch some of the vehicle 1 load to another vehicle 2 slot, that would be more expensive. This is why you don't get such a solution in output. You could test that by removing the vehicle 1 from the input altogether.

**Comment by Fusix** [comment]
Yes I understand why this is the result but will it be possible to force the 50 jobs to be equally divided even though it would be a more expensive solution? 

It should still use the best possible solution but with the constraint to use all vehicles almost equally.

Thanks again for your answer!

**Comment by jcoupey** [comment]
> force the 50 jobs to be equally divided 

Based on the 8 tasks max per vehicle, you need at least 7 vehicles to handle the 50 jobs. The perfect balance across 7 vehicles would be ~7.14 tasks per vehicle so the solution you listed above looks quite balanced already. You could maybe avoid 6-tasks routes by using `"max_tasks": 7` for all vehicles but one with `"max_tasks": 8`.

**Comment by Fusix** [comment]
To described the desired result here is another table describing the intended distribution across all available verhicles.

Given e.g. 5 vehicles in the fleet the objective is that all 5 vehicles should be busy on each day. When the `max_tasks` is set to `5` we could get the following matrix: 

![image](https://user-images.githubusercontent.com/6383231/216600408-f0022b28-e750-4f32-a468-1888afa8b96b.png)

As you can see sometimes it is okay if one vehicle can not be busy to the fullest but the optimum will be the maximum.

I hope it gets more clear now. That means that the equal distribution should depend on the amount of jobs per verhicle and the amount of jobs for all available vehicles in general.

**Comment by jcoupey** [comment]
What's wrong with dividing the total number of jobs by the number of vehicle slots to decide the right `max_tasks` value? That's merely what I did in my previous comment.

**Comment by Fusix** [comment]
It seems actually setting `max_tasks` fixes the problem: 

|    start   | employeeId | total |
|:----------:|:----------:|:-----:|
| 2023-01-02 | 1          | 5     |
| 2023-01-02 | 2          | 3     |
| 2023-01-02 | 3          | 5     |
| 2023-01-02 | 4          | 5     |
| 2023-01-02 | 5          | 5     |
| 2023-01-03 | 1          | 5     |
| 2023-01-03 | 2          | 5     |
| 2023-01-03 | 3          | 5     |
| 2023-01-03 | 4          | 5     |
| 2023-01-03 | 5          | 5     |
| 2023-01-04 | 1          | 5     |
| 2023-01-04 | 2          | 5     |
| 2023-01-04 | 3          | 5     |
| 2023-01-04 | 4          | 5     |
| 2023-01-04 | 5          | 5     |
| 2023-01-05 | 1          | 4     |
| 2023-01-05 | 2          | 5     |
| 2023-01-05 | 3          | 5     |
| 2023-01-05 | 4          | 5     |
| 2023-01-05 | 5          | 5     |
| 2023-01-06 | 1          | 5     |
| 2023-01-06 | 2          | 5     |
| 2023-01-06 | 3          | 5     |
| 2023-01-06 | 4          | 5     |
| 2023-01-06 | 5          | 5     |
| 2023-01-09 | 1          | 5     |
| 2023-01-09 | 2          | 5     |
| 2023-01-09 | 3          | 5     |
| 2023-01-09 | 4          | 5     |
| 2023-01-09 | 5          | 5     |
| 2023-01-10 | 2          | 5     |
| 2023-01-10 | 3          | 5     |
| 2023-01-10 | 4          | 5     |
| 2023-01-10 | 5          | 5     |

Maybe the previous examples were meaningful enough as there were only 2 vehicles. 
I close this issue as resolved.
