### ISSUE TITLE
Choosing the best pickup automatically from a list of possibilities.

### ISSUE THREAD

**Issue by fsty** [VROOM-Project/vroom#868]
Hi!
My use case is as follows: 
Suppose we have 6 stores: A B C D E F

A B and C want to be delivered today
A can be delivered by B , C  or F
B can be delivered by A , C,  D  or F
C can be delivered by A,  D,  E  or F

The objective would be to select the most efficient combination of pickup and delivery locations for the "shipment" object.

**Comment by jcoupey** [comment]
The `shipment` objects take both pickup and delivery descriptions as input and it is not possible to pass a list of options. The assignment choice you describe has to be made outside VROOM based on your own business rules.
