### ISSUE TITLE
Fixed vehicle quantity

### ISSUE THREAD

**Issue by andybmx** [VROOM-Project/vroom#871]
Hi. Can you please tell me, if it is possible to force vroom to make a solution for fixed number of vehicles? e.g. I have 10 vehicles, and I want them all to be used. If there are 10 deliviries - let it be one vehicle for one point, for example. There are many reasons to do so. 
Thanks for your project - it`s really great!

**Comment by jcoupey** [comment]
>If there are 10 deliviries - let it be one vehicle for one point

That would amount to using a `"max_tasks": 1` on all vehicles.

You may also want to read #466 on a related topic.

**Comment by andybmx** [comment]
Appreciate for your answer. Sorry, I`ve missed that discussion. 
Setting `max_tasks` and `capacity` constrains really did the trick. 
Thank you!!!!
