### ISSUE TITLE
Increasing MAX_PRIORITY variable

### ISSUE THREAD

**Issue by matej14086** [VROOM-Project/vroom#878]
I have three types of jobs;

 A- most valuable
 B- less valuable
 C- least valuable

I would like to set that value of job A is 15 times value of job B, and value of job B is 15 time value of job C.
That would result that job C has priority 1, job B has priority 15 and job A has priority 225.

But because priority is int between 0 and 100 I can't achieve that.

So my question will I introduce some optimization problems if I increase MAX_PRIORITY to 1000 or 100000. 
Would engine still generate good solutions?

**Comment by jcoupey** [comment]
Closing as answered.
