### ISSUE TITLE
Different service costs for different vehicle types

### ISSUE THREAD

**Issue by RegularnaMatrica** [VROOM-Project/vroom#879]
Is it possible to have different `service` times in `jobs` for different vehicle types (profiles)? For example, for `vehicle_type_1`, and `vehicle_type_2`:

`{
  id = 0,
  ...,
  service = {vehicle_type_1 = 10, vehicle_type_2 = 20},
  ...
}`

**Comment by RegularnaMatrica** [comment]
Thank you for directions. Just to confirm, only scaling factor is being considered at the moment?

**Comment by jcoupey** [comment]
There is no roadmap prioritization for this currently, let alone an actual choice on how to do it. If you (or others) are willing to push this forward, we're always open to mutualizing dev funding.
