### ISSUE TITLE
Invalid time_windows array for job 62

### ISSUE THREAD

**Issue by droppy2014** [VROOM-Project/vroom#880]
I am trying to send a simple query through vroom-express

curl --header "Content-Type:application/json" --data '{"jobs":[],"shipments":[{"pickup":{"id":62,"description":"order_id=62","location":[30.366084,59.929218],"setup":0,"service":0,"time_windows":[]},"delivery":{"id":62,"description":"order_id=62","location":[30.40109,59.97106],"setup":0,"service":0,"time_windows":[]},"skills":[1000000007]}],"vehicles":[{"id":1,"description":"description","start":[30.315257,59.936927],"end":[30.321222,59.936309],"skills":[1000000007],"max_tasks":40}]}' http://localhost:3000

but have an error

Tue, 31 Jan 2023 11:48:55 GMT: [Error] Invalid time_windows array for job 62.

I am trying to use "time_windows":false, "time_windows":null and "time_windows":[] but the error is still the same. I know that if I avoid using time_window parameter at all, then there is no error. But I have to use it because it is generating by my mode by default.

vroom was run by docker
docker run -dt --name vroom --net host -v $PWD/conf:/conf -e VROOM_ROUTER=osrm vroomvrp/vroom-docker:v1.12.2

**Comment by jcoupey** [comment]
> I am trying to use "time_windows":false, "time_windows":null and "time_windows":[]

This won't work as you noticed. You have to either omit the `time_windows` key or provide at least a valid time frame in the array.

**Comment by jcoupey** [comment]
Closing as answered.
