### ISSUE TITLE
Include a build system (CMake) to ensure high-quality development?

### ISSUE THREAD

**Issue by SC-One** [VROOM-Project/vroom#881]
Hi there, Thanks for reading this note.
I checked the whole source (not completely, but I got what was going on).
I found some problems when using raw make file(build system unused) in this project :

- no test cases (i.e., using GTest to test functionalities)
- no benchmark(test) vs previous versions benchmark tests(i.e change an algorithms to new one and compare to previous version algo)
- using various new IDEs to have better control in so many cases(using beautifiers , static code analyzer , profiling , debugging
- generate files for other IDEs too, like QtCreator, VS, Code, etc (if a developer is working on another platform, debugging and fixing problems are easier!).
- seprate stages and any cases that should be seprated is easier in modern build systems , for example creating example, library(here is vroom), benchmark , install stage.
- and finally controlling over variables when build or install (I mean make variables and other configs that is needed) is easier in modern build systems (i.e: showing variables and configs in cmake-gui)

I agree that you can do the above cases with a makefile too, since cmake finally generates makefiles too :| , but it's about having easier control over these ideas!

We have other reasons too, but I think this is enough  for making you convience.
I just listed all the problems to say that I can add a build system and change hierarchy files (not functionality) and project files if you will merge them!
Why I asked this question? because maybe later we added new features or make some optimizations(either you , or me) it's so hard to merging withtogether , so I decided before coding on this update ,I ask you. If you will not accept the pull request for this update, I will not move forward.
also I checked cmake keyword in issues too. cause of that I made these informations.(The top related issue was this [link](https://github.com/VROOM-Project/vroom/issues/454))

So do you agree with that? If yes, I will start that.

**Comment by jcoupey** [comment]
Thanks for the input! You're raising many points so I'll do my best to answer all of them. ;-)

>  no benchmark(test) vs previous versions benchmark tests

Yes we do extensively use quite a lot of benchmark instances as [functional](https://github.com/VROOM-Project/vroom/#functional-tests) and non-regression tests. For convenience, the instances are in a separate repo but everything is reusable and reproducible.

> no test cases (i.e., using GTest to test functionalities)

We don't have unit tests, neither are we using a test/mocking framework. The rationale is that the benchmarks we use provide a large functional coverage. Of course this is a debatable topic in itself, but I don't really see a direct relation with the build system. I mean it's possible to have tests or no tests both when using plain make or CMake.

> using various new IDEs to have better control in so many cases(using beautifiers , static code analyzer , profiling , debugging

We have our own `clang-format` [script](https://github.com/VROOM-Project/vroom/blob/master/CONTRIBUTING.md#automatic-formatting). Of course using additional tools for code analysis could be useful, see for example some existing tickets: #789, #797. I'm open to other suggestions but again I don't really see how it relates to the build system.

> generate files for other IDEs too, like QtCreator, VS, Code, etc (if a developer is working on another platform, debugging and fixing problems are easier!).

Not sure I get your point here, do you mean editor-specific config files for the project?

> seprate stages and any cases that should be seprated is easier in modern build systems , for example creating example, library(here is vroom), benchmark , install stage.

We already have two stages in the current makefile to build the main `vroom` exec and the `libvroom.a` library.

> and finally controlling over variables when build or install (I mean make variables and other configs that is needed) is easier in modern build systems (i.e: showing variables and configs in cmake-gui)

This may make sense when you have a ton of build variables but setting aside the compiler choice, the only build variable our users may tweak is `USE_ROUTING` and that's already for very specific situations.

I'm sorry if I'm sounding a bit skeptical here, but as I noted in #454, I really want to keep things as simple as possible as long as it works this way.

**Comment by SC-One** [comment]
Thanks for the answer; I appreciate it and am considering your entire response.
So I want to say the reason for this change, and it's your decision to choose which one:
Whole of the tasks and jobs in the world can be done, but how? In this case, we can do the whole of the tasks (benchmarking, testing, adding new features, bug fixing, hot fixing, building dependencies, installing the Vroom library, loading in a new IDE, configuring and loading in other platforms too, and CC for other platforms) by making a make file and using Autotools. but with so many aches and pains!and so many extra tasks! Using modern build systems will assist the new developer who is joining this project in doing rapid configuration on his or her platform!because modern construction systems handled it!We have numerous examples that demonstrate why they did not use makefile instead of cmake!So many projects are written with a modern build system (you're hesitant to change because it's easier to stay in this stage, but high-quality projects are always updated with modern features, just like the standard version in this project, which is really nice, it's C++17).
and I'd like to point out that this change is similar to having a one-click configuration project and moving forward with your new idea.
In actuality, with this change, you made your project simpler than the old version, and it grew better and more rapidly!

for example:
You can use libvroom in third-party projects without having to deal with direct build and installation:
_add_library(libvroom)_
You can also create cmake configuration files and easy to use libvroom in other projects
_find_package(libvroom)_
or having benchmark tools in another folder, while other developers add new benchmarks that you didn't consider! but in a simple way:
_find_package (benchmark required) or add_subdirectory (benchmark)_
and modern IDEs will detect cmake and can generate a GUI (such as cmake-qt-gui) for easy variable control.
For example, building as shared or static is really easy for cross-platform in cmake.(dll/so , a/lib)
As I previously stated, you can contribute large projects in any way (makefile or modern buildsystems), but it is entirely up to you whether to use one-click and simple configurations!or configure all of these processes manually.(For example, enable examples, and it will copy inputs and outputs to the out directory, and tests will check if the outputs passed or not with a single click, or manually configure in any platform or situation).
Actually, it's a standard way to handle these types of projects (like so many high-quality projects). Sorry if it was a long answer, but when something is standard, growing it and making it better will be easier than before.

And finally, a mini note: when you can use CMake, modern IDEs (and future IDEs that don't use autotools__useful on makefiles) will support the project better, and modern IDEs have so many features that help you work on the project easier. and exactly how cmake generates makefiles too, but they correspond to the platform and other situations that maybe you didn't consider.

**Comment by THM-T** [comment]
> Of course your points make sense, especially for big projects with a distributed dev team, and with a huge basis of potential contributors. On the other hand:
> 
>     1. contributions to VROOM are obviously gladly welcome, but let's face it, it is quite a niche since people have to be skilled both in C++ and operational research to dig in the code, let alone change it in a relevant way. I honestly think this is the main blocker for getting more significant contributions, not the few steps required to build the project.
> 
>     2. I'm doing most of the dev here and sharing it for free, but it does not mean I'm ready to commit to a higher maintenance burden and this is what will surely happen to some extent if we change the build system. My aim is to run VROOM in a straightforward way on (Ubuntu) Linux and the current makefile does a very good job for that use-case. Anyone with a need to run it on other platforms should invest their own time into it.

totally answered out of bias.

**Comment by nilsnolde** [comment]
I'd also be very interested to have CMake as a build system. But honestly, anyone here should be VERY happy that such a high-quality code base is "freely" available. You're welcome to maintain a public fork with the changes necessary, which is also VERY doable, since it's only adding files, so I'd barely expect any conflicts when syncing. 

If an organization has a need for all the bells and whistles, you'll find someone to maintain that fork for you. If @jcoupey wouldn't like to be funded for that, I'd be interested.

**Comment by jcoupey** [comment]
>  totally answered out of bias.

Of course this is biased! Do you really expect me to include contributions without taking into account my own company interest/roadmap while we've been pushing the whole dev effort for years now and making it available to everyone?

If I weren't somehow biased and favoring our needs and the ones of our paying users, I don't think it would be possible to build a sustainable business model around this open-source project at all.
