### ISSUE TITLE
Priority 0 works differently than expected

### ISSUE THREAD

**Issue by fbaierl** [VROOM-Project/vroom#882]
In our project, we encountered an issue concerning priorities. We use priorities in the following manner:

- priority 0: do those, if you cannot do anything else
- priority 2: second highest priority
- priority 100: highest priority

Unfortunately, we noticed in one of our examples, that VROOM prefers doing roughly five priority 0 shipments over one priority 2 shipment (id 19 and 20). I thought it works like this: 0 * 5 < 2 * 1 => prefer the priority 2 shipment.

Do we have a misunderstanding here? The API description is not a 100% clear on this.

I attached the input/output of our example here:

[input.txt](https://github.com/VROOM-Project/vroom/files/10566152/input.txt)
[output.txt](https://github.com/VROOM-Project/vroom/files/10566153/output.txt)

*Edit: I tried the same input but with priority 10 instead of 2 and then it works as expected. So my guess is, that VROOM currently treats priority 0 like I would expect priority 1 to work.

We are using VROOM v1.13-rc1

**Comment by jcoupey** [comment]
Your understanding is correct and including a single shipment with priority 2 *is* considered better than fitting 5 shipments with priority 0. It may be that we don't come across the solution with 4 shipments less but higher priority in the search, and are thus providing a sub-optimal solution in that regard.

It would be useful to have a [standalone problem instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) in order to reproduce. Also it would be great if you can share the changes you'd make to the current solution to get to the expected result (route steps orderings).

**Comment by fbaierl** [comment]
> It may be that we don't come across the solution with 4 shipments less but higher priority in the search, and are thus providing a sub-optimal solution in that regard.

That is unlikely, since VROOM found the solution once I changed priorities from 2 to 10. 

> It would be useful to have a [standalone problem instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance)

I tried creating one with the linked scripts, but at the moment it does not seem to work with OSRM instances not running locally. I can try again once I find the time for it.

**Comment by jcoupey** [comment]
@fbaierl I tried taking a fresh look at this but unfortunately the solution I get with the OSRM stack I have at hand is very different (more unassigned tasks), and the solution you report is deemed invalid. Did you get around using the matrix-adding script? You should be able to adjust the remote OSRM instance using its raw IP.

> That is unlikely, since VROOM found the solution once I changed priorities from 2 to 10.

Can you share the route tasks ordering (or full solution) you get in that case?

**Comment by jcoupey** [comment]
@fbaierl is this still something you're coming across? If not, I'd be inclined to simply close here.

But if we're indeed producing sub-optimal solutions with regard to priority score, we should definitely tag this issue accordingly and keep it for reference. But I'd need a reproducible example for this: standalone input problem + manual solution that is better (and valid) in term of priority.
