### ISSUE TITLE
vehicle height & field path

### ISSUE THREAD

**Issue by Kirbylix** [VROOM-Project/vroom#889]
hello,

I have two questions:
1. How can I include the vehicle height in the request?
Since it spits out a route that goes through a tunnel that is too low for our vehicle.

2. he should not include dirt roads in the calculation, because we can not drive on them.

Thanks already

**Comment by jcoupey** [comment]
This is something you want to handle at the routing level: have your routing engine rule out the roads you want to discard. Then the matrices and routes we get from VROOM will reflect those choices.

**Comment by chrishubert** [comment]
@Kirbylix If you use OSRM, you should play around with the vehicle profile: 
For example, https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua 
In there, you can restrict dirt roads and height. 

Then you pass it to VROOM for the routing

**Comment by jcoupey** [comment]
Closing as answered.
