### ISSUE TITLE
Optimized pickup location or continious pickup/delivery model.

### ISSUE THREAD

**Issue by AMHZR** [VROOM-Project/vroom#891]
I am working on a problem in which we have multiple pickup locations around the city and all the pickup points hold the same type of inventory e.g Milk along with the pickup locations we also have a depo where the Vehicles are parked only (Start and End Locations). 

I am not able to extrapolate how Vroom can be used to build the optimal pickup and delivery route on the fly.
 I tried to use the shipments but they can only take one pickup location and that fixes the location of the pickup 

@jcoupey  What I need is the Dynamic Pickup and Drop solution, if you help me here or point to some previously documented discussion that will be super generous.

**Comment by jcoupey** [comment]
It's correct that shipments can only take one pickup location so in your case you'd have to decide on the pickup location prior to defining a shipment.

This question is a bit hard to answer without looking at the full problem and business constraints, all the more since the "dynamic" part seems to involve (re-)running optimization steps. In this case, you should probably wrap your own business logic around VROOM using evolving models.

**Comment by AMHZR** [comment]
Thanks for the quick response. really appreciate it.

 I will try to explain the use case  

We are a business, serving customers with a few types of products which they can request using our mobile APP, along with this we have scheduled customers as well.
We use Transit Vans to deliver these products, Our Drivers initially load the inventory at the beginning of the shift and follow the route assigned to them ( we use Vroom Jobs) to serve here, which is doing an awesome job so far. 

but now we have scaled up the business and established many stores in the city **( PickUp Locations)** along with the warehouses we initially had.

The Vans we use can carry up to a certain amount of  inventory, which will be delivered within a couple of hours after the beginning of the shift, which means they will have to come back to the warehouse and pick up the inventory again ( reload the van)

previously we had one warehouse and things were smooth but as now we have many pickup locations we want our Vans to go to the nearest possible pickup location and load the necessary inventory to continue delivering the product.

here we have an example

L1, L2, L3 ... Ln are the Pickup locations and we can pick up any number of products ( no limits for now)

C1, C2, C3, C4, and C5.  are the customers who have requested products of a certain quantity  ( 120, 55, 70, 50,100) with a timeslot.

we have  Vans  loaded initially with a certain capacity

V1 (150), V2 (150)

possible routes can be 

**V1 Start** --> **C3** (-70) --> **C4** (-50) --> **L2** (+120) --> **C5**( -100)

**V2 Start** --> **C1** (-120) --> **L1** (+25) --> **C2**(-55)


How can we assign the optimized pickup step for our vans using Vroom to do the CONTINUOUS DELIVERY..

**Comment by jcoupey** [comment]
You have two key concerns here:

1. Multiple pickup locations. As previously stated, you could use shipments to model the P&D context but then you have to somehow fix the desired pickup location, and possibly some other constraints, e.g. pickup TW. Alternatively, you could maybe get away with using only jobs in a simplified model that you have evolving during the day, but this would be really dependent on the whole workflow and the next concern below.
2. The "continuous delivery" part suggests you need to update the plan regularly. The frequency for that and the number/type of business decisions and assumptions you're making upon re-solving is key to designing a relevant model around VROOM, if even possible.

Frankly, I don't think this is something we can easily cover in a simple GitHub chat. Besides, this is the kind of consulting work we provide at [Verso](https://verso-optim.com/) for open-source users that want to make the best out of VROOM for a specific use-case. ;-) Feel free to reach out to me directly on that option.

**Comment by jcoupey** [comment]
Closing as answered.
