### ISSUE TITLE
Tasks assigned outside of vehicle time window

### ISSUE THREAD

**Issue by eocasio** [VROOM-Project/vroom#896]
Hi!  

First, thank you for sharing your work!

I have been scratching my head for weeks trying to figure out why VROOM assigns tasks to a vehicle beyond its operating time window.  

I have modified capacities, skills, assigning shorter an longer time windows, but  for some vehicles the algorithm assigns tasks well after the defined vehicle's time window.  At first I suspected I was messing up the timestamps, but that does not seem to be the case.

I have attached a standalone problem instance to review at your convenience.

Than you.
 
[stand_alone_test_problem_matrix.txt](https://github.com/VROOM-Project/vroom/files/10889617/stand_alone_test_problem_matrix.txt)

**Comment by jcoupey** [comment]
Tasks can have several time windows and  thus use a `time_windows` (plural) key that is an array of TW. Vehicles can only have a single time window, so the key is `time_window` (singular).

The `vehicle.time_windows` entries in your instance are basically ignored.

**Comment by eocasio** [comment]
You are right!  Thank you from your quick response.
