### ISSUE TITLE
Optional distance-matrix server connection if custom matrices are provided

### ISSUE THREAD

**Issue by DCSnip3r** [VROOM-Project/vroom#898]
I have a situation where my ORS and VROOM servers are protected with separate authentication.  I am fetching the distance matrix first, and supplying it to Vroom so Vroom does not have to load it.

It seems my Vroom server is unable to connect to the matrix service.  It would make sense that vroom isn't able to send an authenticated request. It is ALSO possible that I've also misconfigured the connection to the server in the config (any common issues here?).

It's failing here: 
https://github.com/VROOM-Project/vroom/blob/1c60bd1b04d43c271dfa2525d5a165bad2ecd897/src/routing/http_wrapper.cpp#L85

```
[Error] Failed to connect to https://matrixservice.app:443

    data: {
      code: 3,
      error: 'Failed to connect to https://matrixservice.app:433'
    },
    status: 500,
    statusText: 'Internal Server Error',

```

1) Is it possible to configure auth for Vroom's matrix-service request? What we really would want to do is allow it to make requests with google's auth library. Also open to suggestions for related issues

2) If a custom matrix is provided, can the connection to the matrix service become optional? This is possibly the simpler solution.

To reproduce this locally:
I am supplying a Vroom input with a custom matrix which is leading to 0 loading times as expected. 
However, when I turn my matrix server off and retry the problem, vroom throws an error because it's failing to connect with the matrix service. Is a successful connection to the matrix service necessary when custom matrices are provided? Or can I bypass the need to configure Vroom to talk to the matrix service by sending the requests separately myself?

Running vroom 1.8.0

**Comment by DCSnip3r** [comment]
Surprised I didn't see this sooner: https://github.com/VROOM-Project/vroom/issues/219

It looks like auth is a headache and so is writing all these wrappers. 

Optional matrix connections (suggestion 2) as a solution would somewhat fix the above issue, allowing for generic matrix services without needing to write wrappers for them.

**Comment by nilsnolde** [comment]
Holy, that's already 4 years ago?! Damn.. 

Supporting an API key is not such a big deal IMO, it's a config item and a tiny bit of code. Ideally no wrappers will have to be written as long as the API providers aren't obfuscating OSRM/Valhalla requests/responses and have the same HTTP interface as the FOSS projects. It's really mostly new config and parsing that, all else (except for API key), VROOM already provides. 

I'd love to have it at some point as well, custom matrices are ugly to build. But for now, that's still the way to go. I'm open for people who want to fund it as a development, don't think it's too much effort. Without it'll just take longer, but will also be done at some point I'm sure.

**Comment by DCSnip3r** [comment]
Julian you're a beast! Great catch. Turned off geometry fetching in my config and it yes this works. Closing this!

**Comment by DCSnip3r** [comment]
Julian you're a beast! Great catch. Turned off geometry fetching in my config and it yes this works. Closing this!
