### ISSUE TITLE
Skills optional in Jobs

### ISSUE THREAD

**Issue by fabrizotus** [VROOM-Project/vroom#899]
How can optional skills be included in a job, meaning that if skills 1 and 2 are added to a job, vehicles that have either skill 1 or skill 2 can be assigned?

Example

Skills: Junior, Expert, Installer 
1, 2, 3

Jhon: 2, 3
Jimmy: 3
Mike: 1

Job1:
J or E

Job2:
E or I

Job3:
J or I

Job4:
J or I or E

**Comment by fbaierl** [comment]
Can't you use a new skill for e.g. "J or E". 

Skills: Junior, Expert, Installer, Junior or Expert
1, 2, 3, 4

Job1: 4

And then your Junior gets the skills: 1, 4 and the expert gets 2, 4.

**Comment by jcoupey** [comment]
Closing as answered.

**Comment by keshavoh** [comment]
We are doing something similar for a client, but i take it from them that the Either OR is not feasible. May i know the reason why? Is there any inherent complexity for the same.
