### ISSUE TITLE
Additional meta-data fields as part of vRoom payload

### ISSUE THREAD

**Issue by stewgloves** [VROOM-Project/vroom#900]
Hello,

Could a non-required key be included as part of the payload to Vroom? E.g to have a `meta_data` key as part of the vRoom payload that will either contain a String or Hash object that is ignored by the algorithm during routing but will be output with the vRoom response. 

I believe this could be useful for tracking things like state or adding timestamps or other business-specific data that would save a lot of data manipulation before or after using vRoom?

Many thanks!

**Comment by stewgloves** [comment]
@jcoupey yes good point and this is what I am currently using. I think in my mind the ability for this to not just be a String would go on to further help make it easier to manipulate the data.

**Comment by jcoupey** [comment]
An easy workaround is to pass an arbitrary json object serialized as a string. Maybe it would make sense to make this a bit cleaner by just storing a json object and feeding it back in the response.
