### ISSUE TITLE
Question about time_window

### ISSUE THREAD

**Issue by mhosman** [VROOM-Project/vroom#904]
Right now you can set a time_window for a vehicle to set start and end times. There's a way to set the start time only (without end time)? In that way you can start at that given time but without limits.

**Comment by jcoupey** [comment]
The time windows do not exactly set start and end times, they're just bounds you provide for those values. Depending on tasks TW, a vehicle can start much later than its TW start and/or end much sooner than its TW deadline.

If you do not want to set a strong constraint on end time, what about providing a very high TW deadline for the vehicle?

**Comment by mhosman** [comment]
Ok thanks!!! I'm gonna provide a very high TW deadline for the vehicle, just thought maybe there was a more elegant way, so just in case haha. Thank you so much!
