### ISSUE TITLE
Vehicle cost per kilometer

### ISSUE THREAD

**Issue by lgmadurange** [VROOM-Project/vroom#908]
I Want To Set Vehicle Cost For Per Kilometer ,

**Comment by jcoupey** [comment]
We don't have a way to do this currently. #788 introduced an improved cost model where we can account for fixed and travel-time related costs.

Similar to what the recent `costs.per_hour` factor allows, it would be interesting to have a `costs.per_km` factor to allow users to ponderate time and distance costs at vehicle level.

**Comment by RichAth** [comment]
I second this feature request and propose an extension to this as well. 

It would be nice to be able to apply a multiplier to the `costs.per_km` for the km's traveled to either pickups or deliveries. This would allow for the optimization of km traveled empty in some use cases which would be advantageous to many companies and drivers. 

Always very appreciative of the work you guys have done so far with Vroom, cheers Rich.

**Comment by jcoupey** [comment]
>the km's traveled to either pickups or deliveries

I'm not sure how this could be clearly defined. Considering the type of the next step for a route leg does not seem to make sense when the route can have any arbitrary sequence of pickup and deliveries after that?

**Comment by RichAth** [comment]
Yes you are right, I did not think about it in that capacity. Considering the type of the next step does not make sense. 

Do you have any recommendations with the current system of how one could optimize to reduce empty km's where the problem set is pickup 1 amount -> deliver 1 amount -> pickup 1 amount-> delivery 1 amount.

**Comment by jcoupey** [comment]
> how one could optimize to reduce empty km's

Worth opening a dedicated ticket if you'd like to discuss this, as this is different from the scope of this feature.

**Comment by lgmadurange** [comment]
> I Want To Set Vehicle Cost For Per Kilometer ,

Is this feature now available?

**Comment by jcoupey** [comment]
Not yet, otherwise this ticket would have been closed. If you want to make this happen faster, you're welcome to fund part of the dev work on this, feel free to reach out to me in case you're interested.

**Comment by martinon97** [comment]
Is the cost.per_km feature now available?

**Comment by jcoupey** [comment]
As the "closed this as completed" mention above suggests, it is now implemented. The feature is available in `master`, but not released yet.
