### ISSUE TITLE
have 3D Cubes - Problems  resulutions ? 

### ISSUE THREAD

**Issue by angelorfontana** [VROOM-Project/vroom#917]

**Comment by angelorfontana** [comment]
I see about 3d container problem this link is a exemple    youtube.com/watch?v=EnE4cIwT7uk

**Comment by jcoupey** [comment]
Bin packing definitely sounds fun and your link has nice colors in the visualization. But if you have a precise question, would you please care to elaborate?

**Comment by angelorfontana** [comment]
VROOM manages to solve 3D bin packing problem?

**Comment by jcoupey** [comment]
No, VROOM focuses on the Vehicle Routing Problem. We do handle capacity restrictions across several user-defined metrics (see the docs on `vehicle.capacity`), but nothing with regard to actual vehicle loading and bin packing.

**Comment by angelorfontana** [comment]
I will try to include the 3d cubing method. Can you tell me which part would be better to include?

**Comment by jcoupey** [comment]
> Can you tell me which part would be better to include?

You mean what method in order to solve the packing problem?
