### ISSUE TITLE
Inconsistent Breaks 

### ISSUE THREAD

**Issue by stewgloves** [VROOM-Project/vroom#920]
Hey @jcoupey 

Could you shed some light on the following error 'Inconsistent Breaks for Vehicle X' please? I couldn't find much in the docs that detailed why this error may occur. 

When we create a Vans initial route via the solver, I am allowing vRoom to create a break with a large time_window (9am-8pm). I then want this break to persist across any future solver runs therefore I take the existing breaks' arrival time and set it as the start and end time_windows in any future break like so:

```ruby
 [
   {
       id: 12,
       service: 1800,
       time_windows: [[arrival_time, arrival_time]]
      }
   ]
```

Many thanks
Stewart

**Comment by jcoupey** [comment]
This errors is raised in the `TWRoute` constructor:

https://github.com/VROOM-Project/vroom/blob/9b7165ec568bd0443ca1f01ba2353a504b895157/src/structures/vroom/tw_route.cpp#L29-L48

What happens there is that we propagate earliest dates for vehicle breaks. If for a given break we don't find a suitable TW (ending after the current earliest date), it means that the empty route is not doable based on the vehicle and breaks TW.

In your situation if you have a single break, that would mean that the break deadline is smaller than the vehicle TW start.

**Comment by stewgloves** [comment]
Perfect thanks! This makes a lot of sense and has solved my problem! We are dynamically setting the start time of the Vans shift which in some instances would place the break before the start time.
