### ISSUE TITLE
stops with location

### ISSUE THREAD

**Issue by gutofurlan** [VROOM-Project/vroom#926]
Today I set up a stop with the times, so far it's perfect, the VROOM calculates perfectly, but I would like it to give me the latitude and kongitude of that stop, how could I do that?

```
{
                    "type": "job",
                    "description": "JOB->16",
                    "location": [
                        -43.2538923,
                        -22.8627576
                    ],
                    "id": 16,
                    "setup": 0,
                    "service": 900,
                    "waiting_time": 0,
                    "job": 16,
                    "load": [
                        0,
                        0,
                        0,
                        0,
                        3
                    ],
                    "arrival": 1661347568,
                    "duration": 420247,
                    "violations": [],
                    "distance": 5459597
                },
                {
                    "type": "break",
                    "description": "Almoço",
                    "id": 2,
                    "setup": 0,
                    "service": 3600,
                    "waiting_time": 0,
                    "load": [
                        0,
                        0,
                        0,
                        0,
                        3
                    ],
                    "arrival": 1661349600,
                    "duration": 421379,
                    "violations": [],
                    "distance": 5470925
                },
```

In the code above I show a job and stop it, see the distance increases, but I needed this stop to come with latitude and longitude

How to do this ?

Thanks

**Comment by jcoupey** [comment]
Do you mean you expect a location for the `break` step?

**Comment by gutofurlan** [comment]
> Do you mean you expect a location for the `break` step?

Yes, I don't want to define, I want VROOM to define

**Comment by gutofurlan** [comment]
Because the vroom generates the polyline, I would like to know which point belongs to the break

**Comment by jcoupey** [comment]
The purpose of a break is precisely to have a task without a location so I don't think it would make much sense to provide an actual location in the steps response.

What happens under the hood is that breaks are (like all tasks) precisely placed in *time*. What you could do is use the times and locations for previous and next tasks to determine a rough approximate of the break location. This is actually what we do currently for the `distance` value in the break step. There is nothing accurate there: it's just a *prorata* estimate based on the total distance between previous and next tasks, and on how much travel has been done before the break and how much is left after.

**Comment by gutofurlan** [comment]
Ok, I get it.
Is there a way for me to pass the job order to the VROOM? and does he always obey that order?

**Comment by jcoupey** [comment]
If you want to decide the order in input, you should check the plan mode: https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#plan-mode.
