### ISSUE TITLE
Unable to use Valhalla routing service

### ISSUE THREAD

**Issue by SimonBradley1993** [VROOM-Project/vroom#928]
HI,

I'm experimenting with using Valhalla routing service instead of OSRM, but when I try and invoke the Vroom CLI I'm getting : 

```
[Error] Valhalla matrix error (No costing method found: 'car').
{"code":3,"error":"Valhalla matrix error (No costing method found: 'car')."}
```

I'm using a small test json file and invoking the CLI like this : 

```
vroom -a localhost -r valhalla -p 8002 -i test.json
```

Where the test.json file is :

```
{"vehicles":[{"id":1,"start":[2.35044,48.71764],"end":[2.35044,48.71764],"capacity":[4],"skills":[1,14],"time_window":[1600416000,1600430400]}],"jobs":[{"id":1,"service":300,"delivery":[1],"location":[1.98935,48.701],"skills":[1],"time_windows":[[1600419600,1600423200]]},{"id":2,"service":300,"pickup":[1],"location":[2.03655,48.61128],"skills":[1]}]}
```

I'm on an M1 Mac running MacOS Monterey and have installed Vroom with Homebrew, which is on the latest version 1.13.0.

Any help is much appreciated!

**Comment by nilsnolde** [comment]
You'll just need to include a `profile` key for the vehicle(s), see https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#vehicles. 

Also here you can see all of the relevant ones: https://github.com/VROOM-Project/vroom-express/blob/8326c0b8969a6b010b1bf331712f586c02f5ea13/config.yml#L17

**Comment by SimonBradley1993** [comment]
Thanks for the quick reply!

I missed that option on the vehicle object, that's great.

Looking at the Valhalla options I've tried defining the profile as both `auto` and `taxi` but I get an error for both of those : ```
[Error] Invalid profile: auto.
{"code":2,"error":"Invalid profile: auto."}
```

test json for completeness : 

```
{"vehicles":[{"id":1,"profile":"auto","start":[2.35044,48.71764],"end":[2.35044,48.71764],"capacity":[4],"skills":[1,14],"time_window":[1600416000,1600430400]}],"jobs":[{"id":1,"service":300,"delivery":[1],"location":[1.98935,48.701],"skills":[1],"time_windows":[[1600419600,1600423200]]},{"id":2,"service":300,"pickup":[1],"location":[2.03655,48.61128],"skills":[1]}]}
```

**Comment by jcoupey** [comment]
VROOM has to somehow be told how profiles match to routing servers (beyond the default `car` value). The link Nils shared above shows how it's done when going through `vroom-express`.

The command-line flags syntax (see `vroom -h`) allows this in the form `-a taxi:localhost -p taxi:8002`.

**Comment by SimonBradley1993** [comment]
That's done it, thanks both!
