### ISSUE TITLE
Duplicate Pickups in the result

### ISSUE THREAD

**Issue by Richard6536** [VROOM-Project/vroom#939]
Hello!
Is it normal for multiple shipments created with the same Pickup but different destinations to result in duplicate pickups?

For example:

Input:
Shipment 1:   Pickup 1 --> Delivery 1
Shipment 2:   Pickup 1 --> Delivery 2
Shipment 3:   Pickup 1 --> Delivery 3

Output: 
https://pastebin.com/ZrABqDMa

`
{
      "steps": [
        {
          "type": "start",
          "location": [
            -73.14345,
            -40.59347
          ],
          "service": 0,
          "waiting_time": 0,
          "load": [
            0
          ],
          "arrival": 0,
          "duration": 0,
          "violations": []
        },
        {
          "type": "pickup",
          "description": "",
          "location": [
            -73.12091,
            -40.5716562
          ],
          "id": 10005,
          "service": 15,
          "waiting_time": 0,
          "job": 10005,
          "load": [
            0
          ],
          "arrival": 454,
          "duration": 454,
          "violations": []
        },
        {
          "type": "pickup",
          "description": "",
          "location": [
            -73.12091,
            -40.5716562
          ],
          "id": 10006,
          "service": 15,
          "waiting_time": 0,
          "job": 10006,
          "load": [
            0
          ],
          "arrival": 469,
          "duration": 454,
          "violations": []
        },
        {
          "type": "pickup",
          "description": "",
          "location": [
            -73.12091,
            -40.5716562
          ],
          "id": 10001,
          "service": 15,
          "waiting_time": 0,
          "job": 10001,
          "load": [
            0
          ],
          "arrival": 484,
          "duration": 454,
          "violations": []
        },
        {
          "type": "pickup",
          "description": "",
          "location": [
            -73.12091,
            -40.5716562
          ],
          "id": 10002,
          "service": 15,
          "waiting_time": 0,
          "job": 10002,
          "load": [
            0
          ],
          "arrival": 499,
          "duration": 454,
          "violations": []
        },
        {
          "type": "pickup",
          "description": "",
          "location": [
            -73.12091,
            -40.5716562
          ],
          "id": 10004,
          "service": 15,
          "waiting_time": 0,
          "job": 10004,
          "load": [
            0
          ],
          "arrival": 514,
          "duration": 454,
          "violations": []
        },
        {
          "type": "pickup",
          "description": "",
          "location": [
            -73.12091,
            -40.5716562
          ],
          "id": 10003,
          "service": 15,
          "waiting_time": 0,
          "job": 10003,
          "load": [
            0
          ],
          "arrival": 529,
          "duration": 454,
          "violations": []
        },
        {
          "type": "delivery",
          "description": "509",
          "location": [
            -73.158367,
            -40.5546696
          ],
          "id": 5,
          "service": 10,
          "waiting_time": 0,
          "job": 5,
          "load": [
            0
          ],
          "arrival": 1010,
          "duration": 920,
          "violations": []
        },
        {
          "type": "delivery",
          "description": "377",
          "location": [
            -73.1574679,
            -40.5730362
          ],
          "id": 4,
          "service": 10,
          "waiting_time": 0,
          "job": 4,
          "load": [
            0
          ],
          "arrival": 1293,
          "duration": 1193,
          "violations": []
        },
        {
          "type": "delivery",
          "description": "643",
          "location": [
            -73.1700006,
            -40.5870181
          ],
          "id": 6,
          "service": 10,
          "waiting_time": 0,
          "job": 6,
          "load": [
            0
          ],
          "arrival": 1551,
          "duration": 1441,
          "violations": []
        },
        {
          "type": "delivery",
          "description": "880",
          "location": [
            -73.170793199999991,
            -40.567225
          ],
          "id": 1,
          "service": 10,
          "waiting_time": 0,
          "job": 1,
          "load": [
            0
          ],
          "arrival": 1859,
          "duration": 1739,
          "violations": []
        },
        {
          "type": "delivery",
          "description": "34",
          "location": [
            -73.16728599999999,
            -40.566801
          ],
          "id": 2,
          "service": 10,
          "waiting_time": 0,
          "job": 2,
          "load": [
            0
          ],
          "arrival": 1923,
          "duration": 1793,
          "violations": []
        },
        {
          "type": "delivery",
          "description": "223",
          "location": [
            -73.150672,
            -40.5739243
          ],
          "id": 3,
          "service": 10,
          "waiting_time": 0,
          "job": 3,
          "load": [
            0
          ],
          "arrival": 2157,
          "duration": 2017,
          "violations": []
        },
        {
          "type": "end",
          "location": [
            -73.14345,
            -40.59347
          ],
          "service": 0,
          "waiting_time": 0,
          "load": [
            0
          ],
          "arrival": 2498,
          "duration": 2348,
          "violations": []
        }
      ]
}
`

The result is the same Pickup but duplicated for each destination.

Thanks.

**Comment by jcoupey** [comment]
Yes, that is the expected output. By _"created with the same Pickup"_ you mean that you expect both pickups to happen at the same time in your use-case. But actually the pickups are different: they have different ids and in some situations it could make sense to separate them based on other constraints. So in term of optimization we have to see them as separate tasks.
