### ISSUE TITLE
Vehicle definitions - how do the matrices work?

### ISSUE THREAD

**Issue by CloudUX-AU** [VROOM-Project/vroom#942]
Sincerest apologies writing here - I expect this is not the right place to ask, however my search is exhausted - I have looked high and low and cannot find any resources describing how the matrices work in vehicles. These durations for example. Is there any further resources I can reference to understand how to configure these? 
![IMG_7324](https://github.com/VROOM-Project/vroom/assets/913767/3489396a-6f8c-4286-9719-dde6de997e05)

**Comment by nilsnolde** [comment]
This is the work of the routing engines, not VROOM. Not sure on which level you're interested (algorithmically, configuration etc), in any case these are the routing engines VROOM interfaces with (but has otherwise absolutely nothing to do with it, it's kind of a convenience that VROOM integrates with those):

- https://github.com/Project-OSRM/osrm-backend
- https://github.com/valhalla/valhalla
- https://github.com/GIScience/openrouteservice

Docs are abundant and you'll need to do the digging yourself.

**Comment by CloudUX-AU** [comment]
This is exactly the advice I needed - thank you!

**Comment by CloudUX-AU** [comment]
This is exactly the direction I needed - thank you!

**Comment by CatonTheRoRo** [comment]
I thought that Vroom role starts after after the routing engine offers its data (e.g. distance/duration matrix).
The question is how to identify which of matrix element is which point in Vroom request json, like if a certain point in matrix were a vehicle or a shipment pickup or delivery or a job, and which one?

Sounds like there must be logical approach to identify such thing.

**Comment by Orthae** [comment]
You are the one providing to the engine which point is which. You have two ways.
1. You provide coordinates in the request json.
2. You provide matrix index in the request json.

For example, when passing vehicle you pass either, coordinates or matrix index. If you pass coordinates the Vroom will fetch the data from supported routing engine, if you pass the matrix index, you are responsible for creating proper matrix and selecting proper index.
https://github.com/VROOM-Project/vroom/blob/release/1.14/docs/example_2.json


// I have no clue why I was subscribed to this issue 🙃

**Comment by jcoupey** [comment]
Quick complement on @Orthae answer:

- if you're using a routing engine, you don't need to worry about how the matrices are laid out internally;
- if you're providing custom matrices, check out the optional `location_index`, `start_index` and `end_index` keys.
