### ISSUE TITLE
Vehicle with stop time

### ISSUE THREAD

**Issue by pablopique97** [VROOM-Project/vroom#944]
Hi there,

I have some issues with the stop time of the vehicle. A vehicle with the same profile can have different timings in order to deliver the job.
I mean a trailer can take more time to deliver the job than a van.

Is it posible that vehicle can take as input stopTime?

Best regards,

**Comment by jcoupey** [comment]
Closing as duplicate for https://github.com/VROOM-Project/vroom/issues/336.

TL;DR not possible, service time are task-dependent, no link with vehicles.
