### ISSUE TITLE
The result has returns to the Pickup for replenishment with volume still loaded

### ISSUE THREAD

**Issue by ziongh** [VROOM-Project/vroom#948]
The Optimizer is loading more product than needed on the first Pickup, and this results in remaining product on the truck when going for a replenishment in the pickup (the same as the previous or another new one), which is not optimal, because the fuel comsumption is higher when loaded.

I'm using Shipments with pickup and Delivery.

**Comment by jcoupey** [comment]
Hard to take any action on just a description, could you please share a [standalone instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) that would allow to reproduce the problem you're facing?

**Comment by jcoupey** [comment]
Closing as not actionable, feel free to re-open if you can share an instance to reproduce your problem.
