### ISSUE TITLE
How to optimize multiple pickups and deliveries with multiple vehicles, with each vehicle having multiple compartments with diferent volumes?

### ISSUE THREAD

**Issue by ziongh** [VROOM-Project/vroom#949]
Imagine a situation where we have multiple order of products of diferent kinds (eg.: Diesel, Gasoline, etc). And each product must be on an isolated compartiment of the truck.

The following example may or may not return the optimal result, but i'm just showing a case:

## Shipments:

- From X to A carring 1000 galons of diesel
- From X to A carring 1500 galos of gasoline
- From X to B carring 800 galons of diesel
- From X to C carring 1200 galons of diesel
- From Y to D carring 1500 galons of gasoline
- from Y to D carring 1000 galons of diesel
- from Y to E carring 800 galons of diesel

## Vehicles

- Truck AAA with the following compartiments:
  - Compartiment 1: 1000 galons
  - Compartiment 2: 2000 galons
  - Compartiment 3: 500 galons
  - Compartiment 4: 500 galons
  - Compartiment 5: 200 galons
  - Compartiment 6: 100 galons

- Truck BBB with the following compartiments:
  - Compartiment 1: 200 galons
  - Compartiment 2: 300 galons
  - Compartiment 3: 500 galons
  - Compartiment 4: 500 galons
  - Compartiment 5: 500 galons
  - Compartiment 6: 500 galons
  - Compartiment 7: 200 galons
  - Compartiment 8: 1500 galons

How to optimize the use of trucks and compartments so that:
- the compartments are fully loaded or not loaded at all
- a single compartiment should never be used by more than one order before replenishment on the pickup location
- one order can use multiple compartiments
- all the other restrictions are applyed (attendance window on the pickup and delivery, etc.)

I've reached a suboptimal solution setting for each vehicle two dimensions on the capacity field (one is the sum of all compartment volumes and the other is the number os compartiments).

And on the Shipment i've used two dimensions also (one for the volume and one with the number 1)

However this settings returns some results that when you try to divide in the compartiments, there is no combination that will fit all... even when the total sum of volumes should theoreticaly fit, but the compartiments are not continuos.

**Comment by jcoupey** [comment]
We don't have a way to model this out of the box, so you're left with using workarounds like the one you mentioned. Now how good (read *suboptimal* or even *valid*) the solutions are is highly dependent on how you "simplify" the problem in your model, and the actual use-case you have: fleet, compartment and tasks setup.

I realize this probably does not help much, but I'm afraid there is no generic answer to that problem using VROOM.

**Comment by ziongh** [comment]
Thanks for the answer. Do you think it would be possible for me to add logic in the optimizer to take this into account? I could add an extra field in Vehicle to store the compartments, and in the optimizer (I believe vrp.h) I could add a logic (perhaps in LocalSearch **run()** method) to take this into account (it would tag which compartments were used according to the loads being allocated).

Could you please point to the correct direction (files that I'll need to check)? Thanks again!

**Comment by jcoupey** [comment]
If you want to change or extend the current capacity constraint logic, you have to adjust all `RawRoute::is_valid_addition_for_*` functions (see `src/structures/vroom/raw_route.h`). Those are the low-level checks that are called throughout the codebase to make sure potential changes yield valid routes with regard to capacity.

Note that those functions are called in hot spots of the code so any additional complexity you introduce there could result in huge computing time increases. FWIW, all functions have a constant time complexity, except for `RawRoute::is_valid_addition_for_capacity_inclusion` that is linear in the size of the inserted range in the worst case.

Disclaimer: I did not give a thorough thought to your specific use-case so I have no idea whether this kind of change would be enough to actually achieve what you want.

**Comment by jcoupey** [comment]
Closing as answered.
