### ISSUE TITLE
Not considering service time to meet time windows

### ISSUE THREAD

**Issue by NadineLoop** [VROOM-Project/vroom#950]
Hi all, 

I am planning a trip with 1 vehicle and 37 jobs. Some jobs have time windows and some don't but all have a service of 360 (6 minutes). 

If we consider this, I am expecting 222 minutes (3 hrs 42 minutes) of service time but I am getting back that my total trip duration is 2hrs. Which lead me to believe that it is only considering the driving time and not the service time when trying to ensure that all my time windows are met. 

I have 1 job that can be serviced from the the start of my vehicles time window (8am), until 9am SAST. And a few that can be serviced until 10.30am SAST. Currently because my trip is only 2hrs long, all jobs can be serviced by 10.30am but this is not the case if the service time is considered. I currently have jobs that would be serviced at 13.42pm. I am unsure if something is perhaps in an incorrect format. Some guidance would be appreciated. 

Example Job
`{
            "id": 14,
            "description": "By 9AM",
            "location": [
                18.4346202,
                -34.0807881
            ],
            "time_windows": [
                [
                    1689055200,
                    1689058680
                ]
            ],
            "delivery": [
                1
            ],
            "service":360,
            "skill": [
                1
            ]
        }`

My vehicles
`"vehicles": [
        {
            "id": 1,
            "start": [
                18.539331,
                -33.838782
            ],
            "end": [
                18.539331,
                -33.838782
            ],
            "capacity": [
                50
            ],
            "time_window": [
                1689055200,
                1699714800
            ]
        }
    ],`
   
   All of the red ones are out of the time window:

![image](https://github.com/VROOM-Project/vroom/assets/139317205/be954fd8-a35a-4c7a-8f90-ac56bf72d536)

**Comment by jcoupey** [comment]
> Which lead me to believe that it is only considering the driving time and not the service time when trying to ensure that all my time windows are met.

The docs clearly state that all `duration` values are related to *travel time* only, so you should indeed add other values (e.g. `service`, `waiting_time`) to get the full route time span. Now the optimization does take *all* timing values (travel, service etc.) in order to decide on TW validity. Put it simply: service times at preceding jobs impact the arrival times further down the line, hence the TW validity.

If you think that is not the case in one of your examples, could you please share the full input/output you're using and pinpoint exactly what key/value you think is breaking a constraint.

**Comment by NadineLoop** [comment]
Thanks @jcoupey - I have been playing around more and have been getting somewhere. I have done a little research across some other projects. Could it be that if is not possible to have the orders done within their time windows? With my first request, I did not have any violations/unassigned jobs reported, but my understanding is that we potentially have to set up within our own project how we want violations to be handled. Is this correct?

When I decreased my service time and made the start time of my vehicle earlier, it obeyed all the time windows. And had a few unassigned jobs which made sense.

**Comment by jcoupey** [comment]
> my understanding is that we potentially have to set up within our own project how we want violations to be handled.

No, the constraints you provide using time windows for jobs and vehicles are hard constraints, they cannot be broken by the optimization process. If you get a solution that is not valid wrt the timing constraints, that would be a bug.

This being said, it's impossible to provide more feedback without an actual reproducible example. If you want more help, please share:

1. an example of input/output;
2. how you're running `vroom`;
3. what version you're using;
4. what you think is wrong in the solution.

**Comment by leobudima** [comment]
@NadineLoop If it helps, the time-windows in Vroom specify by when the vehicle needs to *arrive* at the job, not *complete* it. So if you need to account for service time within the time window, you can simply, before sending the jobs to optimization, shorten the time-window duration for the amount needed for service time. 

E.g. if a job has a time-window of 10:00-11:00, but there is a 15 min service time, the vehicle needs to arrive by 10:45 at latest, so you set 10:00-10:45 as a new time-window.

**Comment by jcoupey** [comment]
Closing as answered.
