### ISSUE TITLE
Get suggestions for time slots

### ISSUE THREAD

**Issue by Fusix** [VROOM-Project/vroom#951]
Hey, we are currently using this project for a job time window suggestion engine.

I want to use VROOM to get suggestions what possible vehicle can be used. For that the working day is sliced into time slots with a margin of 15 minutes each. The duration (e.g. 1h) is variable and sets the job's (time slot) service duration.
![image](https://github.com/VROOM-Project/vroom/assets/6383231/9cbafa1c-1990-468d-bd47-5643c10283e8)

For each time slot there should be a suggestions what vehicles are available and can do the job. They have to be free (no other planned jobs) and are able to reach the event in time.

Planned jobs:
![image](https://github.com/VROOM-Project/vroom/assets/6383231/9521250f-021b-4a2e-bede-779873f4966d)

Right now I am creating jobs for each time slot with a specific skill and vehicles for each time slot (5 Slots with 3 Vehicles => 15 Vehicles, 5 Jobs). Each vehicle that should be assigned to the time slot get that "time slot skill". The vehicles start from their respective home location. If any of the vehicles have a planned job, the vehicle in the time slot after the planned job should start from the last job and not from the home location. A planned job is another job next to the time slot jobs with again a specific skill that is only assigned to specific vehicle that is involved in the planned job.

The current modeling of the problem does work but costs a lot of time since there are many vehicles included in the solution. How would one improve or simplify the problem so that so calculation is faster?

I hope that there is another solution with vroom, that does not include that many vehicles. I am happy for help or further suggestions! :)

**Comment by jcoupey** [comment]
Using time windows on both jobs and vehicles is already a way to make sure jobs are only served by vehicles that are available and for which travel and service times fit in the required time frames. So I don't really get the point in introducing skills here?

**Comment by Fusix** [comment]
The problem with using just time windows is that it is too constrained. Right now jobs have time window set to the starting time of the slot so that they definitely start at the time slot start. All vehicles have a time window set to the working hours. When setting the time window to the duration of the time slot this would result in vehicles that are unable to reach the slot in time. 

Here are the vroom input [input.txt](https://github.com/VROOM-Project/vroom/files/12047283/input.txt) and the suggestion engines result [result.txt](https://github.com/VROOM-Project/vroom/files/12047282/result.txt) (simplified to only include one vehicle and the time slots for one day + planned jobs). This solution works but there are way too many vehicles included to achieve the expected results.

**Comment by jcoupey** [comment]
I'm not sure I fully get the problem since I don't have the underlying business need. It looks like you're trying to answer multiple questions: can vehicle X handle this job in time slot Y. You could do one request per vehicle and time slot. My understanding is that the way you duplicate jobs and vehicles is simply a wrapper to put everything in the same request with independent vehicles/jobs pairs (based on skills).

If you want to test out all possible options and there are $V$ vehicles and $T$ time slots, I don't see how you can avoid having a $V\times T$ combination somewhere, either as the number of (simple) requests or as the combinations in a more elaborate request.

**Comment by Fusix** [comment]
Indeed that will be the matrix to solve. I recently made another observation. When following the instructions at https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance and using that as an input, the result is way faster! It seems like the "optimization" dropping duplicate locations in the duration matrix and referencing the same tuple for the vehicles speeds up the optimization. So maybe that could be included in vroom as well so that duplicate locations will be dropped and the custom matrix will be build up before.

[problem_matrix.txt](https://github.com/VROOM-Project/vroom/files/12078590/problem_matrix.txt)

**Comment by jcoupey** [comment]
The location deduplication is already happening inside VROOM before sending the matrix request. The difference in computing time you're seeing is probably due to the fact that generating the standalone instance already covers computing the matrix. So when solving the problem after that you're left with "only" the solving time. Check out the `summary.computing_times` object: `loading` is usually mostly computing the matrix.

**Comment by Fusix** [comment]
Damn, sadly I only took one day into account for the optimization. The calculation for a week still lasts 10 seconds to solve the problem. The only way to reduce the solving time would be to lower the exploration level parameter. I think for the stated problem there will be no other faster solution than calculating all V x T combinations.

**Comment by Fusix** [comment]
@leobudima right now we are splitting the request on a daily basis. The request for one day lasts about a seconds, which is acceptable for our needs. The days will be fetches one after the other. Indeed we do filter the vehicles to shrink the problem to solve but in the worst case all vehicles are available at any time.

**Comment by jcoupey** [comment]
Closing here as it looks we reached some kind of agreement.
