### ISSUE TITLE
Unable to run plan mode with Homebrew Vroom

### ISSUE THREAD

**Issue by SimonBradley1993** [VROOM-Project/vroom#955]
I'm running on an M1 Mac and have installed Vroom via Homebrew. When I tried to use the plan mode I get this error : 

```
[Error] VROOM compiled without libglpk installed.
```

I've tried installing this package from here : https://formulae.brew.sh/formula/glpk and reinstalling Vroom but I still get the same error.

Is this down to my machine, or is Vroom on Homebrew missing this dependency?

**Comment by jcoupey** [comment]
My guess is that you're getting a pre-compiled binary from Homebrew, so if this was built without glpk installed, then installing glpk locally won't fix the error. You basically have two choices:

- build VROOM from source yourself with glpk installed;
- fix this in the Homebrew formula (or at least open a ticket upstream).

For what it's worth, the glpk detection happens [here](https://github.com/VROOM-Project/vroom/blob/dea333369b2d558ca58e37cfaeb6065267943682/src/makefile#L45-L54) in the makefile. Not sure how very portable that is.

**Comment by jcoupey** [comment]
@SimonBradley1993 shall we close here? Or maybe leave this ticket open until something happens upstream (in which case it would be helpful to link to some relevant issue in Homebrew)?
