### ISSUE TITLE
Add Time Restriction between Jobs

### ISSUE THREAD

**Issue by Rabbit0923** [VROOM-Project/vroom#958]
Is it possible to add a time restriction between jobs. In my case I am planning a month where every job has timewindows. There is the case that I have Job A and Job B. Job A can be done between the 1st and 15st of the Month, but Job B needs do be done 14 days after Job A. So If Job A is done on the 5th Job be should be on 19th and if Job B is done on the 10th Job B should be done on the 24th. Can I model this constraints?

**Comment by jcoupey** [comment]
No, there is no way to express this kind of constraint, except by defining job time windows but then you can only enforce bounds on the time difference between jobs. See also #902.

**Comment by jcoupey** [comment]
Closing as answered.
