### ISSUE TITLE
Routes do not take one-way roads into consideration

### ISSUE THREAD

**Issue by kuba-orlik** [VROOM-Project/vroom#959]
Consider the following route generated by Vroom - visiting each target point in the proposed order would mean driving against the traffic flow on a one-way street:

![Screenshot from 2023-07-30 11-21-49](https://github.com/VROOM-Project/vroom/assets/2697916/332e86ec-01a7-435b-8751-21d5cc455e32)

**Comment by Orthae** [comment]
This is not related to Vroom, but to the underlying routing engine, you could try running it locally with the newest graph, and it should be working correctly.
![image](https://github.com/VROOM-Project/vroom/assets/43386385/2bb1e04a-7494-4f34-b61f-1356559aba77)

**Comment by jcoupey** [comment]
That is indeed definitely a problem related with data and routing. If you look closely to your screenshot, you can see that the geometry does not even align with routes on the OSM tiles.

**DISCLAIMER**: the data used by the demo server is (embarrassingly) old. The sole purpose of this demo server is to showcase the *optimization* efficiency and there is no guarantee whatsoever, see [usage terms](https://github.com/VROOM-Project/vroom/wiki/Demo-server).

If you want updated data, you should run your own stack, or use the commercial API from [Verso](https://verso-optim.com) (the company leading the VROOM dev) for improved routing and optimization.

FWIW, here is the route I get using our API, it does align to actual way geometries and observes oneway restrictions.
![Screenshot 2023-07-31 at 11-23-40 VERSO frontend](https://github.com/VROOM-Project/vroom/assets/6639205/24f86eb4-499c-452b-9045-95f8becfd732)

**Comment by kuba-orlik** [comment]
Thanks for the explanation!
