### ISSUE TITLE
Adding or removing skills during jobs?

### ISSUE THREAD

**Issue by Haapavuo** [VROOM-Project/vroom#974]
Hi. In our case, we need to add or remove certain functionalities / capabilities (i.e. skills) of the vehicles during some job phases.

Say you have a hook on the vehicle that can carry only single object, which is filled during a certain job which requires the hook skill. After that job the vehicle can no more do jobs that require the hook skill.

There are also other kinds of features on the vehicles which are updated during jobs and should affect the vehicles capability to perform other jobs after that.

Is this possible? Any ideas? Thanks.

**Comment by jcoupey** [comment]
> a hook on the vehicle that can carry only single object, which is filled during a certain job 

Sounds exactly like a capacity restriction. What about having a capacity component dedicated to the "hook space"?

**Comment by jcoupey** [comment]
Closing as answered.
