### ISSUE TITLE
Vroom Matrices API not giving correct distances with multiple vehicles

### ISSUE THREAD

**Issue by bc123139** [VROOM-Project/vroom#980]
I am using Vroom metrics api, because I want to exclude "Ferry" routes, so I am computing table service from OSRM and getting the distance and duration from table service and passing it to Vroom.
Scenerio:
I want to build jobs with multiple vehicles(e.g: 14 vehicles), all vehicles have to start from different locations and lets suppose I have 476 locations. Now I'm expecting from VRoom to give me the optimal jobs in result. But Vroom is giving me the distance like 1600 km which will visit in 2 hrs, so the output is unrealistic,

In the VROOM documentation Sample request is not working also for Metrics: https://github.com/VROOM-Project/vroom/blob/master/docs/example_2.json

Here, I have some confusions like I have 14 vehicles. 
1): What should be start_index and _end_index of each vehicle?
2): I have 476 locations, so for the distance and duration metrix,
 should I only have to pass 476 locations, or shoud I pass 14 vehicles start locations+476 locations+14 vehices end locations, what will be the format, because in the docment metrics api format is not defined properly.

Sample Request which I tried using Postman:

{
  "vehicles": [
    {
      "capacity": [
        450
      ],
      "time_window": [
        28800,
        57600
      ],
      "speed_factor": 0.95,
      "breaks": [],
      "id": 1,
      "start": [
        10.2039,
        56.1629
      ],
      "end": [
        10.2039,
        56.1629
      ],
      "start_index": 0,
      "end_index": 4,
      "profile": "daocar",
      "description": "arhus"
    }
  ],
  "jobs": [
    {
      "service": 456,
      "delivery": [
        25
      ],
      "id": 1,
      "location": [
        10.0978642,
        56.4770617
      ],
      "location_index": 1,
      "description": "Røllikedalen 17, 8930 Randers, Denmark"
    },
    {
      "service": 360,
      "delivery": [
        9
      ],
      "id": 2,
      "location": [
        10.2714,
        56.5205
      ],
      "location_index": 2,
      "description": "Voer færgested, 8950, Denmark"
    },
    {
      "id": 3,
      "location": [
        10.2069,
        56.5209
      ],
      "location_index": 3,
      "description": "Fjordhøj 3, 8930 Randers, Denmark"
    }
  ],
  "shipments": [],
  "matrices": {
    "daocar": {
      "durations": [
        [
          0,0,0,
          1888,
          649
        ],
        [
          0,0,1864,
          0,
          2314
        ],
        [
          0,0,664,
          2348,
          0
        ]
      ],
      "distances": [
        [0,0, 150, 1000,0],
        [0,1200, 0, 1300,0],
        [0,150, 1300, 0,0]
      ]
    }
  },
  "options": {
    "g": true,
    "c": false,
    "costs": ["distance", "duration"],
    "t": 16,
    "x": 1
  }
}

**Comment by jcoupey** [comment]
> I am using Vroom metrics api, because I want to exclude "Ferry" routes

Sounds like you're making it unnecessary complex. What about excluding ferry routes by default at OSRM level, then simply letting VROOM do the OSRM calls in the background for you?

**Comment by bc123139** [comment]
> > I am using Vroom metrics api, because I want to exclude "Ferry" routes
> 
> Sounds like you're making it unnecessary complex. What about excluding ferry routes by default at OSRM level, then simply letting VROOM do the OSRM calls in the background for you?

I'm calling the table service and I'm using the exclude parameter for it.
If I use ORS flow instead of matrix api, there is no way to pass exclude parameter from Vroom to Osrm.
If I exclude ferry intentionally then I need to extract osrm with ferry routes exclusion. And in future if I have to exclude motorway routes then I will need separate osrm extraction. This solution is not feasible, because it'll increase infrastructure cost

**Comment by jcoupey** [comment]
Well, if you input your own matrices, then the `*_index` values are just the line/row ranks of the associated locations in the matrices you send.

>because in the docment metrics api format is not defined properly.

If two locations (be it jobs, vehicle starts or ends) have `*_index` values `i` and `j`, then VROOM will use `matrices["profile_name"]["durations"][i][j]` as travel time cost between locations for any vehicle with `"profile": "profile_name"`. That's really all there is to it.

If you're not sure how to build the instance with matrices, you may want to check how it's done in the script we have to generate [standalone instances](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance).

**Comment by bc123139** [comment]
> Well, if you input your own matrices, then the `*_index` values are just the line/row ranks of the associated locations in the matrices you send.
> 
> > because in the docment metrics api format is not defined properly.
> 
> If two locations (be it jobs, vehicle starts or ends) have `*_index` values `i` and `j`, then VROOM will use `matrices["profile_name"]["durations"][i][j]` as travel time cost between locations for any vehicle with `"profile": "profile_name"`. That's really all there is to it.
> 
> If you're not sure how to build the instance with matrices, you may want to check how it's done in the script we have to generate [standalone instances](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance).

Can you please give me the sample request for multiple vehicles and multiple locations with distance and duration matrices?

**Comment by bc123139** [comment]
> Can you please give me the sample request for multiple vehicles and multiple locations with distance and duration matrices?

Can you please give me the sample request for multiple vehicles and multiple locations with distance and duration matrices?

**Comment by bc123139** [comment]
> Well, if you input your own matrices, then the `*_index` values are just the line/row ranks of the associated locations in the matrices you send.
> 
> > because in the docment metrics api format is not defined properly.
> 
> If two locations (be it jobs, vehicle starts or ends) have `*_index` values `i` and `j`, then VROOM will use `matrices["profile_name"]["durations"][i][j]` as travel time cost between locations for any vehicle with `"profile": "profile_name"`. That's really all there is to it.
> 
> If you're not sure how to build the instance with matrices, you may want to check how it's done in the script we have to generate [standalone instances](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance).

I already generate Standalone instance and its running in Azure Container Instance

**Comment by bc123139** [comment]
> Well, if you input your own matrices, then the `*_index` values are just the line/row ranks of the associated locations in the matrices you send.
> 
> > because in the docment metrics api format is not defined properly.
> 
> If two locations (be it jobs, vehicle starts or ends) have `*_index` values `i` and `j`, then VROOM will use `matrices["profile_name"]["durations"][i][j]` as travel time cost between locations for any vehicle with `"profile": "profile_name"`. That's really all there is to it.
> 
> If you're not sure how to build the instance with matrices, you may want to check how it's done in the script we have to generate [standalone instances](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance).

Can you please give me the sample request for multiple vehicles and multiple locations with distance and duration matrices?

**Comment by bc123139** [comment]
> Well, if you input your own matrices, then the `*_index` values are just the line/row ranks of the associated locations in the matrices you send.
> 
> > because in the docment metrics api format is not defined properly.
> 
> If two locations (be it jobs, vehicle starts or ends) have `*_index` values `i` and `j`, then VROOM will use `matrices["profile_name"]["durations"][i][j]` as travel time cost between locations for any vehicle with `"profile": "profile_name"`. That's really all there is to it.
> 
> If you're not sure how to build the instance with matrices, you may want to check how it's done in the script we have to generate [standalone instances](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance).

This solution is only work, when all vehicles have same start and end locations, but when do we have different start and end addresses  then we have to explain that you've to skip other vehicles start and end location indexes from metrics other remaining vehicles start and end will be visit by those vehicles which don't need to go there and it will impact on cost

**Comment by jcoupey** [comment]
Closing as answered.
