### ISSUE TITLE
error: no type named 'OptionException' in namespace 'cxxopts' issue 

### ISSUE THREAD

**Issue by chenrui333** [VROOM-Project/vroom#997]
👋 while trying to build the bottle for sonoma, we found there is build issue with `error: no type named 'OptionException' in namespace 'cxxopts' `, details as below:

```
clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -c algorithms/local_search/operator.cpp -o algorithms/local_search/operator.o
  main.cpp:105:22: error: no member named 'OptionException' in namespace 'cxxopts'
        throw cxxopts::OptionException("Argument '" + limit_arg +
              ~~~~~~~~~^
  main.cpp:[118](https://github.com/Homebrew/homebrew-core/actions/runs/6255124360/job/16983922323#step:4:119):27: error: no type named 'OptionException' in namespace 'cxxopts'
    } catch (const cxxopts::OptionException& e) {
                   ~~~~~~~~~^
  2 errors generated.
  clang++ -MMD -MP -I. -std=c++17 -Wextra -Wpedantic -Wall -O3 -DASIO_STANDALONE -DUSE_ROUTING=true -DNDEBUG -c routing/http_wrapper.cpp -o routing/http_wrapper.o
  make: *** [main.o] Error 1
  make: *** Waiting for unfinished jobs....
```

brew config

```
  Clang: 15.0.0 build 1500
  Git: 2.39.3 => /usr/bin/git
  Curl: 8.1.2 => /usr/bin/curl
  macOS: 14.0-arm64
  CLT: 15.0.0.0.1.1694021235
  Xcode: 15.0
  Rosetta 2: false
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6255124360/job/16983922323

relates to https://github.com/Homebrew/homebrew-core/issues/142161

**Comment by jcoupey** [comment]
I have no idea what "build the bottle for Sonoma" actually means, but I guess that's beside the point.

What version of VROOM are you trying to build here?

This looks like a problem with `cxxopts` which is a dependency we currently ship using a submodule. Did you `git submodule init` and `git submodule update` at some point?

**Comment by Orthae** [comment]
It is related to building Vroom on MacOS for brew. Anyway, the issue is that brew is not using the cxxopts or rapidjson from the Vroom repository, instead they are injecting their own versions, causing the source mismatch. I have the same issue building it on MacOS 13, AARM M1.

https://github.com/Homebrew/homebrew-core/blob/2440a7a0dd273ef9accfd5ef003e3beb3a0e66b4/Formula/v/vroom.rb#L28
```
    # Use brewed dependencies instead of vendored dependencies
    cd "include" do
      rm_rf ["cxxopts", "rapidjson"]
      mkdir_p "cxxopts"
      ln_s Formula["cxxopts"].opt_include, "cxxopts/include"
      ln_s Formula["rapidjson"].opt_include, "rapidjson"
    end```

**Comment by jcoupey** [comment]
> instead they are injecting their own versions

Right, that was my intuition too. Depending on the cxxopts version, it means either:

- brew is on an older version so there is nothing to do on our side, just update cxxopts over at brew;
- brew is on a more recent version and we'll hit that when we update.

Only in the latter case would we need to do something, but I would be surprised since we're currently on `cxxopts @ c74846a` which is [v3.0.0](https://github.com/jarro2783/cxxopts/releases/tag/v3.0.0) so this would mean more recent releases from the `v3` series broke something.

**Comment by jcoupey** [comment]
Can someone confirm the cxxopts version  at brew is older than `v3.0.0`?

**Comment by Orthae** [comment]
They are using the newest version, I have taken a look at the cxxopts releases and 3.1 made some changes on the exceptions. The change looks small enough, and I can make PR, hopefully not breaking anything in the process. 

```Cleanup exception code, add cxxopts::exceptions namespace.```

**Comment by jcoupey** [comment]
Does this means that the `cxxopts::OptionException` type disappeared between version 3.0 and 3.1? Sounds like a breaking change.

**Comment by Orthae** [comment]
Yea, they nuked the previous version of exceptions and replaced them with new one.

https://github.com/jarro2783/cxxopts/pull/347/files

**Comment by jcoupey** [comment]
OK, the changelog over there states *"The project adheres to semantic versioning"* but nevermind. Thanks for the PR!

**Comment by jamesjjk** [comment]
@jcoupey Would an interim release v1.13.1 with the PR not be advisable? - Working on a aws Lambda container for vroom and it would be helpful.

**Comment by Orthae** [comment]
You should have zero issues with building lambda layers.

**Comment by jcoupey** [comment]
https://github.com/VROOM-Project/vroom/pull/999#issuecomment-1733246247

**Comment by jamesjjk** [comment]
@jcoupey @Orthae vroom-docker unfortunately fails to build now with cxxopts::OptionException

**Comment by jcoupey** [comment]
I don't really understand: when using `cxxopts` via git submodule, then the code should be consistent with the vendored version, no matter if using Docker or not.

**Comment by jamesjjk** [comment]
```
RUN echo "Cloning and installing vroom release ${VROOM_RELEASE}..." && \
    git clone  --recurse-submodules https://github.com/VROOM-Project/vroom.git && \
    cd vroom && \
    git fetch --tags && \
    git checkout -q $VROOM_RELEASE && \
    make -C /vroom/src -j$(nproc) && \
    cd /
```

**Comment by Orthae** [comment]
@jamesjjk You can use this one for now and it should do the trick.

https://github.com/VROOM-Project/vroom-docker/pull/69

**Comment by jamesjjk** [comment]
git clone  --branch $VROOM_RELEASE --recurse-submodules https://github.com/VROOM-Project/vroom.git

**Comment by jamesjjk** [comment]
@Orthae You were too fast :) thank you! I also would like to commit some additional constraint features that I still have to document - and a aws lambda image that I will work on in other tickets/branches
